### ISSUE TITLE
发送群聊没响应。

### ISSUE THREAD

**Issue by zhenda-hub** [zhayujie/chatgpt-on-wechat#1015]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

用 railway 部署后， @bot 发送个人可以响应，@bot 发送群聊没响应。

### 问题描述 😯

@bot 发送群聊没响应。

### 终端日志 📒

```log
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
response.begin()
File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
response.begin()
File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/lib/itchat/components/login.py", line 301, in maintain_loop
msgList, contactList = self.get_msg()
File "/app/lib/itchat/components/login.py", line 390, in get_msg
r = self.s.post(url, data=json.dumps(data),
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
return self.request("POST", url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by zhenda-hub** [comment]
有时候 会 终端报错，有时候什么反应也没有。

**Comment by zhenda-hub** [comment]
好像是docker有问题，不支持群聊，本地运行支持群聊的

**Comment by lanvent** [comment]
检查是否是配置问题

**Comment by zhenda-hub** [comment]
修改了dockerfile后，群聊可以了，果然是现在版本的dockerfile不支持群聊。

**Comment by lanvent** [comment]
你使用railway部署，跟dockerfile没有关系，只跟环境变量的配置有关。个人微信不存在只支持私聊不支持群聊的情况

**Comment by zhenda-hub** [comment]
> 你使用railway部署，跟dockerfile没有关系，只跟环境变量的配置有关。个人微信不存在只支持私聊不支持群聊的情况

railway使用dockerfile进行部署的，有直接关系呀。dockerfile用的是作者的一个镜像，和代码好像没关系

**Comment by yangyayuan** [comment]
> 修改了dockerfile后，群聊可以了，果然是现在版本的dockerfile不支持群聊。

大佬，咋修改的，能分享下不？

**Comment by zhenda-hub** [comment]
> > 修改了dockerfile后，群聊可以了，果然是现在版本的dockerfile不支持群聊。
> 
> 大佬，咋修改的，能分享下不？
你也是遇到同样的情况了吗？
我这么改的：
FROM python:3.9
WORKDIR /app
COPY requirements.txt .
COPY requirements-optional.txt .
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ \
    && pip install -r requirements.txt \
    && pip install -r requirements-optional.txt
COPY . .
# 必须双引号
CMD ["python", "app.py"]

**Comment by yangyayuan** [comment]
> 

是的，看来是个bug，谢谢大兄弟的分享
