### ISSUE TITLE
上下文超过一定字符会报错

### ISSUE THREAD

**Issue by linkboy2007** [zhayujie/chatgpt-on-wechat#103]
### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

上下文超过一定字符会报错

[ERROR][2023-02-08 12:13:55][open_ai_bot.py:51] - The server had an error while processing your request. Sorry about that!
Traceback (most recent call last):
  File "C:\chatgpt-on-wechat\bot\openai\open_ai_bot.py", line 39, in reply_text
    response = openai.Completion.create(
  File "C:\Program Files\python\lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 115, in create
    response, _, api_key = requestor.request(
  File "C:\Program Files\python\lib\site-packages\openai\api_requestor.py", line 181, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Program Files\python\lib\site-packages\openai\api_requestor.py", line 396, in _interpret_response
    self._interpret_response_line(
  File "C:\Program Files\python\lib\site-packages\openai\api_requestor.py", line 429, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!
[ERROR][2023-02-08 12:13:55][wechat_channel.py:116] - object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "C:\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 112, in _do_send
    reply_text = super().build_reply_content(query, context).strip()
  File "C:\chatgpt-on-wechat\channel\channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "C:\chatgpt-on-wechat\bridge\bridge.py", line 9, in fetch_reply_content
    return bot_factory.create_bot("openAI").reply(query, context)
  File "C:\chatgpt-on-wechat\bot\openai\open_ai_bot.py", line 31, in reply
    Session.save_session(query, reply_content, from_user_id)
  File "C:\chatgpt-on-wechat\bot\openai\open_ai_bot.py", line 157, in save_session
    Session.discard_exceed_conversation(user_session[user_id], max_tokens)
  File "C:\chatgpt-on-wechat\bot\openai\open_ai_bot.py", line 167, in discard_exceed_conversation
    count += len(history_conv["question"]) + len(history_conv["answer"])
TypeError: object of type 'NoneType' has no len()

**Comment by zhayujie** [comment]
> ### 问题描述
> > 简要说明、截图、复现步骤等，也可以是需求或想法
> 
> 上下文超过一定字符会报错
> 
> [ERROR][2023-02-08 12:13:55][open_ai_bot.py:51] - The server had an error while processing your request. Sorry about that! Traceback (most recent call last): File "C:\chatgpt-on-wechat\bot\openai\open_ai_bot.py", line 39, in reply_text response = openai.Completion.create( File "C:\Program Files\python\lib\site-packages\openai\api_resources\completion.py", line 25, in create return super().create(*args, **kwargs) File "C:\Program Files\python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 115, in create response, _, api_key = requestor.request( File "C:\Program Files\python\lib\site-packages\openai\api_requestor.py", line 181, in request resp, got_stream = self._interpret_response(result, stream) File "C:\Program Files\python\lib\site-packages\openai\api_requestor.py", line 396, in _interpret_response self._interpret_response_line( File "C:\Program Files\python\lib\site-packages\openai\api_requestor.py", line 429, in _interpret_response_line raise self.handle_error_response( openai.error.RateLimitError: The server had an error while processing your request. Sorry about that! [ERROR][2023-02-08 12:13:55][wechat_channel.py:116] - object of type 'NoneType' has no len() Traceback (most recent call last): File "C:\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 112, in _do_send reply_text = super().build_reply_content(query, context).strip() File "C:\chatgpt-on-wechat\channel\channel.py", line 31, in build_reply_content return Bridge().fetch_reply_content(query, context) File "C:\chatgpt-on-wechat\bridge\bridge.py", line 9, in fetch_reply_content return bot_factory.create_bot("openAI").reply(query, context) File "C:\chatgpt-on-wechat\bot\openai\open_ai_bot.py", line 31, in reply Session.save_session(query, reply_content, from_user_id) File "C:\chatgpt-on-wechat\bot\openai\open_ai_bot.py", line 157, in save_session Session.discard_exceed_conversation(user_session[user_id], max_tokens) File "C:\chatgpt-on-wechat\bot\openai\open_ai_bot.py", line 167, in discard_exceed_conversation count += len(history_conv["question"]) + len(history_conv["answer"]) TypeError: object of type 'NoneType' has no len()

是最新代码嘛，不是的话重新获取一下
