### ISSUE TITLE
在centos8上 编码问题

### ISSUE THREAD

**Issue by greenhandrocy** [zhayujie/chatgpt-on-wechat#108]
[ERROR][2023-02-08 16:32:00][app.py:20] - App startup failed!
[ERROR][2023-02-08 16:32:00][app.py:21] - 'utf-8' codec can't decode byte 0xed in position 265: invalid continuation byte
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 12, in <module>
    config.load_config()
  File "/root/chatgpt-on-wechat/config.py", line 17, in load_config
    config_str = read_file(config_path)
  File "/root/chatgpt-on-wechat/config.py", line 30, in read_file
    return f.read()
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 265: invalid continuation byte

**Comment by zhayujie** [comment]
config.json 贴一下 (不包括api_key)
