### ISSUE TITLE
msg_signature

### ISSUE THREAD

**Issue by 627171314** [zhayujie/chatgpt-on-wechat#1080]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Railway

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

other

### 复现步骤 🕹

企业微信 Railway部署，填完变量，服务器启动之后，试了几次都是这个错误

### 问题描述 😯

Railway部署企业微信
<img width="729" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/4272272/6f04fc70-81d4-4ab0-a13c-74e6e3408fe9">
把地址输入浏览器时报如下错误：
<img width="779" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/4272272/9b4c04fd-91f4-4e57-81f9-bb401ed3a881">

### 终端日志 📒

```log
[INFO][2023-05-11 09:08:59][wechatcomapp_channel.py:133] - [wechatcom] receive params: <Storage {}>
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/web/utils.py", line 104, in __getattr__
return self[key]
KeyError: 'msg_signature'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/web/application.py", line 280, in process
return self.handle()
File "/usr/local/lib/python3.10/site-packages/web/application.py", line 271, in handle
return self._delegate(fn, self.fvars, args)
File "/usr/local/lib/python3.10/site-packages/web/application.py", line 517, in _delegate
return handle_class(cls)
File "/usr/local/lib/python3.10/site-packages/web/application.py", line 495, in handle_class
return tocall(*args)
File "/app/channel/wechatcom/wechatcomapp_channel.py", line 135, in GET
signature = params.msg_signature
File "/usr/local/lib/python3.10/site-packages/web/utils.py", line 106, in __getattr__
raise AttributeError(k)
AttributeError: 'msg_signature'
192.168.0.4:59306 - - [11/May/2023 09:08:59] "HTTP/1.1 GET /wxcomapp" - 500 Internal Server Error
[INFO][2023-05-11 09:08:59][wechatcomapp_channel.py:133] - [wechatcom] receive params: <Storage {}>
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/web/utils.py", line 104, in __getattr__
return self[key]
KeyError: 'msg_signature'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/web/application.py", line 280, in process
return self.handle()
File "/usr/local/lib/python3.10/site-packages/web/application.py", line 271, in handle
return self._delegate(fn, self.fvars, args)
File "/usr/local/lib/python3.10/site-packages/web/application.py", line 517, in _delegate
return handle_class(cls)
File "/usr/local/lib/python3.10/site-packages/web/application.py", line 495, in handle_class
return tocall(*args)
File "/app/channel/wechatcom/wechatcomapp_channel.py", line 135, in GET
signature = params.msg_signature
File "/usr/local/lib/python3.10/site-packages/web/utils.py", line 106, in __getattr__
raise AttributeError(k)
AttributeError: 'msg_signature'
192.168.0.4:59314 - - [11/May/2023 09:08:59] "HTTP/1.1 GET /wxcomapp" - 500 Internal Server Error
```

**Comment by lanvent** [comment]
出现的报错图正常，因为这个服务本来就不是提供给人访问的。有报错说明国内能访问到railway.app，已经足够了，可以接着进行之后的步骤
