### ISSUE TITLE
概率性报错：The server had an error while processing your request. Sorry about that!

### ISSUE THREAD

**Issue by ronaldinho1000** [zhayujie/chatgpt-on-wechat#109]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
![图片](https://user-images.githubusercontent.com/35184678/217483455-abab0bdc-33c7-4f05-b498-9a26fbcab77e.png)

### 终端日志 (如有报错)
Start auto replying.
[INFO][2023-02-08 16:49:49][open_ai_bot.py:20] - [OPEN_AI] query=你好
[ERROR][2023-02-08 16:49:50][open_ai_bot.py:52] - The server had an error while processing your request. Sorry about that!
Traceback (most recent call last):
  File "bot\openai\open_ai_bot.py", line 48, in reply_text
  File "openai\api_resources\completion.py", line 25, in create
  File "openai\api_resources\abstract\engine_api_resource.py", line 160, in create
  File "openai\api_requestor.py", line 227, in request
  File "openai\api_requestor.py", line 624, in _interpret_response
  File "openai\api_requestor.py", line 681, in _interpret_response_line
openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：windows10 64位
 - Python版本  ( 执行 `python3 -V` )：               python 3.7.8       
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Ratten-fanger** [comment]
见 #50

**Comment by ronaldinho1000** [comment]
出现这种报错时，能否实现下面两种解决措施：
1、提示用户，重新再发送一次；
2、根据异常返回值，内部重新再发送一下用户的指令，并正确返回给用户？
