### ISSUE TITLE
用midjourney-proxy做了个小插件

### ISSUE THREAD

**Issue by Git-HandClup** [zhayujie/chatgpt-on-wechat#1117]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

Openai的画图感觉还是有点不太行，所以想试试看能不能调用midjourney，结果感觉还不错，效果如图

### 举例

![1684403965056](https://github.com/zhayujie/chatgpt-on-wechat/assets/38003767/3e12a8a0-5325-4dd8-b7a7-1368de7835bd)

**Comment by OliverSunWH** [comment]
厉害，期待pr！

**Comment by qxsomeone** [comment]
很棒！

**Comment by mari1995** [comment]
期待

**Comment by HAdesblog** [comment]
大佬牛逼

**Comment by Git-HandClup** [comment]
其实我这个插件的实际代码很少，主要是请求了midjourney-proxy这个项目的接口，这个在github上是开源的，我只是借用了一下，搭建起来不麻烦但是需要多起两个服务，所以如果是非必须的情况下其实也没必要这么做，有能力的可以按照这个项目的思路做个完全在插件中调用的。

**Comment by adminlove520** [comment]
> 其实我这个插件的实际代码很少，主要是请求了midjourney-proxy这个项目的接口，这个在github上是开源的，我只是借用了一下，搭建起来不麻烦但是需要多起两个服务，所以如果是非必须的情况下其实也没必要这么做，有能力的可以按照这个项目的思路做个完全在插件中调用的。

请问如何调用呢

**Comment by adminlove520** [comment]
我现在就差插件  midjourney-proxy这个搞定了

**Comment by Git-HandClup** [comment]
> 我现在就差插件 midjourney-proxy这个搞定了

midjourney那边画完以后会回调指定的接口，我这边指定的接口所做的事是直接将返回的结果存到了redis，然后在插件这边我做的是将请求传给midjourney-proxy以后就开始按照提供的任务ID每隔30s查询一次redis，等查询到有结果以后就将图片链接提供给Reply了，不过因为图片链接是需要代理才能访问的，所以我这边还改了一下wechat_channel的源码，在get图片链接的时候通过代理服务器。

**Comment by Git-HandClup** [comment]
> > 我现在就差插件 midjourney-proxy这个搞定了
> 
> midjourney那边画完以后会回调指定的接口，我这边指定的接口所做的事是直接将返回的结果存到了redis，然后在插件这边我做的是将请求传给midjourney-proxy以后就开始按照提供的任务ID每隔30s查询一次redis，等查询到有结果以后就将图片链接提供给Reply了，不过因为图片链接是需要代理才能访问的，所以我这边还改了一下wechat_channel的源码，在get图片链接的时候通过代理服务器。

但是midjourney那边在发生异常或者错误的时候不会回调接口，所以为了避免插件一直轮询redis，我这边做的是设置超出指定时间后就直接return，最后直接回复超时错误。

**Comment by adminlove520** [comment]
> > > 我现在就差插件 midjourney-proxy这个搞定了
> > 
> > 
> > midjourney那边画完以后会回调指定的接口，我这边指定的接口所做的事是直接将返回的结果存到了redis，然后在插件这边我做的是将请求传给midjourney-proxy以后就开始按照提供的任务ID每隔30s查询一次redis，等查询到有结果以后就将图片链接提供给Reply了，不过因为图片链接是需要代理才能访问的，所以我这边还改了一下wechat_channel的源码，在get图片链接的时候通过代理服务器。
> 
> 但是midjourney那边在发生异常或者错误的时候不会回调接口，所以为了避免插件一直轮询redis，我这边做的是设置超出指定时间后就直接return，最后直接回复超时错误。

[plugin_midjourney](https://github.com/ffwen123/plugin_midjourney.git)
我看到一个仓库 貌似也是插件 这个逻辑可以参考下

**Comment by Git-HandClup** [comment]
> > > > 我现在就差插件 midjourney-proxy这个搞定了
> > > 
> > > 
> > > midjourney那边画完以后会回调指定的接口，我这边指定的接口所做的事是直接将返回的结果存到了redis，然后在插件这边我做的是将请求传给midjourney-proxy以后就开始按照提供的任务ID每隔30s查询一次redis，等查询到有结果以后就将图片链接提供给Reply了，不过因为图片链接是需要代理才能访问的，所以我这边还改了一下wechat_channel的源码，在get图片链接的时候通过代理服务器。
> > 
> > 
> > 但是midjourney那边在发生异常或者错误的时候不会回调接口，所以为了避免插件一直轮询redis，我这边做的是设置超出指定时间后就直接return，最后直接回复超时错误。
> 
> [plugin_midjourney](https://github.com/ffwen123/plugin_midjourney.git) 我看到一个仓库 貌似也是插件 这个逻辑可以参考下

它这个好像就没有调用discord频道的机器人，直接调用自己的账号去给midjourney发送指令，这个就很方便。

**Comment by Git-HandClup** [comment]
> > > > 我现在就差插件 midjourney-proxy这个搞定了
> > > 
> > > 
> > > midjourney那边画完以后会回调指定的接口，我这边指定的接口所做的事是直接将返回的结果存到了redis，然后在插件这边我做的是将请求传给midjourney-proxy以后就开始按照提供的任务ID每隔30s查询一次redis，等查询到有结果以后就将图片链接提供给Reply了，不过因为图片链接是需要代理才能访问的，所以我这边还改了一下wechat_channel的源码，在get图片链接的时候通过代理服务器。
> > 
> > 
> > 但是midjourney那边在发生异常或者错误的时候不会回调接口，所以为了避免插件一直轮询redis，我这边做的是设置超出指定时间后就直接return，最后直接回复超时错误。
> 
> [plugin_midjourney](https://github.com/ffwen123/plugin_midjourney.git) 我看到一个仓库 貌似也是插件 这个逻辑可以参考下

我之前找了半天都没找到（可能是我不太会找，所以就干脆用别的项目接口来调用midjourney，实际上这么做蛮折腾

**Comment by adminlove520** [comment]
> > > > > 我现在就差插件 midjourney-proxy这个搞定了
> > > > 
> > > > 
> > > > midjourney那边画完以后会回调指定的接口，我这边指定的接口所做的事是直接将返回的结果存到了redis，然后在插件这边我做的是将请求传给midjourney-proxy以后就开始按照提供的任务ID每隔30s查询一次redis，等查询到有结果以后就将图片链接提供给Reply了，不过因为图片链接是需要代理才能访问的，所以我这边还改了一下wechat_channel的源码，在get图片链接的时候通过代理服务器。
> > > 
> > > 
> > > 但是midjourney那边在发生异常或者错误的时候不会回调接口，所以为了避免插件一直轮询redis，我这边做的是设置超出指定时间后就直接return，最后直接回复超时错误。
> > 
> > 
> > [plugin_midjourney](https://github.com/ffwen123/plugin_midjourney.git) 我看到一个仓库 貌似也是插件 这个逻辑可以参考下
> 
> 我之前找了半天都没找到（可能是我不太会找，所以就干脆用别的项目接口来调用midjourney，实际上这么做蛮折腾

proxy那个项目最近也在迭代呢   我去 不会是群友吧。。。。

**Comment by Git-HandClup** [comment]
> > > > > > 我现在就差插件 midjourney-proxy这个搞定了
> > > > > 
> > > > > 
> > > > > midjourney那边画完以后会回调指定的接口，我这边指定的接口所做的事是直接将返回的结果存到了redis，然后在插件这边我做的是将请求传给midjourney-proxy以后就开始按照提供的任务ID每隔30s查询一次redis，等查询到有结果以后就将图片链接提供给Reply了，不过因为图片链接是需要代理才能访问的，所以我这边还改了一下wechat_channel的源码，在get图片链接的时候通过代理服务器。
> > > > 
> > > > 
> > > > 但是midjourney那边在发生异常或者错误的时候不会回调接口，所以为了避免插件一直轮询redis，我这边做的是设置超出指定时间后就直接return，最后直接回复超时错误。
> > > 
> > > 
> > > [plugin_midjourney](https://github.com/ffwen123/plugin_midjourney.git) 我看到一个仓库 貌似也是插件 这个逻辑可以参考下
> > 
> > 
> > 我之前找了半天都没找到（可能是我不太会找，所以就干脆用别的项目接口来调用midjourney，实际上这么做蛮折腾
> 
> proxy那个项目最近也在迭代呢 我去 不会是群友吧。。。。

我没加群哈哈哈，我就是昨天找到了这个项目然后拿来做了，可惜垫图的功能还没做出来，只能静静等待作者的迭代了

**Comment by qq460046000** [comment]
期待

**Comment by Git-HandClup** [comment]
插件已更新至最新版，最新版可支持垫图、以及根据图片生成描述，插件地址：[https://github.com/Git-HandClup/plugin_midjourney](https://github.com/Git-HandClup/plugin_midjourney)，请详细阅读使用说明后再考虑是否需要使用。

**Comment by zhaoxitao** [comment]
> > > > > 我现在就差插件 midjourney-proxy这个搞定了
> > > > 
> > > > 
> > > > midjourney那边画完以后会回调指定的接口，我这边指定的接口所做的事是直接将返回的结果存到了redis，然后在插件这边我做的是将请求传给midjourney-proxy以后就开始按照提供的任务ID每隔30s查询一次redis，等查询到有结果以后就将图片链接提供给Reply了，不过因为图片链接是需要代理才能访问的，所以我这边还改了一下wechat_channel的源码，在get图片链接的时候通过代理服务器。
> > > 
> > > 
> > > 但是midjourney那边在发生异常或者错误的时候不会回调接口，所以为了避免插件一直轮询redis，我这边做的是设置超出指定时间后就直接return，最后直接回复超时错误。
> > 
> > 
> > [plugin_midjourney](https://github.com/ffwen123/plugin_midjourney.git) 我看到一个仓库 貌似也是插件 这个逻辑可以参考下
> 
> 它这个好像就没有调用discord频道的机器人，直接调用自己的账号去给midjourney发送指令，这个就很方便。

我研究了一下，其实他也不是调用Discord频道的机器人，因为据我了解目前Midjourney官方就没有开发过MJ的API接口，他这个也是走的一个第三方API去执行MJ的命令的，这个第三方API是付费的，40刀/月。

**Comment by Git-HandClup** [comment]
> > > > > > 我现在就差插件 midjourney-proxy这个搞定了
> > > > > 
> > > > > 
> > > > > midjourney那边画完以后会回调指定的接口，我这边指定的接口所做的事是直接将返回的结果存到了redis，然后在插件这边我做的是将请求传给midjourney-proxy以后就开始按照提供的任务ID每隔30s查询一次redis，等查询到有结果以后就将图片链接提供给Reply了，不过因为图片链接是需要代理才能访问的，所以我这边还改了一下wechat_channel的源码，在get图片链接的时候通过代理服务器。
> > > > 
> > > > 
> > > > 但是midjourney那边在发生异常或者错误的时候不会回调接口，所以为了避免插件一直轮询redis，我这边做的是设置超出指定时间后就直接return，最后直接回复超时错误。
> > > 
> > > 
> > > [plugin_midjourney](https://github.com/ffwen123/plugin_midjourney.git) 我看到一个仓库 貌似也是插件 这个逻辑可以参考下
> > 
> > 
> > 它这个好像就没有调用discord频道的机器人，直接调用自己的账号去给midjourney发送指令，这个就很方便。
> 
> 我研究了一下，其实他也不是调用Discord频道的机器人，因为据我了解目前Midjourney官方就没有开发过MJ的API接口，他这个也是走的一个第三方API去执行MJ的命令的，这个第三方API是付费的，40刀/月。

不太清楚，midjourney-proxy这个项目没有研究过，只是当时看到这个能用就尝试了一下， 目前使用起来也都一切正常，关于Midjourney官方的api我在两个月前付费的时候在订阅界面看到有api的选项入口，但是点进去就是报错的，所以我寻思后续可能会有官方的api出来，其他的我就没有做过多的了解。

**Comment by mouxangithub** [comment]
我也做了个[`midjourney`]https://github.com/[mouxangithub/midjourney](https://github.com/mouxangithub/midjourney)，也是基于midjourney-proxy请求他的api

**Comment by Dhl9864** [comment]
[ERROR][2023-10-27 14:27:36][chat_channel.py:284] - Worker return exception: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhl/code/chatgpt-on-wechat-1.3.9.5/channel/chat_channel.py", line 155, in _handle
    reply = self._generate_reply(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhl/code/chatgpt-on-wechat-1.3.9.5/channel/chat_channel.py", line 165, in _generate_reply
    e_context = PluginManager().emit_event(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhl/code/chatgpt-on-wechat-1.3.9.5/plugins/plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/home/dhl/code/chatgpt-on-wechat-1.3.9.5/plugins/plugin_midjourney/mj.py", line 75, in on_handle_context
    image = self._get_midjourney_task(imagine["result"], "image")
                                      ~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
这啥情况啊作者大大

**Comment by effectZz** [comment]
> 我也做了个插件：https://github.com/mouxangithub/midjourney 也是基于midjourney-proxy请求他的api

大佬，昨天刚接了这个，很好用。

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
