### ISSUE TITLE
pip3 install --upgrade openai后报错！是使用的pyton版本有问题吗

### ISSUE THREAD

**Issue by shelleiey** [zhayujie/chatgpt-on-wechat#112]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.8.5
3. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
pip3 install --upgrade openai后报错
是使用的pyton版本有问题吗

Could not find a version that satisfies the requirement pandas>=1.2.3 (from openai) (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
No matching distribution found for pandas>=1.2.3 (from openai)

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：
[root@VM-24-8-centos ~]# python3 -V
Python 3.6.8
[root@VM-24-8-centos ~]# pip3 -V
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
[root@VM-24-8-centos ~]# python3 -m pip install --upgrade pip

**Comment by shelleiey** [comment]
[ERROR][2023-02-08 18:24:21][wechat_channel.py:116] - No module named 'openai'
Traceback (most recent call last):
  File "/opt/chatgpt-on-wechat-master/channel/wechat/wechat_channel.py", line 112, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "/opt/chatgpt-on-wechat-master/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/opt/chatgpt-on-wechat-master/bridge/bridge.py", line 9, in fetch_reply_content
    return bot_factory.create_bot("openAI").reply(query, context)
  File "/opt/chatgpt-on-wechat-master/bot/bot_factory.py", line 24, in create_bot
    from bot.openai.open_ai_bot import OpenAIBot
  File "/opt/chatgpt-on-wechat-master/bot/openai/open_ai_bot.py", line 6, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Comment by chuwei** [comment]
[root@VM-4-7-centos chatgpt-on-wechat]# pip3 install --upgrade openai
Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
Collecting openai
  Using cached http://mirrors.tencentyun.com/pypi/packages/35/41/eefdec12990436f746e39a16ccfcfbd8693cd8a5762014f27ec216d2487d/openai-0.26.5.tar.gz (55 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-ewun0254/openai.egg-info
      writing /tmp/pip-modern-metadata-ewun0254/openai.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-ewun0254/openai.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-modern-metadata-ewun0254/openai.egg-info/entry_points.txt
      writing requirements to /tmp/pip-modern-metadata-ewun0254/openai.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-ewun0254/openai.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-ewun0254/openai.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-ewun0254/openai.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-ewun0254/openai.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-ewun0254/openai-0.26.5.dist-info'
      /tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/dist.py:778: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
        % (opt, underscore_opt)
      Traceback (most recent call last):
        File "/usr/local/python3.7/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/python3.7/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/python3.7/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/command/dist_info.py", line 101, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 958, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/tmp/pip-build-env-fn3l3cd_/overlay/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
          module = import_module(match.group('module'))
        File "/usr/local/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/tmp/pip-build-env-fn3l3cd_/normal/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 28, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-fn3l3cd_/normal/lib/python3.7/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/usr/local/python3.7/lib/python3.7/ctypes/__init__.py", line 7, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


操作系统类型 (Mac/Windows/Linux)：centOS8
Python版本 ( 执行 python3 -V )：Python 3.7.16
pip版本 ( 依赖问题此项必填，执行 pip3 -V)：pip 23.0

**Comment by shelleiey** [comment]
Collecting openai
  Downloading http://mirrors.tencentyun.com/pypi/packages/79/b8/8d3986ab63b4a6d6149d015e3f4ddd3d3eac4a3dc71c484d448f138940e1/openai-0.10.5.tar.gz (157kB)
    100% |████████████████████████████████| 163kB 1.3MB/s 
Requirement already up-to-date: requests>=2.20 in /usr/local/lib/python3.6/site-packages (from openai)
Collecting tqdm (from openai)
  Downloading http://mirrors.tencentyun.com/pypi/packages/47/bb/849011636c4da2e44f1253cd927cfb20ada4374d8b3a4e425416e84900cc/tqdm-4.64.1-py2.py3-none-any.whl (78kB)
    100% |████████████████████████████████| 81kB 301kB/s 
Collecting pandas>=1.2.3 (from openai)
  Could not find a version that satisfies the requirement pandas>=1.2.3 (from openai) (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
No matching distribution found for pandas>=1.2.3 (from openai)

**Comment by ChunlinYu** [comment]
我也遇到了，我是更新了pip，然后pip手动安装panda就可以了

**Comment by shelleiey** [comment]
> 我也遇到了，我是更新了pip，然后pip手动安装panda就可以了

我是安装python有问题导致的

**Comment by shelleiey** [comment]
Login successfully as Colin
Start auto replying.
[INFO][2023-02-08 19:59:56][open_ai_bot.py:71] - [OPEN_AI] image_query=一个黑狗和一个菜狗
[ERROR][2023-02-08 19:59:56][open_ai_bot.py:89] - module 'openai' has no attribute 'Image'
Traceback (most recent call last):
  File "/opt/chatgpt-on-wechat-master/bot/openai/open_ai_bot.py", line 72, in create_img
    response = openai.Image.create(
AttributeError: module 'openai' has no attribute 'Image'
这个问题  应该怎么解决  不能画图  网上都说是openai版本过低，但是我已经更新了 还是不行
[root@VM-24-8-centos ~]# pip show openai
Name: openai
Version: 0.26.5
Summary: Python client library for the OpenAI API
Home-page: https://github.com/openai/openai-python
Author: OpenAI
Author-email: support@openai.com
License: 
Location: /usr/local/lib/python3.8/site-packages
Requires: aiohttp, requests, tqdm
Required-by:

**Comment by ronaldinho1000** [comment]
自己去openai 的官网，下载最新的版本0.26.4，解压出来之后，直接替换python 下openai 里面的所有内容，imageCreate 就可以正常使用了

**Comment by zhayujie** [comment]
你的python3 指向的是3.6

可以这样安装
python3.8 -m pip install --upgrade openai

**Comment by ChunlinYu** [comment]
启动命令 你改成python3.8启动试一下：  nohup python3.8 app.py & tail -f nohup.out

**Comment by wuhonghui123** [comment]
我遇到这个问题升级pip后就搞定了
sudo python3 -m pip install --upgrade pip
