### ISSUE TITLE
个人wx使用itchat登陆失败

### ISSUE THREAD

**Issue by CurisZhou** [zhayujie/chatgpt-on-wechat#1123]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

个人wx, 使用itchat, 扫码登陆报错：
requests.exceptions.SSLError: HTTPSConnectionPool(host='wx8.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=CATJ6As_ciAJipxAA5A36VRa@qrticket_0&uuid=gabd4yAs4Q==&lang=zh_CN&scan=1674697036 (Caused by SSLError(SSLCertVerificationError("hostname 'wx8.qq.com' doesn't match either of 'wx.qq.com', '*.web.wechat.com', '*.web1.wechat.com', '*.web2.wechat.com', '*.wechat.com', '*.weixin.qq.com', '*.wx.qq.com', '*.wx1.qq.com', '*.wx2.qq.com', 'wechat.com', 'weixin.qq.com', 'wx1.qq.com', 'wx2.qq.com'")))

### 问题描述 😯

使用的个人微信是老微信号，微信号可正常使用。5月18号前使用itchat登陆没问题，并且程序可以一直保持登陆状态自动回复。18号之后微信突然 LOG OUT 了，接着再使用个人微信号登陆，就一直报这个 "hostname 'wx8.qq.com' doesn't match" 的错误无法登陆桌面微信。求各位大佬帮忙看看是咋回事🙏

### 终端日志 📒

```log
<PIL.PngImagePlugin.PngImageFile image mode=1 size=450x450 at 0x7F3694768520>
[ERROR][2023-05-19 13:03:36][app.py:52] - App startup failed!

[ERROR][2023-05-19 13:03:36][app.py:53] - HTTPSConnectionPool(host='wx8.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket= CATJ6As_ciAJipxAA5A36VRa@qrticket_0&uuid= gabd4yAs4Q ==&lang=zh_CN&scan= 1674697036 (Caused by SSLError(SSLCertVerificationError("hostname 'wx8.qq.com' doesn't match either of 'wx.qq.com', '*.web.wechat.com', '*.web1.wechat.com', '*.web2.wechat.com', '*.wechat.com', '*.weixin.qq.com', '*.wx.qq.com', '*.wx1.qq.com', '*.wx2.qq.com', 'wechat.com', 'weixin.qq.com', 'wx1.qq.com', 'wx2.qq.com'")))
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 464, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 512, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/root/anaconda3/lib/python3.8/ssl.py", line 416, in match_hostname
    raise CertificateError("hostname %r "
ssl.SSLCertVerificationError: ("hostname 'wx8.qq.com' doesn't match either of 'wx.qq.com', '*.web.wechat.com', '*.web1.wechat.com', '*.web2.wechat.com', '*.wechat.com', '*.weixin.qq.com', '*.wx.qq.com', '*.wx1.qq.com', '*.wx2.qq.com', 'wechat.com', 'weixin.qq.com', 'wx1.qq.com', 'wx2.qq.com'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx8.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket= CATJ6As_ciAJipxAA5A36VRa@qrticket_0&uuid= gabd4yAs4Q ==&lang=zh_CN&scan= 1674697036 (Caused by SSLError(SSLCertVerificationError("hostname 'wx8.qq.com' doesn't match either of 'wx.qq.com', '*.web.wechat.com', '*.web1.wechat.com', '*.web2.wechat.com', '*.wechat.com', '*.weixin.qq.com', '*.wx.qq.com', '*.wx1.qq.com', '*.wx2.qq.com', 'wechat.com', 'weixin.qq.com', 'wx1.qq.com', 'wx2.qq.com'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 50, in run
    channel.startup()
  File "/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 116, in startup
    itchat.auto_login(
  File "/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/chatgpt-on-wechat/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/chatgpt-on-wechat/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/chatgpt-on-wechat/lib/itchat/components/login.py", line 177, in process_login_info
    r = core.s.get(core.loginInfo['url'],
  File "/root/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)

requests.exceptions.SSLError: HTTPSConnectionPool(host='wx8.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=CATJ6As_ciAJipxAA5A36VRa@qrticket_0&uuid=gabd4yAs4Q==&lang=zh_CN&scan=1674697036 (Caused by SSLError(SSLCertVerificationError("hostname 'wx8.qq.com' doesn't match either of 'wx.qq.com', '*.web.wechat.com', '*.web1.wechat.com', '*.web2.wechat.com', '*.wechat.com', '*.weixin.qq.com', '*.wx.qq.com', '*.wx1.qq.com', '*.wx2.qq.com', 'wechat.com', 'weixin.qq.com', 'wx1.qq.com', 'wx2.qq.com'")))
```

**Comment by zhayujie** [comment]
删掉本地的  itchat.pkl  重启试试

**Comment by CurisZhou** [comment]
> 删掉本地的 itchat.pkl 重启试试

大佬好，我看了下，我之前是用的enableCmdOR=2的方式登录的，不是热加载，貌似没有itchat.pkl文件生成？😂

**Comment by lanvent** [comment]
<img width="767" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/26515464/325fb1b4-1e6d-459f-a0b3-a42462f108ef">

这个是wx的问题了，它没有把wx8.qq.com加到证书里。如果手机微信重新上下线一直是这个情况，建议在requests的部分增加参数verify=False

**Comment by daidaixiaoge** [comment]
> <img alt="image" width="767" src="https://user-images.githubusercontent.com/26515464/239813431-325fb1b4-1e6d-459f-a0b3-a42462f108ef.png">
> 这个是wx的问题了，它没有把wx8.qq.com加到证书里。如果手机微信重新上下线一直是这个情况，建议在requests的部分增加参数verify=False

所以具体怎么操作呢，可以详细说说吗，网页版微信一直登录不了

**Comment by qjhe** [comment]
不能用了吗，我的扫描二维码打印下面内容后就停止了
raceback (most recent call last):
  File "/Users/andou/ssProducts/wechatyPy/1.py", line 10, in <module>
    itchat.auto_login()
  File "/Users/andou/.pyenv/versions/3.9.2/lib/python3.9/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/andou/.pyenv/versions/3.9.2/lib/python3.9/site-packages/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/Users/aaa/.pyenv/versions/3.9.2/lib/python3.9/site-packages/itchat/components/login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "/Users/aaa/.pyenv/versions/3.9.2/lib/python3.9/site-packages/itchat/components/login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/Users/aaa/.pyenv/versions/3.9.2/lib/python3.9/xml/dom/minidom.py", line 1998, in parseString
    return expatbuilder.parseString(string)
  File "/Users/aaa/.pyenv/versions/3.9.2/lib/python3.9/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/Users/aaa/.pyenv/versions/3.9.2/lib/python3.9/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4

**Comment by classmateoula** [comment]
我也是
```
Please press confirm on your phone.
<PIL.PngImagePlugin.PngImageFile image mode=1 size=450x450 at 0x7F3D84A400D0>
[ERROR][2024-06-11 16:40:22][wechat_channel.py:135] - 'wxsid'
Traceback (most recent call last):
  File "/app/channel/wechat/wechat_channel.py", line 121, in startup
    itchat.auto_login(
  File "/app/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/app/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/app/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/app/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
```
