### ISSUE TITLE
Macos python3.10。

### ISSUE THREAD

**Issue by chaos2021699054** [zhayujie/chatgpt-on-wechat#1124]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

app.py 后

### 问题描述 😯

[INFO][2023-05-20 13:36:30][config.py:145] - [Config] User datas file not found, ignore.
[ERROR][2023-05-20 13:36:30][app.py:52] - App startup failed!
[ERROR][2023-05-20 13:36:30][app.py:53] - No module named 'requests'
Traceback (most recent call last):
  File "/Users/arbotyoung/chatgpt-on-wechat/app.py", line 45, in run
    channel = channel_factory.create_channel(channel_name)
  File "/Users/arbotyoung/chatgpt-on-wechat/channel/channel_factory.py", line 13, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "/Users/arbotyoung/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

### 终端日志 📒

```log
<此处粘贴终端日志>
```chatgpt-on-wechat % python3 app.py
[INFO][2023-05-20 13:36:30][config.py:195] - [INIT] load config: {'open_ai_api_key': '保密', 'model': 'gpt-3.5-turbo', 'proxy': '127.0.0.1:7890', 'single_chat_prefix': ['', ''], 'single_chat_reply_prefix': '[] ', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ChatGPT测试群', 'ChatGPT测试群2'], 'group_chat_in_one_session': ['ChatGPT测试群'], 'image_create_prefix': ['画', '看', '找'], 'speech_recognition': False, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 1000, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'subscribe_msg': '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。'}
[INFO][2023-05-20 13:36:30][config.py:145] - [Config] User datas file not found, ignore.
[ERROR][2023-05-20 13:36:30][app.py:52] - App startup failed!
[ERROR][2023-05-20 13:36:30][app.py:53] - No module named 'requests'
Traceback (most recent call last):
  File "/Users/arbotyoung/chatgpt-on-wechat/app.py", line 45, in run
    channel = channel_factory.create_channel(channel_name)
  File "/Users/arbotyoung/chatgpt-on-wechat/channel/channel_factory.py", line 13, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "/Users/arbotyoung/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
arbotyoung@bogon chatgpt-on-wechat % python3 
Python 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D

**Comment by zhayujie** [comment]
有成功安装依赖嘛， python3 -m  pip install -r requirements.txt

**Comment by chaos2021699054** [comment]
上面是没问题了，但是我扫完二维码后又出现了这个
【二维码】
Please press confirm on your phone.
[ERROR][2023-05-20 15:07:37][app.py:52] - App startup failed!
[ERROR][2023-05-20 15:07:37][app.py:53] - 'wxsid'
Traceback (most recent call last):
  File "/Users/arbotyoung/chatgpt-on-wechat/app.py", line 50, in run
    channel.startup()
  File "/Users/arbotyoung/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 116, in startup
    itchat.auto_login(
  File "/Users/arbotyoung/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/arbotyoung/chatgpt-on-wechat/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/Users/arbotyoung/chatgpt-on-wechat/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/Users/arbotyoung/chatgpt-on-wechat/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
arbotyoung@bogon chatgpt-on-wechat %

**Comment by chaos2021699054** [comment]
> 有成功安装依赖嘛， python3 -m pip install -r requirements.txt

已经安装上了
现在又出现了这个
扫完二维码

Please press confirm on your phone.
[ERROR][2023-05-20 15:07:37][app.py:52] - App startup failed!
[ERROR][2023-05-20 15:07:37][app.py:53] - 'wxsid'
Traceback (most recent call last):
  File "/Users/arbotyoung/chatgpt-on-wechat/app.py", line 50, in run
    channel.startup()
  File "/Users/arbotyoung/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 116, in startup
    itchat.auto_login(
  File "/Users/arbotyoung/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/arbotyoung/chatgpt-on-wechat/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/Users/arbotyoung/chatgpt-on-wechat/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/Users/arbotyoung/chatgpt-on-wechat/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
arbotyoung@bogon chatgpt-on-wechat %

**Comment by chaos2021699054** [comment]
已解决

**Comment by chaos2021699054** [comment]
> 有成功安装依赖嘛， python3 -m pip install -r requirements.txt

已解决
