### ISSUE TITLE
突发无法登陆

### ISSUE THREAD

**Issue by Tyler913** [zhayujie/chatgpt-on-wechat#1126]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

微信扫码登录后一直显示这个然后就logout了

### 问题描述 😯

突然就无法使用了，之前都是使用的非常愉快的

### 终端日志 📒

```log
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/itchat/components/login.py", line 288, in maintain_loop
    i = sync_check(self)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/itchat/components/login.py", line 351, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range

Traceback (most recent call last):
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/connection.py", line 429, in connect
    tls_in_tls=tls_in_tls,
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1684571989739&skey=%40crypt_c670da4_8ad8cffd4eacb6c32b0573d4674bbbf6&sid=wOSbNbuBi%2F6jZmoO&uin=404606428&deviceid=e503234878281657&synckey=1_808515657%7C2_808515697%7C3_808515554%7C1000_1684567860&_=1684571984497 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/itchat/components/login.py", line 348, in sync_check
    timeout=config.TIMEOUT)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1684571989739&skey=%40crypt_c670da4_8ad8cffd4eacb6c32b0573d4674bbbf6&sid=wOSbNbuBi%2F6jZmoO&uin=404606428&deviceid=e503234878281657&synckey=1_808515657%7C2_808515697%7C3_808515554%7C1000_1684567860&_=1684571984497 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/itchat/components/login.py", line 288, in maintain_loop
    i = sync_check(self)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/itchat/components/login.py", line 351, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range

Traceback (most recent call last):
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/connection.py", line 429, in connect
    tls_in_tls=tls_in_tls,
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1684571990769&skey=%40crypt_c670da4_8ad8cffd4eacb6c32b0573d4674bbbf6&sid=wOSbNbuBi%2F6jZmoO&uin=404606428&deviceid=e503234878281657&synckey=1_808515657%7C2_808515697%7C3_808515554%7C1000_1684567860&_=1684571984498 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/itchat/components/login.py", line 348, in sync_check
    timeout=config.TIMEOUT)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1684571990769&skey=%40crypt_c670da4_8ad8cffd4eacb6c32b0573d4674bbbf6&sid=wOSbNbuBi%2F6jZmoO&uin=404606428&deviceid=e503234878281657&synckey=1_808515657%7C2_808515697%7C3_808515554%7C1000_1684567860&_=1684571984498 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/itchat/components/login.py", line 288, in maintain_loop
    i = sync_check(self)
  File "/home/liandan/anaconda3/envs/GPTWechat/lib/python3.7/site-packages/itchat/components/login.py", line 351, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range

LOG OUT!
```

**Comment by bentennysonyoung** [comment]
什么套圈高手，要不试试全新服务器，重装python3.8以上版本再试试。

**Comment by lanvent** [comment]
检查网络环境，配合搜索引擎工具

**Comment by Tyler913** [comment]
> 什么套圈高手，要不试试全新服务器，重装python3.8以上版本再试试。

我试试看，主要是服务器没办法换新的，但是环境可以试试重新来！，感谢哈
