### ISSUE TITLE
二维码扫描登陆正常，发消息后台出错

### ISSUE THREAD

**Issue by kenixxie** [zhayujie/chatgpt-on-wechat#113]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
Start auto replying.
[ERROR][2023-02-08 12:28:25][wechat_channel.py:116] - No module named 'openai'
Traceback (most recent call last):
  File "/home/jxsas/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 112, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "/home/jxsas/chatgpt-on-wechat/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/home/jxsas/chatgpt-on-wechat/bridge/bridge.py", line 9, in fetch_reply_content
    return bot_factory.create_bot("openAI").reply(query, context)
  File "/home/jxsas/chatgpt-on-wechat/bot/bot_factory.py", line 24, in create_bot
    from bot.openai.open_ai_bot import OpenAIBot
  File "/home/jxsas/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 6, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
[ERROR][2023-02-08 12:28:33][wechat_channel.py:116] - No module named 'openai'
Traceback (most recent call last):
  File "/home/jxsas/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 112, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "/home/jxsas/chatgpt-on-wechat/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/home/jxsas/chatgpt-on-wechat/bridge/bridge.py", line 9, in fetch_reply_content
    return bot_factory.create_bot("openAI").reply(query, context)
  File "/home/jxsas/chatgpt-on-wechat/bot/bot_factory.py", line 24, in create_bot
    from bot.openai.open_ai_bot import OpenAIBot
  File "/home/jxsas/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 6, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'


### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Linux
 - Python版本  ( 执行 `python3 -V` )：   Python 3.10.7                   
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 22.2 from /usr/lib/python3/dist-packages/pip (python 3.10

**Comment by tjc6386675** [comment]
同问

**Comment by zhayujie** [comment]
see #88

**Comment by zhayujie** [comment]
执行 pip3 show openai 看看有没有下载

**Comment by kenixxie** [comment]
已经解决了，就是python新旧版本环境变量的问题，作者在另外一个issue中已回答了。




发自我的手机


-------- 原始邮件 --------
发件人： zhayujie ***@***.***>
日期： 2023年2月8日周三 23:30
收件人： zhayujie/chatgpt-on-wechat ***@***.***>
抄送： kenixxie ***@***.***>, Author ***@***.***>
主 题： Re: [zhayujie/chatgpt-on-wechat] 二维码扫描登陆正常，发消息后台出错 (Issue #113)

执行 pip3 show openai 看看有没有下载

―
