### ISSUE TITLE
已安装了各种库，但一旦会话就提示OpenAI找不到

### ISSUE THREAD

**Issue by NeoGoal** [zhayujie/chatgpt-on-wechat#1134]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

![8f5d32d1da6e250fb5be2b08fd9d06f](https://github.com/zhayujie/chatgpt-on-wechat/assets/114658875/d39f0614-ab77-403a-9511-183dc07d3c96)
![5f87cb570d0b3333ca47bc83223657a](https://github.com/zhayujie/chatgpt-on-wechat/assets/114658875/e903dedc-f647-4469-99c2-9451de82b85c)
![7745ed1db9484f2d5ba4cd9a36710e7](https://github.com/zhayujie/chatgpt-on-wechat/assets/114658875/d999ce6a-5fa8-4c22-bf75-ffbe009252b2)

### 问题描述 😯

请大神知道，我在railway等第三方docker上均没有这个问题，用了Singapore的tx云服务器，三天了，重复装系统，升级python，安装包，都是一样的错误，不得已求助大神，谢谢！

### 终端日志 📒

```log
Login successfully as 睿睿
[INFO][2023-05-22 14:32:14][wechat_channel.py:112] - Wechat login success, user_id: @d6a6c2bfac8eec884252c7b73d2ee603391db96fb07f9fe99b883d14b990136b, nickname: 睿睿
Start auto replying.
[INFO][2023-05-22 14:32:47][bridge.py:28] - create bot chatGPT for chat
[ERROR][2023-05-22 14:32:47][chat_channel.py:240] - Worker return exception: No module named 'openai'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/www/wwwroot/yyai-3/channel/chat_channel.py", line 128, in _handle
    reply = self._generate_reply(context)
  File "/www/wwwroot/yyai-3/channel/chat_channel.py", line 139, in _generate_reply
    'channel': self, 'context': context, 'reply': reply}))
  File "/www/wwwroot/yyai-3/plugins/plugin_manager.py", line 159, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/www/wwwroot/yyai-3/plugins/role/role.py", line 95, in on_handle_context
    bot = Bridge().get_bot("chat")
  File "/www/wwwroot/yyai-3/bridge/bridge.py", line 34, in get_bot
    self.bots[typename] = bot_factory.create_bot(self.btype[typename])
  File "/www/wwwroot/yyai-3/bot/bot_factory.py", line 20, in create_bot
    from bot.chatgpt.chat_gpt_bot import ChatGPTBot
  File "/www/wwwroot/yyai-3/bot/chatgpt/chat_gpt_bot.py", line 5, in <module>
    from bot.openai.open_ai_image import OpenAIImage
  File "/www/wwwroot/yyai-3/bot/openai/open_ai_image.py", line 2, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
Log in time out, reloading QR code.
Getting uuid of QR code.
Downloading QR code.
You can also scan QRCode in any website below:
```

**Comment by NeoGoal** [comment]
已验证，是tx云的问题，换了环境就好了
