### ISSUE TITLE
小号不能登录

### ISSUE THREAD

**Issue by iKingEast** [zhayujie/chatgpt-on-wechat#114]
### 前置确认

1. 运行于国外网络环境，开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

今天刚装好，用自己的微信大号登录问问题一切正常，vps重启，用新手机注册了个新微信，并且把这个信号拉进群。
用这个新微信不能登录，换回老号能登陆。

### 终端日志 (如有报错)
Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-02-08 20:09:14][app.py:19] - App startup failed!
[ERROR][2023-02-08 20:09:14][app.py:20] - list index out of range
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 17, in <module>
    channel.startup()
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/lib/python3.9/dist-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.9/dist-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/usr/local/lib/python3.9/dist-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.9/dist-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

### 环境

 - 操作系统类型  (Linux)：
 - Python版本  ( 执行 `python3.9` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by iKingEast** [comment]
小号没有实名所以不行
