### ISSUE TITLE
登录一段时间后就不回复了

### ISSUE THREAD

**Issue by losteye** [zhayujie/chatgpt-on-wechat#1147]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

自从昨天（5月24日）下午自动退出登录后，再重新登录，大概只有刚登录的时候给bot发信息会正常回复，但是过段时间就不回复了，但是手机显示桌面微信已登录，并没有退出登录，但发消息就是不回复。期间未pull过代码

### 问题描述 😯

重新扫码登陆后，只能比较短的时间内bot可以回复，后续不回复问题，但微信手机端并未显示已经退出网页端微信。

最近两次登录的log如下（隐去了部分个人信息）

### 终端日志 📒

[INFO][2023-05-24 16:16:11][config.py:195] - [INIT] load config: {'open_ai_api_key': 'sk-xxxxxxxxxxxxxxxxxxx', 'model': 'gpt-3.5-turbo', 'proxy': '', 'single_chat_prefix': ['', '@bot'], 'single_chat_reply_prefix': '[Babbage.GPT] ', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ChatGPT测试群', '], 'group_chat_in_one_session': [''], 'image_create_prefix': ['画', '看', 'draw'], 'speech_recognition': True, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 1000, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'subscribe_msg': '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。'}
[INFO][2023-05-24 16:16:11][config.py:143] - [Config] User datas loaded.
[INFO][2023-05-24 16:16:11][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-05-24 16:16:11][plugin_manager.py:66] - Scaning plugins ...
[INFO][2023-05-24 16:16:11][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-05-24 16:16:11][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-05-24 16:16:11][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-05-24 16:16:11][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[ERROR][2023-05-24 16:16:11][plugin_manager.py:91] - Failed to import plugin tool: No module named 'chatgpt_tool_hub'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/plugins/plugin_manager.py", line 88, in scan_plugins
    self.loaded[plugin_path] = importlib.import_module(import_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/chatgpt-on-wechat/plugins/tool/__init__.py", line 1, in <module>
    from .tool import *
  File "/root/chatgpt-on-wechat/plugins/tool/tool.py", line 4, in <module>
    from chatgpt_tool_hub.apps import AppFactory
ModuleNotFoundError: No module named 'chatgpt_tool_hub'
[INFO][2023-05-24 16:16:11][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-05-24 16:16:12][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-05-24 16:16:12][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-05-24 16:16:12][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[ERROR][2023-05-24 16:16:12][plugin_manager.py:156] - Plugin Tool not found, but found in plugins.json
[INFO][2023-05-24 16:16:12][godcmd.py:181] - [Godcmd] 因未设置口令，本次的临时口令为1680。
[INFO][2023-05-24 16:16:12][godcmd.py:196] - [Godcmd] inited
[INFO][2023-05-24 16:16:12][keyword.py:40] - [keyword] {}
[INFO][2023-05-24 16:16:12][keyword.py:42] - [keyword] inited.
[INFO][2023-05-24 16:16:12][role.py:69] - [Role] inited
[INFO][2023-05-24 16:16:12][dungeon.py:56] - [Dungeon] inited
[INFO][2023-05-24 16:16:12][hello.py:23] - [Hello] inited
[INFO][2023-05-24 16:16:12][finish.py:23] - [Finish] inited
[INFO][2023-05-24 16:16:35][wechat_channel.py:124] - Wechat login success, user_id: @90583268158ec79a8e37d6453444290a18d8e515b6dcd7538fc86e513392f21c, nickname: zzzzz
[INFO][2023-05-24 16:18:53][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-05-24 16:18:54][chat_gpt_bot.py:49] - [CHATGPT] query=test
[INFO][2023-05-24 16:18:55][wechat_channel.py:184] - [WX] sendMsg=Reply(type=TEXT, content=[Babbage.GPT] 你好，有什么我可以帮助你解决的问题吗？), receiver=@6f09457b23a10cada3231d66e0be870adcf9c200340b5974655375b25ad31cc5
[INFO][2023-05-24 17:25:53][config.py:195] - [INIT] load config: {'open_ai_api_key': 'sk-jjjjjjjjjjjjjjjjjjjY', 'model': 'gpt-3.5-turbo', 'proxy': '', 'single_chat_prefix': ['', '@bot'], 'single_chat_reply_prefix': '[Babbage.GPT] ', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ChatGPT测试群',], 'group_chat_in_one_session': ['], 'image_create_prefix': ['画', '看', 'draw'], 'speech_recognition': True, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 1000, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'subscribe_msg': '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。'}
[INFO][2023-05-24 17:25:53][config.py:143] - [Config] User datas loaded.
[INFO][2023-05-24 17:25:53][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-05-24 17:25:53][plugin_manager.py:66] - Scaning plugins ...
[INFO][2023-05-24 17:25:53][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-05-24 17:25:53][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-05-24 17:25:53][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-05-24 17:25:53][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[ERROR][2023-05-24 17:25:53][plugin_manager.py:91] - Failed to import plugin tool: No module named 'chatgpt_tool_hub'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/plugins/plugin_manager.py", line 88, in scan_plugins
    self.loaded[plugin_path] = importlib.import_module(import_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/chatgpt-on-wechat/plugins/tool/__init__.py", line 1, in <module>
    from .tool import *
  File "/root/chatgpt-on-wechat/plugins/tool/tool.py", line 4, in <module>
    from chatgpt_tool_hub.apps import AppFactory
ModuleNotFoundError: No module named 'chatgpt_tool_hub'
[INFO][2023-05-24 17:25:53][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-05-24 17:25:53][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-05-24 17:25:53][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-05-24 17:25:53][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[ERROR][2023-05-24 17:25:53][plugin_manager.py:156] - Plugin Tool not found, but found in plugins.json
[INFO][2023-05-24 17:25:53][godcmd.py:181] - [Godcmd] 因未设置口令，本次的临时口令为5374。
[INFO][2023-05-24 17:25:53][godcmd.py:196] - [Godcmd] inited
[INFO][2023-05-24 17:25:53][keyword.py:40] - [keyword] {}
[INFO][2023-05-24 17:25:53][keyword.py:42] - [keyword] inited.
[INFO][2023-05-24 17:25:53][role.py:69] - [Role] inited
[INFO][2023-05-24 17:25:53][dungeon.py:56] - [Dungeon] inited
[INFO][2023-05-24 17:25:53][hello.py:23] - [Hello] inited
[INFO][2023-05-24 17:25:53][finish.py:23] - [Finish] inited
[INFO][2023-05-24 17:26:19][wechat_channel.py:124] - Wechat login success, user_id: @760cdd25baa199c1e939b6edfdf0b6c96df8da790923e361acfeb17fda243323, nickname: zzzzz
[INFO][2023-05-24 17:26:56][chat_channel.py:106] - [WX]receive group at
[INFO][2023-05-24 17:26:56][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-05-24 17:26:56][chat_gpt_bot.py:49] - [CHATGPT] query=将“判决后履行金额为……”中的“履行金额”翻译为英文
[INFO][2023-05-24 17:26:58][wechat_channel.py:184] - [WX] sendMsg=Reply(type=TEXT, content=The "履行金额" in the sentence "判决后履行金额为……" can be translated to English as "the amount of performance/implement/payment".), receiver=@@274b3dc91bf08bc42c904dd2af5e091f9b0a3d2d489ae551b0fe0b32ae9e3843
[INFO][2023-05-24 17:28:16][chat_gpt_bot.py:49] - [CHATGPT] query=嗨
[INFO][2023-05-24 17:28:18][wechat_channel.py:184] - [WX] sendMsg=Reply(type=TEXT, content=[Babbage.GPT] 你好！有什么我能帮助你解决的问题吗？), receiver=@b38aa7c032f75646d7ba17eb49aafee1
[INFO][2023-05-24 17:28:36][chat_gpt_bot.py:49] - [CHATGPT] query=
[INFO][2023-05-24 17:28:44][wechat_channel.py:184] - [WX] sendMsg=Reply(type=TEXT, content=[Babbage.GPT] 冷。), receiver=@b38aa7c032f75646d7ba17eb49aafee1
[INFO][2023-05-25 18:35:42][config.py:195] - [INIT] load config: {'open_ai_api_key': ', 'model': 'gpt-3.5-turbo', 'proxy': '', 'single_chat_prefix': ['', '@bot'], 'single_chat_reply_prefix': '[Babbage.GPT] ', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ChatGPT测试群', 'group_chat_in_one_session': ['], 'image_create_prefix': ['画', '看', 'draw'], 'speech_recognition': True, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 1000, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'subscribe_msg': '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。'}
[INFO][2023-05-25 18:35:42][config.py:143] - [Config] User datas loaded.
[INFO][2023-05-25 18:35:43][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-05-25 18:35:43][plugin_manager.py:66] - Scaning plugins ...
[INFO][2023-05-25 18:35:43][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-05-25 18:35:43][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-05-25 18:35:43][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-05-25 18:35:43][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[ERROR][2023-05-25 18:35:43][plugin_manager.py:91] - Failed to import plugin tool: No module named 'chatgpt_tool_hub'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/plugins/plugin_manager.py", line 88, in scan_plugins
    self.loaded[plugin_path] = importlib.import_module(import_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/chatgpt-on-wechat/plugins/tool/__init__.py", line 1, in <module>
    from .tool import *
  File "/root/chatgpt-on-wechat/plugins/tool/tool.py", line 4, in <module>
    from chatgpt_tool_hub.apps import AppFactory
ModuleNotFoundError: No module named 'chatgpt_tool_hub'
[INFO][2023-05-25 18:35:43][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-05-25 18:35:43][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-05-25 18:35:43][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-05-25 18:35:43][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[ERROR][2023-05-25 18:35:43][plugin_manager.py:156] - Plugin Tool not found, but found in plugins.json
[INFO][2023-05-25 18:35:43][godcmd.py:181] - [Godcmd] 因未设置口令，本次的临时口令为9387。
[INFO][2023-05-25 18:35:43][godcmd.py:196] - [Godcmd] inited
[INFO][2023-05-25 18:35:43][keyword.py:40] - [keyword] {}
[INFO][2023-05-25 18:35:43][keyword.py:42] - [keyword] inited.
[INFO][2023-05-25 18:35:43][role.py:69] - [Role] inited
[INFO][2023-05-25 18:35:43][dungeon.py:56] - [Dungeon] inited
[INFO][2023-05-25 18:35:43][hello.py:23] - [Hello] inited
[INFO][2023-05-25 18:35:43][finish.py:23] - [Finish] inited
[INFO][2023-05-25 18:36:07][wechat_channel.py:124] - Wechat login success, user_id: @c84ecb406b4fc942d188a39e3b69716e7abe93a12187a64c61e0b48992756608, nickname: zzzzz
[INFO][2023-05-25 18:37:32][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-05-25 18:37:32][chat_gpt_bot.py:49] - [CHATGPT] query=Test
[INFO][2023-05-25 18:37:36][wechat_channel.py:184] - [WX] sendMsg=Reply(type=TEXT, content=[Babbage.GPT] Hello! I'm ChatGPT, a language model trained by OpenAI. How can I assist you today?), receiver=@3fc5ded2ab5208bee106ffd8df4e3dacbb51d829d4438f65fa213a1a7e9a15ab
[INFO][2023-05-25 18:40:33][chat_gpt_bot.py:49] - [CHATGPT] query=Explain in English
[INFO][2023-05-25 18:40:39][wechat_channel.py:184] - [WX] sendMsg=Reply(type=TEXT, content=[Babbage.GPT] "i" is a term in Chinese that refers to kinetic energy recovery systems (KERS). KERS is a technology used in the motorsport industry that recovers kinetic energy created by the vehicle's braking system and converts it into electrical energy.

The recovered energy can then be used to power the vehicle's engine or other electrical systems, resulting in better fuel efficiency and performance. KERS is also used in hybrid and electric cars to improve their overall efficiency.

In summary, "Dong Neng She Shi" or KERS is a technology that recovers kinetic energy and converts it into usable energy, resulting in better fuel efficiency and performance in a vehicle.), receiver=@8eaf63c274aabc58a7cacc5dee921baf

**Comment by guanhuai0603** [comment]
同样问题

**Comment by zhayujie** [comment]
从日志看，回复已经生成并且向微信发送了，但是没发出去，可能被屏蔽或者限制了

**Comment by guanhuai0603** [comment]
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as 关怀
[INFO][2023-05-27 06:24:26][wechat_channel.py:124] - Wechat login success, user_id: @606bef9998154d20d64e96b15284acd4, nickname: 关怀
Start auto replying.
我的登录了，但发信息没反应，也不打日志，这是为什么

**Comment by kscMaster** [comment]
我一句话都不回复，消息已经发出去了，但是一个回复都没有

**Comment by losteye** [comment]
我重新pull了一次代码，现在没有这个问题了

**Comment by five3** [comment]
我是运行一段时间后，比如10小时后会异常退出

**Comment by losteye** [comment]
现在又出现同样问题了 pull代码也没用

**Comment by codezzzsleep** [comment]
我也有相同的问题，并且在登陆时拿不到user_id，和nickname，换一个账号就可以了，看来是微信那边做了限制
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as
[INFO][2023-07-23 10:10:21][wechat_channel.py:123] - Wechat login success, user_id: , nickname:
Start auto replying.

**Comment by huluohu** [comment]
> 我也有相同的问题，并且在登陆时拿不到user_id，和nickname，换一个账号就可以了，看来是微信那边做了限制 Please press confirm on your phone. Loading the contact, this may take a little while. Login successfully as [INFO][2023-07-23 10:10:21][wechat_channel.py:123] - Wechat login success, user_id: , nickname: Start auto replying.

我也是同样的问题，获取不到user_id和nickname，然后啥也不回复了。

**Comment by boxoutmark** [comment]
> > 我也有相同的问题，并且在登陆时拿不到user_id，和nickname，换一个账号就可以了，看来是微信那边做了限制 Please press confirm on your phone. Loading the contact, this may take a little while. Login successfully as [INFO][2023-07-23 10:10:21][wechat_channel.py:123] - Wechat login success, user_id: , nickname: Start auto replying.
> 
> 我也是同样的问题，获取不到user_id和nickname，然后啥也不回复了。

我遇到了同样的问题，你解决了吗？

**Comment by isinry** [comment]
> > > 我也有相同的问题，并且在登陆时拿不到user_id，和昵称，换一个账号就可以了，看来是微信这边做了限制，请按手机上的确认键。正在加载联系人，这可能需要一些时间。 [INFO][2023-07-23 10:10:21][wechat_channel.py:123] 登录成功 - 微信登录成功，user_id: ,昵称: 开始自动回复。
> > 
> > 
> > 我也是同样的问题，获取不到user_id和nickname，然后啥也没有回复了。
> 
> 我遇到了同样的问题，你解决了吗？

有解决吗，我也一直出现这个问题

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
