### ISSUE TITLE
扫码登录后报错

### ISSUE THREAD

**Issue by nebidun** [zhayujie/chatgpt-on-wechat#1176]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

之前程序运行一直正常，这周发现已经无法正常登录，运行app.py后正常显示二维码；扫码后报错

### 问题描述 😯

之前程序运行一直正常，这周发现已经无法正常登录，运行app.py后正常显示二维码；扫码后报错

### 终端日志 📒

```log
Please press confirm on your phone.
[ERROR][2023-05-30 19:03:18][app.py:52] - App startup failed!
[ERROR][2023-05-30 19:03:18][app.py:53] - HTTPSConnectionPool(host='wx8.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=CFUHHgndGi0iMlTDRWkmViP6@qrticket_0&uuid=Iawakgl1Lw==&lang=zh_CN&scan=1685444583 (Caused by SSLError(SSLCertVerificationError("hostname 'wx8.qq.com' doesn't match either of 'wx.qq.com', '*.web.wechat.com', '*.web1.wechat.com', '*.web2.wechat.com', '*.wechat.com', '*.weixin.qq.com', '*.wx.qq.com', '*.wx1.qq.com', '*.wx2.qq.com', 'wechat.com', 'weixin.qq.com', 'wx1.qq.com', 'wx2.qq.com'")))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 464, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 512, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3.9/ssl.py", line 416, in match_hostname
    raise CertificateError("hostname %r "
ssl.SSLCertVerificationError: ("hostname 'wx8.qq.com' doesn't match either of 'wx.qq.com', '*.web.wechat.com', '*.web1.wechat.com', '*.web2.wechat.com', '*.wechat.com', '*.weixin.qq.com', '*.wx.qq.com', '*.wx1.qq.com', '*.wx2.qq.com', 'wechat.com', 'weixin.qq.com', 'wx1.qq.com', 'wx2.qq.com'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx8.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=CFUHHgndGi0iMlTDRWkmViP6@qrticket_0&uuid=Iawakgl1Lw==&lang=zh_CN&scan=1685444583 (Caused by SSLError(SSLCertVerificationError("hostname 'wx8.qq.com' doesn't match either of 'wx.qq.com', '*.web.wechat.com', '*.web1.wechat.com', '*.web2.wechat.com', '*.wechat.com', '*.weixin.qq.com', '*.wx.qq.com', '*.wx1.qq.com', '*.wx2.qq.com', 'wechat.com', 'weixin.qq.com', 'wx1.qq.com', 'wx2.qq.com'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 50, in run
    channel.startup()
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 115, in startup
    itchat.auto_login(
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 177, in process_login_info
    r = core.s.get(core.loginInfo['url'],
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='wx8.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=CFUHHgndGi0iMlTDRWkmViP6@qrticket_0&uuid=Iawakgl1Lw==&lang=zh_CN&scan=1685444583 (Caused by SSLError(SSLCertVerificationError("hostname 'wx8.qq.com' doesn't match either of 'wx.qq.com', '*.web.wechat.com', '*.web1.wechat.com', '*.web2.wechat.com', '*.wechat.com', '*.weixin.qq.com', '*.wx.qq.com', '*.wx1.qq.com', '*.wx2.qq.com', 'wechat.com', 'weixin.qq.com', 'wx1.qq.com', 'wx2.qq.com'")))
```

**Comment by Chowhound-G** [comment]
同，扫码登录之后就出现SSLError，然后终止

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
