### ISSUE TITLE
使用香港地域云服务器报443

### ISSUE THREAD

**Issue by repickswap** [zhayujie/chatgpt-on-wechat#1180]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

香港服务器 配置了python3.8  也修改了config.json 直接本地运行报错

### 问题描述 😯

requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

连接这个host 也是可以的
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/57622365/f4326aeb-5f66-4647-9abd-92085d07ba65)
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/57622365/f48e41a2-1607-4aff-abba-f5bd014997dc)

### 终端日志 📒

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/57622365/a288ca8b-1d83-472d-921a-c1de26e0e479)
[INFO][2023-05-31 11:05:10][tool.py:32] - [tool] inited
[DEBUG][2023-05-31 11:05:10][role.py:62] - [Role] no role found for tag comments 
[INFO][2023-05-31 11:05:10][role.py:69] - [Role] inited
[INFO][2023-05-31 11:05:10][dungeon.py:56] - [Dungeon] inited
[INFO][2023-05-31 11:05:10][hello.py:23] - [Hello] inited
[INFO][2023-05-31 11:05:10][finish.py:23] - [Finish] inited
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 692, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1011, in _new_conn
    raise SSLError(
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/lib/itchat/utils.py", line 134, in test_connect
    r = requests.get(config.BASE_URL)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

**Comment by repickswap** [comment]
参考这篇文档解决了：https://www.cnblogs.com/ykcbwdt/p/12023160.html
