### ISSUE TITLE
登录成功后自动退出了

### ISSUE THREAD

**Issue by MarshalT** [zhayujie/chatgpt-on-wechat#12]
██████
██████████████████████████████████████████████████████████████████████████████
Login successfully as 溶进咖啡的糖🔝
Start auto replying.
Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Traceback (most recent call last):
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\login.py", line 256, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\components\messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "C:\Users\prm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

LOG OUT!

**Comment by zhayujie** [comment]
请问你安装的是itchat还是itchat-uos，如果是itchat，要卸载掉换成itchat-uos，版本是1.5.0.dev0。  如果已经有itchat-uos还不行的话，可能是Python版本过高的问题，可以改成 3.7 ~3.9 之间的版本试试。

**Comment by MarshalT** [comment]
PS C:\Users\prm\Downloads\chatgpt-on-wechat-master\chatgpt-on-wechat-master> python3 -m pip list
Package            Version
------------------ ------------
certifi            2022.12.7
charset-normalizer 2.1.1
colorama           0.4.6
et-xmlfile         1.1.0
idna               3.4
itchat             1.3.10
itchat-uos         1.5.0.dev0
numpy              1.24.0
openai             0.25.0
openpyxl           3.0.10
pandas             1.5.2
pandas-stubs       1.5.2.221213
pip                22.3.1
pypng              0.20220715.0
PyQRCode           1.2.1
python-dateutil    2.8.2
pytz               2022.7
requests           2.28.1
six                1.16.0
tqdm               4.64.1
types-pytz         2022.7.0.0
typing_extensions  4.4.0
urllib3            1.26.13
PS C:\Users\prm\Downloads\chatgpt-on-wechat-master\chatgpt-on-wechat-master> & C:/Users/prm/AppData/Local/Programs/Python/Python38/python.exe c:/Users/prm/Downloads/chatgpt-on-wechat-master/chatgpt-on-wechat-master/app.py
Traceback (most recent call last):
  File "c:/Users/prm/Downloads/chatgpt-on-wechat-master/chatgpt-on-wechat-master/app.py", line 4, in <module>
    from channel import channel_factory
  File "c:\Users\prm\Downloads\chatgpt-on-wechat-master\chatgpt-on-wechat-master\channel\channel_factory.py", line 5, in <module>      
    from channel.wechat.wechat_channel import WechatChannel
  File "c:\Users\prm\Downloads\chatgpt-on-wechat-master\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 6, in <module>
    import itchat
ModuleNotFoundError: No module named 'itchat'
PS C:\Users\prm\Downloads\chatgpt-on-wechat-master\chatgpt-on-wechat-master>

3.10 能登录会自动推出 切换到3.8 提示No module named 'itchat' 但是我是有安装的

**Comment by zhayujie** [comment]
itchat是在3.10下面安装的，切换到3.8要再装一下itchat-uos

python3.8 -m pip install itchat-uos
