### ISSUE TITLE
设置QRCODE API后报错

### ISSUE THREAD

**Issue by rainberg** [zhayujie/chatgpt-on-wechat#1208]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

terminal

### 复现步骤 🕹

不知道 

### 问题描述 😯

设置二维码的API后开始报错

"receive_qrcode_api": ""https://api.isoyu.com/qr/?m=1&e=L&p=20&url={}""

报错

### 终端日志 📒

```log
(bot) [lighthouse@VM-4-8-centos bot-on-anything]$ python3 app.py 
Load config success
[INFO][2023-06-04 00:36:56][plugin_registry.py:23] - Plugin CreateImg_v0.1 registered
[INFO][2023-06-04 00:36:56][plugin_registry.py:23] - Plugin Selector_v0.1 registered
[INFO][2023-06-04 00:36:56][log.py:32] - [Selector] inited
Load config success
[INFO][2023-06-04 00:36:56][log.py:34] - [MultiChannel] Start up chatgpt on wechat
[ERROR][2023-06-04 00:36:56][log.py:47] - [MultiChannel] Start up failed on wechat: auto_login() got an unexpected keyword argument 'hot_reload'
[ERROR][2023-06-04 00:36:56][log.py:45] - App startup failed!
[ERROR][2023-06-04 00:36:56][log.py:50] - auto_login() got an unexpected keyword argument 'hot_reload'
Traceback (most recent call last):
  File "/home/lighthouse/bot-on-anything/app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "/home/lighthouse/bot-on-anything/app.py", line 23, in start_process
    raise e
  File "/home/lighthouse/bot-on-anything/app.py", line 20, in start_process
    channel.startup()
  File "/home/lighthouse/bot-on-anything/channel/wechat/wechat_channel.py", line 46, in startup
    itchat.auto_login(enableCmdQR=2, hot_reload=hot_reload, qrCallback=self.login)
TypeError: auto_login() got an unexpected keyword argument 'hot_reload'
(bot) [lighthouse@VM-4-8-centos bot-on-anything]$ vi config.json 
(bot) [lighthouse@VM-4-8-centos bot-on-anything]$ python3 app.py 
Load config success
[INFO][2023-06-04 00:41:20][plugin_registry.py:23] - Plugin CreateImg_v0.1 registered
[INFO][2023-06-04 00:41:20][plugin_registry.py:23] - Plugin Selector_v0.1 registered
[INFO][2023-06-04 00:41:20][log.py:32] - [Selector] inited
Load config success
[INFO][2023-06-04 00:41:20][log.py:34] - [MultiChannel] Start up chatgpt on wechat
[ERROR][2023-06-04 00:41:20][log.py:47] - [MultiChannel] Start up failed on wechat: auto_login() got an unexpected keyword argument 'hot_reload'
[ERROR][2023-06-04 00:41:20][log.py:45] - App startup failed!
[ERROR][2023-06-04 00:41:20][log.py:50] - auto_login() got an unexpected keyword argument 'hot_reload'
Traceback (most recent call last):
  File "/home/lighthouse/bot-on-anything/app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "/home/lighthouse/bot-on-anything/app.py", line 23, in start_process
    raise e
  File "/home/lighthouse/bot-on-anything/app.py", line 20, in start_process
    channel.startup()
  File "/home/lighthouse/bot-on-anything/channel/wechat/wechat_channel.py", line 46, in startup
    itchat.auto_login(enableCmdQR=2, hot_reload=hot_reload, qrCallback=self.login)
TypeError: auto_login() got an unexpected keyword argument 'hot_reload'
```

**Comment by lanvent** [comment]
请在bot-on-anything项目中提问
