### ISSUE TITLE
企业微信必须要有服务器吗？没有服务器url怎么填写？

### ISSUE THREAD

**Issue by axiba053** [zhayujie/chatgpt-on-wechat#1216]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

This domain name is not allowed. Please reset it.

### 问题描述 😯

没有服务器，个人团体，企业未认证，url填的是http://127.0.0.1:9898/wxcomapp，最后报错：This domain name is not allowed. Please reset it.

使用个人电脑不能部署企业微信吗？应该怎么填才可以？

### 终端日志 📒

```log
[INFO][2023-06-05 21:42:13][config.py:195] - [INIT] load config: {'open_ai_api_key': 'sk-KIrEceUqXApNkj4eybT0T3BlbX3OTqvg7YNgPsw', 'model': 'gpt-3.5-turbo', 'proxy': '', 'single_chat_prefix': [''], 'single_chat_reply_prefix': '', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ChatGPT测试群', 'ChatGPT测试群2'], 'group_chat_in_one_session': ['ChatGPT测试群'], 'image_create_prefix': ['画', '看', '找'], 'speech_recognition': True, 'group_speech_recognition': False, 'voice_reply_voice': True, 'baidu_app_id': '15639231', 'baidu_api_key': 'uhAGKVkjPNXhxV', 'baidu_secret_key': 'V8y5V88gs7Z19P9rP3', 'baidu_dev_pid': '1536', 'channel_type': 'wechatcom_app', 'wechatcom_corp_id': 'wwd3f1ba151', 'wechatcomapp_token': 'LPyyUa2QoLnBOtJ6i', 'wechatcomapp_port': 9898, 'wechatcomapp_secret': 'XeFYHb12cJl4mRyIPXydJJAQuBk4A', 'wechatcomapp_agent_id': '1000002', 'wechatcomapp_aes_key': 'yF0Zu3HBymh2QQumD3iQxIoC3UE', 'conversation_max_tokens': 1000, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'subscribe_msg': '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。'}
[INFO][2023-06-05 21:42:13][config.py:143] - [Config] User datas loaded.
[INFO][2023-06-05 21:42:13][wechatcomapp_channel.py:39] - [wechatcom] init: 
[INFO][2023-06-05 21:42:13][plugin_manager.py:50] - Loading plugins config...
[INFO][2023-06-05 21:42:13][plugin_manager.py:66] - Scaning plugins ...
[INFO][2023-06-05 21:42:13][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-06-05 21:42:13][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-06-05 21:42:13][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-06-05 21:42:13][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2023-06-05 21:42:13][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-06-05 21:42:13][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-06-05 21:42:13][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-06-05 21:42:13][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
[ERROR][2023-06-05 21:42:13][plugin_manager.py:91] - Failed to import plugin tool: No module named 'chatgpt_tool_hub'
Traceback (most recent call last):
  File "/Users/qiangzi/Documents/python/ai/chatgpt-on-wechat-master/plugins/plugin_manager.py", line 88, in scan_plugins
    self.loaded[plugin_path] = importlib.import_module(import_path)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/qiangzi/Documents/python/ai/chatgpt-on-wechat-master/plugins/tool/__init__.py", line 1, in <module>
    from .tool import *
  File "/Users/qiangzi/Documents/python/ai/chatgpt-on-wechat-master/plugins/tool/tool.py", line 4, in <module>
    from chatgpt_tool_hub.apps import AppFactory
ModuleNotFoundError: No module named 'chatgpt_tool_hub'
[INFO][2023-06-05 21:42:13][godcmd.py:193] - [Godcmd] 因未设置口令，本次的临时口令为7516。
[INFO][2023-06-05 21:42:13][godcmd.py:208] - [Godcmd] inited
```

**Comment by 6vision** [comment]
不需要也可以，看readme提供的文档说明，或者查看这里https://mp.weixin.qq.com/s/qZl581m4q2DR2xhUW7CIcQ

**Comment by lanvent** [comment]
如果要在个人电脑部署的话，需要有公网IP或者内网穿透才行

**Comment by axiba053** [comment]
非常感谢！
