### ISSUE TITLE
运行python3 app.py 没有任何反应

### ISSUE THREAD

**Issue by heloook** [zhayujie/chatgpt-on-wechat#1258]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

在cmd里

执行pip3 install -r requirements.txt 成功
pip3 install -r requirements-optional.txt 成功

就 最后一步python3 app.py 没有任何反应

难道是我电脑的问题吗？咋回事？

### 问题描述 😯

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/27837566/ed8cee54-c417-441e-a7c9-1bf8cf3d9e95)

### 终端日志 📒

```log
[INFO][2023-06-17 19:43:08][config.py:172] - 配置文件不存在，将使用config-template.json模板
[INFO][2023-06-17 19:43:08][config.py:201] - [INIT] load config: {'open_ai_api_key': 'YOUR API KEY', 'model': 'gpt-3.5-turbo', 'proxy': '', 'single_chat_prefix': ['bot', '@bot'], 'single_chat_reply_prefix': '[bot] ', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ChatGPT测试群', 'ChatGPT测试群2'], 'group_chat_in_one_session': ['ChatGPT测试群'], 'image_create_prefix': ['画', '看', '找'], 'speech_recognition': False, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 1000, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'subscribe_msg': '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。', 'use_linkai': False, 'linkai_api_key': '', 'linkai_app_code': ''}
[INFO][2023-06-17 19:43:08][config.py:151] - [Config] User datas file not found, ignore.
[ERROR][2023-06-17 19:43:08][app.py:52] - App startup failed!
[ERROR][2023-06-17 19:43:08][app.py:53] - No module named 'requests'
Traceback (most recent call last):
  File "C:\Users\Administrator\chatgpt-on-wechat\app.py", line 45, in run
    channel = channel_factory.create_channel(channel_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\chatgpt-on-wechat\channel\channel_factory.py", line 13, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "C:\Users\Administrator\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[INFO][2023-06-17 19:47:12][config.py:201] - [INIT] load config: {'open_ai_api_key': 'sk-xx', 'model': 'gpt-3.5-turbo-0613', 'proxy': '', 'single_chat_prefix': ['', '@chi'], 'single_chat_reply_prefix': '', 'group_chat_prefix': ['@chi'], 'group_name_white_list': ['xx', '有事启奏 无事退朝'], 'group_chat_in_one_session': ['xx'], 'image_create_prefix': ['画', '看', '找'], 'speech_recognition': True, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 4096, 'expires_in_seconds': 3600, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'subscribe_msg': '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。', 'use_linkai': False, 'linkai_api_key': '', 'linkai_app_code': ''}
[INFO][2023-06-17 19:47:12][config.py:151] - [Config] User datas file not found, ignore.
[ERROR][2023-06-17 19:47:12][app.py:52] - App startup failed!
[ERROR][2023-06-17 19:47:12][app.py:53] - No module named 'requests'
Traceback (most recent call last):
  File "C:\Users\Administrator\chatgpt-on-wechat\app.py", line 45, in run
    channel = channel_factory.create_channel(channel_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\chatgpt-on-wechat\channel\channel_factory.py", line 13, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "C:\Users\Administrator\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

```

**Comment by hunanfan** [comment]
一样，我也遇到了这个问题，这个终端日志在哪看

**Comment by mick839** [comment]
No module named 'requests'

这个意思是需要安装依赖，运行pip3 install requests

**Comment by Romofish** [comment]
python可能安装了多个版本

**Comment by zhayujie** [comment]
windows下 用 python app.py
