### ISSUE TITLE
部署了 azure，配置 azure 相关参数后，提示 endpoint 或 key 有误

### ISSUE THREAD

**Issue by alisx** [zhayujie/chatgpt-on-wechat#1285]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1. 部署了 azure openai service，从 配置中获得：endpoint，key，部署名，模型名：gpt-35-turbo-16k
2. 在 config.json 中，配置了 
   - `open_ai_api_key`  值为 key
   - `open_ai_api_base` 值为 endpoint
   - `model` 值为 部署名
   - `azure_deployment_id` 值为 部署名
   - `use_azure_chatgpt` 值为 true
   > 我不能区分config.json 配置中的 `model` 和 `use_azure_chatgpt`，在 azure 中，他们的值是否相同？
3. 在本地启动程序 `python app.py`， 成功后扫描二维码登录
4. 在微信聊天中输入机器人前缀，以及问题
5. 获得的反馈是 `[ERROR] 我现在有点类了，等会再来吧`

### 问题描述 😯

我做了单步调试，发现在 :

1. `chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py` 109行，`reply_text`  方法中，参数 `api_key`为空
2. 122 行，`self.args` 中， `open_ai_api_key` 也是空的

经过查找，暂时没有找到如何让 self.args 获得 config.json 配置中的 `open_ai_api_key` 的位置。

### 终端日志 📒

```log
下面是错误栈信息：
```
[ERROR][2023-07-02 11:23:02][chat_gpt_bot.py:154] - [CHATGPT] Exception: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
Traceback (most recent call last):
  File "/home/alisx/Project/python/chatbot/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 123, in reply_text
    response = openai.ChatCompletion.create(api_key=api_key, messages=session.messages, **args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alisx/miniconda3/envs/ChatBot/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alisx/miniconda3/envs/ChatBot/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/home/alisx/miniconda3/envs/ChatBot/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alisx/miniconda3/envs/ChatBot/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/alisx/miniconda3/envs/ChatBot/lib/python3.11/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
```
```

**Comment by alisx** [comment]
问题发现了，原因是我在调试过程中，在chatGPT bot 里写死了 key，导致后面配置的新key 如法生效。
关闭问题。

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
