### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by adminlove520** [zhayujie/chatgpt-on-wechat#1294]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

突然报错

### 终端日志 📒

```log
[ERROR][2023-07-05 03:47:02][chat_channel.py:270] - Worker return exception: 'EventContext' object has no attribute 'is_break'
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/Person/Realease/chatgpt-on-wechat/channel/chat_channel.py", line 146, in _handle
    reply = self._generate_reply(context)
  File "/home/Person/Realease/chatgpt-on-wechat/channel/chat_channel.py", line 165, in _generate_reply
    if e_context.is_break():
AttributeError: 'EventContext' object has no attribute 'is_break'

```

**Comment by chazzjimel** [comment]
正常使用，提供更多debug信息才能分析
