### ISSUE TITLE
requests. AND urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url:

### ISSUE THREAD

**Issue by swumagic** [zhayujie/chatgpt-on-wechat#1340]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

Start auto replying.
Traceback (most recent call last):
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "M:\SD\Python31011\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "M:\SD\Python31011\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "M:\SD\Python31011\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\SD\git\chatgpt-on-wechat\lib\itchat\components\login.py", line 301, in maintain_loop
    msgList, contactList = self.get_msg()
  File "M:\SD\git\chatgpt-on-wechat\lib\itchat\components\login.py", line 390, in get_msg
    r = self.s.post(url, data=json.dumps(data),
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=**

### 问题描述 😯

本地电脑部署扫码成功后，回复消息就出现如上BUG

### 终端日志 📒

Start auto replying.
Traceback (most recent call last):
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "M:\SD\Python31011\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "M:\SD\Python31011\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "M:\SD\Python31011\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=N**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\SD\git\chatgpt-on-wechat\lib\itchat\components\login.py", line 301, in maintain_loop
    msgList, contactList = self.get_msg()
  File "M:\SD\git\chatgpt-on-wechat\lib\itchat\components\login.py", line 390, in get_msg
    r = self.s.post(url, data=json.dumps(data),
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "M:\SD\git\chatgpt-on-wechat\venv\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=N**
```

**Comment by 6vision** [comment]
本地部署，代理软件开规则模式，不要开全局
