### ISSUE TITLE
查询文本报错

### ISSUE THREAD

**Issue by wazxhy** [zhayujie/chatgpt-on-wechat#14]
[INFO][2022-12-28 13:08:40][open_ai_bot.py:21] - [OPEN_AI] query=皮肤怎么保养
[ERROR][2022-12-28 13:08:41][open_ai_bot.py:35] - You exceeded your current quota, please check your plan and billing details.
Traceback (most recent call last):
  File "/Users/aviagames/Downloads/python/01-代码-笔记/chatgpt/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 23, in reply_text
    response = openai.Completion.create(
  File "/Users/aviagames/Desktop/work2/python/python3.8/lib/python3.8/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/aviagames/Desktop/work2/python/python3.8/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 115, in create
    response, _, api_key = requestor.request(
  File "/Users/aviagames/Desktop/work2/python/python3.8/lib/python3.8/site-packages/openai/api_requestor.py", line 181, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/aviagames/Desktop/work2/python/python3.8/lib/python3.8/site-packages/openai/api_requestor.py", line 396, in _interpret_response
    self._interpret_response_line(
  File "/Users/aviagames/Desktop/work2/python/python3.8/lib/python3.8/site-packages/openai/api_requestor.py", line 429, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
[ERROR][2022-12-28 13:08:41][wechat_channel.py:114] - 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/Users/aviagames/Downloads/python/01-代码-笔记/chatgpt/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 110, in _do_send
    reply_text = super().build_reply_content(query, context).strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by zhayujie** [comment]
去这个页面 https://beta.openai.com/account/usage 看下你的openAI账号是不是免费额度用完了，如果用完了可以换个账号使用

**Comment by wazxhy** [comment]
是的

**Comment by wazxhy** [comment]
可以接入飞书吗

**Comment by zhayujie** [comment]
> 可以接入飞书吗

只要飞书有提供 回复的开放接口，或者有其他方式实现实现自动回复， 就可以接入
