### ISSUE TITLE
docker环境下扫码出现 KeyEroor wxsid问题

### ISSUE THREAD

**Issue by GuoWeiChi** [zhayujie/chatgpt-on-wechat#1406]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

docker安装，扫码后出现

### 问题描述 😯

[ERROR][2023-09-07 06:54:47][app.py:53] - 'wxsid'
Traceback (most recent call last):
  File "/app/app.py", line 50, in run
    channel.startup()
  File "/app/channel/wechat/wechat_channel.py", line 118, in startup
    itchat.auto_login(
  File "/app/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/app/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/app/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/app/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

### 终端日志 📒

```log
[ERROR][2023-09-07 06:54:47][app.py:53] - 'wxsid'
Traceback (most recent call last):
  File "/app/app.py", line 50, in run
    channel.startup()
  File "/app/channel/wechat/wechat_channel.py", line 118, in startup
    itchat.auto_login(
  File "/app/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/app/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/app/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/app/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
```

**Comment by 6vision** [comment]
微信号未实名认证绑卡
