### ISSUE TITLE
扫码成功后app.py报错

### ISSUE THREAD

**Issue by henryyan** [zhayujie/chatgpt-on-wechat#141]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本3.9 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-02-09 23:41:06][app.py:19] - App startup failed!
[ERROR][2023-02-09 23:41:06][app.py:20] - list index out of range
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat-master/app.py", line 17, in <module>
    channel.startup()
  File "/root/chatgpt-on-wechat-master/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/lib/python3.9/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.9/site-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/usr/local/lib/python3.9/site-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.9/site-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：     Python 3.9.6             
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 21.1.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

**Comment by zhayujie** [comment]
wx有实名认证吗

**Comment by henryyan** [comment]
实名认证后正常了

**Comment by Datamore** [comment]
但我实名论证了，也还是有这个问题。

**Comment by goodpadd** [comment]
确实是没有实名的问题
