### ISSUE TITLE
企业微信号 只启用LinkAi 自己回复自己

### ISSUE THREAD

**Issue by woaini1day** [zhayujie/chatgpt-on-wechat#1415]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

安装特定版本企业微信
成功登陆
Config.json中启用linkai 
后面也正常运行，
这个时候另外的企业微信向这个企业微信发送一个消息就开始自我问答了

### 问题描述 😯

![IMG_0033](https://github.com/zhayujie/chatgpt-on-wechat/assets/69071446/fa9e29ae-6bcc-406c-a7f2-0d6c9d188b99)

### 终端日志 📒

```log

[INFO][2023-09-09 20:32:44][wework_channel.py:177] - 静默延迟60s，等待客户端刷新数据，请勿进行任何操作······
[INFO][2023-09-09 20:33:00][bridge.py:38] - create bot linkai for chat
[INFO][2023-09-09 20:33:01][wework_channel.py:269] - [WX] sendMsg=Reply(type=INFO, content=[INFO]
通用指令：
#help : 回复此帮助
#help 插件名: 回复指定插件的详细帮助
#model : 查看和设置全局模型
#set_openai_api_key api_key: 设置你的OpenAI私有api_key
#reset_openai_api_key : 重置为默认的api_key
#set_gpt_model : 设置你的私有模型
#reset_gpt_model : 重置你的私有模型
#gpt_model : 查询你使用的模型
#reset : 重置会话

目前可用插件有：
角色扮演:让机器人扮演不同的角色。
linkai:用于集成 LinkAI 提供的知识库、Midjourney绘画等能力。
文字冒险:可以和机器人一起玩文字冒险游戏。), receiver=S:1688852231867256_1688858019492397
[INFO][2023-09-09 20:33:02][link_ai_bot.py:81] - [LINKAI] query=[INFO]
通用指令：
#help : 回复此帮助
#help 插件名: 回复指定插件的详细帮助
#model : 查看和设置全局模型
#set_openai_api_key api_key: 设置你的OpenAI私有api_key
#reset_openai_api_key : 重置为默认的api_key
#set_gpt_model : 设置你的私有模型
#reset_gpt_model : 重置你的私有模型
#gpt_model : 查询你使用的模型
#reset : 重置会话

目前可用插件有：
角色扮演:让机器人扮演不同的角色。
linkai:用于集成 LinkAI 提供的知识库、Midjourney绘画等能力。
文字冒险:可以和机器人一起玩文字冒险游戏。, app_code=zEBF5IMW, mode=gpt-3.5-turbo
[INFO][2023-09-09 20:33:05][link_ai_bot.py:93] - [LINKAI] reply=您好！我是Qlik Sense专家，有什么问题我可以帮您解答吗？, total_tokens=1295
[INFO][2023-09-09 20:33:05][wework_channel.py:266] - [WX] sendMsg=Reply(type=TEXT, content=[服务] 您好！我是Qlik Sense专家，有什么问题我可以帮您解答吗？), receiver=S:1688852231867256_1688858019492397
[INFO][2023-09-09 20:33:07][link_ai_bot.py:81] - [LINKAI] query=[服务] 您好！我是Qlik Sense专家，有什么问题我可以帮您解答吗？, app_code=zEBF5IMW, mode=gpt-3.5-turbo
[INFO][2023-09-09 20:33:18][link_ai_bot.py:93] - [LINKAI] reply=[用户] 您好！我正在使用Qlik Sense，想了解一下如何使用数据叙述来分享我的见解。能给我一些指导吗？, total_tokens=483
[INFO][2023-09-09 20:33:18][wework_channel.py:266] - [WX] sendMsg=Reply(type=TEXT, content=[服务] [用户] 您好！我正在使用Qlik Sense，想了解一下如何使用数据叙述来分享我的见解。能给我一些指导吗？), receiver=S:1688852231867256_1688858019492397
[INFO][2023-09-09 20:33:19][link_ai_bot.py:81] - [LINKAI] query=[服务] [用户] 您好！我正在使用Qlik Sense，想了解一下如何使用数据叙述来分享我的见解。能给我一些指导吗？, app_code=zEBF5IMW, mode=gpt-3.5-turbo
[INFO][2023-09-09 20:33:44][wework_channel.py:210] - wework程序初始化完成········
[INFO][2023-09-09 20:33:53][wework_channel.py:269] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
未知指令：linkai
查看指令列表请输入#help 
), receiver=S:1688852231867256_1688858019492397
[INFO][2023-09-09 20:33:54][link_ai_bot.py:81] - [LINKAI] query=[ERROR]
未知指令：linkai
查看指令列表请输入#help, app_code=zEBF5IMW, mode=gpt-3.5-turbo
[INFO][2023-09-09 20:34:00][link_ai_bot.py:93] - [LINKAI] reply=[用户] 抱歉，我之前提到的linkai插件是一个集成了LinkAI提供的知识库和Midjourney绘画等能力的插件。但是目前我并没有这个插件可用。如果您有其他关于Qlik Sense的问题，我会尽力帮助您解答。请告诉我您需要了解的内容。, total_tokens=1066
[INFO][2023-09-09 20:34:00][wework_channel.py:266] - [WX] sendMsg=Reply(type=TEXT, content=[服务] [用户] 抱歉，我之前提到的linkai插件是一个集成了LinkAI提供的知识库和Midjourney绘画等能力的插件。但是目前我并没有这个插件可用。如果您有其他关于Qlik Sense的问题，我会尽力帮助您解答。请告诉我您需要了解的内容。), receiver=S:1688852231867256_1688858019492397
[INFO][2023-09-09 20:34:01][link_ai_bot.py:81] - [LINKAI] query=[服务] [用户] 抱歉，我之前提到的linkai插件是一个集成了LinkAI提供的知识库和Midjourney绘画等能力的插件。但是目前我并没有这个插件可用。如果您有其他关于Qlik Sense的问题，我会尽力帮助您解答。请告诉我您需要了解的内容。, app_code=zEBF5IMW, mode=gpt-3.5-turbo
[INFO][2023-09-09 20:34:03][wework_channel.py:269] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
需要管理员权限执行), receiver=S:1688852231867256_1688858019492397
[INFO][2023-09-09 20:34:05][link_ai_bot.py:81] - [LINKAI] query=[ERROR]
需要管理员权限执行, app_code=zEBF5IMW, mode=gpt-3.5-turbo
[INFO][2023-09-09 20:34:08][link_ai_bot.py:93] - [LINKAI] reply=[用户] 抱歉，我无法提供管理员权限来执行操作。如果您有关于Qlik Sense的其他问题，我会尽力帮助您解答。, total_tokens=1206
[INFO][2023-09-09 20:34:08][wework_channel.py:266] - [WX] sendMsg=Reply(type=TEXT, content=[服务] [用户] 抱歉，我无法提供管理员权限来执行操作。如果您有关于Qlik Sense的其他问题，我会尽力帮助您解答。), receiver=S:1688852231867256_1688858019492397
[INFO][2023-09-09 20:34:10][link_ai_bot.py:81] - [LINKAI] query=[服务] [用户] 抱歉，我无法提供管理员权限来执行操作。如果您有关于Qlik Sense的其他问题，我会尽力帮助您解答。, app_code=zEBF5IMW, mode=gpt-3.5-turbo
[ERROR][2023-09-09 20:34:19][link_ai_bot.py:112] - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\WeChatGPT\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by zhayujie** [comment]
请问是master分支的最新代码嘛， git log 查看一下最新提交信息

这个应该不是用docker镜像运行的吧？

**Comment by woaini1day** [comment]
> 请问是master分支的最新代码嘛， git log 查看一下最新提交信息
> 
> 这个应该不是用docker镜像运行的吧？

感谢提醒，昨天是下载的release的 zip文件。 今天重新git了，现在看是ok的。 中间出现小插曲是 加了代理超时。

后 取消代理后 正常了。
