### ISSUE TITLE
微信扫码登录失败，提示error

### ISSUE THREAD

**Issue by alexcaiym** [zhayujie/chatgpt-on-wechat#143]
python 3.9  腾讯轻量应用服务器   

Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-02-10 02:28:59][app.py:19] - App startup failed!
[ERROR][2023-02-10 02:28:59][app.py:20] - mismatched tag: line 64, column 4
Traceback (most recent call last):
  File "/home/lighthouse/chatgpt-on-wechat/app.py", line 17, in <module>
    channel.startup()
  File "/home/lighthouse/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/python3.9/lib/python3.9/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/python3.9/lib/python3.9/site-packages/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/usr/local/python3.9/lib/python3.9/site-packages/itchat/components/login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/python3.9/lib/python3.9/site-packages/itchat/components/login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/usr/local/python3.9/lib/python3.9/xml/dom/minidom.py", line 1998, in parseString
    return expatbuilder.parseString(string)
  File "/usr/local/python3.9/lib/python3.9/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/local/python3.9/lib/python3.9/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4

### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by alexcaiym** [comment]
[lighthouse@VM-0-17-centos chatgpt-on-wechat]$ pip3 -V
pip 20.2.3 from /usr/local/python3.9/lib/python3.9/site-packages/pip (python 3.9)

Python 3.9.0

**Comment by alexcaiym** [comment]
服务器节点在东京

**Comment by zhayujie** [comment]
> 服务器节点在东京

需要国内的服务器
