### ISSUE TITLE
大佬，我遇到问题来求助啦

### ISSUE THREAD

**Issue by lslove10010** [zhayujie/chatgpt-on-wechat#1453]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

docker-compose 模式下运行，两个微信号，手机号码登录的微信扫码正常登录，使用也正常，qq号登录的微信扫码后登录失败，看失败内容好像是微信号的问题，能正常登录的微信账号是全字母的，不能正常登录的微信账号中间有个"—"减号，会不会跟这个有关系，求大佬给解答一下疑惑~感谢感谢！！！

### 问题描述 😯

[ERROR][2023-09-26 14:38:10][app.py:52] - App startup failed!
[ERROR][2023-09-26 14:38:10][app.py:53] - 'wxsid'
Traceback (most recent call last):
  File "/app/app.py", line 50, in run
    channel.startup()
  File "/app/channel/wechat/wechat_channel.py", line 118, in startup
    itchat.auto_login(
  File "/app/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/app/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/app/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/app/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

### 终端日志 📒

```log


```

**Comment by resphinas** [comment]
绑定个银行卡就行

**Comment by lslove10010** [comment]
收到~
