### ISSUE TITLE
没有plugin.json文件

### ISSUE THREAD

**Issue by chn-youbai** [zhayujie/chatgpt-on-wechat#1467]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

就是clone完代码，然后填好config.json，然后运行app.py，然后就提示没有这个文件了

### 问题描述 😯

就是clone完代码，然后填好config.json，然后运行app.py，然后就提示没有这个文件了
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/112460920/f5bc082b-4e97-4368-85ca-097624bc55f3)

### 终端日志 📒

[INFO][2023-10-06 14:09:17][config.py:172] - [Config] User datas file not found, ignore.
[INFO][2023-10-06 14:09:17][plugin_manager.py:50] - Loading plugins config...
[ERROR][2023-10-06 14:09:17][app.py:52] - App startup failed!
[ERROR][2023-10-06 14:09:17][app.py:53] - [Errno 2] No such file or directory: './plugins/plugins.json'
Traceback (most recent call last):
  File "g:\chatgpt-on-wechat\app.py", line 47, in run
    PluginManager().load_plugins()
  File "g:\chatgpt-on-wechat\plugins\plugin_manager.py", line 172, in load_plugins
    self.load_config()
  File "g:\chatgpt-on-wechat\plugins\plugin_manager.py", line 62, in load_config
    self.save_config()
  File "g:\chatgpt-on-wechat\plugins\plugin_manager.py", line 46, in save_config
    with open("./plugins/plugins.json", "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './plugins/plugins.json'

**Comment by zhayujie** [comment]
运行的路径是在哪里， 看下 plugins目录下有 plugins.json文件嘛

**Comment by Cn-cpjl** [comment]
[INFO][2023-10-26 12:29:11][config.py:172] - [Config] User datas file not found, ignore.
[WARNING][2023-10-26 12:29:11][audio_convert.py:9] - import pysilk failed, wechaty voice message will not be supported.
█
[INFO][2023-10-26 12:29:11][plugin_manager.py:50] - Loading plugins config...
[ERROR][2023-10-26 12:29:11][app.py:52] - App startup failed!
[ERROR][2023-10-26 12:29:11][app.py:53] - [Errno 13] Permission denied: './plugins/plugins.json'
Traceback (most recent call last):
  File "/app/app.py", line 47, in run
    PluginManager().load_plugins()
  File "/app/plugins/plugin_manager.py", line 172, in load_plugins
    self.load_config()
  File "/app/plugins/plugin_manager.py", line 62, in load_config
    self.save_config()
  File "/app/plugins/plugin_manager.py", line 46, in save_config
    with open("./plugins/plugins.json", "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: './plugins/plugins.json'

**Comment by chn-youbai** [comment]
> 运行的路径是在哪里， 看下 plugins目录下有 plugins.json文件嘛

这个项目的plugins里面本来就没有这个文件
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/112460920/b4819857-663a-42f1-8c67-72e02ec671ad)

**Comment by CX-ZG** [comment]
我也是相同的问题

**Comment by zhOrange** [comment]
首次clone后确实没有，第一次运行后会通过sava_config()这个方法生成一个json文件。

**Comment by clear1202** [comment]
我用的colab来运行的，这个问题解决如下：
1、在/plugins/plugin_manager.py程序里面plugins.json改成config.json. 看了注释，我理解应该是代码写错了。
2.、手动将plugins文件下生成的config.json.temple改成config.json
运行就成功了，大家可以试试

**Comment by Brave963** [comment]
> 我用的colab来运行的，这个问题解决如下： 1、在/plugins/plugin_manager.py程序里面plugins.json改成config.json. 看了注释，我理解应该是代码写错了。 2.、手动将plugins文件下生成的config.json.temple改成config.json 运行就成功了，大家可以试试

真的诶 怎么没人叫我还要改plugin.json的 害得我重启好多次

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
