### ISSUE TITLE
不能启动chatGPTonwechat

### ISSUE THREAD

**Issue by AlphaGoMax** [zhayujie/chatgpt-on-wechat#1484]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[3] 856239
nohup:     load_config()
  File "/root/chatgpt-on-wechat/config.py", line 200, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 17 column 3 (char 350)
ignoring input and appending output to 'nohup.out'
[ERROR][2023-10-21 12:18:21][app.py:52] - App startup failed!
[ERROR][2023-10-21 12:18:21][app.py:53] - Expecting value: line 17 column 3 (char 350)
Traceback (most recent call last):
  File "app.py", line 29, in run
    load_config()
  File "/root/chatgpt-on-wechat/config.py", line 200, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 17 column 3 (char 350)

### 问题描述 😯

[3] 856239
nohup:     load_config()
  File "/root/chatgpt-on-wechat/config.py", line 200, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 17 column 3 (char 350)
ignoring input and appending output to 'nohup.out'
[ERROR][2023-10-21 12:18:21][app.py:52] - App startup failed!
[ERROR][2023-10-21 12:18:21][app.py:53] - Expecting value: line 17 column 3 (char 350)
Traceback (most recent call last):
  File "app.py", line 29, in run
    load_config()
  File "/root/chatgpt-on-wechat/config.py", line 200, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 17 column 3 (char 350)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
启动报错JSONDecodeError 的原因一般是 config.json 中配置文件的json格式错误，报错中会提示哪一行出现问题。你可以去 https://www.json.cn/ 进行在线验证
