### ISSUE TITLE
bot改成chatGPT后失败了

### ISSUE THREAD

**Issue by zouzhenglu** [zhayujie/chatgpt-on-wechat#150]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
将bot实现改成chatGPT,
`        return bot_factory.create_bot("chatGPT").reply(query, context)
`
然后运行起来后，一发消息就崩溃
> 简要说明、截图、复现步骤等，也可以是需求或想法
`create
[ERROR][2023-02-10 11:44:14][wechat_channel.py:116] - That model does not exist
Traceback (most recent call last):
  File "C:\Users\kezhe\Documents\workspace\code\python\chatGPT\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 112, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "C:\Users\kezhe\Documents\workspace\code\python\chatGPT\chatgpt-on-wechat\channel\channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "C:\Users\kezhe\Documents\workspace\code\python\chatGPT\chatgpt-on-wechat\bridge\bridge.py", line 9, in fetch_reply_content
    return bot_factory.create_bot("chatGPT").reply(query, context)
  File "C:\Users\kezhe\Documents\workspace\code\python\chatGPT\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 510, in reply
    return self.bot.ask(query)["choices"][0]["text"]
  File "C:\Users\kezhe\Documents\workspace\code\python\chatGPT\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 125, in ask
    completion = self._get_completion(
  File "C:\Users\kezhe\Documents\workspace\code\python\chatGPT\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 51, in _get_completion
    return openai.Completion.create(
  File "C:\Users\kezhe\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\kezhe\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\kezhe\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\kezhe\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\kezhe\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist`

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
改成chatgpt以后，模型用的是 text-chat-davinci-002-20221122,  现在已经失效了
