### ISSUE TITLE
能登录账号，但是聊天的时候终端报错

### ISSUE THREAD

**Issue by MoYingJiang** [zhayujie/chatgpt-on-wechat#1507]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[run.log](https://github.com/zhayujie/chatgpt-on-wechat/files/13293356/run.log)

### 问题描述 😯

我的香港服务器和我的个人电脑是同一个问题，用的是AI-YYDS API接口，并且两个config文件已经改过了

（"open_ai_api_key": "sk-XiBZmbjRT9cRiHO1DXXXXXXXXXXXXX94Bb763718331f",  # openai api key
#当use_azure_chatgpt为true时，需要设置对应的api base
    "open_ai_api_base": "https://ai-yyds.com/v1"）

除了这两行其他没动过

### 终端日志 📒

```log
<此处粘贴终端日志>
```[INFO][2023-11-08 15:01:09][bridge.py:39] - create bot chatGPT for chat
[ERROR][2023-11-08 15:01:09][chat_channel.py:284] - Worker return exception: No module named 'openai.error'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\22322\chatgpt-on-wechat-1.4.0\channel\chat_channel.py", line 155, in _handle
    reply = self._generate_reply(context)
  File "C:\22322\chatgpt-on-wechat-1.4.0\channel\chat_channel.py", line 165, in _generate_reply
    e_context = PluginManager().emit_event(
  File "C:\22322\chatgpt-on-wechat-1.4.0\plugins\plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "C:\22322\chatgpt-on-wechat-1.4.0\plugins\role\role.py", line 104, in on_handle_context
    bot = Bridge().get_bot("chat")
  File "C:\22322\chatgpt-on-wechat-1.4.0\bridge\bridge.py", line 45, in get_bot
    self.bots[typename] = create_bot(self.btype[typename])
  File "C:\22322\chatgpt-on-wechat-1.4.0\bot\bot_factory.py", line 22, in create_bot
    from bot.chatgpt.chat_gpt_bot import ChatGPTBot
  File "C:\22322\chatgpt-on-wechat-1.4.0\bot\chatgpt\chat_gpt_bot.py", line 6, in <module>
    import openai.error
ModuleNotFoundError: No module named 'openai.error'
[INFO][2023-11-08 15:02:36][app.py:17] - signal 2 received, exiting...
[INFO][2023-11-08 15:02:36][config.py:183] - [Config] User datas saved.

**Comment by MoYingJiang** [comment]
并且我的pip3和python版本是正确的，安装requirements.txt时没有报错

**Comment by MoYingJiang** [comment]
"model"改成了"gpt-4"

**Comment by zhayujie** [comment]
检查下 openai 依赖的版本，最近更新的1.0版本不兼容

查看依赖：pip3 show openai
卸载依赖:   pip3 uninstall openai
重新安装：pip3 install openai==0.27.8

**Comment by MoYingJiang** [comment]
牛逼，成了！

**Comment by MoYingJiang** [comment]
辛苦大佬了

**Comment by shebing5** [comment]
我也是openai.error'用上面代码依旧报错bot 你好
[INFO][2023-12-27 16:44:52][bridge.py:49] - create bot chatGPT for chat
[ERROR][2023-12-27 16:44:53][wechatmp_channel.py:233] - [wechatmp] Fail to generate reply to user, msgId=24391052482993502, exception=No module named 'openai.error'
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/chatgpt-on-wechat/channel/chat_channel.py", line 168, in _handle
    reply = self._generate_reply(context)
  File "/home/ubuntu/chatgpt-on-wechat/channel/chat_channel.py", line 178, in _generate_reply
    e_context = PluginManager().emit_event(
  File "/home/ubuntu/chatgpt-on-wechat/plugins/plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/home/ubuntu/chatgpt-on-wechat/plugins/role/role.py", line 104, in on_handle_context
    bot = Bridge().get_bot("chat")
  File "/home/ubuntu/chatgpt-on-wechat/bridge/bridge.py", line 55, in get_bot
    self.bots[typename] = create_bot(self.btype[typename])
  File "/home/ubuntu/chatgpt-on-wechat/bot/bot_factory.py", line 22, in create_bot
    from bot.chatgpt.chat_gpt_bot import ChatGPTBot
  File "/home/ubuntu/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 6, in <module>
    import openai.error
ModuleNotFoundError: No module named 'openai.error'
162.62.81.123:36434 - - [27/Dec/2023 16:44:53] "HTTP/1.1 POST /wx" - 200 OK

**Comment by zhaowj666** [comment]
@shebing5 你好，请问你解决这个问题了吗？
