### ISSUE TITLE
ChatGPT的回复总是: 请再问我一次吧

### ISSUE THREAD

**Issue by zhouyu168** [zhayujie/chatgpt-on-wechat#151]
ChatGPT的回复总是: 请再问我一次吧
是chatGPT问题? 还是微信的问题呢? 谢谢
<img width="730" alt="微信图片_20230210123351" src="https://user-images.githubusercontent.com/124881099/218001550-bd4633fb-96a5-4849-b9f3-6093b343b9be.png">

**Comment by fwx02** [comment]
你可以尝试关闭代理

**Comment by Shmily1368** [comment]
应该是API欠费了？

**Comment by zhouyu168** [comment]
> 你可以尝试关闭代理

有用! 谢谢! : )

**Comment by lvdqiang** [comment]
> 你可以尝试关闭代理

我的代理是关着的，但还是这种情况

**Comment by zhayujie** [comment]
> > 你可以尝试关闭代理
> 
> 我的代理是关着的，但还是这种情况

日志应该有报错，贴一下

**Comment by Dire16** [comment]
你好，我这个有同样的报错，能帮我看下吗
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。
