### ISSUE TITLE
想在chatgpt-on-wechat中提供API接口，给第三方接口使用。

### ISSUE THREAD

**Issue by hevenwus** [zhayujie/chatgpt-on-wechat#1512]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

想在chatgpt-on-wechat中使用FastAPI启动接口服务，提供给第三方使用。
微信主要功能：给某个人或群组发送定时消息等。

### 举例

`
import uvicorn
from fastapi import FastAPI
from bridge.reply import Reply, ReplyType
from channel.wechat.wechat_channel import WechatChannel

app = FastAPI()

@app.get("/")
async def root():
    reply = Reply(ReplyType.TEXT, "你好！有什么问题或者需要帮助的吗？")     
    WechatChannel().send(reply , “如何封装Context？”)
`

但是以上的做法会报错：

`INFO:     192.168.1.8:49765 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/api/main.py", line 11, in root
    WechatChannel().send(reply , None)
  File "/app/channel/wechat/wechat_channel.py", line 295, in send
    itchat.send(reply.content, toUserName=receiver)
  File "/app/lib/itchat/components/messages.py", line 513, in send
    r = self.send_msg(msg, toUserName)
  File "/app/lib/itchat/components/messages.py", line 283, in send_msg
    r = self.send_raw_msg(1, msg, toUserName)
  File "/app/lib/itchat/components/messages.py", line 264, in send_raw_msg
    url = '%s/webwxsendmsg' % self.loginInfo['url']
KeyError: 'url'`

### 动机

想在chatgpt-on-wechat中使用FastAPI启动接口服务，提供给第三方使用。
微信主要功能：给某个人或群组发送定时消息等。

**Comment by clyquan** [comment]
配置channel_type为wechatcom_app时，其实启动一个web服务，内部再调用openai，可以参考一下这块的实现

**Comment by livypy** [comment]
实现里吗 能分享一下吗

**Comment by lovehug-lin** [comment]
请问你这个问题解决了吗

**Comment by liguoyu666** [comment]
请问实现了吗？我也想把自己本地的模型接入

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
