### ISSUE TITLE
linkai-图像汇总出现超时问题

### ISSUE THREAD

**Issue by XcNgg** [zhayujie/chatgpt-on-wechat#1528]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

![1700192943927](https://github.com/zhayujie/chatgpt-on-wechat/assets/105141135/5207cca5-b696-42d6-a61b-28499a829043)

### 问题描述 😯

图像上传后出现如上报错
config.json里面也添加了
"linkai_api_base": "https://api.link-ai.chat"
 linkai的其他功能都照常

### 终端日志 📒

```log
[ERROR][2023-11-17 11:44:07][chat_channel.py:285] - Worker return exception: ('Connection aborted.', timeout('The write operation timed out'))
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1046, in _send_output
    self.send(chunk)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 968, in send
    self.sock.sendall(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1046, in _send_output
    self.send(chunk)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 968, in send
    self.sock.sendall(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat\channel\chat_channel.py", line 156, in _handle
    reply = self._generate_reply(context)
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat\channel\chat_channel.py", line 166, in _generate_reply
    e_context = PluginManager().emit_event(
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat\plugins\plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat\plugins\linkai\linkai.py", line 57, in on_handle_context
    res = LinkSummary().summary_file(file_path)
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat\plugins\linkai\summary.py", line 17, in summary_file
    res = requests.post(url, headers=self.headers(), files=file_body, timeout=(5, 300))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))
```

**Comment by XcNgg** [comment]
![34e26e279c6dfac64c585e483c29856](https://github.com/zhayujie/chatgpt-on-wechat/assets/105141135/19d6c5ab-a818-480e-9165-ab28ae868ee3)
官方的好像也崩掉了，不知道是不是官方接口的问题，总结没问题，但是图片总结一直没有回复

**Comment by zhayujie** [comment]
你好，这段日志报错的具体时间可以提供一下嘛

('Connection aborted.', timeout('The write operation timed out'))

**Comment by jaylpp** [comment]
@zhayujie 请问下这个 bug 怎么解决的呢
