### ISSUE TITLE
最新版本 (11月17日) 安裝後不能啟動

### ISSUE THREAD

**Issue by henrikclh** [zhayujie/chatgpt-on-wechat#1531]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

完全按照了 https://github.com/zhayujie/chatgpt-on-wechat/ 的指示 (以往版本每次都成功的, 沒有換過平台/方法)

git clone https://github.com/zhayujie/chatgpt-on-wechat
cd chatgpt-on-wechat/
pip3 install -r requirements.txt
pip3 install -r requirements-optional.txt
cp config-template.json config.json (然後跟以往一樣設置好)

touch nohup.out                                   # 首次运行需要新建日志文件  
nohup python3 app.py & tail -f nohup.out          # 在后台运行程序并通过日志输出二维码

就是這步開始報錯

### 问题描述 😯

我用的是騰訊雲, 今天從新開始安裝最新版本, 卻啟動不了 (以往從未發生過), 試過把Python 3.10降到3.9.18也不行
![20231117](https://github.com/zhayujie/chatgpt-on-wechat/assets/118831947/75d8b2d4-f8a3-4902-b787-4cc9e895a31f)

### 终端日志 📒

```log
<[ERROR][2023-11-17 21:21:13][app.py:52] - App startup failed!
[ERROR][2023-11-17 21:21:13][app.py:53] - Expecting value: line 16 column 1 (char 319)
Traceback (most recent call last):
  File "/home/lighthouse/chatgpt-on-wechat/app.py", line 29, in run
    load_config()
  File "/home/lighthouse/chatgpt-on-wechat/config.py", line 205, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 16 column 1 (char 319)
[ERROR][2023-11-17 21:29:21][app.py:52] - App startup failed!
[ERROR][2023-11-17 21:29:21][app.py:53] - Expecting value: line 16 column 1 (char 319)
Traceback (most recent call last):
  File "/home/lighthouse/chatgpt-on-wechat/app.py", line 29, in run
    load_config()
  File "/home/lighthouse/chatgpt-on-wechat/config.py", line 205, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 16 column 1 (char 319)
[ERROR][2023-11-17 21:29:44][app.py:52] - App startup failed!
[ERROR][2023-11-17 21:29:44][app.py:53] - Expecting value: line 16 column 1 (char 319)
Traceback (most recent call last):
  File "/home/lighthouse/chatgpt-on-wechat/app.py", line 29, in run
    load_config()
  File "/home/lighthouse/chatgpt-on-wechat/config.py", line 205, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 16 column 1 (char 319)
[ERROR][2023-11-17 21:39:14][app.py:52] - App startup failed!
[ERROR][2023-11-17 21:39:14][app.py:53] - Expecting value: line 16 column 1 (char 319)
Traceback (most recent call last):
  File "/home/lighthouse/chatgpt-on-wechat/app.py", line 29, in run
    load_config()
  File "/home/lighthouse/chatgpt-on-wechat/config.py", line 205, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 16 column 1 (char 319)
>
```

**Comment by mela93** [comment]
贴一下配置文件，看报错信息是config.json文件解析出错了，看看是不是多了什么符号或者少了`,`，`"`之类

**Comment by henrikclh** [comment]
> 贴一下配置文件看看，注意吧key隐藏或者打马赛克。 看报错信息是config.json文件解析出错了，看看是不是多了什么符号或者少了`,`，`"`之类

最後把config.json全都複製到 vs code, 然後發現幾個空格不符合規格 (截了圖放最下面) 把它們刪了再自己打空格就可以了!

至於原因, 我在把舊的CoW刪之前, 是先把原來和插件的config.json都複製到PPT, 然後安裝新CoW後再逐一貼回去, 沒想到會導致空格格式有異, 謝謝mela93 提醒, 所以才想到把碼複製到vs code排下錯, 感謝!

![20231118](https://github.com/zhayujie/chatgpt-on-wechat/assets/118831947/d4209fe2-03fd-4fd0-8fd5-e978d76841bf)
