### ISSUE TITLE
api填了中转的报错

### ISSUE THREAD

**Issue by dhf2587154870** [zhayujie/chatgpt-on-wechat#1543]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

api填了中转的报错
![photo_2023-11-20_17-13-46](https://github.com/zhayujie/chatgpt-on-wechat/assets/92639256/cc259b85-a084-41dd-8632-333f01b04e5a)
![photo_2023-11-20_18-17-54](https://github.com/zhayujie/chatgpt-on-wechat/assets/92639256/793edb5e-fdb6-465b-b50a-57d0c7b2fce4)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by dhf2587154870** [comment]
我不知道我哪儿填错了 还是哪儿查了点配置 求大佬帮忙指点迷津

**Comment by mela93** [comment]
请仔细看配置说明。
```
{
"open_ai_api_key": "你的openai的key，例：sk-123123123123123123",    
"open_ai_api_base": "中转api地址，例：https://exmaple.com/v1"
}
```

**Comment by dhf2587154870** [comment]
我也试过这样填但是还是不行

Immortal ***@***.***> 于2023年11月23日周四 17:54写道：

**Comment by mela93** [comment]
看看正确填写后的日志吧，贴一下报什么错误

**Comment by chendy498** [comment]
我的也不行，难顶

**Comment by dongdongla** [comment]
> 我的也不行，难顶

解决了吗哥们儿

**Comment by chendy498** [comment]
你看看你修改的是不是.py文件，要修改那个config.json文件
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年12月31日 10:25
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [zhayujie/chatgpt-on-wechat] api填了中转的报错 (Issue #1543)
        
      
    
  


我的也不行，难顶

解决了吗哥们儿

**Comment by guluahljj** [comment]
我的也是这样子，
``` config
"open_ai_api_key": "sk-vRYddQhaK0Z9a1setMwzhNY7DFhWPD7dDo7j8RH5gtPrWK",
  "open_ai_api_base": "https://api.chatanywhere.tech/v1",
```
```
日志错误如下：

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 168, in _handle
    reply = self._generate_reply(context)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 178, in _generate_reply
    e_context = PluginManager().emit_event(
  File "/root/chatgpt-on-wechat/plugins/plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/root/chatgpt-on-wechat/plugins/newgpt_turbo/main.py", line 107, in on_handle_context
    conversation_output = self.run_conversation(input_messages, e_context)
  File "/root/chatgpt-on-wechat/plugins/newgpt_turbo/main.py", line 127, in run_conversation
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
  File "/usr/local/lib/python3.10/dist-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
···
```
更换了几个APIkey也是这样子的报错，但是同样的API配置在docker中却是可以正常的使用

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
