### ISSUE TITLE
登录时应用自动退出，这是什么情况？

### ISSUE THREAD

**Issue by vvip2u** [zhayujie/chatgpt-on-wechat#1550]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

扫码登录

### 问题描述 😯

扫码后退出了应用

### 终端日志 📒

```log
[ERROR][2023-11-26 12:28:06][app.py:52] - App startup failed!
[ERROR][2023-11-26 12:28:06][app.py:53] - 'wxsid'
Traceback (most recent call last):
  File "D:\workspace\python_workspace\chatgpt-on-wechat\app.py", line 50, in run
    channel.startup()
  File "D:\workspace\python_workspace\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 118, in startup
    itchat.auto_login(
  File "D:\workspace\python_workspace\chatgpt-on-wechat\lib\itchat\components\register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "D:\workspace\python_workspace\chatgpt-on-wechat\lib\itchat\components\login.py", line 61, in login
    status = self.check_login()
  File "D:\workspace\python_workspace\chatgpt-on-wechat\lib\itchat\components\login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "D:\workspace\python_workspace\chatgpt-on-wechat\lib\itchat\components\login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

```

**Comment by zhayujie** [comment]
账号需要实名
