### ISSUE TITLE
本地运行该项目报错

### ISSUE THREAD

**Issue by wxfaith** [zhayujie/chatgpt-on-wechat#1599]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

登陆成功，但是发送bot今天天气怎么样就会报错

### 问题描述 😯

Traceback (most recent call last):
  File "D:\wx_nosleep\chatgpt-on-wechat-master\lib\itchat\components\register.py", line 63, in configured_reply
    r = replyFn(msg)
  File "D:\wx_nosleep\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 35, in handler_single_msg
    WechatChannel().handle_single(cmsg)
  File "D:\wx_nosleep\chatgpt-on-wechat-master\common\time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
  File "D:\wx_nosleep\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 64, in wrapper
    return func(self, cmsg)
  File "D:\wx_nosleep\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 160, in handle_single
    context = self._compose_context(cmsg.ctype, cmsg.content, isgroup=False, msg=cmsg)
  File "D:\wx_nosleep\chatgpt-on-wechat-master\channel\chat_channel.py", line 148, in _compose_context
    img_match_prefix = check_prefix(content, conf().get("image_create_prefix"))
  File "D:\wx_nosleep\chatgpt-on-wechat-master\channel\chat_channel.py", line 381, in check_prefix
    if content.startswith(prefix):
TypeError: startswith first arg must be str or a tuple of str, not list

### 终端日志 📒

```log
<此处粘贴终端日志>

**Comment by zhayujie** [comment]
是不是删除了 image_create_prefix 配置， 如果不需要画图可以配置成 
```
"image_create_prefix": [
    ""
  ],
```

**Comment by wxfaith** [comment]
> 是不是删除了 image_create_prefix 配置， 如果不需要画图可以配置成
> 
> ```
> "image_create_prefix": [
>     ""
>   ],
> ```
if content.startswith(prefix)这句话上面改成了str(prefix)就不报错了，不过我换电脑就没有这个问题了。
