### ISSUE TITLE
model配置为gemini后，无法使用text_to_image功能

### ISSUE THREAD

**Issue by colakang** [zhayujie/chatgpt-on-wechat#1615]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

config.json:
model = gemini,
text_to_image = dall-e-3

微信指令:
画一个lego模型

### 问题描述 😯

微信发出指令:
画一个lego模型

服务端报下列错误

### 终端日志 📒

```log
[WARNING][2023-12-20 00:53:28][google_gemini_bot.py:31] - [Gemini] Unsupported message type, type=IMAGE_CREATE
[ERROR][2023-12-20 00:53:28][chat_channel.py:299] - Worker return exception: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "\miniconda3\envs\wechat\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "\wechatbot\chatgpt-on-wechat\channel\chat_channel.py", line 172, in _handle
    reply = self._decorate_reply(context, reply)
  File "\wechatbot\chatgpt-on-wechat\channel\chat_channel.py", line 257, in _decorate_reply
    reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")
TypeError: can only concatenate str (not "NoneType") to str
[WARNING][2023-12-20 00:54:34][google_gemini_bot.py:31] - [Gemini] Unsupported message type, type=IMAGE_CREATE
[ERROR][2023-12-20 00:54:34][chat_channel.py:299] - Worker return exception: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "\miniconda3\envs\wechat\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "\Downloads\digital life\wechatbot\chatgpt-on-wechat\channel\chat_channel.py", line 172, in _handle
    reply = self._decorate_reply(context, reply)
  File "\Downloads\digital life\wechatbot\chatgpt-on-wechat\channel\chat_channel.py", line 257, in _decorate_reply
    reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by XueJourney** [comment]
最好把完整的config.json发一下，方面判断

**Comment by sparkssssssss** [comment]
同样的问题

**Comment by chne2001** [comment]
看了一下 gemini好像根本没有写接口进去

**Comment by MasonWest** [comment]
gemini目前画不了

**Comment by FIELA** [comment]
how does this goes now?
