### ISSUE TITLE
微信登陆失败

### ISSUE THREAD

**Issue by WDAhyhy** [zhayujie/chatgpt-on-wechat#1632]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

根据文档进行操作，扫码登陆之后发生错误，且无法实现正常的功能

### 终端日志 📒

[ERROR][2023-12-28 04:28:24][app.py:52] - App startup failed!
[ERROR][2023-12-28 04:28:24][app.py:53] - 'wxsid'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 50, in run
    channel.startup()
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 118, in startup
    itchat.auto_login(
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

**Comment by snowman109** [comment]
有同样的问题，自己的账号没问题，新建的小号有问题

**Comment by cleven1** [comment]
今天也遇到这个问题, 新建的小号无法获取到cookies
core.s.cookies.get_dict() 这个方法拿到的是空, 这个代码在login.py 198行的位置

大佬该怎么解决呢?

**Comment by snowman109** [comment]
> 今天也遇到这个问题, 新建的小号无法获取到cookies core.s.cookies.get_dict() 这个方法拿到的是空, 这个代码在login.py 198行的位置
> 
> 大佬该怎么解决呢?

实名认证就好了
