### ISSUE TITLE
使用文心一言无法画图Worker return exception: 'BaiduWenxinBot' object has no attribute 'create_img'

### ISSUE THREAD

**Issue by xiaoyu0909** [zhayujie/chatgpt-on-wechat#1633]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

只要发送触发画图的关键字日志就会报错Worker return exception: 'BaiduWenxinBot' object has no attribute 'create_img'

### 问题描述 😯

![微信截图_20231228124258](https://github.com/zhayujie/chatgpt-on-wechat/assets/144976293/04b0c13e-a297-49ba-9f0c-17931bf402f0)

### 终端日志 📒

```log
[ERROR][2023-12-28 04:42:41][chat_channel.py:299] - Worker return exception: 'BaiduWenxinBot' object has no attribute 'create_img'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/channel/chat_channel.py", line 168, in _handle
    reply = self._generate_reply(context)
  File "/app/channel/chat_channel.py", line 189, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "/app/channel/channel.py", line 37, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/app/bridge/bridge.py", line 64, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "/app/bot/baidu/baidu_wenxin.py", line 56, in reply
    ok, retstring = self.create_img(query, 0)
AttributeError: 'BaiduWenxinBot' object has no attribute 'create_img'

```

**Comment by forealmy** [comment]
这个功能在文心上没有实现吧？用的不是3.5吗

**Comment by 6vision** [comment]
百度文心未支持作图
