### ISSUE TITLE
可以把gemini部署在Railway的模板上吗

### ISSUE THREAD

**Issue by limaolin2017** [zhayujie/chatgpt-on-wechat#1639]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 复现步骤 🕹

railway一键部署

### 问题描述 😯

在railway中没有安装支持gemini的库

### 终端日志 📒

```log
Start auto replying.

[INFO][2023-12-31 01:09:34][bridge.py:49] - create bot gemini for chat

[ERROR][2023-12-31 01:09:34][chat_channel.py:299] - Worker return exception: No module named 'google.generativeai'

Traceback (most recent call last):

File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run

result = self.fn(*self.args, **self.kwargs)

File "/app/channel/chat_channel.py", line 168, in _handle

reply = self._generate_reply(context)

File "/app/channel/chat_channel.py", line 189, in _generate_reply

reply = super().build_reply_content(context.content, context)

File "/app/channel/channel.py", line 37, in build_reply_content

return Bridge().fetch_reply_content(query, context)

File "/app/bridge/bridge.py", line 64, in fetch_reply_content

return self.get_bot("chat").reply(query, context)

File "/app/bridge/bridge.py", line 55, in get_bot

self.bots[typename] = create_bot(self.btype[typename])

File "/app/bot/bot_factory.py", line 52, in create_bot

from bot.gemini.google_gemini_bot import GoogleGeminiBot

File "/app/bot/gemini/google_gemini_bot.py", line 10, in <module>

import google.generativeai as genai

ModuleNotFoundError: No module named 'google.generativeai'
```

**Comment by zwdzwdzwd** [comment]
同样的错误，在原来openai 的位置填gemini的key 就是这样的结果，求解。

**Comment by li5bo5** [comment]
我也想把gemini部署在Railway，该怎么操作啊

**Comment by 6vision** [comment]
railway不再免费部署，后续应不再维护了，建议服务器直接部署
