### ISSUE TITLE
企业微信无法启动

### ISSUE THREAD

**Issue by aidmji** [zhayujie/chatgpt-on-wechat#1652]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 问题描述 😯

![21](https://github.com/zhayujie/chatgpt-on-wechat/assets/86823530/0538879e-c1d0-4448-b3fa-38e1c2da90bc)
按企业微信教程进行配置，无法启动

### 终端日志 📒

[ERROR][2024-01-05 12:58:41][app.py:52] - App startup failed!
[ERROR][2024-01-05 12:58:41][app.py:53] - Extra data: line 21 column 1 (char 841)
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 29, in run
    load_config()
  File "/root/chatgpt-on-wechat/config.py", line 227, in load_config
    config = Config(json.loads(config_str))
  File "/usr/local/python3/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 21 column 1 (char 841)

**Comment by aidmji** [comment]
个人微信可以正常使用
