### ISSUE TITLE
钉钉对接报错

### ISSUE THREAD

**Issue by AaronSttttt** [zhayujie/chatgpt-on-wechat#1685]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

python版本 3.9.5
chatgpt-on-wechat版本 1.5.5
运行项目后报错，
接入个人微信正常，换钉钉后报错，钉钉应用和机器人都已做完，stream模式推送的 已完成接入，验证连接通道 点完后提示 stream模式接入失败

### 终端日志 📒

```log
2024-01-18 11:32:32,667 dingtalk_stream.client INFO     open connection, url=https://api.dingtalk.com/v1.0/gateway/connections/open [stream.py:133]
2024-01-18 11:32:32,928 dingtalk_stream.client INFO     endpoint is {'endpoint': 'wss://wss-open-connection.dingtalk.com:443/connect', 'ticket': '3726a276-b5b2-11ee-8ef4-6e1e6cb7263c'} [stream.py:72]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dingtalk_stream/stream.py", line 119, in start_forever
    asyncio.run(self.start())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/dingtalk_stream/stream.py", line 75, in start
    async with websockets.connect(uri) as websocket:
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 629, in __aenter__
    return await self
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

```

**Comment by liushenmer** [comment]
我是无法安装这个dingding库，运行pip就会出现以下报错，整懵了暂时没办法
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

**Comment by liushenmer** [comment]
dingtalk_stream.client ERROR    open connection failed, error=401 Client Error: Unauthorized for url: https://api.dingtalk.com/v1.0/gateway/connections/open, response.body={'requestid': 'B42891A9-C380-7449-93FB-69E04D308CC1', 'code': 'authFailed', 'message': '鉴权失败'} [stream.py:162]

有兄弟遇到过吗？怎么解决？

**Comment by baojingyu** [comment]
出错：
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

解决方法
进入python 3.9 的application安装路径。

cd /Applications/Python\ 3.9/

执行证书安装命令：

./Install\ Certificates.command 

安装完成，重新运行app.py

**Comment by dhr2333** [comment]
Stream模式接入失败,请参考Stream模式SDK接入指南。
这是什么情况？

**Comment by zhayujie** [comment]
安装证书可解决

**Comment by AchieSun** [comment]
获取评论
