### ISSUE TITLE
Cannot connect to proxy

### ISSUE THREAD

**Issue by bboychencan** [zhayujie/chatgpt-on-wechat#170]
### 前置确认

1. 运行于国内网络环境，开了vpn代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 长时间没有访问请求以后自动log out

### 终端日志 (如有报错)

```
[INFO][2023-02-11 01:37:43][wechat_channel.py:103] - [WX] sendMsg=你可以问我任何你想知道的问题。我会尽力回答你。, receiver=@ec175a7994bc083591c78e7abdc7e185
Traceback (most recent call last):
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1676051126144&skey=%40crypt_61679a52_e4868a17eda9ad898e75f80f2694355c&sid=gPBbWbsUpKdNzXn4&uin=749685876&deviceid=e517950028871019&synckey=1_745302866%7C2_745303046%7C3_745302880%7C11_745302919%7C19_32046%7C23_1676048529%7C24_1676050665%7C27_2341%7C201_1676050661%7C203_1676048593%7C206_101%7C1000_1676037602%7C1001_1676034125&_=1676048529528 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/itchat/components/login.py", line 348, in sync_check
    r = self.s.get(url, params=params, headers=headers,
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1676051126144&skey=%40crypt_61679a52_e4868a17eda9ad898e75f80f2694355c&sid=gPBbWbsUpKdNzXn4&uin=749685876&deviceid=e517950028871019&synckey=1_745302866%7C2_745303046%7C3_745302880%7C11_745302919%7C19_32046%7C23_1676048529%7C24_1676050665%7C27_2341%7C201_1676050661%7C203_1676048593%7C206_101%7C1000_1676037602%7C1001_1676034125&_=1676048529528 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/itchat/components/login.py", line 289, in maintain_loop
    i = sync_check(self)
  File "/Users/canchen/Develop/Applications/miniconda3/lib/python3.10/site-packages/itchat/components/login.py", line 352, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range

LOG OUT!
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：mac
 - Python版本  ( 执行 `python3 -V` )：         3.10.9       
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：22.3.1

**Comment by zhayujie** [comment]
是不是中途开了代理什么的吗

**Comment by bboychencan** [comment]
我一直挂着clashx 的 vpn，没有中途动过。 是跟这个有关吗？
这个不需要翻墙就可以使用的吗？ 国内是可以调用openai的接口的是么？

**Comment by zhayujie** [comment]
> 我一直挂着clashx 的 vpn，没有中途动过。 是跟这个有关吗？ 这个不需要翻墙就可以使用的吗？ 国内是可以调用openai的接口的是么？

对的，不需要翻墙

**Comment by fantuanliu** [comment]
> 我一直挂着clashx 的 vpn，没有中途动过。 是跟这个有关吗？ 这个不需要翻墙就可以使用的吗？ 国内是可以调用openai的接口的是么？

请问你的可以用了吗？我碰到了同样的问题
