### ISSUE TITLE
wechatpy.exceptions.WeChatClientException: Error code: 60020, message: not allow to access from your ip

### ISSUE THREAD

**Issue by Ikaros-521** [zhayujie/chatgpt-on-wechat#1728]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

正常配置后，通过frp穿透9898到云服务器
正常发送信息给bot，bot处理后，无法返回数据

### 终端日志 📒

```log
[ERROR][2024-02-02 12:38:36][chat_channel.py:314] - [WX] sendMsg error: Error code: 60020, message: not allow to access from your ip, hint: [1706848717432011565347844], from ip: x.x.x.x, more info at https://open.work.weixin.qq.com/devtool/query?e=60020
[ERROR][2024-02-02 12:38:36][chat_channel.py:317] - Error code: 60020, message: not allow to access from your ip, hint: [1706848717432011565347844], from ip: x.x.x.x, more info at https://open.work.weixin.qq.com/devtool/query?e=60020
Traceback (most recent call last):
  File "E:\GitHub_pro\chatgpt-on-wechat\channel\chat_channel.py", line 312, in _send
    self.send(reply, context)
  File "E:\GitHub_pro\chatgpt-on-wechat\channel\wechatcom\wechatcomapp_channel.py", line 60, in send
    self.client.message.send_text(self.agent_id, receiver, text)
  File "e:\GitHub_pro\chatgpt-on-wechat\Miniconda3\lib\site-packages\wechatpy\enterprise\client\api\message.py", line 62, in send_text
    return self.send(
  File "e:\GitHub_pro\chatgpt-on-wechat\Miniconda3\lib\site-packages\wechatpy\enterprise\client\api\message.py", line 58, in send
    return self._post('message/send', data=data)
  File "e:\GitHub_pro\chatgpt-on-wechat\Miniconda3\lib\site-packages\wechatpy\client\api\base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "e:\GitHub_pro\chatgpt-on-wechat\Miniconda3\lib\site-packages\wechatpy\client\base.py", line 182, in post
    return self._request(
  File "e:\GitHub_pro\chatgpt-on-wechat\Miniconda3\lib\site-packages\wechatpy\client\base.py", line 101, in _request
    return self._handle_result(
  File "e:\GitHub_pro\chatgpt-on-wechat\Miniconda3\lib\site-packages\wechatpy\client\base.py", line 158, in _handle_result
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: 60020, message: not allow to access from your ip, hint: [1706848714562580138459166], from ip: x.x.x.x, more info at https://open.work.weixin.qq.com/devtool/query?e=60020
```

**Comment by Ikaros-521** [comment]
bot应用中 底部添加对应ip后解决
![0WZ{6CD~~AC2HG5T`_F% 73](https://github.com/zhayujie/chatgpt-on-wechat/assets/40910637/d36f5904-2287-4da3-a2b6-d19a32f6b409)

**Comment by bigBoLang** [comment]
> bot应用中 底部添加对应ip后解决 ![0WZ{6CD~~AC2HG5T`_F% 73](https://github.com/zhayujie/chatgpt-on-wechat/assets/40910637/d36f5904-2287-4da3-a2b6-d19a32f6b409)

这个现在得有域名是吧，家庭的网络能用嘛
