### ISSUE TITLE
dall-e-3 无法通过中转调用

### ISSUE THREAD

**Issue by kflyfly** [zhayujie/chatgpt-on-wechat#1734]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

使用第三方中转平台，会直接返回错误：
[ERROR]
画图出现问题，请休息一下再问我吧

测试了7个平台，也全部都不能调用。已经和平台主联系，确定是wechat 项目的问题。不是第三方平台的问题

### 问题描述 😯

# 在最新版本的调用中bug日志：
````
open_ai_image.py:22] - [OPEN_AI] image_query=两头莫奈风格的野猪，浪漫主义点彩风格再加上未来主义运动色差
[ERROR][2024-02-05 19:33:26][open_ai_image.py:42] - The server is overloaded or not ready yet.
Traceback (most recent call last):
  File "/root/wechat/chatgpt-on-wechat/bot/openai/open_ai_image.py", line 23, in create_img
    response = openai.Image.create(
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/image.py", line 39, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 743, in _interpret_response_line
    raise error.ServiceUnavailableError(
openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.
[INFO][2024-02-05 19:33:27][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
画图出现问题，请休息一下再问我吧), receiver=@77e399f396b********************************

````

# 在上一个版本报错信息：
````
[INFO][2024-02-05 18:44:17][open_ai_image.py:22] - [OPEN_AI] image_query=两头莫奈风格的野猪，浪漫主义点彩风格再加上未来主义运动色差
[INFO][2024-02-05 18:44:17][wechat_channel.py:54] - Wechat message 3505740523706516164 already received, ignore
[INFO][2024-02-05 18:44:17][wechat_channel.py:54] - Wechat message 3505740523706516164 already received, ignore
[ERROR][2024-02-05 18:44:18][open_ai_image.py:42] - bad response status code 307 (request id: 20240205184417751420936Q63EBTqp) {"error":{"message":"bad response status code 307 (request id: 20240205184417751420936Q63EBTqp)","type":"upstream_error","param":"307","code":"bad_response_status_code"}} 307 {'error': {'message': 'bad response status code 307 (request id: 20240205184417751420936Q63EBTqp)', 'type': 'upstream_error', 'param': '307', 'code': 'bad_response_status_code'}} {'Date': 'Mon, 05 Feb 2024 10:44:18 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '170', 'Connection': 'keep-alive', 'X-Oneapi-Request-Id': '20240205184417751420936Q63EBTqp', 'Cache-Control': 'no-cache', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=qQ83VG%2Fd0RFA5xy3OVpX%2F1wfgCOtkacOIXXw7%2BJfs546zke0PsdivZiSoKTUccr3b5tuaFEQWBbhgPFmDLWUEyVHpSyzbtWRKra%2B5OaQIz%2B5HNYMuYMGjn%2B%2FAq8%2BbdY%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '850a8ea97f9e2332-HKG', 'alt-svc': 'h3=":443"; ma=86400'}
Traceback (most recent call last):
  File "/root/wechat/chatgpt-on-wechat/bot/openai/open_ai_image.py", line 23, in create_img
    response = openai.Image.create(
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/image.py", line 39, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: bad response status code 307 (request id: 20240205184417751420936Q63EBTqp) {"error":{"message":"bad response status code 307 (request id: 20240205184417751420936Q63EBTqp)","type":"upstream_error","param":"307","code":"bad_response_status_code"}} 307 {'error': {'message': 'bad response status code 307 (request id: 20240205184417751420936Q63EBTqp)', 'type': 'upstream_error', 'param': '307', 'code': 'bad_response_status_code'}} {'Date': 'Mon, 05 Feb 2024 10:44:18 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '170', 'Connection': 'keep-alive', 'X-Oneapi-Request-Id': '20240205184417751420936Q63EBTqp', 'Cache-Control': 'no-cache', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=qQ83VG%2Fd0RFA5xy3OVpX%2F1wfgCOtkacOIXXw7%2BJfs546zke0PsdivZiSoKTUccr3b5tuaFEQWBbhgPFmDLWUEyVHpSyzbtWRKra%2B5OaQIz%2B5HNYMuYMGjn%2B%2FAq8%2BbdY%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '850a8ea97f9e2332-HKG', 'alt-svc': 'h3=":443"; ma=86400'}
[INFO][2024-02-05 18:44:18][wechat_channel.py:207] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
画图出现问题，请休息一下再问我吧), receiver=@1ef060f3de2770181526a4a493225be0c5748a*************************
[INFO][2024-02-05 18:45:14][wechat_channel.py:54] - Wechat message 5021133391921074937 already received, ignore
[INFO][2024-02-05 18:45:14][wechat_channel.py:54] - Wechat message 5021133391921074937 already received, ignore
````

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by VectorZhao** [comment]
one-api代理的dall-e-3是不是没法调用？

**Comment by kflyfly** [comment]
> one-api代理的dall-e-3是不是没法调用？
与one-api无关，发现部分贩子渠道是可以在wechat 调用成功的，但是很多在wechat端不支持，主要原因是wechat 项目只是别个别图片链接，导致接受了图片，却不能下载
