### ISSUE TITLE
登录后第二天报错IndexError: tuple index out of range，但不影响正常使用（大概）

### ISSUE THREAD

**Issue by youyi0218** [zhayujie/chatgpt-on-wechat#1745]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

扫码登陆后第一天可以正常使用，第二天就会出现报错，但不影响使用（？）

### 问题描述 😯

第一天登录后可以正常使用，第二天就会出现报错，询问微信群内机器人说是网络问题，但是用的是讯飞模型且可以正常联网。询问的第一句话后台有接收显示但不会回复，第二句话就可以正常回复

### 终端日志 📒

```log
<此处粘贴终端日志>
```Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\python\3.10.11\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000018786E8BFD0>: Failed to resolve 'wx.qq.com' ([Errno 11002] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=AWOy0kCXJ7anp+23&skey=@crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&pass_ticket=TXy%2FwXh4G3mHETItHORkDI7TqFdWeDL9JZenpmni%2BQGelApBMQCp267gRwR87KlADC74e4l0cgMfkWBgVIAbbw%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786E8BFD0>: Failed to resolve 'wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 301, in maintain_loop
    msgList, contactList = self.get_msg()
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 390, in get_msg
    r = self.s.post(url, data=json.dumps(data),
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=AWOy0kCXJ7anp+23&skey=@crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&pass_ticket=TXy%2FwXh4G3mHETItHORkDI7TqFdWeDL9JZenpmni%2BQGelApBMQCp267gRwR87KlADC74e4l0cgMfkWBgVIAbbw%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786E8BFD0>: Failed to resolve 'wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\python\3.10.11\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000018786FAE8C0>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1707441102515&skey=%40crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&sid=AWOy0kCXJ7anp%2B23&uin=1186530606&deviceid=e382612741627493&synckey=1_810441505%7C2_810441586%7C3_810441435%7C11_810440705%7C19_36191%7C23_1707395814%7C24_1707440754%7C25_810441586%7C27_2943%7C201_1707440754%7C206_101%7C1000_1707431416%7C1001_1707435061&_=1707395816342 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786FAE8C0>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 356, in sync_check
    r = self.s.get(url, params=params, headers=headers,
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1707441102515&skey=%40crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&sid=AWOy0kCXJ7anp%2B23&uin=1186530606&deviceid=e382612741627493&synckey=1_810441505%7C2_810441586%7C3_810441435%7C11_810440705%7C19_36191%7C23_1707395814%7C24_1707440754%7C25_810441586%7C27_2943%7C201_1707440754%7C206_101%7C1000_1707431416%7C1001_1707435061&_=1707395816342 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786FAE8C0>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 295, in maintain_loop
    i = sync_check(self)
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 360, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\python\3.10.11\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000018786FAEAA0>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1707441103548&skey=%40crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&sid=AWOy0kCXJ7anp%2B23&uin=1186530606&deviceid=e382612741627493&synckey=1_810441505%7C2_810441586%7C3_810441435%7C11_810440705%7C19_36191%7C23_1707395814%7C24_1707440754%7C25_810441586%7C27_2943%7C201_1707440754%7C206_101%7C1000_1707431416%7C1001_1707435061&_=1707395816343 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786FAEAA0>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 356, in sync_check
    r = self.s.get(url, params=params, headers=headers,
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1707441103548&skey=%40crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&sid=AWOy0kCXJ7anp%2B23&uin=1186530606&deviceid=e382612741627493&synckey=1_810441505%7C2_810441586%7C3_810441435%7C11_810440705%7C19_36191%7C23_1707395814%7C24_1707440754%7C25_810441586%7C27_2943%7C201_1707440754%7C206_101%7C1000_1707431416%7C1001_1707435061&_=1707395816343 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786FAEAA0>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 295, in maintain_loop
    i = sync_check(self)
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 360, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\python\3.10.11\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000018786FAE230>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1707441104569&skey=%40crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&sid=AWOy0kCXJ7anp%2B23&uin=1186530606&deviceid=e382612741627493&synckey=1_810441505%7C2_810441586%7C3_810441435%7C11_810440705%7C19_36191%7C23_1707395814%7C24_1707440754%7C25_810441586%7C27_2943%7C201_1707440754%7C206_101%7C1000_1707431416%7C1001_1707435061&_=1707395816344 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786FAE230>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 356, in sync_check
    r = self.s.get(url, params=params, headers=headers,
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1707441104569&skey=%40crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&sid=AWOy0kCXJ7anp%2B23&uin=1186530606&deviceid=e382612741627493&synckey=1_810441505%7C2_810441586%7C3_810441435%7C11_810440705%7C19_36191%7C23_1707395814%7C24_1707440754%7C25_810441586%7C27_2943%7C201_1707440754%7C206_101%7C1000_1707431416%7C1001_1707435061&_=1707395816344 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786FAE230>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 295, in maintain_loop
    i = sync_check(self)
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 360, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\python\3.10.11\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000018786FACF40>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1707441105588&skey=%40crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&sid=AWOy0kCXJ7anp%2B23&uin=1186530606&deviceid=e382612741627493&synckey=1_810441505%7C2_810441586%7C3_810441435%7C11_810440705%7C19_36191%7C23_1707395814%7C24_1707440754%7C25_810441586%7C27_2943%7C201_1707440754%7C206_101%7C1000_1707431416%7C1001_1707435061&_=1707395816345 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786FACF40>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 356, in sync_check
    r = self.s.get(url, params=params, headers=headers,
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1707441105588&skey=%40crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&sid=AWOy0kCXJ7anp%2B23&uin=1186530606&deviceid=e382612741627493&synckey=1_810441505%7C2_810441586%7C3_810441435%7C11_810440705%7C19_36191%7C23_1707395814%7C24_1707440754%7C25_810441586%7C27_2943%7C201_1707440754%7C206_101%7C1000_1707431416%7C1001_1707435061&_=1707395816345 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786FACF40>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 295, in maintain_loop
    i = sync_check(self)
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 360, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\python\3.10.11\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "D:\python\3.10.11\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000018786FAECE0>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\python\3.10.11\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\python\3.10.11\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1707441106611&skey=%40crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&sid=AWOy0kCXJ7anp%2B23&uin=1186530606&deviceid=e382612741627493&synckey=1_810441505%7C2_810441586%7C3_810441435%7C11_810440705%7C19_36191%7C23_1707395814%7C24_1707440754%7C25_810441586%7C27_2943%7C201_1707440754%7C206_101%7C1000_1707431416%7C1001_1707435061&_=1707395816346 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786FAECE0>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 356, in sync_check
    r = self.s.get(url, params=params, headers=headers,
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\3.10.11\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1707441106611&skey=%40crypt_b26d1be0_d094e369d4f669c27699fd7fb00e2910&sid=AWOy0kCXJ7anp%2B23&uin=1186530606&deviceid=e382612741627493&synckey=1_810441505%7C2_810441586%7C3_810441435%7C11_810440705%7C19_36191%7C23_1707395814%7C24_1707440754%7C25_810441586%7C27_2943%7C201_1707440754%7C206_101%7C1000_1707431416%7C1001_1707435061&_=1707395816346 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018786FAECE0>: Failed to resolve 'webpush.wx.qq.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 295, in maintain_loop
    i = sync_check(self)
  File "D:\Program\chatgpt-on-wechat\lib\itchat\components\login.py", line 360, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range

[INFO][2024-02-09 09:41:14][xunfei_spark_bot.py:58] - [XunFei] query=你好
[INFO][2024-02-09 09:50:37][xunfei_spark_bot.py:105] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '你好'}]
[ERROR][2024-02-09 09:50:37][xunfei_spark_bot.py:193] - [XunFei] error: [Errno 11002] getaddrinfo failed
[INFO][2024-02-09 09:51:12][xunfei_spark_bot.py:91] - [XunFei-API] response=, time=34.617164850234985s, usage={}
[INFO][2024-02-09 09:51:12][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=), receiver=@ecfe1c38229390ff3f60a58718de9d665b17e1581655f6a2c666e1a761b16ad6
[INFO][2024-02-09 09:55:03][xunfei_spark_bot.py:58] - [XunFei] query=你好吗
[INFO][2024-02-09 09:55:03][xunfei_spark_bot.py:105] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '你好吗'}]
[INFO][2024-02-09 09:55:03][xunfei_spark_bot.py:204] - [XunFei] Start websocket, session_id=@ecfe1c38229390ff3f60a58718de9d665b17e1581655f6a2c666e1a761b16ad6_170744370358
[INFO][2024-02-09 09:55:04][xunfei_spark_bot.py:91] - [XunFei-API] response=我很好，谢谢您的关心。请问有什么可以帮助您的吗？, time=1.1049604415893555s, usage={'text': {'question_tokens': 2, 'prompt_tokens': 3, 'completion_tokens': 13, 'total_tokens': 16}}
[INFO][2024-02-09 09:55:04][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=我很好，谢谢您的关心。请问有 什么可以帮助您的吗？), receiver=@ecfe1c38229390ff3f60a58718de9d665b17e1581655f6a2c666e1a761b16ad6

**Comment by 2022Cyberpunk** [comment]
我的登录微信成功开始自动回复，在群里触发时就会报循环这个错误，大佬你解决了吗？

**Comment by 6vision** [comment]
更新最新版本试试

**Comment by a-Dmears** [comment]
我docker部署的，最新版的镜像，一样有这个问题

**Comment by AreChen** [comment]
我是本地部署的python3.12，一样有这个问题,第二天开始出这个错误,设置了监听全部群聊

**Comment by AreChen** [comment]
解决了,urllib3和系统代理问题参考这篇[文章](https://blog.caomingjun.com/fixing-conflict-between-urllib3-and-proxy/)解决
