### ISSUE TITLE
channel切换为wechaty后，编译遇到问题，报错，提示'WechatyChannel' object has no attribute 'handler_pool'

### ISSUE THREAD

**Issue by SamYueHW** [zhayujie/chatgpt-on-wechat#1748]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 问题描述 😯

config.json里已经改为
"channel_type": "wxy",
”wechaty_puppet_service_token": "puppet_padlocal_d6。。。“

### 终端日志 📒

```log
[INFO][2024-02-14 23:18:09][role.py:69] - [Role] inited
[INFO][2024-02-14 23:18:09][dungeon.py:56] - [Dungeon] inited
[INFO][2024-02-14 23:18:09][hello.py:24] - [Hello] inited
[INFO][2024-02-14 23:18:09][finish.py:23] - [Finish] inited
[ERROR][2024-02-14 23:18:09][app.py:66] - App startup failed!
[ERROR][2024-02-14 23:18:09][app.py:67] - 'WechatyChannel' object has no attribute 'handler_pool'
Traceback (most recent call last):
  File "/Users/samuelyue/Desktop/Coding/cow/chatgpt-on-wechat/app.py", line 61, in run
    start_channel(channel_name)
  File "/Users/samuelyue/Desktop/Coding/cow/chatgpt-on-wechat/app.py", line 40, in start_channel
    channel.startup()
  File "/Users/samuelyue/Desktop/Coding/cow/chatgpt-on-wechat/channel/wechat/wechaty_channel.py", line 42, in startup
    asyncio.run(self.main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/samuelyue/Desktop/Coding/cow/chatgpt-on-wechat/channel/wechat/wechaty_channel.py", line 47, in main
    self.handler_pool._initializer = lambda: asyncio.set_event_loop(loop)
AttributeError: 'WechatyChannel' object has no attribute 'handler_pool'
```

**Comment by mashagua** [comment]
我也遇到了，解决了吗

**Comment by fireStarGXZ** [comment]
我也出现这个问题了
[ERROR][2024-02-29 21:48:31][app.py:66] - App startup failed!
[ERROR][2024-02-29 21:48:31][app.py:67] - 'WechatyChannel' object has no attribute 'handler_pool'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 61, in run
    start_channel(channel_name)
  File "/root/chatgpt-on-wechat/app.py", line 40, in start_channel
    channel.startup()
  File "/root/chatgpt-on-wechat/channel/wechat/wechaty_channel.py", line 42, in startup
    asyncio.run(self.main())
  File "/usr/lib64/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/chatgpt-on-wechat/channel/wechat/wechaty_channel.py", line 47, in main
    self.handler_pool._initializer = lambda: asyncio.set_event_loop(loop)
AttributeError: 'WechatyChannel' object has no attribute 'handler_pool'

**Comment by felixiao** [comment]
遇到同样问题，有人知道怎么解决嘛？还有wechaty的个微的token是要去买嘛？免费的只有7天时间

**Comment by mashagua** [comment]
> 遇到同样问题，有人知道怎么解决嘛？还有wechaty的个微的token是要去买嘛？免费的只有7天时间

对，是要去买，一个月200，一年的话打5折，这个就是不知道它对应的wechaty的版本是哪个，没有写在requirements.txt里，最新装的好像没有那个属性

**Comment by gattaca2017** [comment]
from channel.chat_channel import ChatChannel, handler_pool   # add 

class WechatyChannel(ChatChannel):
    NOT_SUPPORT_REPLYTYPE = []

    def __init__(self):
        super().__init__()
        self.handler_pool = handler_pool    # add this line

**Comment by kvgary** [comment]
@SamYueHW 问题解决了吗？

**Comment by PinkPanther-ny** [comment]
已解决，请看我的这个PR
https://github.com/zhayujie/chatgpt-on-wechat/pull/1884

**Comment by mashagua** [comment]
> self.handler_pool = handler_pool    # add this line

添加了之后原来的问题是没有了，但是出现了
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/wechaty/wechaty.py", line 445, in start
    await self.puppet.start()
  File "/root/miniconda3/lib/python3.10/site-packages/wechaty_puppet_service/puppet.py", line 911, in start
    self._init_puppet()
  File "/root/miniconda3/lib/python3.10/site-packages/wechaty_puppet_service/puppet.py", line 876, in _init_puppet
    raise WechatyPuppetGrpcError(
wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)

**Comment by lixizhenggmail** [comment]
> > self.handler_pool = handler_pool    # add this line
> 
> 添加了之后原来的问题是没有了，但是出现了 Traceback (most recent call last): File "/root/miniconda3/lib/python3.10/site-packages/wechaty/wechaty.py", line 445, in start await self.puppet.start() File "/root/miniconda3/lib/python3.10/site-packages/wechaty_puppet_service/puppet.py", line 911, in start self._init_puppet() File "/root/miniconda3/lib/python3.10/site-packages/wechaty_puppet_service/puppet.py", line 876, in _init_puppet raise WechatyPuppetGrpcError( wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)

是的，我的也出现了，不知道是不是wechaty的版本不对还是其它什么原因。

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
