### ISSUE TITLE
接入微信公众号时，公众号后台里的服务器配置已启用，但是出现48001，api unauthorized的报错

### ISSUE THREAD

**Issue by 7tinghua** [zhayujie/chatgpt-on-wechat#1757]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp_service(公众号, 服务号)

### 复现步骤 🕹

公众号后台里的服务器配置提交成功，也已经启动成功，服务器ip也加入了白名单，但是对话时会报错，api unauthorized，不知道怎么解决。
麻烦帮忙看下是怎么回事，感谢！

### 问题描述 😯

公众号后台里的服务器配置提交成功，也已经启动成功，服务器ip也加入了白名单，但是对话时会报错，api unauthorized，不知道怎么解决。
麻烦帮忙看下是怎么回事，感谢！

### 终端日志 📒

162.62.80.8:53923 - - [19/Feb/2024 17:09:50] "HTTP/1.1 GET /wx" - 200 OK
[INFO][2024-02-19 17:10:00][active_reply.py:44] - [wechatmp] 162.62.81.123:20410 Receive post query ovoP86StRqgrw8PFM3QTl7dffp9E 24457868635345587: hi
162.62.81.123:20410 - - [19/Feb/2024 17:10:00] "HTTP/1.1 POST /wx" - 200 OK
[INFO][2024-02-19 17:10:00][chat_gpt_bot.py:49] - [CHATGPT] query=hi
[ERROR][2024-02-19 17:10:01][chat_channel.py:287] - [WX] sendMsg error: Error code: 48001, message: api unauthorized rid: 65d38b69-62497c5f-7e6c18da
[ERROR][2024-02-19 17:10:01][chat_channel.py:290] - Error code: 48001, message: api unauthorized rid: 65d38b69-62497c5f-7e6c18da
Traceback (most recent call last):
  File "/home/ubuntu/wxOA/channel/chat_channel.py", line 285, in _send
    self.send(reply, context)
  File "/home/ubuntu/wxOA/channel/wechatmp/wechatmp_channel.py", line 150, in send
    self.client.message.send_text(receiver, text)
  File "/usr/local/lib/python3.10/dist-packages/wechatpy/client/api/message.py", line 51, in send_text
    return self._send_custom_message(data, account=account)
  File "/usr/local/lib/python3.10/dist-packages/wechatpy/client/api/message.py", line 21, in _send_custom_message
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/wechatpy/client/api/base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wechatpy/client/base.py", line 182, in post
    return self._request(
  File "/home/ubuntu/wxOA/channel/wechatmp/wechatmp_client.py", line 37, in _request
    return super()._request(method, url_or_endpoint, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/lib/python3.10/dist-packages/wechatpy/client/base.py", line 158, in _handle_result
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: 48001, message: api unauthorized rid: 65d38b69-62497c5f-7e6c18da

**Comment by jack120233** [comment]
我的也是，48001,为什么会这样呢，我使用微信测试号，就没有问题。使用自己的公众号就会提示这个模块没有权限调用。

**Comment by Lxhnnn** [comment]
怎么弄好的呢
