### ISSUE TITLE
私聊不行，群聊正常

### ISSUE THREAD

**Issue by jachin113** [zhayujie/chatgpt-on-wechat#1800]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

用的试casaos系统，然后去安装，私聊不行，群聊可以，[''],[""],[ai],["ai"]都尝试了，都是报错，

### 问题描述 😯

![微信图片_20240308101552](https://github.com/zhayujie/chatgpt-on-wechat/assets/132930541/fb543ee9-2fb3-4086-86cc-c767c9dc1943)

### 终端日志 📒

chatgpt-on-wechat  | [INFO][2024-03-08 02:03:03][chat_gpt_bot.py:49] - [CHATGPT] query=/help
chatgpt-on-wechat  | [WARNING][2024-03-08 02:03:03][session_manager.py:72] - Exception when counting tokens precisely for prompt: '>' not supported between instances of 'int' and 'str'
chatgpt-on-wechat  | [WARNING][2024-03-08 02:03:06][session_manager.py:83] - Exception when counting tokens precisely for session: '>' not supported between instances of 'int' and 'str'
chatgpt-on-wechat  | [ERROR][2024-03-08 02:03:06][chat_channel.py:301] - Worker return exception: can only concatenate list (not "str") to list
chatgpt-on-wechat  | Traceback (most recent call last):
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
chatgpt-on-wechat  |     result = self.fn(*self.args, **self.kwargs)
chatgpt-on-wechat  |   File "/app/channel/chat_channel.py", line 174, in _handle
chatgpt-on-wechat  |     reply = self._decorate_reply(context, reply)
chatgpt-on-wechat  |   File "/app/channel/chat_channel.py", line 259, in _decorate_reply
chatgpt-on-wechat  |     reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")
chatgpt-on-wechat  | TypeError: can only concatenate list (not "str") to list

**Comment by jachin113** [comment]
之前的是用['']的日志，这个是用["ai"]前缀的错误日志：
chatgpt-on-wechat  | [INFO][2024-03-08 02:48:24][chat_gpt_bot.py:49] - [CHATGPT] query=你好
chatgpt-on-wechat  | [WARNING][2024-03-08 02:48:28][session_manager.py:72] - Exception when counting tokens precisely for prompt: '>' not supported between instances of 'int' and 'str'
chatgpt-on-wechat  | [WARNING][2024-03-08 02:48:32][session_manager.py:83] - Exception when counting tokens precisely for session: '>' not supported between instances of 'int' and 'str'
chatgpt-on-wechat  | [ERROR][2024-03-08 02:48:32][chat_channel.py:301] - Worker return exception: can only concatenate list (not "str") to list
chatgpt-on-wechat  | Traceback (most recent call last):
chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
chatgpt-on-wechat  |     result = self.fn(*self.args, **self.kwargs)
chatgpt-on-wechat  |   File "/app/channel/chat_channel.py", line 174, in _handle
chatgpt-on-wechat  |     reply = self._decorate_reply(context, reply)
chatgpt-on-wechat  |   File "/app/channel/chat_channel.py", line 259, in _decorate_reply
chatgpt-on-wechat  |     reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")
chatgpt-on-wechat  | TypeError: can only concatenate list (not "str") to list

**Comment by Zhaoyi-Yan** [comment]
"single_chat_reply_prefix": "xxx "， xxx放你想要的前缀。

**Comment by wh0am111** [comment]
> "single_chat_reply_prefix": "xxx "， xxx放你想要的前缀。

qwen ，如此配置，群聊机器人可以，单聊机器人还是不行

**Comment by wh0am111** [comment]
> "single_chat_reply_prefix": "xxx "， xxx放你想要的前缀。

 "channel_type": "wx",
  "model": "qwen",
  "open_ai_api_key": "YOUR API KEY",
  "text_to_image": "dall-e-2",
  "voice_to_text": "openai",
  "text_to_voice": "openai",
  "proxy": "",
  "hot_reload": false,
  "single_chat_prefix": ["小全"],
  "single_chat_reply_prefix": "[bot] ",
  "group_chat_prefix": [
    "@bot", "bot", "小全", "小芯"
  ],

  "group_at_off": true,
  "group_name_white_list": [
    "xxx",
    "xxx",
    "xxx"
  ],

**Comment by shoot82003** [comment]
{
  "channel_type": "wx",
"model": "gemini",
"gemini_api_key":"XX-XX",
  "text_to_image": "dall-e-2",
  "proxy": "",
  "hot_reload": false,
  "single_chat_prefix": [""],
  "single_chat_reply_prefix": "[bot] ",
  "group_chat_prefix": ["@bot"],
  "group_chat_keyword": ["什么"
,"怎么"
,"你说"
,"知道"
,"啥事"
,"何时"
,"哪里"
,"如何"
,"是否"
,"是不是"
,"多少"
,"有没有"],
  "group_name_white_list": ["ALL_GROUP"],
  "image_create_prefix": ["画画画"],
  "speech_recognition": false,
  "group_speech_recognition": false,
  "voice_reply_voice": false,
  "conversation_max_tokens": 2500,
  "expires_in_seconds": 3600,
  "temperature": 0.7,
  "character_desc": "你是gemini。",
  "subscribe_msg": "感谢您的关注！"
}
我的是反过来,私聊可以,群聊不触发.
日志有内容:
[Gemini] query=***内容***
[Gemini] reply=***好的，感谢您的回复***。

**Comment by 6vision** [comment]
> { "channel_type": "wx", "model": "gemini", "gemini_api_key":"XX-XX", "text_to_image": "dall-e-2", "proxy": "", "hot_reload": false, "single_chat_prefix": [""], "single_chat_reply_prefix": "[bot] ", "group_chat_prefix": ["@bot"], "group_chat_keyword": ["什么" ,"怎么" ,"你说" ,"知道" ,"啥事" ,"何时" ,"哪里" ,"如何" ,"是否" ,"是不是" ,"多少" ,"有没有"], "group_name_white_list": ["ALL_GROUP"], "image_create_prefix": ["画画画"], "speech_recognition": false, "group_speech_recognition": false, "voice_reply_voice": false, "conversation_max_tokens": 2500, "expires_in_seconds": 3600, "temperature": 0.7, "character_desc": "你是gemini。", "subscribe_msg": "感谢您的关注！" } 我的是反过来,私聊可以,群聊不触发. 日志有内容: [Gemini] query=_**内容**_ [Gemini] reply=_**好的，感谢您的回复**_。

可以贴一下详细log，和说明

**Comment by 6vision** [comment]
> "single_chat_reply_suffix", ""

"single_chat_reply_suffix", ""  这里是字符串，不要写成[""]哈
