### ISSUE TITLE
使用讯飞星火，个人聊天，不管发什么内容，响应只有 [bot] 是什么原因呢

### ISSUE THREAD

**Issue by sweetWayBoy** [zhayujie/chatgpt-on-wechat#1807]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

使用讯飞星火，个人聊天，不管发什么内容，响应只有 [bot] 是什么原因呢

### 终端日志 📒

```log
<此处粘贴终端日志>
```
[INFO][2024-03-11 16:47:05][xunfei_spark_bot.py:91] - [XunFei-API] response=, time=31.189411878585815s, usage={}
[INFO][2024-03-11 16:47:06][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=[bot] ), receiver=@62b7259c602a47ccd68b43af01c45b4c8720bdcbba3f722c2a65674f942ad6b2
[INFO][2024-03-11 16:48:29][xunfei_spark_bot.py:58] - [XunFei] query=李白是哪里人
[INFO][2024-03-11 16:48:29][xunfei_spark_bot.py:105] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '你好哇'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '李白是哪里人'}]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/hanyh/个人/learn/AIGC/chatgpt-on-wechat/bot/xunfei/xunfei_spark_bot.py", line 107, in create_web_socket
    wsUrl = self.create_url()
  File "/Users/hanyh/个人/learn/AIGC/chatgpt-on-wechat/bot/xunfei/xunfei_spark_bot.py", line 138, in create_url
    signature_sha = hmac.new(self.api_secret.encode('utf-8'),
AttributeError: 'NoneType' object has no attribute 'encode'
[INFO][2024-03-11 16:49:00][xunfei_spark_bot.py:91] - [XunFei-API] response=, time=31.180160999298096s, usage={}
[INFO][2024-03-11 16:49:01][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=[bot] ), receiver=@62b7259c602a47ccd68b43af01c45b4c8720bdcbba3f722c2a65674f942ad6b2
[INFO][2024-03-11 16:52:05][xunfei_spark_bot.py:58] - [XunFei] query=你好
[INFO][2024-03-11 16:52:05][xunfei_spark_bot.py:105] - [XunFei] start connect, prompt=[{'role': 'user', 'content': '你好哇'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '李白是哪里人'}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '你好'}]
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/hanyh/个人/learn/AIGC/chatgpt-on-wechat/bot/xunfei/xunfei_spark_bot.py", line 107, in create_web_socket
    wsUrl = self.create_url()
  File "/Users/hanyh/个人/learn/AIGC/chatgpt-on-wechat/bot/xunfei/xunfei_spark_bot.py", line 138, in create_url
    signature_sha = hmac.new(self.api_secret.encode('utf-8'),
AttributeError: 'NoneType' object has no attribute 'encode'
[INFO][2024-03-11 16:52:37][xunfei_spark_bot.py:91] - [XunFei-API] response=, time=31.201261043548584s, usage={}
[INFO][2024-03-11 16:52:38][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=[bot] ), receiver=@62b7259c602a47ccd68b43af01c45b4c8720bdcbba3f722c2a65674f942ad6b2

**Comment by 281049519** [comment]
我也出现同样的报错问题。

**Comment by sweetWayBoy** [comment]
已解决。星火的配置问题，json 文件配置的键名称不对
