### ISSUE TITLE
如何使用训练好的fine-tuned gpt3.5models

### ISSUE THREAD

**Issue by O1ive2** [zhayujie/chatgpt-on-wechat#1808]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 问题描述 😯

{
  "channel_type": "wx",
  "model": "ft:gpt-3.5-turbo-0125:oliver::91clwH84",
  配置文件中我使用自己训练的模型，无法成功回复

### 终端日志 📒

```log
<[ERROR][2024-03-12 00:30:01][chat_channel.py:301] - Worker return exception: No module named 'openai.error'
Traceback (most recent call last):
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt-on-wechat\channel\chat_channel.py", line 170, in _handle
    reply = self._generate_reply(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt-on-wechat\channel\chat_channel.py", line 180, in _generate_reply
    e_context = PluginManager().emit_event(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt-on-wechat\plugins\plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\project\chatgpt-on-wechat\plugins\role\role.py", line 104, in on_handle_context
    bot = Bridge().get_bot("chat")
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt-on-wechat\bridge\bridge.py", line 57, in get_bot
    self.bots[typename] = create_bot(self.btype[typename])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt-on-wechat\bot\bot_factory.py", line 22, in create_bot
    from bot.chatgpt.chat_gpt_bot import ChatGPTBot
  File "D:\project\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 6, in <module>
    import openai.error
ModuleNotFoundError: No module named 'openai.error'
[INFO][2024-03-12 00:30:27][bridge.py:51] - create bot chatGPT for chat
[ERROR][2024-03-12 00:30:27][chat_channel.py:301] - Worker return exception: No module named 'openai.error'
Traceback (most recent call last):
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt-on-wechat\channel\chat_channel.py", line 170, in _handle
    reply = self._generate_reply(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt-on-wechat\channel\chat_channel.py", line 180, in _generate_reply
    e_context = PluginManager().emit_event(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt-on-wechat\plugins\plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\project\chatgpt-on-wechat\plugins\role\role.py", line 104, in on_handle_context
    bot = Bridge().get_bot("chat")
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt-on-wechat\bridge\bridge.py", line 57, in get_bot
    self.bots[typename] = create_bot(self.btype[typename])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt-on-wechat\bot\bot_factory.py", line 22, in create_bot
    from bot.chatgpt.chat_gpt_bot import ChatGPTBot
  File "D:\project\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 6, in <module>
    import openai.error
ModuleNotFoundError: No module named 'openai.error'>
```

**Comment by 6vision** [comment]
报错应该是openai版本问题，可以安装依赖文件写的版本
