### ISSUE TITLE
使用ali语音的时候，后台报错

### ISSUE THREAD

**Issue by cype62** [zhayujie/chatgpt-on-wechat#1825]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

切换ali语音的时候，就有这个错误。

### 问题描述 😯

<img width="715" alt="image" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/37395207/47c6e5c8-c084-4408-b4d6-632fbaf523b7">

使用百度语音没有问题，但切换ali的时候，就有这个错误。

### 终端日志 📒

```log
[DEBUG][2024-03-20 09:16:52][wechat_channel.py:174] - [WX]receive voice msg: tmp/240320-091652.mp3
[DEBUG][2024-03-20 09:16:52][chat_channel.py:343] - [WX] consume context: Context(type=VOICE, content=tmp/240320-091652.mp3, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x7f7debea3550>, 'origin_ctype': <ContextType.VOICE: 2>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@8b1570894310d77bad871d103327ccb1', 'receiver': '@8b1570894310d77bad871d103327ccb1', 'desire_rtype': <ReplyType.VOICE: 2>})
[DEBUG][2024-03-20 09:16:52][chat_channel.py:168] - [WX] ready to handle context: Context(type=VOICE, content=tmp/240320-091652.mp3, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x7f7debea3550>, 'origin_ctype': <ContextType.VOICE: 2>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@8b1570894310d77bad871d103327ccb1', 'receiver': '@8b1570894310d77bad871d103327ccb1', 'desire_rtype': <ReplyType.VOICE: 2>})
[DEBUG][2024-03-20 09:16:52][plugin_manager.py:187] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-20 09:16:52][plugin_manager.py:187] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-20 09:16:52][plugin_manager.py:187] - Plugin BANWORDS triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-20 09:16:52][plugin_manager.py:187] - Plugin SUM4ALL triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-20 09:16:52][plugin_manager.py:187] - Plugin MIDJOURNEY_TURBO triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-20 09:16:52][plugin_manager.py:187] - Plugin ROLE triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-20 09:16:52][plugin_manager.py:187] - Plugin DUNGEON triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-20 09:16:52][plugin_manager.py:187] - Plugin HELLO triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-20 09:16:52][plugin_manager.py:187] - Plugin FINISH triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-20 09:16:52][chat_channel.py:188] - [WX] ready to handle context: type=VOICE, content=tmp/240320-091652.mp3
[ERROR][2024-03-20 09:16:52][chat_channel.py:301] - Worker return exception: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/channel/chat_channel.py", line 170, in _handle
    reply = self._generate_reply(context)
  File "/app/channel/chat_channel.py", line 203, in _generate_reply
    reply = super().build_voice_to_text(wav_path)
  File "/app/channel/channel.py", line 41, in build_voice_to_text
    return Bridge().fetch_voice_to_text(voice_file)
  File "/app/bridge/bridge.py", line 71, in fetch_voice_to_text
    return self.get_bot("voice_to_text").voiceToText(voiceFile)
  File "/app/voice/voice.py", line 11, in voiceToText
    raise NotImplementedError
NotImplementedError
```

**Comment by azz212** [comment]
ITchat没实现吧？

**Comment by 6vision** [comment]
ali语音转文字可以试试这个 #2154
