### ISSUE TITLE
扫码了无法登陆报错

### ISSUE THREAD

**Issue by 125540947** [zhayujie/chatgpt-on-wechat#183]
### 问题描述
扫码了无法登陆

> 简要说明、截图、复现步骤等，也可以是需求或想法
本地服务器，无代理

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-02-12 11:40:03][app.py:19] - App startup failed!
[ERROR][2023-02-12 11:40:03][app.py:20] - list index out of range
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/chatgpt-on-wechat/app.py", line 17, in <module>
    channel.startup()
  File "/root/chatgpt-on-wechat/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/root/miniconda3/lib/python3.10/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/root/miniconda3/lib/python3.10/site-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/root/miniconda3/lib/python3.10/site-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/root/miniconda3/lib/python3.10/site-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range
^C



### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V`pip 22.3.1 from /root/miniconda3/lib/python3.10/site-packages/pip (python 3.10 )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
是不是微信没实名

**Comment by superyzh** [comment]
我有相同的问题，今天更新本地代码后，报上面的错误，微信已经实名认证过了。

**Comment by HernandoR** [comment]
抓到问题, 需要开通微信支付才能用

**Comment by sdsxzhang** [comment]
已经实名且微信支付也开了，，

**Comment by zhayujie** [comment]
see #63
