### ISSUE TITLE
运行代码后直接报错

### ISSUE THREAD

**Issue by Tofu-killer** [zhayujie/chatgpt-on-wechat#1833]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 问题描述 😯

![微信图片_20240325004715](https://github.com/zhayujie/chatgpt-on-wechat/assets/118033755/6ced14ae-40b3-492e-8cc3-292326e4192e)

### 终端日志 📒

```log
<此处粘贴终端日志>
```root@vmi1704850:~/chatgpt-on-wechat# nohup python3 app.py & tail -f nohup.out
[1] 1840983
    load_config()
  File "/root/chatgpt-on-wechat/config.py", line 232, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 7 column 3 (char 184)
nohup: ignoring input and appending output to 'nohup.out'
[ERROR][2024-03-24 17:44:34][app.py:66] - App startup failed!
[ERROR][2024-03-24 17:44:34][app.py:67] - Expecting ',' delimiter: line 7 column 3 (char 184)
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 46, in run
    load_config()
  File "/root/chatgpt-on-wechat/config.py", line 232, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 7 column 3 (char 184)

**Comment by 991547436** [comment]
目测你配置文件json格式错误，建议使用json格式化工具检测下

**Comment by Tofu-killer** [comment]
前面的问题解决了
![微信图片_20240325183112](https://github.com/zhayujie/chatgpt-on-wechat/assets/118033755/05b40f8c-b633-4b38-94f7-9c4da7bbf4d7)
！但是遇到了新的问题，我接入了gemini，然后无法回复信息

**Comment by 6vision** [comment]
Gemini对IP要求比较严格，需要使用服务支持地区的服务器或者代理
