### ISSUE TITLE
支持Ollama部署的大模型服务

### ISSUE THREAD

**Issue by kaina404** [zhayujie/chatgpt-on-wechat#1845]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

Ollama本地服务目前支持了Qwen、Gemma、Mistral、Codellama等多种大模型，可参考[Ollama支持的模型](https://ollama.com/library)

这里我在现有的项目中做了如下更改以支持Ollama服务本地部署在本地的所有大模型。

## Step1:

const.py文件中增加配置：``OLLAMA = "ollama"``

```python
MODEL_LIST = [... , OLLAMA]
```

## Step2:

创建 /bot/ollama/ollama_bot.py

```python
from bot.bot import Bot
from bot.session_manager import SessionManager
from bridge.context import ContextType, Context
from bridge.reply import Reply, ReplyType
from common.log import logger
from config import conf
from bot.baidu.baidu_wenxin_session import BaiduWenxinSession
import ollama


# Ollama对话模型API (可用)
class OllamaBot(Bot):

    def __init__(self):
        super().__init__()
        self.model = conf().get("model") or "gemma:7b"
        # 复用文心的token计算方式
        self.sessions = SessionManager(BaiduWenxinSession, model=conf().get("model") or "gemma:7b")

    def reply(self, query, context: Context = None) -> Reply:
        try:
            if context.type != ContextType.TEXT:
                logger.warn(f"[Ollama] Unsupported message type, type={context.type}")
                return Reply(ReplyType.TEXT, None)
            logger.info(f"[Ollama] query={query}")
            session_id = context["session_id"]
            session = self.sessions.session_query(query, session_id)
            # 这里直接调用本地的Ollama服务
            response = ollama.chat(
                model=self.model,
                messages=self.filter_messages(session.messages))
            reply_text = response['message']['content']
            self.sessions.session_reply(reply_text, session_id)
            logger.info(f"[Ollama] reply={reply_text}")
            return Reply(ReplyType.TEXT, reply_text)
        except Exception as e:
            logger.error("[Ollama] fetch reply error, may contain unsafe content")
            logger.error(e)
            return Reply(ReplyType.ERROR, "invoke [Ollama] api failed!")

    def _convert_to_gemini_messages(self, messages: list):
        res = []
        for msg in messages:
            if msg.get("role") == "user":
                role = "user"
            elif msg.get("role") == "assistant":
                role = "model"
            else:
                continue
            res.append({
                "role": role,
                "parts": [{"text": msg.get("content")}]
            })
        return res

    @staticmethod
    def filter_messages(messages: list):
        res = []
        turn = "user"
        if not messages:
            return res
        for i in range(len(messages) - 1, -1, -1):
            message = messages[i]
            if message.get("role") != turn:
                continue
            res.insert(0, message)
            if turn == "user":
                turn = "assistant"
            elif turn == "assistant":
                turn = "user"
        return res

```

## Step3:

修改[bot_factory.py](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/bot/bot_factory.py)处理如下

```python
def create_bot(bot_type):
    
    elif bot_type == const.OLLAMA:
        from bot.ollama.ollama_bot import OllamaBot
        return OllamaBot()

    raise RuntimeError
```

## Step4:

requirements.txt增加ollama

## Step5:

修改bridge.py

```python
self.btype = {
  #....修改"chat": const.CHATGPT为下面.....
            "chat": conf().get("bot_type", const.CHATGPT)
  ...
}
```

## Step6:

[config.py](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/config.py)文件中的``available_setting``增加配置:``"bot_type":"ollama",``修改``"model": "gemma:7b "``

> Ollama支持的所有模型，执行命令： ollama list，然后将你想要用的NAME复制到model中，例如这里的NAME为gemma:7b 。

### 举例

ollama list
<img width="240" alt="截屏2024-03-27 10 23 52" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/13998159/5a54dd6d-c101-4da9-8eab-b6b1a6d14ef4">
涉及修改的文件：

<img width="310" alt="截屏2024-03-27 10 24 39" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/13998159/89ccabe5-f568-4efa-b6c1-b80e06ad0433">

### 动机

Ollama支持将大部分模型能在本地快速部署或者服务端部署并运行，通过对Ollama的支持，能够减少对ChatGPT的依赖。能够将这个项目的底层大模型支持范围拓展的更广阔。

**Comment by taozhiyuai** [comment]
针对STEP6, 建议改成不需要修改MODEL,就用默认的gpt3.5 turbo. LM STUDIO做服务器时, COW只需要修改API和BASE,可以工作. 每次换模型还需要改MODEL,太麻烦了. @kaina404

**Comment by taozhiyuai** [comment]
STEP 1 除了你写的, # bot_type下面不需要加 OLLAMA="ollama"吗? @kaina404

**Comment by taozhiyuai** [comment]
我这边启动显示错误

Traceback (most recent call last):
  File "/Users/taozhiyu/Downloads/chatgpt-on-wechat/app.py", line 8, in <module>
    from channel import channel_factory
  File "/Users/taozhiyu/Downloads/chatgpt-on-wechat/channel/channel_factory.py", line 4, in <module>
    from common import const
  File "/Users/taozhiyu/Downloads/chatgpt-on-wechat/common/const.py", line 27, in <module>
    "gpt-4-turbo-preview", "gpt-4-1106-preview", GPT4_TURBO_PREVIEW, QWEN, GEMINI, ZHIPU_AI, MOONSHOT, OLLAMA]
                                                                                                       ^^^^^^
NameError: name 'OLLAMA' is not defined


我修改的const.py如下

# bot_type
OPEN_AI = "openAI"
CHATGPT = "chatGPT"
BAIDU = "baidu"
XUNFEI = "xunfei"
CHATGPTONAZURE = "chatGPTOnAzure"
LINKAI = "linkai"
CLAUDEAI = "claude"
CLAUDEAPI= "claudeAPI"
QWEN = "qwen"
GEMINI = "gemini"
ZHIPU_AI = "glm-4"
MOONSHOT = "moonshot"


# model
CLAUDE3 = "claude-3-opus-20240229"
GPT35 = "gpt-3.5-turbo"
GPT4 = "gpt-4"
GPT4_TURBO_PREVIEW = "gpt-4-0125-preview"
GPT4_VISION_PREVIEW = "gpt-4-vision-preview"
WHISPER_1 = "whisper-1"
TTS_1 = "tts-1"
TTS_1_HD = "tts-1-hd"

MODEL_LIST = ["gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-4", "wenxin", "wenxin-4", "xunfei", "claude","claude-3-opus-20240229", "gpt-4-turbo",
              "gpt-4-turbo-preview", "gpt-4-1106-preview", GPT4_TURBO_PREVIEW, QWEN, GEMINI, ZHIPU_AI, MOONSHOT, OLLAMA]

# channel
FEISHU = "feishu"
DINGTALK = "dingtalk"

**Comment by taozhiyuai** [comment]
STEP 5少了逗号

**Comment by taozhiyuai** [comment]
我这边解决上面问题后运行成功. 建议吧STEP 6的model 解决下. 最好和lm studio一样, 忽略model, 否则每次换模型都改,太麻烦了.

成功运行截图
<img width="586" alt="截屏2024-03-27 10 57 33" src="https://github.com/zhayujie/chatgpt-on-wechat/assets/146583103/9de43e78-2a86-446d-a402-805903589e67">

**Comment by taozhiyuai** [comment]
STEP 6 我没有在config.py里修改model, 只是在config.json里面按你说的修改了model. 运行成功. 还是如上说的,是否能像LM STUDIO, 用默认的模型设置

**Comment by taozhiyuai** [comment]
@zhayujie 建议合并代码,这样太好了.谢谢 @kaina404

**Comment by taozhiyuai** [comment]
> > STEP 6 我没有在config.py里修改model, 只是在config.json里面按你说的修改了model. 运行成功. 还是如上说的,是否能像LM STUDIO, 用默认的模型设置
> > 这里的config.json需要增加 `  "bot_type": "ollama",   "model": "qwen:7b",`
> 
> <img alt="截屏2024-03-27 11 06 19" width="596" src="https://private-user-images.githubusercontent.com/13998159/317110168-7479c52f-dae1-485e-9c5c-7522a4296e0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDkxNTgsIm5iZiI6MTcxMTUwODg1OCwicGF0aCI6Ii8xMzk5ODE1OS8zMTcxMTAxNjgtNzQ3OWM1MmYtZGFlMS00ODVlLTljNWMtNzUyMmE0Mjk2ZTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMDczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNTFlN2JlNGQ5ZWFlZDJkNGYyYTQwOWI4ZmZkNTQwYTAxYWViNTM1NWM4ZDY2ZGU4OTlmM2FhODc0NjhiNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EsooNJT03raEQmAS1UmWT4NwE5eGXHcsvdzjeGe2Qjc">

![WX20240327-110858@2x](https://github.com/zhayujie/chatgpt-on-wechat/assets/146583103/44bd34e1-8e97-4215-9d18-184609cafca8)
![WX20240327-111047@2x](https://github.com/zhayujie/chatgpt-on-wechat/assets/146583103/73279b98-2595-4797-9576-4d5aec19ea0e)
我没有在config.py里面改model, 如图改的,运行成功

**Comment by taozhiyuai** [comment]
> > 针对STEP6, 建议改成不需要修改MODEL,就用默认的gpt3.5 turbo. LM STUDIO做服务器时, COW只需要修改API和BASE,可以工作. 每次换模型还需要改MODEL,太麻烦了. @kaina404
> 
> 这里是为了将默认的chat模型切换到ollama部署支持的模型，当然你可以直接修改bot_type为之前的chat模型也是可以的。当你修改了bot_type然后，就可以修改model对应的值，这样就可以直接切换ollama支持的其他模型了，例如：Gemma、qwen、llava、mistral等等

好复杂. 我用 lm studio + cow, 只需要修改config.json的api key 和api base,不需要改 model. 你看ollama + cow是否也可以这样.

**Comment by taozhiyuai** [comment]
> @taozhiyuai 这是我本地的修改。

能否实现像LM STUDIO一样,不用修改MODEL呢?

**Comment by taozhiyuai** [comment]
@kaina404 还遇到个问题.因为我是COW ,OLLAMA本机MAC环境部署. 我盒盖休息时,COW就断了.再也不能恢复.但是openwebui就可以直接回应消息. 能否解决这个问题呢?

**Comment by taozhiyuai** [comment]
> > @taozhiyuai 这是我本地的修改。
> 
> 能否实现像LM STUDIO一样,不用修改MODEL呢?

这个能解决吗?

**Comment by taozhiyuai** [comment]
行吧.够好了.谢谢.希望还有其他开发者能进一步完善

**Comment by maomingxing** [comment]
大佬，用api接口对接可以吗？http://localhost:11434
怎么做呢？

**Comment by jinghunsanzu** [comment]
新版本的ollama的API变了，变成了http://localhost:11434/api/chat，我这边照着API填写进去，发送文字没回应，大佬有解决么

**Comment by jinghunsanzu** [comment]
有反应了，但是提示
[ERROR]
invoke [Ollama] api failed!

**Comment by taozhiyuai** [comment]
> > 有反应了，但是提示 [ERROR] invoke [Ollama] api failed!
> @jinghunsanzu 
> 
> https://github.com/kaina404/chatgpt-on-wechat/tree/feature/ollama_support

快让cow合并这个代码吧

**Comment by taozhiyuai** [comment]
@zhayujie @6vision 麻烦尽快合并这个代码.实际使用没有问题.

**Comment by gentte6666** [comment]
请问使用ollama 本地大语言模型, 是否支持运行插件,我直接修改api base 和chatgpt api key, 可以对话,但是无法调用插件

**Comment by MoYingJiang** [comment]
试了，总是失败，我是docker的ollama，端口给的5XXX

**Comment by s441014112** [comment]
谢谢，接了一下千问2.5也成功了

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
