### ISSUE TITLE
刷新太快了，进不去，抢手速进去然后直接报错

### ISSUE THREAD

**Issue by Rhran6** [zhayujie/chatgpt-on-wechat#187]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-02-12 20:36:08][app.py:19] - App startup failed!
[ERROR][2023-02-12 20:36:08][app.py:20] - 'wxsid'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat-master\app.py", line 17, in <module>
    channel.startup()
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\itchat\components\login.py", line 55, in login
    status = self.check_login()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\itchat\components\login.py", line 141, in check_login
    if process_login_info(self, r.text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\itchat\components\login.py", line 183, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
                                                                     ~~~~~~~^^^^^^^^^
KeyError: 'wxsid'
输入任意键结束

> 简要说明、截图、复现步骤等，也可以是需求或想法




### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```



### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
1.抢手速看一下 #8 
2.wxsid的问题 看一下  https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs#4%E7%99%BB%E5%BD%95%E6%8A%A5%E9%94%99-keyerrorwxsid
