### ISSUE TITLE
WIKI处配置文件错误

### ISSUE THREAD

**Issue by ReddotCleaner** [zhayujie/chatgpt-on-wechat#191]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

```
# config.json文件内容示例
{ 
  "open_ai_api_key": "YOUR API KEY"                           # 填入上面创建的 OpenAI API KEY
  "single_chat_prefix": ["bot", "@bot"],                      # 私聊时文本需要包含该前缀才能触发机器人回复
```

配置模板里的格式是正确的，但是WIKI里的KEY后面是不是缺失了一个逗号？
最近见到很多算是小白遇到了这个问题，也算是把一部分人挡在门槛外了。

终端日志 (如有报错)
配置文件错误会导致以下错误
```
[ERROR][2023-02-13 09:46:39][app.py:19] - App startup failed!
[ERROR][2023-02-13 09:46:39][app.py:20] - Expecting ',' delimiter: line 3 column 3 (char 79)
Traceback (most recent call last):
  File "/chatgpt-on-wechat/./app.py", line 11, in <module>
    config.load_config()
  File "/chatgpt-on-wechat/config.py", line 18, in load_config
    config = json.loads(config_str)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 3 (char 79)
```

**Comment by zhayujie** [comment]
已更正，多谢
