### ISSUE TITLE
讯飞调用问题

### ISSUE THREAD

**Issue by Ansel123** [zhayujie/chatgpt-on-wechat#1913]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

讯飞星火无法调用，依赖都已安装

### 问题描述 😯

讯飞星火无法调用，依赖都已安装

### 终端日志 📒

```log
Start auto replying.
[INFO][2024-04-23 11:47:22][bridge.py:56] - create bot xunfei for chat
[ERROR][2024-04-23 11:47:22][chat_channel.py:303] - Worker return exception: No module named 'websocket'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\GPT_Wechat\env\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrator\Desktop\GPT_Wechat\channel\chat_channel.py", line 170, in _handle
    reply = self._generate_reply(context)
  File "C:\Users\Administrator\Desktop\GPT_Wechat\channel\chat_channel.py", line 193, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "C:\Users\Administrator\Desktop\GPT_Wechat\channel\channel.py", line 38, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "C:\Users\Administrator\Desktop\GPT_Wechat\bridge\bridge.py", line 71, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "C:\Users\Administrator\Desktop\GPT_Wechat\bridge\bridge.py", line 62, in get_bot
    self.bots[typename] = create_bot(self.btype[typename])
  File "C:\Users\Administrator\Desktop\GPT_Wechat\bot\bot_factory.py", line 37, in create_bot
    from bot.xunfei.xunfei_spark_bot import XunFeiBot
  File "C:\Users\Administrator\Desktop\GPT_Wechat\bot\xunfei\xunfei_spark_bot.py", line 25, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'
```

**Comment by Tzlibai** [comment]
这个错误表明你的Python环境中缺少名为websocket的模块。这通常发生在尝试使用某些需要websocket库的并发或网络应用程序时。

解决方法：

你需要安装websocket模块。如果你使用的是pip包管理器，可以通过以下命令来安装：

pip install websocket-client
如果你正在使用特定版本的Python，或者在使用虚拟环境，确保你在正确的环境中执行这个命令。安装完成后，重新运行你的程序，问题应该会被解决。如果你已经安装了websocket模块，但是仍然遇到这个错误，可能是因为你的Python解释器没有找到这个模块。这种情况下，检查你的环境变量，确保Python的路径设置正确，或者在你的应用程序中指定正确的Python解释器路径。
