### ISSUE TITLE
为什么识别不到消息 

### ISSUE THREAD

**Issue by javencpdd** [zhayujie/chatgpt-on-wechat#1951]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/90599089/ca0411f8-ac9e-4c6a-bb2f-ae5ee2d9c5cc)
在配置完后，run了app.py后，爆出这两个warn，
在私聊的时候，发消息，一直没有识别到
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/90599089/756a24ee-7908-478a-a11c-d0cee213d2fa)

### 问题描述 😯

问题，已放在复现步骤里了

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by javencpdd** [comment]
![879f66437a8b0ca2ca3010475006924d](https://github.com/zhayujie/chatgpt-on-wechat/assets/90599089/39e4a22a-ce2b-4297-95ad-d9521f8c1e0b)
发现发重复了图片

**Comment by javencpdd** [comment]
弹出日志 
`tart auto replying.
[WARNING][2024-05-09 17:46:15][wechat_message.py:92] - [WX]get other_user_id failed: 'UserName'
[WARNING][2024-05-09 17:46:15][chat_channel.py:231] - [WX] unknown context type: ACCEPT_FRIEND
Traceback (most recent call last):
  File "C:\Users\19046\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19046\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\19046\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "C:\Program Files\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\http\client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\19046\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\19046\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\19046\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=APBj6W7OAdj4xWou&skey=@crypt_b80a20f7_49657de9785e94794530a75ea2841dfb&pass_ticket=1XnkOOKHUdg4DxJUSjW3xdnPuy5OU7bdd4VtKChbAioFf4%2BowHaJJn%2FYrlbCtMid0dCBLSte2H4nDJ61hgyzOw%3D%3D (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19046\Desktop\Code\BotWX\chatgpt-on-wechat\lib\itchat\components\login.py", line 301, in maintain_loop
    msgList, contactList = self.get_msg()
                           ^^^^^^^^^^^^^^
  File "C:\Users\19046\Desktop\Code\BotWX\chatgpt-on-wechat\lib\itchat\components\login.py", line 390, in get_msg
    r = self.s.post(url, data=json.dumps(data),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19046\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19046\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19046\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19046\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=APBj6W7OAdj4xWou&skey=@crypt_b80a20f7_49657de9785e94794530a75ea2841dfb&pass_ticket=1XnkOOKHUdg4DxJUSjW3xdnPuy5OU7bdd4VtKChbAioFf4%2BowHaJJn%2FYrlbCtMid0dCBLSte2H4nDJ61hgyzOw%3D%3D (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))) `

**Comment by 6vision** [comment]
看起来是网络或者wx号的问题，可以换号排查一下试试
