### ISSUE TITLE
百度文心偶发报错336006

### ISSUE THREAD

**Issue by a-Dmears** [zhayujie/chatgpt-on-wechat#1959]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

[WARNING][2024-05-10 08:26:24][baidu_wenxin.py:94] - [BAIDU] Exception: 'result'
[ERROR][2024-05-10 08:26:24][chat_channel.py:303] - Worker return exception: 'total_tokens'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/channel/chat_channel.py", line 170, in _handle
    reply = self._generate_reply(context)
  File "/app/channel/chat_channel.py", line 193, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "/app/channel/channel.py", line 38, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/app/bridge/bridge.py", line 74, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "/app/bot/baidu/baidu_wenxin.py", line 41, in reply
    result["total_tokens"],
KeyError: 'total_tokens'

**Comment by 6vision** [comment]
修复了 KeyError: 'total_tokens' 报错，336006错误码见[错误码](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/tlmyncueh)，暂时没复现，可以提供更多log信息

**Comment by 6vision** [comment]
> #2012   修复了 KeyError: 'total_tokens' 报错，336006错误码见[错误码](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/tlmyncueh)，暂时没复现，可以提供更多log信息
