### ISSUE TITLE
无法调用智谱ai

### ISSUE THREAD

**Issue by Ansel123** [zhayujie/chatgpt-on-wechat#1971]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

```log
ModuleNotFoundError: No module named 'zhipuai'
[INFO][2024-05-13 17:32:53][bridge.py:56] - create bot glm-4 for chat
[ERROR][2024-05-13 17:32:53][chat_channel.py:303] - Worker return exception: No module named 'zhipuai'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\GPT_Wechat\env\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrator\Desktop\GPT_Wechat\channel\chat_channel.py", line 170, in _handle
    reply = self._generate_reply(context)
  File "C:\Users\Administrator\Desktop\GPT_Wechat\channel\chat_channel.py", line 182, in _generate_reply
    e_context = PluginManager().emit_event(
  File "C:\Users\Administrator\Desktop\GPT_Wechat\plugins\plugin_manager.py", line 191, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\GPT_Wechat\plugins\godcmd\godcmd.py", line 235, in on_handle_context
    bot = Bridge().get_bot("chat")
  File "C:\Users\Administrator\Desktop\GPT_Wechat\bridge\bridge.py", line 62, in get_bot
    self.bots[typename] = create_bot(self.btype[typename])
  File "C:\Users\Administrator\Desktop\GPT_Wechat\bot\bot_factory.py", line 61, in create_bot
    from bot.zhipuai.zhipuai_bot import ZHIPUAIBot
  File "C:\Users\Administrator\Desktop\GPT_Wechat\bot\zhipuai\zhipuai_bot.py", line 15, in <module>
    from zhipuai import ZhipuAI
ModuleNotFoundError: No module named 'zhipuai'

```

**Comment by 6vision** [comment]
缺少依赖，可以把报错复制给项目[智能小助手](https://link-ai.tech/app/Kv2fXJcH)，或者问一下gpt就明白了
