### ISSUE TITLE
微信扫码登录错误

### ISSUE THREAD

**Issue by NHPT** [zhayujie/chatgpt-on-wechat#1989]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

扫码后报错
[ERROR][2024-05-16 11:31:13][wechat_channel.py:135] - 'wxsid'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 121, in startup
    itchat.auto_login(
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

![1715830516111](https://github.com/zhayujie/chatgpt-on-wechat/assets/42366434/d7e675e6-0dcb-4387-b0f2-47959c6c7571)

### 终端日志 📒

```log
INFO][2024-05-16 11:30:55][role.py:69] - [Role] inited
[INFO][2024-05-16 11:30:55][dungeon.py:56] - [Dungeon] inited
[INFO][2024-05-16 11:30:55][hello.py:38] - [Hello] inited
[INFO][2024-05-16 11:30:55][finish.py:23] - [Finish] inited
[ERROR][2024-05-16 11:31:13][wechat_channel.py:135] - 'wxsid'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 121, in startup
    itchat.auto_login(
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
[INFO][2024-05-16 11:35:54][app.py:19] - signal 2 received, exiting...
[INFO][2024-05-16 11:35:54][config.py:219] - [Config] User datas saved.
```

**Comment by BiCffQ** [comment]
同样的报错
![企业微信截图_20240517101926](https://github.com/zhayujie/chatgpt-on-wechat/assets/31585109/8275f718-4cc6-41a7-aa92-2703fecaf401)

**Comment by WqiancangQ** [comment]
同样的错误＋1
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/13100277/d01147cc-94c5-4435-909a-a7ec6a4b23ac)

**Comment by BiCffQ** [comment]
这种问题好像是就是被Tencent封号了，禁止web登录的缘故。

**Comment by BiCffQ** [comment]
> 这种问题好像是就是被Tencent封号了，禁止web登录的缘故。

可以先访问https://web.weixin.qq.com/，看能否正常登录，微信号需要实名验证开通支付功能
![1231](https://github.com/zhayujie/chatgpt-on-wechat/assets/31585109/b1fc33c7-5c31-4161-99c2-cb1417010fd8)

**Comment by sbcxk** [comment]
微信账号实名了吗？

**Comment by 6vision** [comment]
需要实名绑卡认证，腾讯官方的要求

**Comment by aspack00** [comment]
> 需要实名绑卡认证，腾讯官方的要求

正解，我加了就好了

**Comment by NHPT** [comment]
是的  我也是实名认证完添加银行卡就好了
