### ISSUE TITLE
failed log

### ISSUE THREAD

**Issue by chgy188** [zhayujie/chatgpt-on-wechat#2]
Python 3.9.13
Traceback (most recent call last):
  File "D:\python39\lib\site-packages\itchat\components\login.py", line 255, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "D:\python39\lib\site-packages\itchat\components\messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "D:\python39\lib\site-packages\itchat\components\messages.py", line 236, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "D:\python39\lib\site-packages\itchat\utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

**Comment by zhayujie** [comment]
> python 3.9 及以上 itchat 不兼容，参考这个 issue: https://github.com/littlecodersh/ItChat/issues/963

建议使用 Python 3.7.1 - 3.9 之间 的版本 ( 3.7.5 亲测可以)，  后面考虑修改下itchat 或者 替换其他库

**Comment by zhayujie** [comment]
The case has been solved by using itchat-uos, now supports python 3.9+ and solved the limitation of web wechat.
Commit: https://github.com/zhayujie/chatgpt-on-wechat/commit/3c7016ccd426a930a318e81592863b21b21d1476

**Comment by dfldylan** [comment]
> > python 3.9 及以上 itchat 不兼容，参考这个 issue: [littlecodersh/ItChat#963](https://github.com/littlecodersh/ItChat/issues/963)
> 
> 建议使用 Python 3.7.1 - 3.9 之间 的版本 ( 3.7.5 亲测可以)， 后面考虑修改下itchat 或者 替换其他库

老板，有啥计划的框架吗。我最近找了一圈只找到个GOLANG的还一直在维护
https://github.com/eatmoreapple/openwechat
另外这学期wehcat-uos更新了，但是好像还没人提取新的api
