### ISSUE TITLE
个人微信正常登陆出现奇怪错误.

### ISSUE THREAD

**Issue by taozhiyuai** [zhayujie/chatgpt-on-wechat#2008]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

只是正常的扫码登陆. 其他的微信号都没有问题.

### 终端日志 📒

```log
taozhiyu@603e5f4a42f1 chatgpt-on-wechat % ./cow.sh
[INFO][2024-05-22 13:13:07][config.py:260] - [INIT] load config: {'channel_type': 'wx', 'model': 'ERNIE-Speed-128K', 'open_ai_api_key': 'sk-xN7IG04OaimAmXv01c33Fe84E8874aD19a8a0d068807C69b', 'open_ai_api_base': 'http://localhost:3001/v1', 'claude_api_key': 'YOUR API KEY', 'text_to_image': 'dall-e-2', 'voice_to_text': 'openai', 'text_to_voice': 'openai', 'proxy': '', 'hot_reload': False, 'single_chat_prefix': [''], 'single_chat_reply_prefix': '[bot] ', 'group_chat_prefix': ['@bot'], 'group_name_keyword_white_list': ['浅水湾', '一意'], 'image_create_prefix': ['不画'], 'speech_recognition': False, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 9000, 'expires_in_seconds': 3600, 'character_desc': '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'temperature': 0.7, 'subscribe_msg': '感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。', 'use_linkai': False, 'linkai_api_key': '', 'linkai_app_code': ''}
[INFO][2024-05-22 13:13:07][config.py:208] - [Config] User datas loaded.
[INFO][2024-05-22 13:13:07][plugin_manager.py:50] - Loading plugins config...
[INFO][2024-05-22 13:13:07][plugin_manager.py:88] - Scaning plugins ...
[INFO][2024-05-22 13:13:07][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2024-05-22 13:13:07][plugin_manager.py:41] - Plugin linkai_v0.1.0 registered, path=./plugins/linkai
[INFO][2024-05-22 13:13:07][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2024-05-22 13:13:07][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2024-05-22 13:13:07][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins/finish
[INFO][2024-05-22 13:13:07][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2024-05-22 13:13:07][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2024-05-22 13:13:07][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2024-05-22 13:13:07][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins/keyword
chatgpt-tool-hub version: 0.5.0
[INFO][2024-05-22 13:13:07][plugin_manager.py:41] - Plugin tool_v0.5 registered, path=./plugins/tool
[INFO][2024-05-22 13:13:07][godcmd.py:194] - [Godcmd] 因未设置口令，本次的临时口令为3120。
[INFO][2024-05-22 13:13:07][godcmd.py:210] - [Godcmd] inited
[INFO][2024-05-22 13:13:07][keyword.py:40] - [keyword] {}
[INFO][2024-05-22 13:13:07][keyword.py:42] - [keyword] inited.
[INFO][2024-05-22 13:13:07][linkai.py:35] - [LinkAI] inited, config={'group_app_map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'group_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}}
[INFO][2024-05-22 13:13:07][tool.py:28] - [tool] inited
[INFO][2024-05-22 13:13:07][role.py:69] - [Role] inited
[INFO][2024-05-22 13:13:07][dungeon.py:56] - [Dungeon] inited
[INFO][2024-05-22 13:13:07][hello.py:38] - [Hello] inited
[INFO][2024-05-22 13:13:07][finish.py:23] - [Finish] inited
Ready to login.
Getting uuid of QR code.
Downloading QR code.
You can also scan QRCode in any website below:
https://api.pwmqr.com/qrcode/create/?url=https://login.weixin.qq.com/l/wew1eGX4vA==
https://my.tv.sohu.com/user/a/wvideo/getQRCode.do?text=https://login.weixin.qq.com/l/wew1eGX4vA==
https://api.qrserver.com/v1/create-qr-code/?size=400×400&data=https://login.weixin.qq.com/l/wew1eGX4vA==
https://api.isoyu.com/qr/?m=1&e=L&p=20&url=https://login.weixin.qq.com/l/wew1eGX4vA==
█▀▀▀▀▀▀▀█▀▀██▀███▀█████▀▀▀▀▀▀▀█
█ █▀▀▀█ ██  ▄ ▄▄█▄▀ ▄██ █▀▀▀█ █
█ █   █ █ █ ██ █▄ ▀▀█▄█ █   █ █
█ ▀▀▀▀▀ █ ▄ █▀▄▀█ ▄▀▄ █ ▀▀▀▀▀ █
█▀███▀█▀▀ ▀█▄▄██▄█ █▄ ▀▀▀▀▀██▀█
██▀ █▄▀▀ ▄▄██▀ ▀ ▄█▄█▄█▄▄▄▄▄▄ █
██▄█  ▄▀ █▀█▄ ▀█▄  ▄▄ ▄█▄▄▄█ ▄█
██▄    ▀█ █▀ █▄▄ █▄ █▀█▄▄   ▄ █
█▄▄▀█  ▀█▄▀█ ██ █▀ ▄█▀ █████ ▄█
█▄▄█ █▀▀▄▄▄██ █▀ ▄  ██▄ ▄ ▄▀▄ █
█▀▀ █▀ ▀▄▀▄  ▄█ ▄█  █▀▀▀▀ ▀█▄ █
█▀▀▀▀▀▀▀█ ▀▀█▄█▀ ▄▄ ▀ █▀█ ▀▀█ █
█ █▀▀▀█ █▀██▀▄▀ █▀ ▄  ▀▀▀ ▀█▄▀█
█ █   █ ██ ▀█▀▄▄ ▄  █  ███▀▀▀ █
█ ▀▀▀▀▀ █▀▀▄▀█▄█▀█ ▀█ ▀▄ █ █ ▄█
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Please press confirm on your phone.
[ERROR][2024-05-22 13:13:23][wechat_channel.py:135] - 'wxsid'
Traceback (most recent call last):
  File "/Users/taozhiyu/Downloads/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 121, in startup
    itchat.auto_login(
  File "/Users/taozhiyu/Downloads/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/taozhiyu/Downloads/chatgpt-on-wechat/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/taozhiyu/Downloads/chatgpt-on-wechat/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/taozhiyu/Downloads/chatgpt-on-wechat/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
                                                                     ~~~~~~~^^^^^^^^^
KeyError: 'wxsid'

```

**Comment by 6vision** [comment]
微信未实名认证绑卡或者被风控  #1655

**Comment by azz212** [comment]
换ipad
