### ISSUE TITLE
wechat_channel中启动报错

### ISSUE THREAD

**Issue by lvdqiang** [zhayujie/chatgpt-on-wechat#201]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

![1676303496736](https://user-images.githubusercontent.com/125290837/218506047-6beefdc3-b34f-403a-89ec-0e63cee518e3.png)

### 终端日志 (如有报错)
[ERROR][2023-02-13 23:39:21][app.py:19] - App startup failed!
[ERROR][2023-02-13 23:39:21][app.py:20] - list index out of range
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "E:\WorkSpace\python\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "D:\python\lib\site-packages\itchat\components\register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "D:\python\lib\site-packages\itchat\components\login.py", line 60, in login
    status = self.check_login()
  File "D:\python\lib\site-packages\itchat\components\login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "D:\python\lib\site-packages\itchat\components\login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lvdqiang** [comment]
itchat.auto_login(enableCmdQR=2)这行代码报错

**Comment by lvdqiang** [comment]
已经实名认证

**Comment by zhayujie** [comment]
python版本是多少

**Comment by lvdqiang** [comment]
> python版本是多少

原因是微信被冻结了，解冻就好了
