### ISSUE TITLE
登录后报错wechat_channel.py:116

### ISSUE THREAD

**Issue by licheng123qp** [zhayujie/chatgpt-on-wechat#202]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[ERROR][2023-02-14 00:34:17][wechat_channel.py:116] - No module named 'openai'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 112, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "/root/chatgpt-on-wechat/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/root/chatgpt-on-wechat/bridge/bridge.py", line 9, in fetch_reply_content
    return bot_factory.create_bot("openAI").reply(query, context)
  File "/root/chatgpt-on-wechat/bot/bot_factory.py", line 24, in create_bot
    from bot.openai.open_ai_bot import OpenAIBot
  File "/root/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 6, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：LINUX Ubuntu22.10
 - Python版本  ( 执行 `python3 -V` )： Python 3.10.6                   
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by sandfilter** [comment]
出现相同的问题

操作系统类型 (Mac/Windows/Linux)：LINUX centos 7
Python版本 ( 执行 python3 -V )： Python 2.7
pip版本 ( 依赖问题此项必填，执行 pip3 -V)：pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)

pip show openai
You are using pip version 8.1.2, however version 23.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by zhayujie** [comment]
> 出现相同的问题
> 
> 操作系统类型 (Mac/Windows/Linux)：LINUX centos 7 Python版本 ( 执行 python3 -V )： Python 2.7 pip版本 ( 依赖问题此项必填，执行 pip3 -V)：pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
> 
> pip show openai You are using pip version 8.1.2, however version 23.0 is available. You should consider upgrading via the 'pip install --upgrade pip' command.

python版本太低了，换成3.7以上吧

**Comment by LGM119** [comment]
微信登录后报错
python版本：Python 3.10.7
PIP版本：pip 22.3.1
Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-02-24 11:18:32][app.py:19] - App startup failed!
[ERROR][2023-02-24 11:18:32][app.py:20] - list index out of range
Traceback (most recent call last):
  File "/root/tmp/chatgpt-on-wechat-1.0.1/app.py", line 17, in <module>
    channel.startup()
  File "/root/tmp/chatgpt-on-wechat-1.0.1/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/lib/python3.10/dist-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.10/dist-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/usr/local/lib/python3.10/dist-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.10/dist-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range
[2]  - done       nohup python3 app.py

**Comment by zhayujie** [comment]
微信号有实名认证吗？或者被冻结了？
