### ISSUE TITLE
扫码登录以后就提示这个，，有人解决了嘛

### ISSUE THREAD

**Issue by sdsxzhang** [zhayujie/chatgpt-on-wechat#207]
Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-02-13 12:44:44][app.py:19] - App startup failed!
[ERROR][2023-02-13 12:44:44][app.py:20] - list index out of range
Traceback (most recent call last):
File "app.py", line 17, in
channel.startup()
File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
itchat.auto_login(enableCmdQR=2)
File "/usr/local/lib/python3.7/dist-packages/itchat/components/register.py", line 36, in auto_login
loginCallback=loginCallback, exitCallback=exitCallback)
File "/usr/local/lib/python3.7/dist-packages/itchat/components/login.py", line 61, in login
status = self.check_login()
File "/usr/local/lib/python3.7/dist-packages/itchat/components/login.py", line 152, in check_login
if process_login_info(self, r.text):
File "/usr/local/lib/python3.7/dist-packages/itchat/components/login.py", line 197, in process_login_info
skey = re.findall('(.*?)', r.text, re.S)[0]
IndexError: list index out of range

**Comment by sdsxzhang** [comment]
微信实名加已经开支付了，，以前还可以登录 现在不行了

**Comment by ZhongHE-029** [comment]
同样的，我也是这样，求解决办法

**Comment by wooxiaowei** [comment]
遇到同样的问题

**Comment by zhayujie** [comment]
如果是实名后的账号， 并且itchat-uos也安装了指定版本， 那就是账号被限制了

**Comment by ZhongHE-029** [comment]
确实是上面大哥说的问题，我的账号支付被冻结了，但是聊天没有，所以没有发现。现在封号很普遍，原因没找到以前大家还是谨慎一点。

**Comment by thefreelight** [comment]
要写地址

**Comment by achen1110** [comment]
我遇到一样的问题，下面是chat GPT 给的回复，不过我也看不明白：
下面这段代码是指什么地方有错误？
[ERROR][2023-02-15 09:41:48][app.py:19] - App startup failed!
[ERROR][2023-02-15 09:41:48][app.py:20] - list index out of range
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 152, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 197, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

这段代码指出了在'/usr/local/lib/python3.8/dist-packages/itchat/components/login.py'文件的第197行存在错误，抛出了一个IndexError异常，即“列表索引超出范围”。

那怎么修改？

可以在'/usr/local/lib/python3.8/dist-packages/itchat/components/login.py'文件的第197行添加适当的代码，以确保查找的skey的结果列表中至少有一个元素，以避免IndexError异常的发生。

**Comment by lzqfree** [comment]
以上问题有谁解决了，请告知一下，谢谢！

**Comment by zhayujie** [comment]
@lzqfree 账号实名了吗，有没有被冻结
