### ISSUE TITLE
容器部署时，第三方镜像调用claude失败

### ISSUE THREAD

**Issue by Pink9999** [zhayujie/chatgpt-on-wechat#2159]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

docker-compose.yml文件中想要生效bot_type:'chatGPT'一项却一直没法实现，是格式不对吗，如果不调用就会导致识别为claude_api格式，创建一个Claudebot，紧接着就不会有任何的响应

### 问题描述 😯

![屏幕截图 2024-07-18 113830](https://github.com/user-attachments/assets/453aa648-06ef-4023-b9cb-7ba4d1c9b857)

![屏幕截图 2024-07-18 113915](https://github.com/user-attachments/assets/6d9aff73-f0bc-48ab-9c59-3d13b5a9ea2c)

### 终端日志 📒

```log
[INFO][2024-07-18 03:18:25][bridge.py:61] - create bot claudeAPI for chat
[INFO][2024-07-18 03:18:27][claude_api_bot.py:42] - [CLAUDE_API] query=你好
[WARNING][2024-07-18 03:18:33][claude_api_bot.py:116] - [CLAUDE_API] Exception: Error code: 403 - {'error': {'type': 'forbidden', 'message': 'Request not allowed'}}
[INFO][2024-07-18 03:18:33][claude_api_bot.py:54] - {'completion_tokens': 0, 'content': '我现在有点累了，等会再来吧'}
[ERROR][2024-07-18 03:18:33][chat_channel.py:303] - Worker return exception: 'total_tokens'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/channel/chat_channel.py", line 170, in _handle
    reply = self._generate_reply(context)
  File "/app/channel/chat_channel.py", line 193, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "/app/channel/channel.py", line 38, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/app/bridge/bridge.py", line 76, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "/app/bot/claudeapi/claude_api_bot.py", line 56, in reply
    result["total_tokens"],
KeyError: 'total_tokens'

```

**Comment by 6vision** [comment]
启动日志中是否有bot_type参数，修改配置需要先compose down再启动
