### ISSUE TITLE
哪位大哥能帮我看一下,openai.error

### ISSUE THREAD

**Issue by LoveClears** [zhayujie/chatgpt-on-wechat#2165]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

钉钉上已经接通,在对机器人发消息的时候,弹出这个错误
openai.error

### 问题描述 😯

![image](https://github.com/user-attachments/assets/6c9a7662-bb0d-4e8c-ba18-2662636bdaca)

### 终端日志 📒

```log
[ERROR][2024-07-19 16:06:35][chat_channel.py:303] - Worker return exception: No module named 'openai.error'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 170, in _handle
    reply = self._generate_reply(context)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 182, in _generate_reply
    e_context = PluginManager().emit_event(
  File "/root/chatgpt-on-wechat/plugins/plugin_manager.py", line 191, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/root/chatgpt-on-wechat/plugins/role/role.py", line 104, in on_handle_context
    bot = Bridge().get_bot("chat")
  File "/root/chatgpt-on-wechat/bridge/bridge.py", line 74, in get_bot
    self.bots[typename] = create_bot(self.btype[typename])
  File "/root/chatgpt-on-wechat/bot/bot_factory.py", line 22, in create_bot
    from bot.chatgpt.chat_gpt_bot import ChatGPTBot
  File "/root/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 6, in <module>
    import openai.error
ModuleNotFoundError: No module named 'openai.error'

```

**Comment by 6vision** [comment]
openai sdk版本过高，安装 openai==0.27.8
