### ISSUE TITLE
接企微:启动报错， No module named 'pilk'和‘nxwork’

### ISSUE THREAD

**Issue by zhangweize** [zhayujie/chatgpt-on-wechat#2183]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

1、config-template.json中"channel_type": "wework"
2、python app.py
![image](https://github.com/user-attachments/assets/434e35e8-09b8-4bc1-9031-7b05e7465f77)

### 终端日志 📒

```log
[INFO][2024-07-25 11:26:08][config.py:266] - 配置文件不存在，将使用config-template.json模板
[INFO][2024-07-25 11:26:08][config.py:295] - [INIT] load config: {'channel_type': 'wework', 'model': '', 'open_ai_api_key': 'YOU*****KEY', 'claude_api_key': 'YOU*****KEY', 'text_to_image': 'dall-e-2', 'voice_to_text': 'openai', 
'text_to_voice': 'openai', 'proxy': '', 'hot_reload': False, 'single_chat_prefix': ['bot', '@bot'], 'single_chat_reply_prefix': '[bot] ', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ChatGPT测试群', 'ChatGPT测试群2'
], 'image_create_prefix': ['画'], 'speech_recognition': True, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 2500, 'expires_in_seconds': 3600, 'character_desc': '你是基于大语言模型的AI 
智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'temperature': 0.7, 'subscribe_msg': '感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要 
求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。', 'use_linkai': False, 'linkai_api_key': '*****', 'linkai_app_code': ''}
[INFO][2024-07-25 11:26:08][config.py:221] - [Config] User datas file not found, ignore.
D:\Python\Python310\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
[ERROR][2024-07-25 11:26:08][app.py:66] - App startup failed!
[ERROR][2024-07-25 11:26:08][app.py:67] - No module named 'pilk'
Traceback (most recent call last):
  File "E:\PycharmProjects\chatgpt-on-wechat\app.py", line 61, in run
    start_channel(channel_name)
  File "E:\PycharmProjects\chatgpt-on-wechat\app.py", line 29, in start_channel
    channel = channel_factory.create_channel(channel_name)
  File "E:\PycharmProjects\chatgpt-on-wechat\channel\channel_factory.py", line 34, in create_channel
    from channel.wework.wework_channel import WeworkChannel
  File "E:\PycharmProjects\chatgpt-on-wechat\channel\wework\wework_channel.py", line 14, in <module>
    from channel.wework.wework_message import *
  File "E:\PycharmProjects\chatgpt-on-wechat\channel\wework\wework_message.py", line 6, in <module>
    import pilk
ModuleNotFoundError: No module named 'pilk'
```

**Comment by 6vision** [comment]
开源项目已不支持的接入渠道

**Comment by simpsonyang** [comment]
你的问题应该是ntwork，你可以到github上下载whl文件，然后pip install *.whl就可以了。
