### ISSUE TITLE
脚本使用出现报错，Traceback (most recent call last)

### ISSUE THREAD

**Issue by xiaomuahua666** [zhayujie/chatgpt-on-wechat#2201]
### 前置确认

- [x] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

正确安装 Python 3.8.10,。
正确下载源代码并解压。
使用 Pycharm 正常安装 requirements.txt（pycharm提示的）
正确修改 config.json 配置文件，已经过 json 检验网站语法核实。
运行app.py，并正常登录。
与自己对话（或使用他人与自己对话）会报错。
结束运行程序，进入 issues 核实要求并反馈。

### 问题描述 😯

无论是服务器还是本地，运行后都会产生以下报错，下方有图片与config.json配置：
```wrong
[ERROR][2024-08-02 09:44:42][chat_channel.py:303] - Worker return exception: can only concatenate list (not "str") to list
Traceback (most recent call last):
  File "C:\Users\86131\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\86131\Desktop\chatgpt-on-wechat-master\channel\chat_channel.py", line 176, in _handle
    reply = self._decorate_reply(context, reply)
  File "C:\Users\86131\Desktop\chatgpt-on-wechat-master\channel\chat_channel.py", line 261, in _decorate_reply
    reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")
TypeError: can only concatenate list (not "str") to list
```

运行证明:
![image](https://github.com/user-attachments/assets/a36fdebd-b388-4928-9b13-4afb6dbaae7d)

config.json 配置：
```json
{
  "channel_type": "wx",
  "model": "wenxin",
  "bot_type": "baidu",
  "baidu_wenxin_model": "eb-instant",
  "baidu_wenxin_api_key": "JtDDTaVKvzLV8LpVWnO98qqD",
  "baidu_wenxin_secret_key": "xZxjt7P4GxjKwWB4C0NOT9NhmZI5Gjko",
  "hot_reload": false,
  "single_chat_prefix": [
    "bot",
    "@bot"
  ],
  "single_chat_reply_prefix": [
    "bot",
    "@bot"
  ],
  "group_chat_prefix": [
    "@bot"
  ],
  "group_name_white_list": [
    "24届新场中学新生交流群"
  ],
  "group_chat_in_one_session" : [
  	"24届新场中学新生交流群"
  ],
  "speech_recognition": false,
  "group_speech_recognition": false,
  "debug": true,
  "voice_reply_voice": false,
  "expires_in_seconds": 3600,
  "conversation_max_tokens": 2500,
  "group_at_off": false,
  "chat_time_module": false,
  "character_desc": "你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。"
}
```

### 终端日志 📒

```log
[INFO][2024-08-02 09:43:22][config.py:295] - [INIT] load config: {'channel_type': 'wx', 'model': 'wenxin', 'bot_type': 'baidu', 'baidu_wenxin_model': 'eb-instant', 'baidu_wenxin_api_key': 'JtD*****qqD', 'baidu_wenxin_secret_key': 'xZx*****jko', 'hot_reload': False, 'single_chat_prefix': ['bot', '@bot'], 'single_chat_reply_prefix': ['bot', '@bot'], 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['24届新场中学新生交流群'], 'group_chat_in_one_session': ['24届新场中学新生交流群'], 'speech_recognition': False, 'group_speech_recognition': False, 'debug': True, 'voice_reply_voice': False, 'expires_in_seconds': 3600, 'conversation_max_tokens': 2500, 'group_at_off': False, 'chat_time_module': False, 'character_desc': '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'}
[INFO][2024-08-02 09:43:22][config.py:219] - [Config] User datas loaded.
[DEBUG][2024-08-02 09:43:23][audio_convert.py:9] - import pysilk failed, wechaty voice message will not be supported.
[INFO][2024-08-02 09:43:23][plugin_manager.py:50] - Loading plugins config...
[INFO][2024-08-02 09:43:23][plugin_manager.py:88] - Scaning plugins ...
[INFO][2024-08-02 09:43:23][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins\banwords
[INFO][2024-08-02 09:43:23][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins\bdunit
[INFO][2024-08-02 09:43:23][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins\dungeon
[INFO][2024-08-02 09:43:23][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins\finish
[INFO][2024-08-02 09:43:23][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins\godcmd
[INFO][2024-08-02 09:43:23][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins\hello
[INFO][2024-08-02 09:43:23][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins\keyword
[INFO][2024-08-02 09:43:23][plugin_manager.py:41] - Plugin linkai_v0.1.0 registered, path=./plugins\linkai
[INFO][2024-08-02 09:43:23][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins\role
[WARNING][2024-08-02 09:43:23][plugin_manager.py:113] - Failed to import plugin tool: No module named 'chatgpt_tool_hub'
[DEBUG][2024-08-02 09:43:23][plugin_manager.py:179] - plugins.json config={'plugins': SortedDict({'Godcmd': {'enabled': True, 'priority': 999}, 'Keyword': {'enabled': True, 'priority': 900}, 'Banwords': {'enabled': False, 'priority': 100}, 'linkai': {'enabled': False, 'priority': 99}, 'Role': {'enabled': True, 'priority': 0}, 'Dungeon': {'enabled': True, 'priority': 0}, 'BDunit': {'enabled': False, 'priority': 0}, 'Hello': {'enabled': True, 'priority': -1}, 'Finish': {'enabled': True, 'priority': -999}}, sort_func=<lambda>, reverse=True)}
[DEBUG][2024-08-02 09:43:23][plugin.py:21] - loading plugin config, plugin_config_path=./plugins\godcmd\config.json, exist=True
[DEBUG][2024-08-02 09:43:23][plugin.py:28] - loading plugin config, plugin_name=Godcmd, conf={'password': '', 'admin_users': []}
[INFO][2024-08-02 09:43:23][godcmd.py:194] - [Godcmd] 因未设置口令，本次的临时口令为3147。
[INFO][2024-08-02 09:43:23][godcmd.py:210] - [Godcmd] inited
[DEBUG][2024-08-02 09:43:23][keyword.py:34] - [keyword]加载配置文件C:\Users\86131\Desktop\chatgpt-on-wechat-master\plugins\keyword\config.json
[INFO][2024-08-02 09:43:23][keyword.py:40] - [keyword] {}
[INFO][2024-08-02 09:43:23][keyword.py:42] - [keyword] inited.
[DEBUG][2024-08-02 09:43:23][role.py:62] - [Role] no role found for tag comments 
[INFO][2024-08-02 09:43:23][role.py:69] - [Role] inited
[INFO][2024-08-02 09:43:23][dungeon.py:56] - [Dungeon] inited
[DEBUG][2024-08-02 09:43:23][plugin.py:21] - loading plugin config, plugin_config_path=./plugins\hello\config.json, exist=False
[DEBUG][2024-08-02 09:43:23][plugin.py:28] - loading plugin config, plugin_name=Hello, conf=None
[DEBUG][2024-08-02 09:43:23][hello.py:119] - No Hello plugin config.json, use plugins/hello/config.json.template
[INFO][2024-08-02 09:43:23][hello.py:38] - [Hello] inited
[INFO][2024-08-02 09:43:23][finish.py:23] - [Finish] inited
[DEBUG][2024-08-02 09:44:05][wechat_channel.py:151] - Login success
[INFO][2024-08-02 09:44:05][wechat_channel.py:131] - Wechat login success, user_id: @ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315, nickname: 麻花
[DEBUG][2024-08-02 09:44:06][wechat_channel.py:45] - [WX]group message 7638494490095871928 skipped: Unsupported message type: Type:Note MsgType:10002
[DEBUG][2024-08-02 09:44:19][wechat_channel.py:180] - [WX]receive text msg: {"MsgId": "4223802396756532174", "FromUserName": "@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315", "ToUserName": "@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315", "MsgType": 1, "Content": "bot你好！你部署成了吗", "Status": 3, "ImgStatus": 1, "CreateTime": 1722563058, "VoiceLength": 0, "PlayLength": 0, "FileName": "", "FileSize": "", "MediaId": "", "Url": "", "AppMsgType": 0, "StatusNotifyCode": 0, "StatusNotifyUserName": "", "RecommendInfo": {"UserName": "", "NickName": "", "QQNum": 0, "Province": "", "City": "", "Content": "", "Signature": "", "Alias": "", "Scene": 0, "VerifyFlag": 0, "AttrStatus": 0, "Sex": 0, "Ticket": "", "OpCode": 0}, "ForwardFlag": 0, "AppInfo": {"AppID": "", "Type": 0}, "HasProductId": 0, "Ticket": "", "ImgHeight": 0, "ImgWidth": 0, "SubMsgType": 0, "NewMsgId": 4223802396756532174, "OriContent": "", "EncryFileName": "", "User": {"MemberList": [], "UserName": "@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315", "City": "", "DisplayName": "", "PYQuanPin": "", "RemarkPYInitial": "", "Province": "", "KeyWord": "", "RemarkName": "", "PYInitial": "", "EncryChatRoomId": "", "Alias": "", "Signature": "乐子，你是来看我成分的吗😇<span class=\"emoji emoji1f51e\"></span>", "NickName": "麻花", "RemarkPYQuanPin": "", "HeadImgUrl": "/cgi-bin/mmwebwx-bin/webwxgeticon?seq=1286353401&username=@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315&skey=@crypt_d75a8720_d44d9674ec0530b787904c92b594a6d6", "UniFriend": 0, "Sex": 1, "AppAccountFlag": 0, "VerifyFlag": 0, "ChatRoomId": 0, "HideInputBarFlag": 0, "AttrStatus": 0, "SnsFlag": 257, "MemberCount": 0, "OwnerUin": 0, "ContactFlag": 0, "Uin": 3475448152, "StarFriend": 0, "Statues": 0, "WebWxPluginSwitch": 0, "HeadImgFlag": 1}, "Type": "Text", "Text": "bot你好！你部署成了吗"}, cmsg=ChatMessage: id=4223802396756532174, create_time=1722563058, ctype=TEXT, content=bot你好！你部署成了吗, from_user_id=@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315, from_user_nickname=麻花, to_user_id=@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315, to_user_nickname=麻花, other_user_id=@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315, other_user_nickname=麻花, is_group=False, is_at=False, actual_user_id=None, actual_user_nickname=None, at_list=None
[DEBUG][2024-08-02 09:44:19][chat_channel.py:345] - [chat_channel] consume context: Context(type=TEXT, content=你好！你部署成了吗, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x00000129464A4D90>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315', 'receiver': '@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315'})
[DEBUG][2024-08-02 09:44:19][chat_channel.py:168] - [chat_channel] ready to handle context: Context(type=TEXT, content=你好！你部署成了吗, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x00000129464A4D90>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315', 'receiver': '@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315'})
[DEBUG][2024-08-02 09:44:19][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:19][godcmd.py:220] - [Godcmd] on_handle_context. content: 你好！你部署成了吗
[DEBUG][2024-08-02 09:44:19][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:19][keyword.py:52] - [keyword] on_handle_context. content: 你好！你部署成了吗
[DEBUG][2024-08-02 09:44:19][plugin_manager.py:189] - Plugin ROLE triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:19][plugin_manager.py:189] - Plugin DUNGEON triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:19][plugin_manager.py:189] - Plugin HELLO triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:19][hello.py:90] - [Hello] on_handle_context. content: 你好！你部署成了吗
[DEBUG][2024-08-02 09:44:19][plugin_manager.py:189] - Plugin FINISH triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:19][finish.py:30] - [Finish] on_handle_context. content: 你好！你部署成了吗
[DEBUG][2024-08-02 09:44:19][chat_channel.py:190] - [chat_channel] ready to handle context: type=TEXT, content=你好！你部署成了吗
[INFO][2024-08-02 09:44:19][bridge.py:68] - create bot baidu for chat
[INFO][2024-08-02 09:44:19][baidu_wenxin.py:36] - [BAIDU] query=你好！你部署成了吗
[DEBUG][2024-08-02 09:44:19][session_manager.py:70] - prompt tokens used=9
[INFO][2024-08-02 09:44:19][baidu_wenxin.py:74] - [BAIDU] model=eb-instant
[INFO][2024-08-02 09:44:20][baidu_wenxin.py:90] - [BAIDU] response text={'id': 'as-14d7hs2wja', 'object': 'chat.completion', 'created': 1722563059, 'result': '你好！我还在努力为你提供服务。不过如果你有任何问题或者需要帮助，我会尽力回答和提供信息。请告诉我你需要了解什么，我会尽我所能帮助你。', 'is_truncated': False, 'need_clear_history': False, 'usage': {'prompt_tokens': 6, 'completion_tokens': 37, 'total_tokens': 43}}
[INFO][2024-08-02 09:44:20][baidu_wenxin.py:94] - [BAIDU] reply=你好！我还在努力为你提供服务。不过如果你有任何问题或者需要帮助，我会尽力回答和提供信息。请告诉我你需要了解什么，我会尽我所能帮助你。
[DEBUG][2024-08-02 09:44:20][baidu_wenxin.py:53] - [BAIDU] new_query=[{'role': 'user', 'content': '你好！你部署成了吗'}], session_id=@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315, reply_cont=你好！我还在努力为你提供服务。不过如果你有任何问题或者需要帮助，我会尽力回答和提供信息。请告诉我你需要了解什么，我会尽我所能帮助你。, completion_tokens=37
[DEBUG][2024-08-02 09:44:20][session_manager.py:81] - raw total_tokens=43, savesession tokens=75
[DEBUG][2024-08-02 09:44:20][chat_channel.py:172] - [chat_channel] ready to decorate reply: Reply(type=TEXT, content=你好！我还在努力为你提供服务。不过如果你有任何问题或者需要帮助，我会尽力回答和提供信息。请告诉我你需要了解什么，我会尽我所能帮助你。)
[ERROR][2024-08-02 09:44:20][chat_channel.py:303] - Worker return exception: can only concatenate list (not "str") to list
Traceback (most recent call last):
  File "C:\Users\86131\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\86131\Desktop\chatgpt-on-wechat-master\channel\chat_channel.py", line 176, in _handle
    reply = self._decorate_reply(context, reply)
  File "C:\Users\86131\Desktop\chatgpt-on-wechat-master\channel\chat_channel.py", line 261, in _decorate_reply
    reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")
TypeError: can only concatenate list (not "str") to list
[DEBUG][2024-08-02 09:44:41][wechat_channel.py:180] - [WX]receive text msg: {"MsgId": "8135729080127153927", "FromUserName": "@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315", "ToUserName": "@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315", "MsgType": 1, "Content": "bot第二问：这种bug好难绷", "Status": 3, "ImgStatus": 1, "CreateTime": 1722563079, "VoiceLength": 0, "PlayLength": 0, "FileName": "", "FileSize": "", "MediaId": "", "Url": "", "AppMsgType": 0, "StatusNotifyCode": 0, "StatusNotifyUserName": "", "RecommendInfo": {"UserName": "", "NickName": "", "QQNum": 0, "Province": "", "City": "", "Content": "", "Signature": "", "Alias": "", "Scene": 0, "VerifyFlag": 0, "AttrStatus": 0, "Sex": 0, "Ticket": "", "OpCode": 0}, "ForwardFlag": 0, "AppInfo": {"AppID": "", "Type": 0}, "HasProductId": 0, "Ticket": "", "ImgHeight": 0, "ImgWidth": 0, "SubMsgType": 0, "NewMsgId": 8135729080127153927, "OriContent": "", "EncryFileName": "", "User": {"MemberList": [], "UserName": "@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315", "City": "", "DisplayName": "", "PYQuanPin": "", "RemarkPYInitial": "", "Province": "", "KeyWord": "", "RemarkName": "", "PYInitial": "", "EncryChatRoomId": "", "Alias": "", "Signature": "乐子，你是来看我成分的吗😇<span class=\"emoji emoji1f51e\"></span>", "NickName": "麻花", "RemarkPYQuanPin": "", "HeadImgUrl": "/cgi-bin/mmwebwx-bin/webwxgeticon?seq=1286353401&username=@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315&skey=@crypt_d75a8720_d44d9674ec0530b787904c92b594a6d6", "UniFriend": 0, "Sex": 1, "AppAccountFlag": 0, "VerifyFlag": 0, "ChatRoomId": 0, "HideInputBarFlag": 0, "AttrStatus": 0, "SnsFlag": 257, "MemberCount": 0, "OwnerUin": 0, "ContactFlag": 0, "Uin": 3475448152, "StarFriend": 0, "Statues": 0, "WebWxPluginSwitch": 0, "HeadImgFlag": 1}, "Type": "Text", "Text": "bot第二问：这种bug好难绷"}, cmsg=ChatMessage: id=8135729080127153927, create_time=1722563079, ctype=TEXT, content=bot第二问：这种bug好难绷, from_user_id=@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315, from_user_nickname=麻花, to_user_id=@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315, to_user_nickname=麻花, other_user_id=@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315, other_user_nickname=麻花, is_group=False, is_at=False, actual_user_id=None, actual_user_nickname=None, at_list=None
[DEBUG][2024-08-02 09:44:41][chat_channel.py:345] - [chat_channel] consume context: Context(type=TEXT, content=第二问：这种bug好难绷, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x00000129464A4C40>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315', 'receiver': '@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315'})
[DEBUG][2024-08-02 09:44:41][chat_channel.py:168] - [chat_channel] ready to handle context: Context(type=TEXT, content=第二问：这种bug好难绷, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x00000129464A4C40>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315', 'receiver': '@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315'})
[DEBUG][2024-08-02 09:44:41][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:41][godcmd.py:220] - [Godcmd] on_handle_context. content: 第二问：这种bug好难绷
[DEBUG][2024-08-02 09:44:41][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:41][keyword.py:52] - [keyword] on_handle_context. content: 第二问：这种bug好难绷
[DEBUG][2024-08-02 09:44:41][plugin_manager.py:189] - Plugin ROLE triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:41][plugin_manager.py:189] - Plugin DUNGEON triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:41][plugin_manager.py:189] - Plugin HELLO triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:41][hello.py:90] - [Hello] on_handle_context. content: 第二问：这种bug好难绷
[DEBUG][2024-08-02 09:44:41][plugin_manager.py:189] - Plugin FINISH triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-08-02 09:44:41][finish.py:30] - [Finish] on_handle_context. content: 第二问：这种bug好难绷
[DEBUG][2024-08-02 09:44:41][chat_channel.py:190] - [chat_channel] ready to handle context: type=TEXT, content=第二问：这种bug好难绷
[INFO][2024-08-02 09:44:41][baidu_wenxin.py:36] - [BAIDU] query=第二问：这种bug好难绷
[DEBUG][2024-08-02 09:44:41][session_manager.py:70] - prompt tokens used=87
[INFO][2024-08-02 09:44:41][baidu_wenxin.py:74] - [BAIDU] model=eb-instant
[INFO][2024-08-02 09:44:42][baidu_wenxin.py:90] - [BAIDU] response text={'id': 'as-p6m1ast588', 'object': 'chat.completion', 'created': 1722563081, 'result': '对于一些难以修复的bug，需要花费更多的时间和精力去调试和解决。这需要开发者具备扎实的技术知识和经验，以及对程序逻辑和算法的深入理解。不过，只要坚持不懈，通过不断地尝试和改进，相信你一定能成功解决这个bug。加油！', 'is_truncated': False, 'need_clear_history': False, 'usage': {'prompt_tokens': 50, 'completion_tokens': 56, 'total_tokens': 106}}
[INFO][2024-08-02 09:44:42][baidu_wenxin.py:94] - [BAIDU] reply=对于一些难以修复的bug，需要花费更多的时间和精力去调试和解决。这需要开发者具备扎实的技术知识和经验，以及对程序逻辑和算法的深入理解。不过，只要坚持不懈，通过不断地尝试和改进，相信你一定能成功解决这个bug。加油！
[DEBUG][2024-08-02 09:44:42][baidu_wenxin.py:53] - [BAIDU] new_query=[{'role': 'user', 'content': '你好！你部署成了吗'}, {'role': 'assistant', 'content': '你好！我还在努力为你提供服务。不过如果你有任何问题或者需要帮助，我会尽力回答和提供信息。请告诉我你需要了解什么，我会尽我所能帮助你。'}, {'role': 'user', 'content': '第二问：这种bug好难绷'}], session_id=@ed86ebe80e770010fd9bca879d8bfbe2e76a5cd721f4d7dc017cff896cdcc315, reply_cont=对于一些难以修复的bug，需要花费更多的时间和精力去调试和解决。这需要开发者具备扎实的技术知识和经验，以及对程序逻辑和算法的深入理解。不过，只要坚持不懈，通过不断地尝试和改进，相信你一定能成功解决这个bug。加油！, completion_tokens=56
[DEBUG][2024-08-02 09:44:42][session_manager.py:81] - raw total_tokens=106, savesession tokens=194
[DEBUG][2024-08-02 09:44:42][chat_channel.py:172] - [chat_channel] ready to decorate reply: Reply(type=TEXT, content=对于一些难以修复的bug，需要花费更多的时间和精力去调试和解决。这需要开发者具备扎实的技术知识和经验，以及对程序逻辑和算法的深入理解。不过，只要坚持不懈，通过不断地尝试和改进，相信你一定能成功解决这个bug。加油！)
[ERROR][2024-08-02 09:44:42][chat_channel.py:303] - Worker return exception: can only concatenate list (not "str") to list
Traceback (most recent call last):
  File "C:\Users\86131\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\86131\Desktop\chatgpt-on-wechat-master\channel\chat_channel.py", line 176, in _handle
    reply = self._decorate_reply(context, reply)
  File "C:\Users\86131\Desktop\chatgpt-on-wechat-master\channel\chat_channel.py", line 261, in _decorate_reply
    reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")
TypeError: can only concatenate list (not "str") to list
[INFO][2024-08-02 09:44:47][app.py:25] - signal 2 received, exiting...
[INFO][2024-08-02 09:44:47][config.py:230] - [Config] User datas saved.

```

**Comment by SFYYH** [comment]
同求一手解决方法，咋解决的哥

**Comment by xiaomuahua666** [comment]
最新报错，文心一言正常使用，正常响应。但无法在聊天框中发送出信息。
![image](https://github.com/user-attachments/assets/c155861a-ea73-4ac2-8dad-d8a10771fdd1)

**Comment by xiaomuahua666** [comment]
> 同求一手解决方法，咋解决的哥

还没有解决，等作者解惑。

**Comment by 6vision** [comment]
`  "single_chat_reply_prefix"` 该参数是字符类型，不是列表，示例：  "single_chat_reply_prefix": "[bot] ",

**Comment by lanvent** [comment]
config.json中的key明文了，记得更换

**Comment by xiaomuahua666** [comment]
谢谢你的提醒，暂时不用微信模块了。

Jianglang ***@***.***> 于2024年10月11日周五 12:17写道：
