### ISSUE TITLE
Failed to establish a new connection: [Errno -2] Name does not resolve'))

### ISSUE THREAD

**Issue by zhangjinxue** [zhayujie/chatgpt-on-wechat#222]
### 前置确认

1. 运行于香港网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> docker部署，环境应该没有问题。
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/10005317/219260375-c9290196-a142-487c-ba6e-9314fb4cc47d.png">

### 终端日志 (如有报错)

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=B3KwhP/OMbvvdoTQ&skey=@crypt_a20613f2_41117820fd4d0bfb9ace42492901a9ba&pass_ticket=BYiCq7%2F4kA64%2BrUFuFq4TPW8eFR2WluO0j4z3VSuhVfE5lvwz2mJN50YbvW%2FHUqa (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc55f16a250>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Linux
 - Python版本  ( 执行 `python3 -V` )：   Python 3.7.9                   
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.0

**Comment by zhayujie** [comment]
看起像网络不通，你的服务器是在国内吗？ 需要能访问wx.qq.com

**Comment by zhangjinxue** [comment]
> 看起像网络不通，你的服务器是在国内吗？ 需要能访问wx.qq.com

服务器在香港
