### ISSUE TITLE
新注册微信账号无法扫码绑定

### ISSUE THREAD

**Issue by wumengze1993** [zhayujie/chatgpt-on-wechat#2239]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

无

### 问题描述 😯

我用新注册的微信账号无法登录，KeyError报错： wxsid

### 终端日志 📒

```log
[ERROR][2024-08-15 10:38:09][wechat_channel.py:135] - 'wxsid'
Traceback (most recent call last):
  File "/home/wumz/chatgpt-on-wechat-master/channel/wechat/wechat_channel.py", line 121, in startup
    itchat.auto_login(
  File "/home/wumz/chatgpt-on-wechat-master/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/home/wumz/chatgpt-on-wechat-master/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
             ^^^^^^^^^^^^^^^^^^
  File "/home/wumz/chatgpt-on-wechat-master/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wumz/chatgpt-on-wechat-master/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
                                                                     ~~~~~~~^^^^^^^^^
KeyError: 'wxsid'
```

**Comment by CQwumingwang** [comment]
我几年前注册的微信，一样遇到了这个问题

**Comment by CQwumingwang** [comment]
我解决了，我的微信实名认证绑定银行卡后就可以登陆了

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
