### ISSUE TITLE
config.json已经为utf-8编码，运行app.py时报错编码错误

### ISSUE THREAD

**Issue by hyh12323** [zhayujie/chatgpt-on-wechat#2257]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

运行app.py后出现以下报错
Python 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
==== RESTART: C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\app.py ====
[ERROR][2024-08-21 14:00:06][config.py:259] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\config.py", line 243, in drag_sensitive
    conf_dict: dict = json.loads(config)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
[ERROR][2024-08-21 14:00:06][app.py:66] - App startup failed!
[ERROR][2024-08-21 14:00:06][app.py:67] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\app.py", line 46, in run
    load_config()
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\config.py", line 275, in load_config
    config = Config(json.loads(config_str))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
>>> 
windows版本windows server 2016

### 问题描述 😯

Python 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
==== RESTART: C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\app.py ====
[ERROR][2024-08-21 14:00:06][config.py:259] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\config.py", line 243, in drag_sensitive
    conf_dict: dict = json.loads(config)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
[ERROR][2024-08-21 14:00:06][app.py:66] - App startup failed!
[ERROR][2024-08-21 14:00:06][app.py:67] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\app.py", line 46, in run
    load_config()
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\config.py", line 275, in load_config
    config = Config(json.loads(config_str))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
>>> 

### 终端日志 📒

Python 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
==== RESTART: C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\app.py ====
[ERROR][2024-08-21 14:00:06][config.py:259] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\config.py", line 243, in drag_sensitive
    conf_dict: dict = json.loads(config)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
[ERROR][2024-08-21 14:00:06][app.py:66] - App startup failed!
[ERROR][2024-08-21 14:00:06][app.py:67] - Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\app.py", line 46, in run
    load_config()
  File "C:\Users\Administrator\Desktop\chatgpt-on-wechat-1.7.0\config.py", line 275, in load_config
    config = Config(json.loads(config_str))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
>>>

**Comment by 6vision** [comment]
升级windows版本windows server版本，比如2022
