### ISSUE TITLE
部分用户发送消息报错，Traceback (most recent call last):   File "/usr/local/lib/python3.8/dist-packages/itchat/components/register.py", line 60, in configured_reply     r = replyFn(msg)   File "/home/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 21, in handler_single_msg     WechatChannel().handle(msg)   File "/home/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 46, in handle     other_user_id = msg['User']['UserName']     # 对手方id KeyError: 'UserName'

### ISSUE THREAD

**Issue by jacklife** [zhayujie/chatgpt-on-wechat#228]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "/home/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 21, in handler_single_msg
    WechatChannel().handle(msg)
  File "/home/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 46, in handle
    other_user_id = msg['User']['UserName']     # 对手方id
KeyError: 'UserName'

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
是不是没加好友

**Comment by LIMo927** [comment]
[INFO][2023-03-21 14:38:23][log.py:34] - [INIT] Start up: chatgpt on wechat
Start auto replying.
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "/home/chatgpt/bot-on-anything/channel/wechat/wechat_channel.py", line 27, in handler_single_msg
    WechatChannel().handle(msg)
  File "/home/chatgpt/bot-on-anything/channel/wechat/wechat_channel.py", line 53, in handle
    other_user_id = msg['User']['UserName']     # 对手方id
KeyError: 'UserName'

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "/home/chatgpt/bot-on-anything/channel/wechat/wechat_channel.py", line 27, in handler_single_msg
    WechatChannel().handle(msg)
  File "/home/chatgpt/bot-on-anything/channel/wechat/wechat_channel.py", line 53, in handle
    other_user_id = msg['User']['UserName']     # 对手方id
KeyError: 'UserName'

KeyError: 'UserName'Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "/home/chatgpt/bot-on-anything/channel/wechat/wechat_channel.py", line 27, in handler_single_msg
    WechatChannel().handle(msg)
  File "/home/chatgpt/bot-on-anything/channel/wechat/wechat_channel.py", line 53, in handle
    other_user_id = msg['User']['UserName']     # 对手方id
KeyError: 'UserName'


请问解决了嘛？我也遇到了
