### ISSUE TITLE
关于hello插件的几个问题

### ISSUE THREAD

**Issue by spacex-3** [zhayujie/chatgpt-on-wechat#2282]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

拉A进群，自动发送欢迎语
进程卡死

### 问题描述 😯

问题1: 如上所示，会卡死，debug没有消息
问题2: 停止cow会有报错，错误如下：

### 终端日志 📒

```log
[WARNING][2024-09-02 21:47:40][wechat_message.py:36] - 机器人加入群聊消息，不处理~
[WARNING][2024-09-02 21:47:40][wechat_message.py:109] - [WX]get other_user_id failed: 'NickName'
[DEBUG][2024-09-02 21:47:40][wechat_channel.py:204] - [WX]receive group msg: None
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 47, in handler_group_msg
    WechatChannel().handle_group(cmsg)
  File "/root/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 65, in wrapper
    return func(self, cmsg)
           ^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 205, in handle_group
    context = self._compose_context(cmsg.ctype, cmsg.content, isgroup=True, msg=cmsg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 64, in _compose_context
    check_contain(group_name, group_name_keyword_white_list),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 394, in check_contain
    if content.find(ky) != -1:
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

[DEBUG][2024-09-02 21:47:41][wechat_channel.py:197] - [WX]receive note msg: "***"邀请"***"加入了群聊
[DEBUG][2024-09-02 21:47:41][wechat_channel.py:204] - [WX]receive group msg: None
[DEBUG][2024-09-02 21:47:41][chat_channel.py:345] - [chat_channel] consume context: Context(type=JOIN_GROUP, content="***"邀请"***"加入了群聊, kwargs={'isgroup': True,
 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x7c92b46440d0>, 'origin_ctype': <ContextType.JOIN_GROUP: 20>, 'openai_api_key': None, 'gpt_model': None, 's
ession_id': '@7ec22cd21d453e9c6435028da201a14461c44b9466ba5b79f9ecebaa304345e8', 'receiver': '@@838b5a01451a53a09317525ab09083155b5eecaa5ad29610d44bae24ebc20931'})
[DEBUG][2024-09-02 21:47:41][chat_channel.py:168] - [chat_channel] ready to handle context: Context(type=JOIN_GROUP, content="***"邀请"***"加入了群聊, kwargs={'isgroup
': True, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x7c92b46440d0>, 'origin_ctype': <ContextType.JOIN_GROUP: 20>, 'openai_api_key': None, 'gpt_model': 
None, 'session_id': '@7ec22cd21d453e9c6435028da201a14461c44b9466ba5b79f9ecebaa304345e8', 'receiver': '@@838b5a01451a53a09317525ab09083155b5eecaa5ad29610d44bae24ebc20931'})
[DEBUG][2024-09-02 21:47:41][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-09-02 21:47:41][plugin_manager.py:189] - Plugin SUM4ALL triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-09-02 21:47:41][plugin_manager.py:189] - Plugin SUM4ALL triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-09-02 21:47:41][plugin_manager.py:189] - Plugin HELLO triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-09-02 21:47:41][plugin_manager.py:194] - Plugin HELLO breaked event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-09-02 21:47:41][chat_channel.py:172] - [chat_channel] ready to decorate reply: Reply(type=TEXT, content=欢迎加入“AI助理”交流群！🎉



[INFO][2024-09-02 22:03:46][config.py:232] - [Config] User datas saved.
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 36, in handler_single_msg
    WechatChannel().handle_single(cmsg)
  File "/root/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 65, in wrapper
    return func(self, cmsg)
           ^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 185, in handle_single
    self.produce(context)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 324, in produce
    with self.lock:
  File "/root/chatgpt-on-wechat/app.py", line 22, in func
    return old_handler(_signo, _stack_frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

[DEBUG][2024-09-02 22:03:46][wechat_channel.py:197] - [WX]receive note msg: "***"邀请"***"加入了群聊
^C[INFO][2024-09-02 22:03:46][app.py:19] - signal 2 received, exiting...
[INFO][2024-09-02 22:03:46][config.py:232] - [Config] User datas saved.
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 47, in handler_group_msg
    WechatChannel().handle_group(cmsg)
  File "/root/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 65, in wrapper
    return func(self, cmsg)
           ^^^^^^^^^^^^^^^^           
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 207, in handle_group
    self.produce(context)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 324, in produce
    with self.lock:
  File "/root/chatgpt-on-wechat/app.py", line 22, in func
    return old_handler(_signo, _stack_frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

[DEBUG][2024-09-02 22:03:46][wechat_channel.py:204] - [WX]receive group msg: None
^C[INFO][2024-09-02 22:03:47][app.py:19] - signal 2 received, exiting...
[INFO][2024-09-02 22:03:47][config.py:232] - [Config] User datas saved.
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 47, in handler_group_msg
    WechatChannel().handle_group(cmsg)
  File "/root/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 65, in wrapper
    return func(self, cmsg)
           ^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 207, in handle_group
    self.produce(context)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 324, in produce
    with self.lock:
  File "/root/chatgpt-on-wechat/app.py", line 22, in func
    return old_handler(_signo, _stack_frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt  
```

**Comment by 6vision** [comment]
换个微信号试试

**Comment by spacex-3** [comment]
从py3.11换成3.8貌似没啥问题了。

另外想问问有没有一个插件可以做到如果机器人卡死了则自动发消息给指定的人（虽然卡死了但是还是坚持发消息出去说自己卡死了\(//∇//)\）

**Comment by 6vision** [comment]
> 从py3.11换成3.8貌似没啥问题了。
> 
> 另外想问问有没有一个插件可以做到如果机器人卡死了则自动发消息给指定的人（虽然卡死了但是还是坚持发消息出去说自己卡死了(//∇//)\）

卡死了，怎么还能继续发消息（手动狗头

**Comment by spacex-3** [comment]
File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 50, in handler_group_msg
    WechatChannel().handle_group(cmsg)
  File "/root/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 68, in wrapper
    return func(self, cmsg)
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 210, in handle_group
    self.produce(context)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 324, in produce
    with self.lock:
  File "/root/chatgpt-on-wechat/app.py", line 23, in func
    sys.exit(0)
SystemExit: 0


不定时卡死，还是有这个日志存在，哭了 @6vision 

> > 从py3.11换成3.8貌似没啥问题了。
> > 另外想问问有没有一个插件可以做到如果机器人卡死了则自动发消息给指定的人（虽然卡死了但是还是坚持发消息出去说自己卡死了(//∇//)\）
> 
> 卡死了，怎么还能继续发消息（手动狗头
