### ISSUE TITLE
通义千问视觉理解大模型Qwen-VL接入错误，正确方法应该如何做？

### ISSUE THREAD

**Issue by Realybig** [zhayujie/chatgpt-on-wechat#2287]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

other

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

1、在 `common/const.py` 的 `MODEL_LIST` 中加入 `qwen-vl-max-0809`
2、在 `config.json` 中加入
```
"model": "qwen-vl-max-0809",
"dashscope_api_key": "sk-dae2*******9cb4**********94bfd097a",
"bot_type": "dashscope",
```
然后正常运行，出现下面问题

### 问题描述 😯

```bash
Start auto replying.
[INFO][2024-09-05 00:33:49][bridge.py:68] - create bot dashscope for chat
[INFO][2024-09-05 00:33:49][dashscope_bot.py:35] - [DASHSCOPE] query=你是什么模型
[ERROR][2024-09-05 00:33:49][dashscope_bot.py:111] - 'qwen-vl-max-0809'
Traceback (most recent call last):
  File "/Users/olivia/MyObjects/2024Projects/project-jobs/chatgpt-on-wechat/bot/dashscope/dashscope_bot.py", line 87, in reply_text
    dashscope_models[self.model_name],
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'qwen-vl-max-0809'
[ERROR][2024-09-05 00:33:49][dashscope_bot.py:111] - 'qwen-vl-max-0809'
Traceback (most recent call last):
  File "/Users/olivia/MyObjects/2024Projects/project-jobs/chatgpt-on-wechat/bot/dashscope/dashscope_bot.py", line 87, in reply_text
    dashscope_models[self.model_name],
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'qwen-vl-max-0809'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olivia/MyObjects/2024Projects/project-jobs/chatgpt-on-wechat/bot/dashscope/dashscope_bot.py", line 87, in reply_text
    dashscope_models[self.model_name],
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'qwen-vl-max-0809'
[ERROR][2024-09-05 00:33:49][dashscope_bot.py:111] - 'qwen-vl-max-0809'
Traceback (most recent call last):
  File "/Users/olivia/MyObjects/2024Projects/project-jobs/chatgpt-on-wechat/bot/dashscope/dashscope_bot.py", line 87, in reply_text
    dashscope_models[self.model_name],
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'qwen-vl-max-0809'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olivia/MyObjects/2024Projects/project-jobs/chatgpt-on-wechat/bot/dashscope/dashscope_bot.py", line 87, in reply_text
    dashscope_models[self.model_name],
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'qwen-vl-max-0809'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olivia/MyObjects/2024Projects/project-jobs/chatgpt-on-wechat/bot/dashscope/dashscope_bot.py", line 87, in reply_text
    dashscope_models[self.model_name],
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'qwen-vl-max-0809'
[INFO][2024-09-05 00:33:50][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我现在有点累了，等会再来吧), receiver=@499d064443454444a603fde46487d837
Unexpected sync check result: window.synccheck={retcode:"1102",selector:"0"}
^C[INFO][2024-09-05 09:36:44][app.py:19] - signal 2 received, exiting...
[INFO][2024-09-05 09:36:44][config.py:234] - [Config] User datas saved.
Traceback (most recent call last):
  File "/Users/olivia/MyObjects/2024Projects/project-jobs/chatgpt-on-wechat/app.py", line 71, in <module>
    run()
  File "/Users/olivia/MyObjects/2024Projects/project-jobs/chatgpt-on-wechat/app.py", line 64, in run
    time.sleep(1)
  File "/Users/olivia/MyObjects/2024Projects/project-jobs/chatgpt-on-wechat/app.py", line 22, in func
    return old_handler(_signo, _stack_frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by 6vision** [comment]
还不支持qwen的视觉模型

**Comment by ejohnyu** [comment]
const.py里没有这个模型
