### ISSUE TITLE
win10在 PowerShell 中使用Start-Job后台运行 Python 问题

### ISSUE THREAD

**Issue by mi-zy** [zhayujie/chatgpt-on-wechat#2296]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

Start-Job -ScriptBlock {cd E:\chatgpt-on-wechat-master ; python.exe app.py} -Name "cow" 
微信登录正常，聊天时没有回复，日志报错：
[ERROR][2024-09-10 10:02:02][wechat_channel.py:135] - 'gbk' codec can't encode character '\u2580' in position 0: illegal multibyte sequence

### 问题描述 😯

![11](https://github.com/user-attachments/assets/5c42023c-650e-4452-8dad-4090f369515a)

### 终端日志 📒

```log
█[ERROR][2024-09-10 10:30:53][wechat_channel.py:135] - 'gbk' codec can't encode character '\u2580' in position 0: illegal multibyte sequence
Traceback (most recent call last):
  File "E:\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 121, in startup
    itchat.auto_login(
  File "E:\chatgpt-on-wechat-master\lib\itchat\components\register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "E:\chatgpt-on-wechat-master\lib\itchat\components\login.py", line 56, in login
    qrStorage = self.get_QR(enableCmdQR=enableCmdQR,
  File "E:\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 103, in qrCallback
    qr.print_ascii(invert=True)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\qrcode\main.py", line 329, in print_ascii
    out.write(codes[pos])
UnicodeEncodeError: 'gbk' codec can't encode character '\u2580' in position 0: illegal multibyte sequence
```

**Comment by mi-zy** [comment]
\channel\wechat\wechat_channel.py", line 103, in qrCallback

   qr.print_ascii(invert=True)  注释掉这行就好了
