### ISSUE TITLE
微信登录报错，手机扫码确认后无法读取联系人信息。

### ISSUE THREAD

**Issue by wisevisioninc** [zhayujie/chatgpt-on-wechat#2299]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

微信登录报错，手机扫码确认后无法读取联系人信息。
Loading the contact, this may take a little while.
[ERROR][2024-09-12 10:27:54][wechat_channel.py:138] - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/jerry/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 124, in startup
    itchat.auto_login(
  File "/home/jerry/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/home/jerry/chatgpt-on-wechat/lib/itchat/components/login.py", line 84, in login
    self.get_contact(True)
  File "/home/jerry/chatgpt-on-wechat/lib/itchat/components/contact.py", line 300, in get_contact
    seq, batchMemberList = _get_contact(seq)
                           ^^^^^^^^^^^^^^^^^
  File "/home/jerry/chatgpt-on-wechat/lib/itchat/components/contact.py", line 296, in _get_contact
    j = json.loads(r.content.decode('utf-8', 'replace'))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/miniconda3/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/miniconda3/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/miniconda3/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### 终端日志 📒

```log
Loading the contact, this may take a little while.
[ERROR][2024-09-12 10:27:54][wechat_channel.py:138] - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/jerry/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 124, in startup
    itchat.auto_login(
  File "/home/jerry/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/home/jerry/chatgpt-on-wechat/lib/itchat/components/login.py", line 84, in login
    self.get_contact(True)
  File "/home/jerry/chatgpt-on-wechat/lib/itchat/components/contact.py", line 300, in get_contact
    seq, batchMemberList = _get_contact(seq)
                           ^^^^^^^^^^^^^^^^^
  File "/home/jerry/chatgpt-on-wechat/lib/itchat/components/contact.py", line 296, in _get_contact
    j = json.loads(r.content.decode('utf-8', 'replace'))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/miniconda3/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/miniconda3/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/miniconda3/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by 6vision** [comment]
换个账号微信号试试呢

**Comment by wisevisioninc** [comment]
其他账号可以，就是群多的账号就报错，无法获取联系方式。

**Comment by 6vision** [comment]
> 其他账号可以，就是群多的账号就报错，无法获取联系方式。

暂时没复现，大概多少个群以上可以复现？

**Comment by wisevisioninc** [comment]
> > 其他账号可以，就是群多的账号就报错，无法获取联系方式。
> 
> 暂时没复现，大概多少个群以上可以复现？

500-1000的群，都无法正常运行repo代码。

**Comment by 6vision** [comment]
> > > 其他账号可以，就是群多的账号就报错，无法获取联系方式。
> > 
> > 
> > 暂时没复现，大概多少个群以上可以复现？
> 
> 500-1000的群，都无法正常运行repo代码。

这是企微群还是微信群，可以500人以上？

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
