### ISSUE TITLE
接口似乎报错?

### ISSUE THREAD

**Issue by tangrufeii** [zhayujie/chatgpt-on-wechat#2321]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

正常windows启动,配置的企业微似乎没有扫码过程

### 问题描述 😯

企业微信

<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">class 'UnicodeDecodeError'&gt; at /wxcomapp</h1><h2 style="padding: 0px; margin: 0px 0px 0.8em; font-weight: normal; color: rgb(102, 102, 102); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">'gbk' codec can't decode byte 0xad in position 2745: illegal multibyte sequence</h2>
Python | C:\Users\Ts\AppData\Local\Programs\Python\Python38\lib\site-packages\web\debugerror.py in _get_lines_from_file, line 246
-- | --
GET http://localhost:9898/wxcomapp

</body>
</html>

### 终端日志 📒

企业微信

<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">class 'UnicodeDecodeError'&gt; at /wxcomapp</h1><h2 style="padding: 0px; margin: 0px 0px 0.8em; font-weight: normal; color: rgb(102, 102, 102); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">'gbk' codec can't decode byte 0xad in position 2745: illegal multibyte sequence</h2>
Python | C:\Users\Ts\AppData\Local\Programs\Python\Python38\lib\site-packages\web\debugerror.py in _get_lines_from_file, line 246
-- | --
GET http://localhost:9898/wxcomapp

</body>
</html>

**Comment by tangrufeii** [comment]
Traceback (most recent call last):
  File "C:\Users\Ts\AppData\Local\Programs\Python\Python38\lib\site-packages\web\application.py", line 280, in process
    return self.handle()
  File "C:\Users\Ts\AppData\Local\Programs\Python\Python38\lib\site-packages\web\application.py", line 271, in handle
    return self._delegate(fn, self.fvars, args)
  File "C:\Users\Ts\AppData\Local\Programs\Python\Python38\lib\site-packages\web\application.py", line 517, in _delegate
    return handle_class(cls)
  File "C:\Users\Ts\AppData\Local\Programs\Python\Python38\lib\site-packages\web\application.py", line 495, in handle_class
    return tocall(*args)
  File "D:\code\chatgpt-on-wechat\channel\wechatcom\wechatcomapp_channel.py", line 141, in GET
    signature = params.msg_signature
  File "C:\Users\Ts\AppData\Local\Programs\Python\Python38\lib\site-packages\web\utils.py", line 106, in __getattr__
    raise AttributeError(k)
AttributeError: 'msg_signature'

During handling of the above exception, another exception occurred:

**Comment by tangrufeii** [comment]
[INFO][2024-09-28 03:21:30][wechatcomapp_channel.py:153] - [wechatcom] receive params: <Storage {'nonce': '1727164274', 'msg_signature': 'e699f0546dcc90ad60eba035a0bb17fbc682ef8e', 'timestamp': '1727464889'}>
14.116.241.251:27298 - - [28/Sep/2024 03:21:30] "HTTP/1.1 POST /wxcomapp" - 200 OK
[INFO][2024-09-28 03:21:43][wechatcomapp_channel.py:153] - [wechatcom] receive params: <Storage {'nonce': '1727404985', 'msg_signature': '352e150055a1c2d34829e0977f5604e601747305', 'timestamp': '1727464903'}>
[INFO][2024-09-28 03:21:46][wechatcomapp_channel.py:153] - [wechatcom] receive params: <Storage {'nonce': '1727289138', 'msg_signature': '1ee132fcc48351b4c52f9773aac1245853977466', 'timestamp': '1727464905'}>
[INFO][2024-09-28 03:21:49][wechatcomapp_channel.py:153] - [wechatcom] receive params: <Storage {'nonce': '1727404985', 'msg_signature': '352e150055a1c2d34829e0977f5604e601747305', 'timestamp': '1727464903'}>
[INFO][2024-09-28 03:21:51][wechatcomapp_channel.py:153] - [wechatcom] receive params: <Storage {'nonce': '1727289138', 'msg_signature': '1ee132fcc48351b4c52f9773aac1245853977466', 'timestamp': '1727464905'}>
[INFO][2024-09-28 03:21:54][wechatcomapp_channel.py:153] - [wechatcom] receive params: <Storage {'nonce': '1727404985', 'msg_signature': '352e150055a1c2d34829e0977f5604e601747305', 'timestamp': '1727464903'}>
[INFO][2024-09-28 03:21:56][wechatcomapp_channel.py:153] - [wechatcom] receive params: <Storage {'nonce': '1727289138', 'msg_signature': '1ee132fcc48351b4c52f9773aac1245853977466', 'timestamp': '1727464905'}>好像没问题但是似乎不回复
