### ISSUE TITLE
二维码无法正常显示

### ISSUE THREAD

**Issue by Sakura200603** [zhayujie/chatgpt-on-wechat#2331]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

配置好之后启动app.py
![c3968694-1207-4356-97bc-42a5f398ee8b](https://github.com/user-attachments/assets/17eb4a2b-a6c9-4c2a-b159-a1676244a085)

### 问题描述 😯

![image](https://github.com/user-attachments/assets/602f3b1b-b582-4cf3-bfe6-60c53f2c5e67
![c3968694-1207-4356-97bc-42a5f398ee8b](https://github.com/user-attachments/assets/9326b024-a12c-42db-9c65-3125d9e58642)

二维码显示不出来，我尝试了linux服务器，也是同样的情况
![c3968694-1207-4356-97bc-42a5f398ee8b](https://github.com/user-attachments/assets/48988a3d-4f63-496f-a73c-272b7b590f07)

### 终端日志 📒

📁 BASE_DIR: /root/chatgpt-on-wechat
🚀 准备启动项目...
🚀 正在启动 ChatGPT-on-WeChat (Linux)...
[INFO][2024-10-08 12:24:26][godcmd.py:210] - [Godcmd] inited
[INFO][2024-10-08 12:24:26][keyword.py:40] - [keyword] {}
[INFO][2024-10-08 12:24:26][keyword.py:42] - [keyword] inited.
[WARNING][2024-10-08 12:24:26][banwords.py:54] - [Banwords] init failed, ignore or see https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/banwords .
[WARNING][2024-10-08 12:24:26][plugin_manager.py:150] - Failed to init BANWORDS, diabled. [Errno 2] No such file or directory: '/root/chatgpt-on-wechat/plugins/banwords/banwords.txt'
[INFO][2024-10-08 12:24:26][linkai.py:35] - [LinkAI] inited, config={'group_app_map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'group_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}}
[INFO][2024-10-08 12:24:26][role.py:69] - [Role] inited
[INFO][2024-10-08 12:24:26][dungeon.py:56] - [Dungeon] inited
[WARNING][2024-10-08 12:24:26][bdunit.py:42] - [BDunit] init failed, ignore 
[WARNING][2024-10-08 12:24:26][plugin_manager.py:150] - Failed to init BDUNIT, diabled. config.json not found
[INFO][2024-10-08 12:24:26][hello.py:38] - [Hello] inited
[INFO][2024-10-08 12:24:26][finish.py:23] - [Finish] inited
Ready to login.
Getting uuid of QR code.
Downloading QR code.
[ERROR][2024-10-08 12:24:26][wechat_channel.py:138] - No module named 'png'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 124, in startup
    itchat.auto_login(
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 56, in login
    qrStorage = self.get_QR(enableCmdQR=enableCmdQR,
  File "/root/chatgpt-on-wechat/lib/itchat/components/login.py", line 130, in get_QR
    qrCode.png(qrStorage, scale=10)
  File "/usr/local/lib/python3.10/dist-packages/pyqrcode/__init__.py", line 462, in png
    builder._png(self.code, self.version, file, scale,
  File "/usr/local/lib/python3.10/dist-packages/pyqrcode/builder.py", line 1266, in _png
    import png
ModuleNotFoundError: No module named 'png'

**Comment by Sakura200603** [comment]
我所有的依赖都安装了

**Comment by Sakura200603** [comment]
解决了，要额外安装pip install pypng，不知道为什么在安装requirements.txt中时候没有，打扰了
