### ISSUE TITLE
语音识别模块和语音模块失败

### ISSUE THREAD

**Issue by TotoQWQ** [zhayujie/chatgpt-on-wechat#2359]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

发送语音后

### 问题描述 😯

语音识别模块和语音模块失败

### 终端日志 📒

[ERROR][2024-10-26 13:35:26][chat_channel.py:303] - Worker return exception: file does not start with RIFF id
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/otserver/chatgpt-on-wechat/channel/chat_channel.py", line 170, in _handle
    reply = self._generate_reply(context)
  File "/home/otserver/chatgpt-on-wechat/channel/chat_channel.py", line 205, in _generate_reply
    reply = super().build_voice_to_text(wav_path)
  File "/home/otserver/chatgpt-on-wechat/channel/channel.py", line 41, in build_voice_to_text
    return Bridge().fetch_voice_to_text(voice_file)
  File "/home/otserver/chatgpt-on-wechat/bridge/bridge.py", line 86, in fetch_voice_to_text
    return self.get_bot("voice_to_text").voiceToText(voiceFile)
  File "/home/otserver/chatgpt-on-wechat/voice/baidu/baidu_voice.py", line 64, in voiceToText
    pcm = get_pcm_from_wav(voice_file)
  File "/home/otserver/chatgpt-on-wechat/voice/audio_convert.py", line 39, in get_pcm_from_wav
    wav = wave.open(wav_path, "rb")
  File "/usr/local/lib/python3.8/wave.py", line 510, in open
    return Wave_read(f)
  File "/usr/local/lib/python3.8/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/local/lib/python3.8/wave.py", line 131, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id

**Comment by 6vision** [comment]
## 需要先安装ffmpeg：

## 在 Linux 上安装 FFmpeg

在 Linux 系统上安装 FFmpeg 的步骤因发行版不同而略有差异。以下是常见的安装方法。

### Ubuntu/Debian 系统
sudo apt update
sudo apt install ffmpeg

#### CentOS 7 及以上版本
sudo yum install epel-release
sudo yum install ffmpeg ffmpeg-devel

### Fedora 系统
sudo dnf install ffmpeg ffmpeg-devel
