### ISSUE TITLE
[CHATGPT] Exception: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by Kevinhuhu** [zhayujie/chatgpt-on-wechat#2369]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

```log
<此处粘贴终端日志>
```[2024-11-02 03:50:25][chat_gpt_bot.py:163] - [CHATGPT] Exception: 'str' object has no attribute 'get'
Traceback (most recent call last):
File "/app/bot/chatgpt/chat_gpt_bot.py", line 131, in reply_text
response = openai.ChatCompletion.create(api_key=api_key, messages=session.messages, **args)
File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
return super().create(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
response, _, api_key = requestor.request(
File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
resp, got_stream = self._interpret_response(result, stream)
File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
self._interpret_response_line(
File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
raise self.handle_error_response(
File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 418, in handle_error_response
error_code=error_data.get("code"),
AttributeError: 'str' object has no attribute 'get'
[INFO][2024-11-02 03:50:25][wechat_channel.py:222] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我现在有点累了，等会再来吧), receiver=@c76395e9d8ffc573474dffc4511f7183

**Comment by 6vision** [comment]
解决了么，看一下openai sdk版本是不是 openai==0.27.8？

**Comment by Ewains** [comment]
我也遇到同样的问题，最新的 clone 的代码，docker 运行，本地运行也是同样的报错。
