### ISSUE TITLE
扫码后报错,拉取不到wxsid

### ISSUE THREAD

**Issue by wufuliang561** [zhayujie/chatgpt-on-wechat#2378]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

直接微信扫码

### 问题描述 😯

就是用微信扫码登录显示keyError

### 终端日志 📒

```log
 [ERROR][2024-11-08 10:26:31][wechat_channel.py:138] - 'wxsid'
chatgpt-on-wechat  | Traceback (most recent call last):
chatgpt-on-wechat  |   File "/app/channel/wechat/wechat_channel.py", line 124, in startup
chatgpt-on-wechat  |     itchat.auto_login(
chatgpt-on-wechat  |   File "/app/lib/itchat/components/register.py", line 38, in auto_login
chatgpt-on-wechat  |     self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
chatgpt-on-wechat  |   File "/app/lib/itchat/components/login.py", line 61, in login
chatgpt-on-wechat  |     status = self.check_login()
chatgpt-on-wechat  |   File "/app/lib/itchat/components/login.py", line 154, in check_login
chatgpt-on-wechat  |     if process_login_info(self, r.text):
chatgpt-on-wechat  |   File "/app/lib/itchat/components/login.py", line 206, in process_login_info
chatgpt-on-wechat  |     core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
chatgpt-on-wechat  | KeyError: 'wxsid'
```

**Comment by 6vision** [comment]
实名认证绑卡，搜一下issue就有了
