### ISSUE TITLE
提示 ImportError: DLL load failed while importing md__mypyc: 找不到指定的程序

### ISSUE THREAD

**Issue by islelea** [zhayujie/chatgpt-on-wechat#238]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装 3.9
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

python3 app.py 执行终端报错

### 终端日志 (如有报错)

```
Traceback (most recent call last):
  File "E:\Users\lele\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\chatgpt-on-wechat\app.py", line 4, in <module>
    from channel import channel_factory
  File "E:\chatgpt-on-wechat\channel\channel_factory.py", line 5, in <module>
    from channel.wechat.wechat_channel import WechatChannel
  File "E:\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 6, in <module>
    import itchat
  File "E:\Users\lele\AppData\Local\Programs\Python\Python39\lib\site-packages\itchat\__init__.py", line 1, in <module>
    from .core import Core
  File "E:\Users\lele\AppData\Local\Programs\Python\Python39\lib\site-packages\itchat\core.py", line 1, in <module>
    import requests
  File "E:\Users\lele\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "E:\Users\lele\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "E:\Users\lele\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "E:\Users\lele\AppData\Local\Programs\Python\Python39\lib\site-packages\charset_normalizer\__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path
  File "E:\Users\lele\AppData\Local\Programs\Python\Python39\lib\site-packages\charset_normalizer\api.py", line 5, in <module>
    from .cd import (
  File "E:\Users\lele\AppData\Local\Programs\Python\Python39\lib\site-packages\charset_normalizer\cd.py", line 9, in <module>
    from .md import is_suspiciously_successive_range
ImportError: DLL load failed while importing md__mypyc: 找不到指定的程序。
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Windows
 - Python版本  ( 执行 `python3 -V` )：     3.9                 
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.0.1 from e:\users\lele\appdata\local\programs\python\python39\lib\site-packages\pip (python 3.9)

**Comment by zhayujie** [comment]
pip3 install chardet 试试
