### ISSUE TITLE
使用glm-4-alltools模型，提示不支持SYNC调用方式

### ISSUE THREAD

**Issue by mela93** [zhayujie/chatgpt-on-wechat#2419]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

将config.json中`"model": "glm-4-alltools",` 运行后发送问题，提示改报错

### 问题描述 😯

日志里提示不支持SYNC调用方式

### 终端日志 📒

```log
[WARNING][2024-12-06 18:37:05][zhipu_ai_session.py:11] - [ZhiPu] `character_desc` can not be empty
--- Logging error ---
Traceback (most recent call last):
  File "/root/cow/bot/zhipuai/zhipuai_bot.py", line 108, in reply_text
    response = self.client.chat.completions.create(messages=session.messages, **args)
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/api_resource/chat/completions.py", line 94, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/core/_http_client.py", line 809, in post
    return cast(ResponseT, self.request(cast_type, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/core/_http_client.py", line 495, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/core/_http_client.py", line 582, in _request
    raise self._make_status_error(err.response) from None
zhipuai.core._errors.APIRequestFailedError: Error code: 400, with error text {"error":{"code":"1212","message":"当前模型不支持SYNC调用方式。"}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/cow/channel/chat_channel.py", line 170, in _handle
    reply = self._generate_reply(context)
  File "/root/cow/channel/chat_channel.py", line 193, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "/root/cow/channel/channel.py", line 38, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/root/cow/bridge/bridge.py", line 83, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "/root/cow/bot/zhipuai/zhipuai_bot.py", line 62, in reply
    reply_content = self.reply_text(session, api_key, args=new_args)
  File "/root/cow/bot/zhipuai/zhipuai_bot.py", line 141, in reply_text
    logger.exception("[ZHIPU_AI] Exception: {}".format(e), e)
Message: '[ZHIPU_AI] Exception: Error code: 400, with error text {"error":{"code":"1212","message":"当前模型不支持SYNC调用方式。"}}'
Arguments: (APIRequestFailedError('Error code: 400, with error text {"error":{"code":"1212","message":"当前模型不支持SYNC调用方式。"}}'),)
--- Logging error ---
Traceback (most recent call last):
  File "/root/cow/bot/zhipuai/zhipuai_bot.py", line 108, in reply_text
    response = self.client.chat.completions.create(messages=session.messages, **args)
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/api_resource/chat/completions.py", line 94, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/core/_http_client.py", line 809, in post
    return cast(ResponseT, self.request(cast_type, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/core/_http_client.py", line 495, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/core/_http_client.py", line 582, in _request
    raise self._make_status_error(err.response) from None
zhipuai.core._errors.APIRequestFailedError: Error code: 400, with error text {"error":{"code":"1212","message":"当前模型不支持SYNC调用方式。"}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/cow/channel/chat_channel.py", line 170, in _handle
    reply = self._generate_reply(context)
  File "/root/cow/channel/chat_channel.py", line 193, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "/root/cow/channel/channel.py", line 38, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/root/cow/bridge/bridge.py", line 83, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "/root/cow/bot/zhipuai/zhipuai_bot.py", line 62, in reply
    reply_content = self.reply_text(session, api_key, args=new_args)
  File "/root/cow/bot/zhipuai/zhipuai_bot.py", line 141, in reply_text
    logger.exception("[ZHIPU_AI] Exception: {}".format(e), e)
Message: '[ZHIPU_AI] Exception: Error code: 400, with error text {"error":{"code":"1212","message":"当前模型不支持SYNC调用方式。"}}'
Arguments: (APIRequestFailedError('Error code: 400, with error text {"error":{"code":"1212","message":"当前模型不支持SYNC调用方式。"}}'),)
```

**Comment by 6vision** [comment]
![image](https://github.com/user-attachments/assets/14493f68-120b-4494-9dd8-50d8cb892040)
`glm-4-alltools`模型要求必须`SSE`模式调用，不支持现在用的同步模式，不好兼容的，后面会先下掉这个模型，可以使用其他模型

**Comment by mela93** [comment]
好的，看到这个模型写在了配置列表里，试用一下，发现报错了，所以反馈。
已经换其他模型用了。
