### ISSUE TITLE
添加对Grok-2的支持

### ISSUE THREAD

**Issue by sr880828** [zhayujie/chatgpt-on-wechat#2428]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

自己定义了Grok-2-1212的配置信息和部分文件修改，但是还是无法正常使用图片创作，在bot对话中encoding的编码一直不正常导致一直在报警告，但是不影响使用

### 举例

[WARNING][2024-12-18 09:11:43][session_manager.py:72] - Exception when counting tokens precisely for prompt: Unknown encoding grok-2-1212

[INFO][2024-12-18 09:08:49][bridge.py:68] - create bot openAI for chat
[INFO][2024-12-18 09:08:49][open_ai_image.py:22] - [OPEN_AI] image_query=一只小鸟带着圣诞帽子在天上翱翔
[ERROR][2024-12-18 09:08:49][open_ai_image.py:43] - 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/chatgpt-on-wechat/bot/openai/open_ai_image.py", line 23, in create_img
    response = openai.Image.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/image.py", line 39, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 418, in handle_error_response
    error_code=error_data.get("code"),
AttributeError: 'str' object has no attribute 'get'

config.json
"open_ai_api_base": "https://api.x.ai/v1",
"model": "grok-2-1212",
"bot_type": "openAI"
"conversation_max_tokens": 131000,

### 动机

Grok-2-1212的模型是业界内比较靠前的，对中文的支持也不错。
x.ai提供的模型画图也不错,最大tokey支持131072，而且费用也不高

**Comment by 6vision** [comment]
`"bot_type": "chatGPT"`  改一下试试

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
