### ISSUE TITLE
扫描二维码后报错App startup failed!

### ISSUE THREAD

**Issue by freshman-hfy** [zhayujie/chatgpt-on-wechat#247]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 终端日志 (如有报错)

```
Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-02-20 21:39:01][app.py:19] - App startup failed!
[ERROR][2023-02-20 21:39:01][app.py:20] - list index out of range
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：linux服务器
 - Python版本  ( 执行 `python3 -V` )：           3.8.10           
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：20.0.2

**Comment by zhilee2023** [comment]
有类似问题，如何解决？

**Comment by freshman-hfy** [comment]
> 有类似问题，如何解决？

我解决了，是因为使用的微信未实名认证的问题。
但成功后的效果感觉不是很好，感觉这个项目应该接的不是真正的chatgpt的API，机器人回答的质量比chatgpt差很多

**Comment by zhilee2023** [comment]
感谢回答，我准备让gpt自己写个程序。
