### ISSUE TITLE
请再问我一次吧

### ISSUE THREAD

**Issue by bboychencan** [zhayujie/chatgpt-on-wechat#253]
[INFO][2023-02-21 15:44:50][open_ai_bot.py:20] - [OPEN_AI] query=吧
[ERROR][2023-02-21 15:44:55][open_ai_bot.py:64] - Internal server error {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}
 500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} {'Date': 'Tue, 21 Feb 2023 07:44:55 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '166', 'Connection': 'keep-alive', 'Vary': 'Origin', 'X-Request-Id': 'bbbcfa735c6c715e8fdd7677b0773558', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'}
Traceback (most recent call last):
  File "/home/lighthouse/chatgpt-on-wechat003/bot/openai/open_ai_bot.py", line 40, in reply_text
    response = openai.Completion.create(
  File "/home/lighthouse/miniconda3/envs/chatgpt-wechat-bot/lib/python3.9/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/lighthouse/miniconda3/envs/chatgpt-wechat-bot/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/lighthouse/miniconda3/envs/chatgpt-wechat-bot/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/lighthouse/miniconda3/envs/chatgpt-wechat-bot/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/lighthouse/miniconda3/envs/chatgpt-wechat-bot/lib/python3.9/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: Internal server error {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}
 500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} {'Date': 'Tue, 21 Feb 2023 07:44:55 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '166', 'Connection': 'keep-alive', 'Vary': 'Origin', 'X-Request-Id': 'bbbcfa735c6c715e8fdd7677b0773558', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'}
[INFO][2023-02-21 15:44:55][wechat_channel.py:103] - [WX] sendMsg=请再问我一次吧, receiver=@0d2b74afb9ab3fc0554dfb5c2e6a05b5

**Comment by OldWang1009** [comment]
我今天也遇到了,上午还是好的

**Comment by Privatexiao** [comment]
我的也出现了这个情况，前一个小时还是好的的

**Comment by jianyanqing** [comment]
> 我的也出现了这个情况，前一个小时还是好的的

me,too

**Comment by beiguoxia** [comment]
我的也出现了这个情况

**Comment by aaaTang** [comment]
me too

**Comment by sorrrrrry** [comment]
我也是酱紫的

**Comment by Mort1f** [comment]
这个是服务器的问题吗？

**Comment by FateEnding** [comment]
same +1 感觉是作者那边的问题

**Comment by jianyanqing** [comment]
“500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} ”，好像是授权报错了，等作者修复吧

**Comment by jiuri0624** [comment]
+10086，

[INFO][2023-02-21 16:54:15][open_ai_bot.py:20] - [OPEN_AI] query=几点啦
[ERROR][2023-02-21 16:54:21][open_ai_bot.py:64] - Internal server error {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}
 500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} {'Date': 'Tue, 21 Feb 2023 08:54:21 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '166', 'Connection': 'keep-alive', 'Vary': 'Origin', 'X-Request-Id': '24c9e592298017fee8f0058bb5bcd46d', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'}
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 48, in reply_text
    stop=["\n\n\n"]
  File "/root/chatgpt-on-wechat/env/lib/python3.7/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/root/chatgpt-on-wechat/env/lib/python3.7/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 160, in create
    request_timeout=request_timeout,
  File "/root/chatgpt-on-wechat/env/lib/python3.7/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/root/chatgpt-on-wechat/env/lib/python3.7/site-packages/openai/api_requestor.py", line 623, in _interpret_response
    stream=False,
  File "/root/chatgpt-on-wechat/env/lib/python3.7/site-packages/openai/api_requestor.py", line 680, in _interpret_response_line
    rbody, rcode, resp.data, rheaders, stream_error=stream_error
openai.error.APIError: Internal server error {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}
 500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} {'Date': 'Tue, 21 Feb 2023 08:54:21 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '166', 'Connection': 'keep-alive', 'Vary': 'Origin', 'X-Request-Id': '24c9e592298017fee8f0058bb5bcd46d', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'}
[INFO][2023-02-21 16:54:21][wechat_channel.py:103] - [WX] sendMsg=请再问我一次吧, receiver=@838a0ec4f68691027124e70f55c30251

**Comment by Wsmachilus** [comment]
好像是chatgpt的服务器满负荷了

**Comment by Tonyfreeman1** [comment]
![image](https://user-images.githubusercontent.com/125958786/220312919-d93b384c-4d21-4c99-9aaf-eeaa2b3fc7fb.png)

**Comment by zhayujie** [comment]
openai接口问题，现在已经恢复了
