### ISSUE TITLE
扫码登录报错

### ISSUE THREAD

**Issue by QWQ2022** [zhayujie/chatgpt-on-wechat#267]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
扫码登录微信后报错，盲猜itchat问题

### 终端日志 (如有报错)
[ERROR][2023-02-23 22:11:08][app.py:19] - App startup failed!
[ERROR][2023-02-23 22:11:08][app.py:20] - 'wxsid'
Traceback (most recent call last):
  File "/storage/emulated/0/1/chatgpt-on-wechat-1.0.2/app.py", line 17, in <module>
    channel.startup()
  File "/storage/emulated/0/1/chatgpt-on-wechat-1.0.2/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/itchat/components/login.py", line 55, in login
    status = self.check_login()
             ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/itchat/components/login.py", line 141, in check_login
    if process_login_info(self, r.text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/itchat/components/login.py", line 183, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
                                                                     ~~~~~~~^^^^^^^^^
KeyError: 'wxsid'



### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Android Termux
 - Python版本  ( 执行 `python3 -V` )：   3.11.2           
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：23.0.1

**Comment by zhayujie** [comment]
首先看下 itchat-uos 有没有安装, 执行：

pip3 show itchat-uos     # 应该显示已安装
pip3 show itchat   # 不应该显示

如果都正常，考虑是python版本太高，换一个低一点的

**Comment by Luuuuuuuuu1** [comment]
我downgrade我的python到3.7.
itchat-uos 也install了
还是一样的报错代码
请问是否是因为运行的网络环境需要在国内？ 我人在美国这边

**Comment by zhayujie** [comment]
> 我downgrade我的python到3.7. itchat-uos 也install了 还是一样的报错代码 请问是否是因为运行的网络环境需要在国内？ 我人在美国这边

是的需要国内

**Comment by GriMu** [comment]
您好，我也是这个错误，有找到解决办法吗 @QWQ2022
