### ISSUE TITLE
安卓手机登录，提示异地登录，继续登录会话，是不是要支持该部分逻辑

### ISSUE THREAD

**Issue by nothingorsomething** [zhayujie/chatgpt-on-wechat#270]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
安卓手机扫描后，异地登录，点击继续登录后无法正常使用，大佬后续是否支持这快逻辑

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
``[ERROR][2023-02-23 22:28:17][app.py:19] - App startup failed!
[ERROR][2023-02-23 22:28:17][app.py:20] - ('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 304, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: HTTP/1.1 0 -^M




### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
正常就会出现异地登录并确认的。  网络正常吗，国内环境没开代理吧？

**Comment by nothingorsomething** [comment]
> 正常就会出现异地登录并确认的。 网络正常吗，国内环境没开代理吧？

网络正常，拿苹果手机测试不会出现异地登录确认，但是安卓换了三四个手机，都会出现异地登录并确认按钮，点击后，无任何反应，出现图上报错信息
