### ISSUE TITLE
 [ERROR][2023-02-26 23:04:10][app.py:19] - App startup failed! [ERROR][2023-02-26 23:04:10]

### ISSUE THREAD

**Issue by LeoQian1** [zhayujie/chatgpt-on-wechat#284]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]

Please press confirm on your phone.
[ERROR][2023-02-26 23:04:10][app.py:19] - App startup failed!
[ERROR][2023-02-26 23:04:10][app.py:20] - list index out of range
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/itchat/components/login.py", line 152, in check_login
    if process_login_info(self, r.text):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/itchat/components/login.py", line 197, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range



### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
账号有实名吗

**Comment by JIAOJIAOMEI** [comment]
我也遇到这个问题了，账号是实名了的，而且也运行成功了，再次deploy就出现了这个问题
