### ISSUE TITLE
openai安装失败

### ISSUE THREAD

**Issue by Runaway00** [zhayujie/chatgpt-on-wechat#30]
[ERROR][2023-01-11 14:30:16][wechat_channel.py:115] - No module named 'openai'
Traceback (most recent call last):
  File "/root/chatgpt/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 111, in _do_send
    reply_text = super().build_reply_content(query, context).strip()
  File "/root/chatgpt/chatgpt-on-wechat/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/root/chatgpt/chatgpt-on-wechat/bridge/bridge.py", line 9, in fetch_reply_content
    return bot_factory.create_bot("openAI").reply(query, context)
  File "/root/chatgpt/chatgpt-on-wechat/bot/bot_factory.py", line 24, in create_bot
    from bot.openai.open_ai_bot import OpenAIBot
  File "/root/chatgpt/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 6, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

（这是一个错误消息，表明程序正在运行的环境中找不到名为'openai'的模块。
可能是因为 openai python package没有正确安装或者安装的包版本不对导致。或者程序设计中没有正确引用了openai package.
它尝试从/root/chatgpt/chatgpt-on-wechat/bot/openai/open_ai_bot.py文件中引用了openai package 但是它没有找到。
建议检查 openai package 是否已经正确安装，并确保程序正确地引用了这个包.）

**Comment by zhayujie** [comment]
openai有安装在你用于运行程序的Python下吗

假设你通过 python3.8 app.py 来启动程序，可以运行 python3.8 -m pip install --upgrade openai 来安装openai

**Comment by Runaway00** [comment]
嗯嗯  解决了  谢谢啦
