### ISSUE TITLE
start auto replying后回答“请再问我一次吧”

### ISSUE THREAD

**Issue by yuany3906** [zhayujie/chatgpt-on-wechat#313]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

成功登录微信，显示Start auto replying，微信发送信息，在终端有记录，但是一直不出现结果，最后报错并回复“请再问我一次吧”，求解答谢谢

### 终端日志 (如有报错)

Start auto replying.
[INFO][2023-03-02 22:28:12][chat_gpt_bot.py:19] - [OPEN_AI] query=你是谁
[ERROR][2023-03-02 22:29:15][chat_gpt_bot.py:67] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F843361F10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段 时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Anaconda\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Anaconda\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Anaconda\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Anaconda\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001F843361F10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Anaconda\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F843361F10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失 败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F843361F10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\67445\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 43, in reply_text
    response = openai.ChatCompletion.create(
  File "C:\Anaconda\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Anaconda\lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
  File "C:\Anaconda\lib\site-packages\openai\api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F843361F10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复 或连接的主机没有反应，连接尝试失败。'))
[INFO][2023-03-02 22:29:15][wechat_channel.py:103] - [WX] sendMsg=[bot] 请再问我一次吧

### 环境

 - 操作系统类型  (Windows)：
 - Python版本  ( 执行 `python3.8.8` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 23.0.1`)

**Comment by aqlkzf** [comment]
我也遇到了同样的问题

Traceback (most recent call last):
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1f9e58c9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/openai/api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/requests/adapters.py", line 565, in send    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1f9e58c9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gxzy/code/chatGPT/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 43, in reply_text
    response = openai.ChatCompletion.create(
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/home/gxzy/basic/CONDA/envs/chatGPT/lib/python3.8/site-packages/openai/api_requestor.py", line 528, in request_raw    raise error.APIConnectionError(openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1f9e58c9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by zhayujie** [comment]
see #310
