### ISSUE TITLE
容易报超出4096tokens从而忘记上下文关系

### ISSUE THREAD

**Issue by mymhzm** [zhayujie/chatgpt-on-wechat#325]
### 问题描述

貌似进行多轮对话后，积累下来的内容没有得到清理，从而导致api回答的session发生改变，导致忘记上下文关系。
这是我在玩文字冒险游戏的时候遇到的。

### 终端日志 (如有报错)
Traceback (most recent call last):
  File "C:\Users\jermynhuang\Desktop\chatwechat\chatgpt-on-wechat-master\bot\chatgpt\chat_gpt_bot.py", line 43, in reply_text
    response = openai.ChatCompletion.create(
  File "C:\ProgramData\Anaconda3\envs\chatgpt-on-wechat-master\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\chatgpt-on-wechat-master\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\ProgramData\Anaconda3\envs\chatgpt-on-wechat-master\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\ProgramData\Anaconda3\envs\chatgpt-on-wechat-master\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\ProgramData\Anaconda3\envs\chatgpt-on-wechat-master\lib\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4096 tokens. However, you requested 4112 tokens (2912 in the messages, 1200 in the completion). Please reduce the length of the messages or completion.

**Comment by mymhzm** [comment]
模型：gpt-3.5-turbo

**Comment by zhayujie** [comment]
好的，要优化下

**Comment by zhayujie** [comment]
see #343
