### ISSUE TITLE
app startup failed

### ISSUE THREAD

**Issue by bigmouse0001** [zhayujie/chatgpt-on-wechat#337]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)
Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-03-04 00:29:10][app.py:19] - App startup failed!
[ERROR][2023-03-04 00:29:10][app.py:20] - list index out of range
Traceback (most recent call last):
  File "C:\Users\arisa\Desktop\chatgpt-on-wechat-master\app.py", line 17, in <module>
    channel.startup()
  File "C:\Users\arisa\Desktop\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "D:\python\Lib\site-packages\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "D:\python\Lib\site-packages\itchat\components\login.py", line 60, in login
    status = self.check_login()
             ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\itchat\components\login.py", line 151, in check_login
    if process_login_info(self, r.text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\itchat\components\login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

```
[在此处粘贴终端日志]
```



### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by EnochYe** [comment]
issue里面有类似问题，建议去下面翻一翻

**Comment by zhayujie** [comment]
查看 [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)

考虑是账号没有实名

**Comment by bigmouse0001** [comment]
> 查看 [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)
> 
> 考虑是账号没有实名

绝对实名了，换成python3.7依然报错。

**Comment by delife642859044** [comment]
[ERROR][2023-03-16 15:16:41][app.py:19] - App startup failed!
[ERROR][2023-03-16 15:16:41][app.py:20] - invalid syntax (contact.py, line 377)
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    channel = channel_factory.create_channel("wx")
  File "/root/chatgpt-on-wechat/channel/channel_factory.py", line 12, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 7, in <module>
    import itchat
  File "/usr/local/lib/python3.5/dist-packages/itchat/__init__.py", line 8, in <module>
    from itchat.components import load_components
  File "/usr/local/lib/python3.5/dist-packages/itchat/components/__init__.py", line 1, in <module>
    from .contact import load_contact
  File "/usr/local/lib/python3.5/dist-packages/itchat/components/contact.py", line 377
    url = f"{self.loginInfo['url']}/webwxverifyuser?r={int(time.time())}&pass_ticket={self.loginInfo['pass_ticket']}"
                                                                                                                    ^
SyntaxError: invalid syntax

**Comment by Matrixgo** [comment]
相同的报错，扫码后出现，然后docker就直接挂了，请问有什么解决思路

微信已经实名，在Windows11的ubuntu 22.04.2 LTS上通过docker-compose启动
配置的是Azure的OpenAI


Please press confirm on your phone.
[ERROR][2023-07-05 13:23:41][app.py:52] - App startup failed!
[ERROR][2023-07-05 13:23:41][app.py:53] - HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=ARs12N_nES-jeMZ9@qrticket_0&uuid=oepr5sw==&lang=zh_CN&scan=168859 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8aa90384c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8aa90384c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

**Comment by EnochYe** [comment]
邮件已收到，祝好！
