### ISSUE TITLE
 时不时，微信收不到回复，虽然后台能看到

### ISSUE THREAD

**Issue by alannewlife** [zhayujie/chatgpt-on-wechat#340]
### 前置确认

1. 运行于国内网络环境，开代理（蓝灯 SG）
3.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
4. 在已有 issue 中未搜索到类似问题
5. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

在本地搭建完毕，跑起来了。
发现：
1. 后台时不时会抛出如下异常
2. 时不时，机器人抛出不回复。严格说，虽然后台log中能看到，已经被send出去了，但微信端没有接收到。

这两者是否是一个问题导致？
有处理方法么？

### 终端日志 (如有报错)
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Python39\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=fL/89h27857iLN7r&skey=@crypt_aceaa6b3_42a87091067c2753cea41e6482e08144&pass_ticket=ZMQswj5bPJu2rQ2luMPjSdHlNSvxBCkqsdbA762ZbdCJbd6Rei6FGWvm3hm7QAen (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\itchat\components\login.py", line 296, in maintain_loop
    msgList, contactList = self.get_msg()
  File "C:\Python39\lib\site-packages\itchat\components\login.py", line 383, in get_msg
    r = self.s.post(url, data=json.dumps(data),
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python39\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=fL/89h27857iLN7r&skey=@crypt_aceaa6b3_42a87091067c2753cea41e6482e08144&pass_ticket=ZMQswj5bPJu2rQ2luMPjSdHlNSvxBCkqsdbA762ZbdCJbd6Rei6FGWvm3hm7QAen (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Windows）
 - Python版本  (3.9)：                      
 - pip版本  ( 依赖问题此项必填，执行 `23.0.1`)：

**Comment by TPF2017** [comment]
遇到相同问题，好像部分分段的文本无法发送到微信上

**Comment by liujin163** [comment]
> 很傻的问题，已解决。
> 
> 是开了科学上网后，对于微信的连接不稳。 在代理设置里，把*.qq.com加到不代理的设置中。
> 
> 关闭

您好，我遇到和您一样的问题。
请问你在蓝灯哪里设置的代理把*.qq.com加到不代理的设置中的呀？
