### ISSUE TITLE
Invalid URL (POST /v1/chat/completions)

### ISSUE THREAD

**Issue by Eric0101** [zhayujie/chatgpt-on-wechat#346]
### 前置确认

1. 运行于国内网络环境，未开代理
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
外网服务器，无法访问接口

### 终端日志 (如有报错)
openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/completions)
[INFO][2023-03-04 18:05:57][wechat_channel.py:103] - [WX] sendMsg=[bot] 请再问我一次吧, receiver=@f3f42f5dccd9531716856deb8a27aa2d2c546424d02edd49239a409178d5e0be
[INFO][2023-03-04 18:06:09][chat_gpt_bot.py:20] - [OPEN_AI] query=你是
[ERROR][2023-03-04 18:06:09][chat_gpt_bot.py:68] - Invalid URL (POST /v1/chat/completions)
Traceback (most recent call last):
  File "/opt/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 44, in reply_text
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/completions)
[INFO][2023-03-04 18:06:09][wechat_channel.py:103] - [WX] sendMsg=[bot] 请再问我一次吧, receiver=@f3f42f5dccd9531716856deb8a27aa2d2c546424d02edd49239a409178d5e0be
[INFO][2023-03-04 18:06:28][chat_gpt_bot.py:20] - [OPEN_AI] query=python递归
[ERROR][2023-03-04 18:06:28][chat_gpt_bot.py:68] - Invalid URL (POST /v1/chat/completions)
Traceback (most recent call last):
  File "/opt/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 44, in reply_text
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Eric0101** [comment]
国外服务器，仍然报这个错

**Comment by GZYZhy** [comment]
初次部署时我遇到了相同的问题，在更换新注册的OpenAI账号的API密钥后得到了解决。猜测OpenAI可能不允许某些账户访问GPT-3.5，更换最近注册的账号应该可以解决问题。或者尝试设置指定使用GPT-3而非GPT-3.5(我记得其他issue中有相关教程)也许可行。

**Comment by gkdtube** [comment]
我也遇到一样的问题，但是采用上面方式还是无法解决，依旧报错，我是用是railway部署的，报错如下：
[INFO][2023-03-26 15:29:55][bridge.py:28] - create bot chatGPTOnAzure for chat
[INFO][2023-03-26 15:29:55][chat_gpt_bot.py:32] - [OPEN_AI] query=在吗
[ERROR][2023-03-26 15:29:55][chat_gpt_bot.py:127] - Invalid URL (POST /v1/openai/deployments/gpt-3.5-turbo/chat/completions)
Traceback (most recent call last):
File "/app/bot/chatgpt/chat_gpt_bot.py", line 100, in reply_text
response = openai.ChatCompletion.create(
File "/opt/venv/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
return super().create(*args, **kwargs)
File "/opt/venv/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
response, _, api_key = requestor.request(
File "/opt/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 226, in request
resp, got_stream = self._interpret_response(result, stream)
File "/opt/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 619, in _interpret_response
self._interpret_response_line(
File "/opt/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /v1/openai/deployments/gpt-3.5-turbo/chat/completions)
[INFO][2023-03-26 15:29:55][wechat_channel.py:179] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
请问有什么好办法解决？

**Comment by Fisher1006** [comment]
> 初次部署时我遇到了相同的问题，在更换新注册的 OpenAI 账号的 API 密钥后得到了解决。猜测 OpenAI 可能不允许某些账户访问 GPT-3.5，更换最近注册的账号 (类似免费额度为 5 美元那种）应该可以解决问题。或者尝试设置指定使用 GPT-3 而非 GPT-3.5 (我记得其他 issue 中有相关教程) 也许可行。但以上两种方法不保证能解决这个问题。

换了key果然好了
