### ISSUE TITLE
微信登陆报错

### ISSUE THREAD

**Issue by RichardHYQ** [zhayujie/chatgpt-on-wechat#357]
### 前置确认

1.  阿里云泰国节点
2.  python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 扫码登陆后报错

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
[ERROR][2023-03-05 10:24:34][app.py:19] - App startup failed!
[ERROR][2023-03-05 10:24:34][app.py:20] - list index out of range
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 17, in <module>
    channel.startup()
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/lib/python3.10/dist-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.10/dist-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/usr/local/lib/python3.10/dist-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.10/dist-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range


### 环境

 - 操作系统类型  (Linux)：Ubuntu 22.04
 - Python版本  ( 执行 `python3 -V` )：      root@iZ0jo8iwqmigfgjegs5pr5Z:~# python3 -V
Python 3.10.6                
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by reBiocoder** [comment]
看你用的什么模型，微信容易封号，gpt3.5API国内被墙了，可以用微信订阅号：https://github.com/zhayujie/chatgpt-on-wechat/issues/353

**Comment by lichengzhe** [comment]
要实名认证

**Comment by RichardHYQ** [comment]
好的，多谢，我尝试下
