### ISSUE TITLE
微信登陆失败

### ISSUE THREAD

**Issue by xwj2** [zhayujie/chatgpt-on-wechat#366]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```[ERROR][2023-03-06 11:31:06][app.py:19] - App startup failed!
[ERROR][2023-03-06 11:31:06][app.py:20] - list index out of range
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "C:\Users\XWJ\PycharmProjects\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "D:\py2\lib\site-packages\itchat\components\register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "D:\py2\lib\site-packages\itchat\components\login.py", line 60, in login
    status = self.check_login()
  File "D:\py2\lib\site-packages\itchat\components\login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "D:\py2\lib\site-packages\itchat\components\login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by reBiocoder** [comment]
微信容易封号，gpt3.5API国内被墙了，可以用微信订阅号：https://github.com/zhayujie/chatgpt-on-wechat/issues/353

**Comment by zhayujie** [comment]
看下账号是否实名
