### ISSUE TITLE
运行报错：module 'openai.error' has no attribute 'Timeout'等“找不到属性”问题

### ISSUE THREAD

**Issue by GZYZhy** [zhayujie/chatgpt-on-wechat#367]
### 问题：
成功部署并登陆微信账号后，收到消息时报错：
```
[ERROR][2023-03-06 11:20:51][wechat_channel.py:121] - module 'openai.error' has no attribute 'Timeout'
Traceback (most recent call last):
  File "/opt/chatgpt/bot/chatgpt/chat_gpt_bot.py", line 60, in reply_text
    response = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/chatgpt/channel/wechat/wechat_channel.py", line 117, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "/opt/chatgpt/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/opt/chatgpt/bridge/bridge.py", line 9, in fetch_reply_content
    return bot_factory.create_bot("chatGPT").reply(query, context)
  File "/opt/chatgpt/bot/chatgpt/chat_gpt_bot.py", line 42, in reply
    reply_content = self.reply_text(new_query, from_user_id, 0)
  File "/opt/chatgpt/bot/chatgpt/chat_gpt_bot.py", line 87, in reply_text
    except openai.error.Timeout as e:
AttributeError: module 'openai.error' has no attribute 'Timeout'
```
### 环境

 - 操作系统类型 ：linux-centos7.9
 - Python版本：  python3.6.8                   
 - pip版本：pip 9.0.3
 - 实例中的部署路径:/opt/chatgpt

**Comment by GZYZhy** [comment]
文件部署目录：/opt/chatgpt

**Comment by reBiocoder** [comment]
微信容易封号，gpt3.5API国内被墙了，可以用微信订阅号：https://github.com/zhayujie/chatgpt-on-wechat/issues/353

**Comment by GZYZhy** [comment]
#这是来自邮箱的自动回复邮件#这封邮件证明您的来信已经发送成功，我会尽快阅读您的来信。感谢您的来信，祝您生活愉快！*前往：我的网站了解更多信息*

**Comment by zhayujie** [comment]
更新下openai版本

pip3 install --upgrade openai

**Comment by xBeTe** [comment]
["Requires: Python >=3.7.1"](https://pypi.org/project/openai/0.27.0/) Python 版本 要3.7.1 以上，才能安装 openai 0.27.0 。
