### ISSUE TITLE
本地主机扫码成功登录后，报错"TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by mxjjk** [zhayujie/chatgpt-on-wechat#369]
### 问题描述
按照教程的要求在我的台式机上配置好环境，修改config并且用我的微信扫码登陆后，别人@我发消息无法得到自动回复，并且我用手机回复消息以后终端会报错，报错信息如下：
Login successfully as xxx
Start auto replying.
Traceback (most recent call last):
  File "C:\Users\80495\anaconda3\lib\site-packages\itchat\components\register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "d:\SoftWare\WeChat\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 27, in handler_group_msg
    WechatChannel().handle_group(msg)
  File "d:\SoftWare\WeChat\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 97, in handle_group
    match_prefix = (msg['IsAt'] and not config.get("group_at_off", False)) or self.check_prefix(origin_content, config.get('group_chat_prefix')) \
  File "d:\SoftWare\WeChat\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 158, in check_prefix
    for prefix in prefix_list:
TypeError: 'NoneType' object is not iterable

### 环境

 - 操作系统类型 ：windows11
 - Python版本  :py3.9.13                 
 - pip版本：pip 22.2.2

**Comment by zhayujie** [comment]
看下 config.json 配置文件，是不是有配置遗漏
