### ISSUE TITLE
登录成功接收消息就报错，请大神帮忙看看

### ISSUE THREAD

**Issue by loringee** [zhayujie/chatgpt-on-wechat#38]
Login successfully as ****
Start auto replying.
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/itchat/components/register.py", line 66, in configured_reply
    r = replyFn(msg)
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 21, in handler_single_msg
    WechatChannel().handle(msg)
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 46, in handle
    other_user_id = msg['User']['UserName']     # 对手方id
KeyError: 'User'

**Comment by zhayujie** [comment]
> Login successfully as **** Start auto replying. Traceback (most recent call last): File "/usr/local/python3/lib/python3.9/site-packages/itchat/components/register.py", line 66, in configured_reply r = replyFn(msg) File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 21, in handler_single_msg WechatChannel().handle(msg) File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 46, in handle other_user_id = msg['User']['UserName'] # 对手方id KeyError: 'User'

这个是收到好友私聊消息的时候报错的吗?   多发几次消息观察下日志，如果一直报错可以加下我wx看看

**Comment by loringee** [comment]
是的，每次收到好友消息都会报这个错，我加您微信

**Comment by zhayujie** [comment]
环境问题，国外服务器接收到的微信消息关键字段存在缺失
