### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jiangweiatgithub** [zhayujie/chatgpt-on-wechat#401]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
用了付费ChatGPT API，用一个老微信账户登录没任何，用了10天前新注册的微信账户登录就出现这个问题

### 终端日志 (如有报错)

```
Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-03-08 02:24:15][app.py:19] - App startup failed!
[ERROR][2023-03-08 02:24:15][app.py:20] - list index out of range
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "/home/ec2-user/jw/gpt-on-wechat/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/home/ec2-user/.local/lib/python3.8/site-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/home/ec2-user/.local/lib/python3.8/site-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/home/ec2-user/.local/lib/python3.8/site-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Linux
 - Python版本  ( 执行 `python3 -V` )：3.8.5                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：23.0.1

**Comment by jiangweiatgithub** [comment]
应当是实名认证问题，哈

**Comment by jiangweiatgithub** [comment]
今天又出现这个问题了。昨天被封，通过好友验证找回来了。刚才正常使用了几分钟，现在又不行了。
