### ISSUE TITLE
绘图请求触犯OpenAI的安全检测的时候，错误不能反馈到微信端

### ISSUE THREAD

**Issue by ss1969** [zhayujie/chatgpt-on-wechat#409]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
如果画图请求被拒绝了，微信这边应该给一个提示。

### 终端日志 (如有报错)

```
[INFO][2023-03-09 02:45:23][chat_gpt_bot.py:99] - [OPEN_AI] image_query=欧美小鲜肉帅哥
[ERROR][2023-03-09 02:45:28][chat_gpt_bot.py:117] - Your request was rejected as a result of our safety system.
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 100, in create_img
    response = openai.Image.create(
  File "/usr/lib/python3.10/site-packages/openai/api_resources/image.py", line 36, in create
    response, _, api_key = requestor.request(
  File "/usr/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/lib/python3.10/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Your request was rejected as a result of our safety system.
[ERROR][2023-03-09 02:45:28][wechat_channel.py:144] - name 'Null' is not defined
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 100, in create_img
    response = openai.Image.create(
  File "/usr/lib/python3.10/site-packages/openai/api_resources/image.py", line 36, in create
    response, _, api_key = requestor.request(
  File "/usr/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/lib/python3.10/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Your request was rejected as a result of our safety system.

```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Docker Linux Alpine
 - Python版本  ( 执行 `python3 -V` )：                      3.10
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：跟这个没关系啦

**Comment by ss1969** [comment]
这个能处理吗。。。

**Comment by lanvent** [comment]
现在会报Error
