### ISSUE TITLE
utuntu系统下微信扫码后报错

### ISSUE THREAD

**Issue by ToyYan** [zhayujie/chatgpt-on-wechat#410]
### 问题描述

> 扫描二维码，手机端登录提示成功后，报错。

### 终端日志 (如有报错)

```
[ERROR][2023-03-09 03:16:48][app.py:20] - HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=AWOpisDODMTX2Wnlcsjf3P2s@qrticket_0&uuid=gc7yMlwvYw==&lang=zh_CN&scan=1678331774 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff9d6da2f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7eff9d6da2f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=AWOpisDODMTX2Wnlcsjf3P2s@qrticket_0&uuid=gc7yMlwvYw==&lang=zh_CN&scan=1678331774 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff9d6da2f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ysj/chatgpt-on-wechat/app.py", line 17, in <module>
    channel.startup()
  File "/home/ysj/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 45, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/home/ysj/.local/lib/python3.10/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/home/ysj/.local/lib/python3.10/site-packages/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/home/ysj/.local/lib/python3.10/site-packages/itchat/components/login.py", line 152, in check_login
    if process_login_info(self, r.text):
  File "/home/ysj/.local/lib/python3.10/site-packages/itchat/components/login.py", line 175, in process_login_info
    r = core.s.get(core.loginInfo['url'],
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=AWOpisDODMTX2Wnlcsjf3P2s@qrticket_0&uuid=gc7yMlwvYw==&lang=zh_CN&scan=1678331774 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff9d6da2f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
ysj@ubuntu:~/chatgpt-on-wechat$ 
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by HuiMoon1** [comment]
我也是这样~
