### ISSUE TITLE
API Key不正确

### ISSUE THREAD

**Issue by LEON121** [zhayujie/chatgpt-on-wechat#413]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
配置好API Key使用中提示API Key不正确，但是在其他地方使用这个Key是可以的

### 终端日志 (如有报错)
![image](https://user-images.githubusercontent.com/37445848/223982018-cbeed775-4399-405e-8e7b-6ec1d71e6e58.png)

```
[在此处粘贴终端日志]
```
Login successfully as Leon
Start auto replying.
[INFO][2023-03-09 17:36:30][chat_gpt_bot.py:26] - [OPEN_AI] query=ChatGPT是什么
[ERROR][2023-03-09 17:36:31][chat_gpt_bot.py:93] - Incorrect API key provided: YOUR API KEY. You can find your API key at https://platform.openai.com/account/api-keys.
Traceback (most recent call last):
  File "D:\WeChat2ChatGPT\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 60, in reply_text
    response = openai.ChatCompletion.create(
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: YOUR API KEY. You can find your API key at https://platform.openai.com/account/api-keys.
[INFO][2023-03-09 17:36:32][wechat_channel.py:137] - [WX] sendMsg=[bot] 请再问我一次吧, receiver=filehelper

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：win11
 - Python版本  ( 执行 `python3 -V` )：3.9                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：23.0.1

**Comment by zhayujie** [comment]
config.json 中 api_key 参数未填写
