### ISSUE TITLE
 添加好友的itchat.add_friend找不到 

### ISSUE THREAD

**Issue by chiakileftcang** [zhayujie/chatgpt-on-wechat#418]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "/Volumes/Data/Code/Haoyuan/ChatGPT/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 34, in add_friend
    itchat.add_friend(**msg['Text'])
  File "/usr/local/lib/python3.9/site-packages/itchat/storage/templates.py", line 158, in verify
    return self.core.add_friend(**self.verifyDict)
AttributeError: 'Core' object has no attribute 'add_friend'

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：   3.9                   
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
代码里没有这部分内容，参考 https://github.com/littlecodersh/ItChat
