### ISSUE TITLE
app.py扫码之后登录报错(已解决，实名即可)

### ISSUE THREAD

**Issue by Lhe99** [zhayujie/chatgpt-on-wechat#434]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
可以扫码，但是在手机确认之后就会报错

### 终端日志 (如有报错)
[ERROR][2023-03-11 04:01:42][app.py:19] - App startup failed!
[ERROR][2023-03-11 04:01:42][app.py:20] - list index out of range
Traceback (most recent call last):
  File "/Users/enengegezuibang/Downloads/chatgpt-on-wechat-master/app.py", line 17, in <module>
    channel.startup()
  File "/Users/enengegezuibang/Downloads/chatgpt-on-wechat-master/channel/wechat/wechat_channel.py", line 45, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/Users/enengegezuibang/opt/anaconda3/lib/python3.9/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/enengegezuibang/opt/anaconda3/lib/python3.9/site-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/Users/enengegezuibang/opt/anaconda3/lib/python3.9/site-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/Users/enengegezuibang/opt/anaconda3/lib/python3.9/site-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac)：
 - Python版本  ( 执行 `python3.9` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 （完全按照文章要求）`)：

**Comment by lzqfree** [comment]
app.py扫码之后登录报错(微信实名也报一样的错）

**Comment by lzqfree** [comment]
[ERROR][2023-03-13 11:22:50][app.py:19] - App startup failed!
[ERROR][2023-03-13 11:22:50][app.py:20] - mismatched tag: line 64, column 4
Traceback (most recent call last):
  File "D:\pythoncode\chatgpt-on-wechat-master\app.py", line 17, in <module>
    channel.startup()
  File "D:\pythoncode\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 45, in startup
    itchat.auto_login(enableCmdQR=2)
  File "D:\pythoncode\chatgpt-on-wechat-master\venv\Lib\site-packages\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "D:\pythoncode\chatgpt-on-wechat-master\venv\Lib\site-packages\itchat\components\login.py", line 53, in login
    status = self.check_login()
             ^^^^^^^^^^^^^^^^^^
  File "D:\pythoncode\chatgpt-on-wechat-master\venv\Lib\site-packages\itchat\components\login.py", line 137, in check_login
    if process_login_info(self, r.text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythoncode\chatgpt-on-wechat-master\venv\Lib\site-packages\itchat\components\login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lzqfr\AppData\Local\Programs\Python\Python311\Lib\xml\dom\minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lzqfr\AppData\Local\Programs\Python\Python311\Lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lzqfr\AppData\Local\Programs\Python\Python311\Lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4

Process finished with exit code 0

**Comment by zhayujie** [comment]
@lzqfree 看下这个 #333

**Comment by lzqfree** [comment]
看了#333 都安装上了，还是以下结果

**Comment by lzqfree** [comment]
[ERROR][2023-03-14 12:29:33][app.py:19] - App startup failed!
[ERROR][2023-03-14 12:29:33][app.py:20] - mismatched tag: line 64, column 4
Traceback (most recent call last):
  File "D:\pythoncode\chatgpt-on-wechat-master\app.py", line 17, in <module>
    channel.startup()
  File "D:\pythoncode\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 45, in startup
    itchat.auto_login(enableCmdQR=2)
  File "D:\pythoncode\chatgpt-on-wechat-master\venv\lib\site-packages\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "D:\pythoncode\chatgpt-on-wechat-master\venv\lib\site-packages\itchat\components\login.py", line 54, in login
    status = self.check_login()
  File "D:\pythoncode\chatgpt-on-wechat-master\venv\lib\site-packages\itchat\components\login.py", line 138, in check_login
    if process_login_info(self, r.text):
  File "D:\pythoncode\chatgpt-on-wechat-master\venv\lib\site-packages\itchat\components\login.py", line 173, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "C:\Users\lzqfr\AppData\Local\Programs\Python\Python310\lib\xml\dom\minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
  File "C:\Users\lzqfr\AppData\Local\Programs\Python\Python310\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "C:\Users\lzqfr\AppData\Local\Programs\Python\Python310\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4

Process finished with exit code 0

**Comment by zhayujie** [comment]
@lzqfree  pip3 show itchat 有输出嘛
