### ISSUE TITLE
20230206版启动报错

### ISSUE THREAD

**Issue by firevenus** [zhayujie/chatgpt-on-wechat#46]
Loading the contact, this may take a little while.
[ERROR][2023-02-06 01:14:35][app.py:19] - App startup failed!
[ERROR][2023-02-06 01:14:35][app.py:20] - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/siyan/codes/weai/chatgpt-on-wechat/app.py", line 17, in <module>
    channel.startup()
  File "/Users/siyan/codes/weai/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/itchat/components/login.py", line 81, in login
    self.get_contact(True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/itchat/components/contact.py", line 300, in get_contact
    seq, batchMemberList = _get_contact(seq)
                           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/itchat/components/contact.py", line 296, in _get_contact
    j = json.loads(r.content.decode('utf-8', 'replace'))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zhayujie** [comment]
应该是python版本过高了，可以尝试换一个低版本的 (3.7 ~ 3.9) 的执行看看

**Comment by firevenus** [comment]
换成了3.9.4还是不太行，这个是不是需要微信的联系人少一点？人太多了会不会超时？

**Comment by firevenus** [comment]
Loading the contact, this may take a little while.
[ERROR][2023-02-06 01:58:27][app.py:19] - App startup failed!
[ERROR][2023-02-06 01:58:27][app.py:20] - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/siyan/codes/weai/chatgpt-on-wechat/app.py", line 17, in <module>
    channel.startup()
  File "/Users/siyan/codes/weai/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/Users/siyan/.pyenv/versions/3.9.4/lib/python3.9/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/siyan/.pyenv/versions/3.9.4/lib/python3.9/site-packages/itchat/components/login.py", line 81, in login
    self.get_contact(True)
  File "/Users/siyan/.pyenv/versions/3.9.4/lib/python3.9/site-packages/itchat/components/contact.py", line 300, in get_contact
    seq, batchMemberList = _get_contact(seq)
  File "/Users/siyan/.pyenv/versions/3.9.4/lib/python3.9/site-packages/itchat/components/contact.py", line 296, in _get_contact
    j = json.loads(r.content.decode('utf-8', 'replace'))
  File "/Users/siyan/.pyenv/versions/3.9.4/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/siyan/.pyenv/versions/3.9.4/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/siyan/.pyenv/versions/3.9.4/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zhayujie** [comment]
> 换成了3.9.4还是不太行，这个是不是需要微信的联系人少一点？人太多了会不会超时？

应该和联系人数量没关系，你是在本地启动的吗，用的什么操作系统，  有没有开代理什么的？ 
不行的话可以先加下我，明天一起看下

**Comment by fj9876** [comment]
试下sudo python app.py，我不加sudo启动也报错，加了就OK

**Comment by firevenus** [comment]
加了sudo还是不行啊

**Comment by zhayujie** [comment]
> 加了sudo还是不行啊

网络环境正常吗，在国内不，没开代理吧？
