### ISSUE TITLE
切换微信账号扫码报错

### ISSUE THREAD

**Issue by chrischjh** [zhayujie/chatgpt-on-wechat#470]
### 问题描述

一个微信账号扫码登录成功，可以与chatgpt交互。换个微信账号扫码报错。

### 终端日志 (如有报错)

```
[ERROR][2023-03-15 08:58:23][app.py:20] - list index out of range
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "/opt/.chat/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 45, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 152, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 197, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Ubuntu20.04
 - Python版本  ( 执行 `python3 -V` )：3.8                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：23.0.1

**Comment by nate872** [comment]
我也这样咋办

**Comment by jiangweiatgithub** [comment]
我也是。。。

**Comment by zhayujie** [comment]
这个账号实名了吗

**Comment by nate872** [comment]
> 

已经解决 目前是新创建的微信号这样，用该微信号发消息之后报错，在微信端发送信息解锁限制即可

**Comment by nate872** [comment]
另外问一下怎么设置敏感词不回答啊

**Comment by chrischjh** [comment]
> 这个账号实名了吗

确实是实名问题，已经解决
