### ISSUE TITLE
APP Start Fail，在扫描QR之后，似乎登录建立失败了

### ISSUE THREAD

**Issue by Leceue** [zhayujie/chatgpt-on-wechat#491]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

在扫描二维码之后，初始化失败是什么情况

### 终端日志 (如有报错)

```
[ERROR][2023-03-16 19:16:57][app.py:19] - App startup failed!
[ERROR][2023-03-16 19:16:57][app.py:20] - list index out of range
Traceback (most recent call last):
  File "D:\CodeProject\Interesting Thing\chatgpt-on-wechat\app.py", line 17, in <module>
    channel.startup()
  File "D:\CodeProject\Interesting Thing\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 45, in startup
    itchat.auto_login(enableCmdQR=2)
  File "D:\CodeProject\Interesting Thing\chatgpt-on-wechat\venv\lib\site-packages\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "D:\CodeProject\Interesting Thing\chatgpt-on-wechat\venv\lib\site-packages\itchat\components\login.py", line 61, in login       
    status = self.check_login()
  File "D:\CodeProject\Interesting Thing\chatgpt-on-wechat\venv\lib\site-packages\itchat\components\login.py", line 152, in check_login    if process_login_info(self, r.text):
  File "D:\CodeProject\Interesting Thing\chatgpt-on-wechat\venv\lib\site-packages\itchat\components\login.py", line 198, in process_login_info
    pass_ticket = re.findall(
IndexError: list index out of range
```

### 环境

 - 操作系统类型  Windows：
 - Python版本 Python 3.9.0：                      
 - pip版本  pip 23.0.1：

**Comment by machilus33** [comment]
新微信号需要先实名认证
