### ISSUE TITLE
nohup python3 app.py & tail -f nohup.out  Issue

### ISSUE THREAD

**Issue by kine0808** [zhayujie/chatgpt-on-wechat#494]
### 前置确认

1. 网络能够访问openai接口 [#351](https://github.com/zhayujie/chatgpt-on-wechat/issues/351)  帮瓦工服务器
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装 CentOS9 自带的3.1
3. 在已有 issue 中未搜索到类似问题 未搜索到， 未找到
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
出错在这步
nohup python3 app.py & tail -f nohup.out 

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```
 nohup python3 app.py & tail -f nohup.out
[1] 58762
nohup: ignoring input and appending output to 'nohup.out'
    config.load_config()
  File "/chatgpt-on-wechat/config.py", line 18, in load_config
    config = json.loads(config_str)
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 10 column 25 (char 325)
[ERROR][2023-03-16 10:20:20][app.py:19] - App startup failed!
[ERROR][2023-03-16 10:20:20][app.py:20] - Expecting value: line 10 column 25 (char 325)
Traceback (most recent call last):
  File "/chatgpt-on-wechat/app.py", line 11, in <module>
    config.load_config()
  File "/chatgpt-on-wechat/config.py", line 18, in load_config
    config = json.loads(config_str)
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 10 column 25 (char 325)

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：CentOS
 - Python版本  ( 执行 `python3 -V` )：    Python 3.9.16                  
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 21.2.3 from /usr/lib/python3.9/site-packages/pip (python 3.9)

**Comment by zhangyiw** [comment]
建议把配置贴出来
