### ISSUE TITLE
您好，我这边出现这个报错我有点没办法

### ISSUE THREAD

**Issue by q23339860** [zhayujie/chatgpt-on-wechat#509]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 一直报这个错误很头疼

![image](https://user-images.githubusercontent.com/58033184/226143679-2c3f7879-2bb1-4018-bb95-b76a2c692cba.png)

### 终端日志 (如有报错)

```
[[ERROR][2023-03-19 06:32:11][wechat_channel.py:163] - module 'openai.error' has no attribute 'Timeout'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 66, in reply_text
    response = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 159, in _do_send_text
    reply_text = super().build_reply_content(query, context)
  File "/root/chatgpt-on-wechat/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/root/chatgpt-on-wechat/bridge/bridge.py", line 18, in fetch_reply_content
    return bot_factory.create_bot(bot_type).reply(query, context)
  File "/root/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 48, in reply
    reply_content = self.reply_text(session, session_id, 0)
  File "/root/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 93, in reply_text
    except openai.error.Timeout as e:
AttributeError: module 'openai.error' has no attribute 'Timeout']
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：CentOS 7.9 64bit
 - Python版本  ( 执行 `python3 -V` )：  Python 3.8.15                    
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 21.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

**Comment by tofun666** [comment]
解决了没

**Comment by EnochYe** [comment]
openai的包要更新，readme里面有写openai包版本的要求

**Comment by q23339860** [comment]
> 

执行了多次pip3 --upgrade openai，但是都没看到openai包的版本

**Comment by q23339860** [comment]
执行了多次pip3 install --upgrade openai，但是都没看到openai包的版本

**Comment by q23339860** [comment]
Requirement already satisfied: openai in /usr/local/lib/python3.6/site-packages (0.8.0)

**Comment by zhayujie** [comment]
@q23339860  升级下 pytthon版本到 3.7.1以上， 你目前是 3.6只支持到 0.8.0

**Comment by EnochYe** [comment]
```shell
wget https://files.pythonhosted.org/packages/47/21/d909d8e92d1867f3daeb8d5c40936e3d37e27ad1ae187c754fefeadcbd4f/openai-0.27.2-py3-none-any.whl
```

```shell
pip install ./openai-0.27.2-py3-none-any.whl
```
