### ISSUE TITLE
昨天还可以正常运行 今天重新运行一下就出问题了

### ISSUE THREAD

**Issue by qpqoqp000** [zhayujie/chatgpt-on-wechat#513]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 最后一步运行出错

### 终端日志 (如有报错)

```
nohup: ignoring input and appending output to 'nohup.out'
[ERROR][2023-03-19 03:31:02][app.py:19] - App startup failed!
[ERROR][2023-03-19 03:31:02][app.py:20] - Expecting value: line 10 column 26 (char 342)
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/app.py", line 11, in <module>
    config.load_config()
  File "/root/chatgpt-on-wechat/config.py", line 18, in load_config
    config = json.loads(config_str)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 10 column 26 (char 342)

```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：linux
 - Python版本  ( 执行 `python3 -V` )： 3.10.6         
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：3.10

**Comment by qpqoqp000** [comment]
我发现是speech_recognition启用后就报错

**Comment by jlynnc** [comment]
你的json某一行写错了，应该就是speech那一行，如果检查没问题的话，那应该就重新git pull一下就行了，我这边是好的

**Comment by qpqoqp000** [comment]
谢谢~

**Comment by qpqoqp000** [comment]
> 你的json某一行写错了，应该就是speech那一行，如果检查没问题的话，那应该就重新git pull一下就行了，我这边是好的

谢谢~
