### ISSUE TITLE
程序已经稳定运行几天，今天突然微信说登陆到期。再重启微信登录后报错index out of range，然后程序logout

### ISSUE THREAD

**Issue by zhangzhanhui** [zhayujie/chatgpt-on-wechat#528]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
微信登录后报错index out of range，然后程序logout
> 简要说明、截图、复现步骤等，也可以是需求或想法
Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-03-20 22:16:00][app.py:19] - App startup failed!
[ERROR][2023-03-20 22:16:00][app.py:20] - list index out of range
Traceback (most recent call last):
  File "/home/jvs086/chatgpt-on-wechat/app.py", line 17, in <module>
    channel.startup()
  File "/home/jvs086/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 45, in startup
    itchat.auto_login(enableCmdQR=2, hotReload=conf().get('hot_reload', False))
  File "/home/jvs086/.local/lib/python3.9/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/home/jvs086/.local/lib/python3.9/site-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/home/jvs086/.local/lib/python3.9/site-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/home/jvs086/.local/lib/python3.9/site-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

### 终端日志 (如有报错)
Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-03-20 22:16:00][app.py:19] - App startup failed!
[ERROR][2023-03-20 22:16:00][app.py:20] - list index out of range
Traceback (most recent call last):
  File "/home/jvs086/chatgpt-on-wechat/app.py", line 17, in <module>
    channel.startup()
  File "/home/jvs086/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 45, in startup
    itchat.auto_login(enableCmdQR=2, hotReload=conf().get('hot_reload', False))
  File "/home/jvs086/.local/lib/python3.9/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/home/jvs086/.local/lib/python3.9/site-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/home/jvs086/.local/lib/python3.9/site-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/home/jvs086/.local/lib/python3.9/site-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：centos8 stream
 - Python版本  ( 执行 `python3 -V` )：   3.9                   
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：20.2.4

**Comment by 1561316811** [comment]
出现同样问题

**Comment by Gyyz** [comment]
今天刚测试，还以为是个老bug，mark一下，等解决

**Comment by maTuaner** [comment]
https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs#5%E7%99%BB%E5%BD%95%E6%8A%A5%E9%94%99-indexerror-list-index-out-of-range

**Comment by zhangzhanhui** [comment]
后来经过验证是由于微信号被临时禁止导致。按提示解禁就好了

**Comment by xionghaizhi** [comment]
果然被封了。。。
