### ISSUE TITLE
稳定性不好,基本都在报错.

### ISSUE THREAD

**Issue by XTeam-Wing** [zhayujie/chatgpt-on-wechat#54]
```
The server had an error while processing your request. Sorry about that!,
```

**Comment by fj9876** [comment]
[ERROR][2023-02-06 21:38:49][open_ai_bot.py:52] - The server had an error while processing your request. Sorry about that!
Traceback (most recent call last):
  File "/home/fujia/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 48, in reply_text
    stop=["#"]
  File "/usr/local/lib/python3.7/dist-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 160, in create
    request_timeout=request_timeout,
  File "/usr/local/lib/python3.7/dist-packages/openai/api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.7/dist-packages/openai/api_requestor.py", line 624, in _interpret_response
    stream=False,
  File "/usr/local/lib/python3.7/dist-packages/openai/api_requestor.py", line 681, in _interpret_response_line
    rbody, rcode, resp.data, rheaders, stream_error=stream_error
openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!
[ERROR][2023-02-06 21:38:49][wechat_channel.py:116] - 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/home/fujia/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 112, in _do_send
    reply_text = super().build_reply_content(query, context).strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by mostlittlebee** [comment]
我这里也有这个情况，看起来是后端openai的api接口不是太稳定。

**Comment by mostlittlebee** [comment]
@zhayujie  是否能实现在发生API后1秒内未报错的情况下，让先回复一次“收到” ，表示正在等待API 回复？  否则不知道是程序报错了还是API速度慢

**Comment by zhayujie** [comment]
> @zhayujie 是否能实现在发生API后1秒内未报错的情况下，让先回复一次“收到” ，表示正在等待API 回复？ 否则不知道是程序报错了还是API速度慢

这样是可行的，不过实现上稍微有点麻烦。

我现在准备加一个报错后的自动重试，如果1次重试还是失败，就自动回复一句

**Comment by fj9876** [comment]
可以加一个自定义重试次数，在配置文件哪里填写参数，超过后在回复设定的回复内容

**Comment by zhayujie** [comment]
See https://github.com/zhayujie/chatgpt-on-wechat/issues/50
