### ISSUE TITLE
能扫码，但是无法登录，是否因为微信不能使用网页版的原因

### ISSUE THREAD

**Issue by xinyonghu2015** [zhayujie/chatgpt-on-wechat#543]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
之前能用，升级3.5后就不行了，能扫码，但是无法登录，是否因为微信不能使用网页版的原因（测试网页版微信提示不能用）？

### 终端日志 (如有报错)

```
[ERROR][2023-03-21 20:35:29][app.py:20] - mismatched tag: line 64, column 4
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "/root/PycharmProjects/pythonProject/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 45, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/root/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/root/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/root/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/itchat/components/login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "/root/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/itchat/components/login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/usr/lib/python3.8/xml/dom/minidom.py", line 1969, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4


```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by adminlove520** [comment]
一样  可能是ichat的锅

**Comment by skymilong** [comment]
有啥解决方案么

**Comment by MakRabbitHole** [comment]
一模一样的错误,

**Comment by zhayujie** [comment]
see #333 

使用 itchat-uos 而不是 itchat
