### ISSUE TITLE
No module named 'VOICE'

### ISSUE THREAD

**Issue by hreatcircu** [zhayujie/chatgpt-on-wechat#545]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
有些包导入不了
![image](https://user-images.githubusercontent.com/128441143/226830071-501311a7-970c-4660-a245-c7518b23a4d8.png)
![image](https://user-images.githubusercontent.com/128441143/226830712-d5ac34ac-d62e-4e79-876d-8f930f3b3a74.png)

### 终端日志 (如有报错)
No module named 'VOICE'
Traceback (most recent call last):
  File "d:\project\chatgpt-on-wechat-master\app.py", line 14, in <module>
    channel = channel_factory.create_channel("wx")
  File "d:\project\chatgpt-on-wechat-master\channel\channel_factory.py", line 12, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "d:\project\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 6, in <module>
    import VOICE as VOICE
ModuleNotFoundError: No module named 'VOICE'
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Windows
 - Python版本  ( 执行 `python3 -V` )：3.9.1                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.0.1

**Comment by hreatcircu** [comment]
> 请问你使用的是哪个版本的代码，好像没有这一句呢
> 
> import VOICE as VOICE

解决了，我下载压缩包解压出来用编辑器打开会多出来这么一行，删掉就可以了，感谢大大提醒！
