### ISSUE TITLE
微信客户端，生成图片指令报错

### ISSUE THREAD

**Issue by 740638339** [zhayujie/chatgpt-on-wechat#553]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中有搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中有类似问题

### 问题描述

有类似问题，不过对方的python 版本号是过高。我这个是3.10也是报错。

指令：“画一个白猫”
结果：报错内容详见日志

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```
[INFO][2023-03-23 11:02:48][chat_gpt_bot.py:114] - [OPEN_AI] image_query=一个白猫
[INFO][2023-03-23 11:02:53][chat_gpt_bot.py:121] - [OPEN_AI] image_url=https://oaidalleapiprodscus.blob.core.windows.net/private/org-48dCRFdPLj6Hh8VXSgQLJOpj/user-RBvkgytGn46Gny3gYogdspxN/img-vkzuJplaSMQ5c9zDcYe5ucGr.png?st=2023-03-23T02%3A02%3A52Z&se=2023-03-23T04%3A02%3A52Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-03-23T02%3A55%3A24Z&ske=2023-03-24T02%3A55%3A24Z&sks=b&skv=2021-08-06&sig=owDQ5bBfezxO7zMY8bXf3Qkx74BKxk9tRuksmEc8HP0%3D
[ERROR][2023-03-23 11:02:55][wechat_channel.py:195] - HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
Traceback (most recent call last):
  File "D:\software\python_3.10\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\software\python_3.10\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\software\python_3.10\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "D:\software\python_3.10\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\software\python_3.10\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\software\python_3.10\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\software\python_3.10\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\software\python_3.10\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\python_3.10\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\software\python_3.10\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\software\python_3.10\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Project\github\wechatbot\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 192, in _do_send_img
    itchat.send_image(image_storage, reply_user_id)
  File "D:\software\python_3.10\lib\site-packages\itchat\components\messages.py", line 424, in send_image
    r = self.upload_file(fileDir, isPicture=not fileDir[-4:] == '.gif', file_=file_)
  File "D:\software\python_3.10\lib\site-packages\itchat\components\messages.py", line 334, in upload_file
    r = upload_chunk_file(self, fileDir, fileSymbol, fileSize,
  File "D:\software\python_3.10\lib\site-packages\itchat\components\messages.py", line 367, in upload_chunk_file
    return core.s.post(url, files=files, headers=headers, timeout=config.TIMEOUT)
  File "D:\software\python_3.10\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\software\python_3.10\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\software\python_3.10\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\software\python_3.10\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='file.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：Python 3.10.6                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.0.1

**Comment by zhayujie** [comment]
访问wx失败，要么是网络连接问题，要么是发送图片的功能被限制了
