### ISSUE TITLE
微信扫码后报错

### ISSUE THREAD

**Issue by cmhello88** [zhayujie/chatgpt-on-wechat#59]
环境描述：
python版本：3.9.13
chatgpt-on-wechat：master分支
具体的错误日志如下：

[ERROR][2023-02-07 09:32:17][app.py:19] - App startup failed!
[ERROR][2023-02-07 09:32:17][app.py:20] - mismatched tag: line 64, column 4
Traceback (most recent call last):
  File "D:\development\python-projects\chatgpt-on-wechat\app.py", line 17, in <module>
    channel.startup()
  File "D:\development\python-projects\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "C:\Users\Administrator\.virtualenvs\chatgpt-on-wechat-4yxyFv2t\lib\site-packages\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "C:\Users\Administrator\.virtualenvs\chatgpt-on-wechat-4yxyFv2t\lib\site-packages\itchat\components\login.py", line 53, in login
    status = self.check_login()
  File "C:\Users\Administrator\.virtualenvs\chatgpt-on-wechat-4yxyFv2t\lib\site-packages\itchat\components\login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "C:\Users\Administrator\.virtualenvs\chatgpt-on-wechat-4yxyFv2t\lib\site-packages\itchat\components\login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "C:\worksoft\scoop\apps\python39\current\lib\xml\dom\minidom.py", line 1998, in parseString
    return expatbuilder.parseString(string)
  File "C:\worksoft\scoop\apps\python39\current\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "C:\worksoft\scoop\apps\python39\current\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4

**Comment by zhayujie** [comment]
看下有装 itchat-uos吗

执行 python3.9 show itchat-uos

**Comment by cmhello88** [comment]
$ pip show itchat-uos
Name: itchat-uos
Version: 1.5.0.dev0
Summary: 复活Itchat, 仅仅需要 pip install itchat-uos, good luck !
Home-page: https://github.com/why2lyj/ItChat-UOS
Author: Snow Wang
Author-email: admin@farseer.vip
License: MIT
Location: c:\users\administrator\.virtualenvs\chatgpt-on-wechat-4yxyfv2t\lib\site-packages
Requires: pypng, pyqrcode, requests
Required-by:

**Comment by zhayujie** [comment]
> $ pip show itchat-uos Name: itchat-uos Version: 1.5.0.dev0 Summary: 复活Itchat, 仅仅需要 pip install itchat-uos, good luck ! Home-page: https://github.com/why2lyj/ItChat-UOS Author: Snow Wang Author-email: [admin@farseer.vip](mailto:admin@farseer.vip) License: MIT Location: c:\users\administrator.virtualenvs\chatgpt-on-wechat-4yxyfv2t\lib\site-packages Requires: pypng, pyqrcode, requests Required-by:

运行程序用的也是这个 venv下的python吗

**Comment by cmhello88** [comment]
是的

**Comment by cmhello88** [comment]
删除venv后，使用pip3 install itchat-uos==1.5.0.dev0和pip3 install --upgrade openai 安装全局的依赖库，微信扫码后没报错

**Comment by YSN-commits** [comment]
使用pip3 install itchat-uos==1.5.0.dev0下载不了
ERROR: Could not find a version that satisfies the requirement itchat-uos==1.5.0.dev0 (from versions: none)
ERROR: No matching distribution found for itchat-uos==1.5.0.dev0

**Comment by YSN-commits** [comment]
> > $ pip show itchat-uos Name: itchat-uos Version: 1.5.0.dev0 Summary: 复活Itchat, 仅仅需要 pip install itchat-uos, good luck ! Home-page: https://github.com/why2lyj/ItChat-UOS Author: Snow Wang Author-email: [admin@farseer.vip](mailto:admin@farseer.vip) License: MIT Location: c:\users\administrator.virtualenvs\chatgpt-on-wechat-4yxyfv2t\lib\site-packages Requires: pypng, pyqrcode, requests Required-by:
> 
> 运行程序用的也是这个 venv下的python吗

使用pip3 install itchat-uos==1.5.0.dev0下载不了
ERROR: Could not find a version that satisfies the requirement itchat-uos==1.5.0.dev0 (from versions: none)
ERROR: No matching distribution found for itchat-uos==1.5.0.dev0

**Comment by zhayujie** [comment]
@YSN-commits  试试
pip3 install itchat-uos==1.5.0.dev0 -i https://pypi.tuna.tsinghua.edu.cn/simple
