### ISSUE TITLE
设定好角色后不回复

### ISSUE THREAD

**Issue by GuXng** [zhayujie/chatgpt-on-wechat#596]
[ERROR][2023-03-25 20:07:03][wechat_channel.py:29] - Worker return exception: key group_chat_reply_prefix not in available_setting
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\guxin\PycharmProjects\1\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 238, in handle
    reply_text = conf().get("group_chat_reply_prefix", "")+reply_text
  File "C:\Users\guxin\PycharmProjects\1\chatgpt-on-wechat\config.py", line 88, in get
    raise e
  File "C:\Users\guxin\PycharmProjects\1\chatgpt-on-wechat\config.py", line 84, in get
    return self[key]
  File "C:\Users\guxin\PycharmProjects\1\chatgpt-on-wechat\config.py", line 74, in __getitem__
    raise Exception("key {} not in available_setting".format(key))
Exception: key group_chat_reply_prefix not in available_setting

@机器人后设置好角色，再@机器人不回复

**Comment by lanvent** [comment]
拉取一下最新的代码。
