### ISSUE TITLE
 Worker return exception: key group_chat_reply_prefix not in available_setting Traceback (most recent call last):

### ISSUE THREAD

**Issue by ywh888** [zhayujie/chatgpt-on-wechat#598]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

登录进去，不回复消息

### 终端日志 (如有报错)

```
[INFO][2023-03-25 08:45:40][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-03-25 08:45:41][chat_gpt_bot.py:32] - [OPEN_AI] query=您好
[ERROR][2023-03-25 08:45:42][wechat_channel.py:29] - Worker return exception: key group_chat_reply_prefix not in available_setting
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 238, in handle
    reply_text = conf().get("group_chat_reply_prefix", "")+reply_text
  File "/root/chatgpt-on-wechat/config.py", line 88, in get
    raise e
  File "/root/chatgpt-on-wechat/config.py", line 84, in get
    return self[key]
  File "/root/chatgpt-on-wechat/config.py", line 74, in __getitem__
    raise Exception("key {} not in available_setting".format(key))
Exception: key group_chat_reply_prefix not in available_setting
```

### 环境

 - 操作系统类型  (/Linux)：
 - Python版本  ( 执行 `python39 -V` )：

**Comment by lanvent** [comment]
拉取一下最新的代码。

**Comment by ywh888** [comment]
z这个是一小时克隆的代码啊

**Comment by zhayujie** [comment]
@ywh888  后面又更新了，再  git pull 拉取一下就好
