### ISSUE TITLE
成功登录后给机器人发送消息后台报错

### ISSUE THREAD

**Issue by shenlu2077** [zhayujie/chatgpt-on-wechat#606]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by xiaoqianshenlu** [comment]
[INFO][2023-03-26 05:57:43][bridge.py:28] - create bot chatGPT for chat
[ERROR][2023-03-26 05:57:43][wechat_channel.py:29] - Worker return exception: No module named 'openai'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 205, in handle
    e_context = PluginManager().emit_event(EventContext(Event.ON_HANDLE_CONTEXT, {'channel' : self, 'context': context, 'reply': reply}))
  File "/chatgpt-on-wechat/plugins/plugin_manager.py", line 131, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/chatgpt-on-wechat/plugins/role/role.py", line 79, in on_handle_context
    bot = Bridge().get_bot("chat")
  File "/chatgpt-on-wechat/bridge/bridge.py", line 34, in get_bot
    self.bots[typename] = bot_factory.create_bot(self.btype[typename])
  File "/chatgpt-on-wechat/bot/bot_factory.py", line 20, in create_bot
    from bot.chatgpt.chat_gpt_bot import ChatGPTBot
  File "/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 10, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Comment by votual** [comment]
pip3 install --upgrade openai

**Comment by Fairyfort** [comment]
遇到一样的问题，尝试pip3 install --upgrade openai报错。
![1679898101345](https://user-images.githubusercontent.com/39402501/227857210-78f6869f-5524-4f92-9f64-25c5e0fae0d2.png)
