### ISSUE TITLE
Wechaty语音识别回复存在bug

### ISSUE THREAD

**Issue by B1gM8c** [zhayujie/chatgpt-on-wechat#609]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

Wechaty框架在给机器人发送语音消息，接收时会出现以下报错
好像之前的版本中不会存在这个问题

### 终端日志 (如有报错)

```
2023-03-26 13:14:32,362 - Message - INFO - Message mention_list
2023-03-26 13:14:32,362 - Message - INFO - Message to FileBox
2023-03-26 13:14:32,370 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsBase64'>, message-4746880423792903104-audio.slk>
[INFO][2023-03-26 13:14:32][wechaty_channel.py:103] - [WX]receive voice file: tmp/message-4746880423792903104-audio.slk
[INFO][2023-03-26 13:14:32][wechaty_channel.py:119] - [WX]receive voice converter: true
[INFO][2023-03-26 13:14:32][bridge.py:28] - create bot openai for voice_to_text
[INFO][2023-03-26 13:14:33][openai_voice.py:26] - [Openai] voiceToText text=你好,你是誰? voice file name=tmp/message-4746880423792903104-audio.wav
Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...startswith'")>) at /usr/local/lib/python3.7/site-packages/pyee/asyncio.py:65
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...startswith'")>) at /usr/local/lib/python3.7/site-packages/pyee/asyncio.py:65>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/site-packages/pyee/asyncio.py", line 71, in callback
    self.emit("error", exc)
  File "/usr/local/lib/python3.7/site-packages/wechaty/wechaty.py", line 332, in emit
    return super().emit(event, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyee/base.py", line 179, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/usr/local/lib/python3.7/site-packages/pyee/base.py", line 139, in _emit_handle_potential_error  
    raise error
  File "/www/wwwroot/wechat/xiongxiong/channel/wechat/wechaty_channel.py", line 123, in on_message
    match_prefix = self.check_prefix(query, conf().get('single_chat_prefix'))
  File "/www/wwwroot/wechat/xiongxiong/channel/wechat/wechaty_channel.py", line 282, in check_prefix
    if content.startswith(prefix):
AttributeError: 'Reply' object has no attribute 'startswith'
```
GPT解答：
这个错误是因为你的代码中使用了一个名为Reply的对象，但这个对象没有startswith()方法，导致该行代码出错。需要检查你的代码中关于Reply对象的部分，并确认它是否具有该方法。

根据报错信息，可以看到Reply对象被使用在文channel/wechat/wechaty_channel.py的第123行。你可以在该文件中查找相关代码，确认是否存在对Reply对象的调用并检查其是否正确。

根据代码，第123行的Reply对象应该是通过调用_do_send_voice()或_do_send()方法返回的。建议检查这两个方法并确认它们是否正确地返回了一个字符串而不是Reply对象。

### 环境

 - 操作系统类型  (Mac/Windows/Linux)： Linux
 - Python版本  ( 执行 `python3 -V` )：   3.7                   
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip3.7

**Comment by B1gM8c** [comment]
一种临时且粗暴的解决方案
https://github.com/zhayujie/chatgpt-on-wechat/blob/master/channel/wechat/wechaty_channel.py#L98
```
            if not msg.is_self(): # 接收语音消息
                # 下载语音文件
                voice_file = await msg.to_file_box()
                silk_file = TmpDir().path() + voice_file.name
                await voice_file.to_file(silk_file)
                logger.info("[WX]receive voice file: " + silk_file)
                # 将文件转成wav格式音频
                wav_file = silk_file.replace(".slk", ".wav")
                with open(silk_file, 'rb') as f:
                    silk_data = f.read()
                pcm_data = pysilk.decode(silk_data)

                with wave.open(wav_file, 'wb') as wav_data:
                    wav_data.setnchannels(1)
                    wav_data.setsampwidth(2)
                    wav_data.setframerate(24000)
                    wav_data.writeframes(pcm_data)
                if os.path.exists(wav_file): 
                    converter_state = "true" # 转换wav成功
                else:
                    converter_state = "false" # 转换wav失败
                logger.info("[WX]receive voice converter: " + converter_state)
                # 语音识别为文本
                query = super().build_voice_to_text(wav_file)
                # 返回消息
                if conf().get('voice_reply_voice'):
                    await self._do_send_voice(query, from_user_id)
                else:
                    await self._do_send(query, from_user_id)
                #清除缓存文件
                os.remove(wav_file)
                os.remove(silk_file)
```
语音输入的时候不对前缀进行判断了，原因如下：
语音识别出来的字不一定和我们预设的字一样，因此即便设置了判断，用户喊了机器人的名字，也有可能会遇到无法触发的情况。

但即便是这样，似乎回复统一为`请再问我一次吧`，下面似乎是Reply不能被JSON格式化
日志如下
```
[INFO][2023-03-26 14:29:29][chat_gpt_bot.py:32] - [OPEN_AI] query=Reply(type=TEXT, content=你好,你在 嗎?)
[ERROR][2023-03-26 14:29:29][chat_gpt_bot.py:127] - Object of type Reply is not JSON serializable
Traceback (most recent call last):
  File "/www/wwwroot/wechat/xiongxiong/bot/chatgpt/chat_gpt_bot.py", line 101, in reply_text
    messages=session, **self.compose_args()
  File "/usr/local/lib/python3.7/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 160, in create
    request_timeout=request_timeout,
  File "/usr/local/lib/python3.7/site-packages/openai/api_requestor.py", line 224, in request
    request_timeout=request_timeout,
  File "/usr/local/lib/python3.7/site-packages/openai/api_requestor.py", line 510, in request_raw
    url, supplied_headers, method, params, files, request_id
  File "/usr/local/lib/python3.7/site-packages/openai/api_requestor.py", line 481, in _prepare_request_raw
    data = json.dumps(params).encode()
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Reply is not JSON serializable
[INFO][2023-03-26 14:29:29][baidu_voice.py:33] - [Baidu] textToVoice text=请再问我一次吧 voice file name=tmp/语音回复_1679812169.mp3
2023-03-26 14:29:29,391 - FileBox - WARNING - detect that you want to send voice file which should be <name>.sil pattern. So we help you rename it.
2023-03-26 14:29:29,392 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsBase64'>, 1679812169.sil>
2023-03-26 14:29:29,392 - FileBox - WARNING - detect that you want to send voice file, but no voiceLength setting, so use the defualt settign: file_box.metadata = {"voiceLength": 1000}you should set it manually
````

**Comment by lanvent** [comment]
拉下最新代码试试看。
