### ISSUE TITLE
个人微信超过5-6小时不使用会保存自动退出登录

### ISSUE THREAD

**Issue by liuxc1** [zhayujie/chatgpt-on-wechat#625]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/itchat/components/login.py", line 294, in maintain_loop
    msgList, contactList = self.get_msg()
  File "/usr/local/python3/lib/python3.9/site-packages/itchat/components/login.py", line 381, in get_msg
    r = self.s.post(url, data=json.dumps(data),
  File "/usr/local/python3/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=iDkGiRPlHMlsTU6e&skey=@crypt_29cab503_4f482dcecc3f4b0f30baf0abeaf13d3c&pass_ticket=fzWqB7qd4wG1KypWgemXaDFKWq4FIn%2B5VpkUfd2d89Idb27bpwnUdDiYzAEgRY8X (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3009d10ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

LOG OUT!
```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  Linux：
 - Python版本  ( 执行 `python3 -V` )： Python 3.9.1                     
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 20.2.3

**Comment by zhayujie** [comment]
这是和微信的连接断了，是不是长时间断网了
