### ISSUE TITLE
个人微信直接提问经常没有应答

### ISSUE THREAD

**Issue by yuriyou** [zhayujie/chatgpt-on-wechat#628]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

个人微信直接提问经常没有应答，针对这个提问，换一个微信提问是正常的。
<img width="540" alt="微信图片_20230327131316" src="https://user-images.githubusercontent.com/43135518/227846793-2904da25-663e-4986-8b18-bc17a38253f2.png">
<img width="540" alt="微信图片_20230327131307" src="https://user-images.githubusercontent.com/43135518/227846811-a90d2727-c15e-4060-9dbc-2e7afdd341ec.png">

### 终端日志 (如有报错)

```

Traceback (most recent call last):
  File "/home/ec2-user/chatgpt-on-wechat/lib/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "/home/ec2-user/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 33, in handler_single_msg
    WechatChannel().handle_text(msg)
  File "/home/ec2-user/chatgpt-on-wechat/common/time_check.py", line 36, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
  File "/home/ec2-user/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 99, in handle_text
    other_user_id = msg['User']['UserName']     # 对手方id
KeyError: 'UserName'
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：   Python 3.7.16                   
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 20.2.2 from /usr/lib/python3.7/site-packages/pip (python 3.7)

**Comment by lanvent** [comment]
应该是陌生人偶尔延迟不能加载到对方信息，拉取最新的代码试试吧。

**Comment by sanpers** [comment]
我也一样
Traceback (most recent call last):
  File "E:\Python\Python39\lib\site-packages\itchat\components\register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "E:\Wechat ChatBot\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 24, in handler_single_msg
    WechatChannel().handle_text(msg)
  File "E:\Wechat ChatBot\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 72, in handle_text
    self._handle_single_msg(msg, content)
  File "E:\Wechat ChatBot\chatgpt-on-wechat-master\channel\wechat\wechat_channel.py", line 77, in _handle_single_msg
    other_user_id = msg['User']['UserName']     # 对手方id
KeyError: 'UserName'
