### ISSUE TITLE
报错信息 list index out of range

### ISSUE THREAD

**Issue by lok6666** [zhayujie/chatgpt-on-wechat#63]
Please press confirm on your phone.
[ERROR][2023-02-07 11:47:27][app.py:19] - App startup failed!
[ERROR][2023-02-07 11:47:27][app.py:20] - list index out of range
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "E:\项目\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "E:\tools\python\lib\site-packages\itchat\components\register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "E:\tools\python\lib\site-packages\itchat\components\login.py", line 61, in login
    status = self.check_login()
  File "E:\tools\python\lib\site-packages\itchat\components\login.py", line 152, in check_login
    if process_login_info(self, r.text):
  File "E:\tools\python\lib\site-packages\itchat\components\login.py", line 197, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

**Comment by zhayujie** [comment]
请问微信有实名认证嘛，没有的话要在支付那认证下

**Comment by lok6666** [comment]
好的我试一下

**Comment by lok6666** [comment]
> 请问微信有实名认证嘛，没有的话要在支付那认证下

好的我试一下
