### ISSUE TITLE
开pac连不上openai

### ISSUE THREAD

**Issue by whckcs** [zhayujie/chatgpt-on-wechat#637]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
开PAC模式连不上openai，即使把openai.com加入了白名单，目前只能开全局使用
> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by zhayujie** [comment]
这是代理软件的问题

**Comment by zssettler** [comment]
我也是，网页端能访问chat gpt，但报错说API不对
Start auto replying.
[INFO][2023-03-29 14:28:46][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-03-29 14:28:46][chat_gpt_bot.py:34] - [OPEN_AI] query=可以嘛
[ERROR][2023-03-29 14:28:48][chat_gpt_bot.py:129] - Incorrect API key provided: YOUR API KEY. You can find your API key at https://platform.openai.com/account/api-keys.
Traceback (most recent call last):
  File "e:\code\gpt on wechat\chatgpt-on-wechat\bot\chatgpt\chat_gpt_bot.py", line 102, in reply_text
    response = openai.ChatCompletion.create(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: YOUR API KEY. You can find your API key at https://platform.openai.com/account/api-keys.
[INFO][2023-03-29 14:28:48][wechat_channel.py:234] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
请再问我一次吧), receiver=@c11380800655cfc1db33ba5

**Comment by YiChengXu** [comment]
ss默认不支持http代理只支持socks5代理，所以你就连不上。linux需要配置http代理，mac建议装别的客户端软件别用ss-ng

**Comment by whckcs** [comment]
> ss默认不支持http代理只支持socks5代理，所以你就连不上。linux需要配置http代理，mac建议装别的客户端软件别用ss-ng

那win除了ss还有什么推荐的

**Comment by murphy-xiang** [comment]
Mac用什么客户端呢？
