### ISSUE TITLE
呼叫gpt报错

### ISSUE THREAD

**Issue by Kevin-0809** [zhayujie/chatgpt-on-wechat#638]
### 前置确认

触发gpt的时候报错。timeout

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[ERROR][2023-03-28 05:59:46][wechat_channel.py:29] - Worker return exception: module 'openai.error' has no attribute 'Timeout'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat-1.1.3/bot/chatgpt/chat_gpt_bot.py", line 100, in reply_text
    response = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/chatgpt-on-wechat-1.1.3/channel/wechat/wechat_channel.py", line 210, in handle
    reply = super().build_reply_content(context.content, context)
  File "/root/chatgpt-on-wechat-1.1.3/channel/channel.py", line 33, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/root/chatgpt-on-wechat-1.1.3/bridge/bridge.py", line 42, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "/root/chatgpt-on-wechat-1.1.3/bot/chatgpt/chat_gpt_bot.py", line 55, in reply
    reply_content = self.reply_text(session, session_id, 0)
  File "/root/chatgpt-on-wechat-1.1.3/bot/chatgpt/chat_gpt_bot.py", line 121, in reply_text
    except openai.error.Timeout as e:
AttributeError: module 'openai.error' has no attribute 'Timeout'

```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：
linux
```
[root@centos7 chatgpt-on-wechat-1.1.3]# python3 -V
Python 3.6.8
[root@centos7 chatgpt-on-wechat-1.1.3]# pip3 -V   
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 21.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
[root@centos7 chatgpt-on-wechat-1.1.3]# 
```

**Comment by zhayujie** [comment]
两个问题
1. python版本太低，升级到3.7.1以上， 然后更新下 openai，需要到 0.27.0版本
2. 访问openai接口超时
