### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by yonwoo9** [zhayujie/chatgpt-on-wechat#639]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

if you @bot after your request in wechatgroup, like this: this is a test @bot
this will cause an error: index out of range

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
[ERROR][2023-03-27 14:36:32][wechat channel.py:29]
Traceback (most recent call last)
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in runresult = self.fn(*self.args , **self.kwargs)
File "/home/ubuntu/project/chatgpt-on-wechat/channel/wechat/wechat channel.py", line 205, in handlee context = PluginManagerl).emit event(Eventontext(Event.0N HANLE CONTEXT, ['chamnel' : self, 'context': context, "reply': replyl)
File "/home/ubuntu/project/chatgpt-on-wechat/plugins/plugin manager.py", line 131, in emit eventinstance.handlers[e context.event](e context,*args,**kwargs)
File "/home/ubuntu/project/chatgpt-on-wechat/plugins/role/role.py", line 84, in on handle context if clist[0] =="$停止扮演":IndexError: list index out of range
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：linux 
 - Python版本  ( 执行 `python3 -V` )：  Python 3.10.6                    
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 22.0.2

**Comment by lanvent** [comment]
感谢issue，现在能够正常的忽略空内容了。
