### ISSUE TITLE
本地启动报错

### ISSUE THREAD

**Issue by moonZ000** [zhayujie/chatgpt-on-wechat#652]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
4. 在已有 issue 中未搜索到类似问题
5. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

[ERROR][2023-03-28 15:43:17][app.py:23] - App startup failed!
[ERROR][2023-03-28 15:43:17][app.py:24] - No module named 'png'
Traceback (most recent call last):
  File "app.py", line 21, in run
    channel.startup()
  File "C:\Users\admin\Desktop\code\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 75, in startup
    raise e
  File "C:\Users\admin\Desktop\code\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 67, in startup
    itchat.auto_login(enableCmdQR=2, hotReload=hotReload)
  File "C:\Users\admin\Desktop\code\chatgpt-on-wechat\lib\itchat\components\register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "C:\Users\admin\Desktop\code\chatgpt-on-wechat\lib\itchat\components\login.py", line 56, in login
    picDir=picDir, qrCallback=qrCallback)
  File "C:\Users\admin\Desktop\code\chatgpt-on-wechat\lib\itchat\components\login.py", line 129, in get_QR
    qrCode.png(qrStorage, scale=10)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pyqrcode\__init__.py", line 463, in png
    module_color, background, quiet_zone)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pyqrcode\builder.py", line 1266, in _png
    import png
ModuleNotFoundError: No module named 'png'

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
apikey暴露了，注意更换。
拉取最新代码后, 执行`pip3 install -r requirements.txt`

**Comment by qq765490023** [comment]
> apikey暴露了，注意更换。 拉取最新代码后, 执行`pip3 install -r requirements.txt`

哪里暴露的

**Comment by gczwf233** [comment]
我也报错在这里哈哈,救命啊

**Comment by moonZ000** [comment]
> apikey暴露了，注意更换。 拉取最新代码后, 执行`pip3 install -r requirements.txt`

谢了老哥

**Comment by moonZ000** [comment]
> 我也报错在这里哈哈,救命啊

第一种可能：
这时可能需要我们升级一下pip版本，于是执行命令

python -m pip install --upgrade pip

执行完后发现还是报一样的错误，

第二种可能：
这时考虑换一个pip源

pip install pymysql -i https://pypi.tuna.tsinghua.edu.cn/simple/

第三种可能：
这时考虑是网速的原因，这时采用国内的镜像源来加速

pip install 包名-i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
