### ISSUE TITLE
新版本语音失败失败，测试了2023.3.28最新代码

### ISSUE THREAD

**Issue by gwailee** [zhayujie/chatgpt-on-wechat#654]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
没有用新版之前，可以回复私聊语音，调用的是百度的语音回复。
新版发现群组在看到后台有响应，但是报错！
私聊也不能用了，同样的后台报错！
已经安装了：pysilk

### 终端日志 (如有报错)
[ERROR][2023-03-28 11:05:01][wechat_channel.py:32] - Worker return exception: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/WX-ChatGPT-308-1/channel/wechat/wechat_channel.py", line 303, in handle
    from voice.audio_convert import mp3_to_wav
  File "/root/WX-ChatGPT-308-1/voice/audio_convert.py", line 2, in <module>
    import pysilk
  File "/usr/local/lib/python3.8/dist-packages/pysilk/__init__.py", line 1, in <module>
    from .pysilk import encode, encode_file, decode, decode_file
  File "/usr/local/lib/python3.8/dist-packages/pysilk/pysilk.py", line 12, in <module>
    _LOOP = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
感谢issue，已修复，请拉取最新代码

**Comment by gittuib** [comment]
**前置确认**
网络能够访问openai接口，
python 已安装：版本在 3.7 ~ 3.10 之间
git pull 拉取最新代码
执行pip3 install -r requirements.txt，检查依赖是否满足
在已有 issue 中未搜索到类似问题
[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题
**问题描述**
文字回复一直没问题，就是语音一直无法使用。
已经安装了：pysilk
**终端日志 (报错信息)**
[ERROR][2023-03-29 09:22:23][wechat_channel.py:31] - Worker return exception: There is no current event loop in thread 'ThreadPoolExecutor-0_1'.
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/2023/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 274, in handle
    # mp3转wav
  File "/2023/chatgpt-on-wechat/voice/audio_convert.py", line 2, in <module>
    import pysilk
  File "/usr/local/lib/python3.9/dist-packages/pysilk/__init__.py", line 1, in <module>
    from .pysilk import encode, encode_file, decode, decode_file
  File "/usr/local/lib/python3.9/dist-packages/pysilk/pysilk.py", line 12, in <module>
    _LOOP = asyncio.get_event_loop()
  File "/usr/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_1'.

**Comment by gwailee** [comment]
刚拉新代码，重新测试，执行了requirements.txt，提示错误：
[INFO][2023-03-29 02:01:13][wechat_channel.py:335] - [WX]receive voice, checkprefix didn't match




***@***.***
 
发件人： gittuib
发送时间： 2023-03-29 09:24
收件人： zhayujie/chatgpt-on-wechat
抄送： gwailee; Author
主题： Re: [zhayujie/chatgpt-on-wechat] 新版本语音失败失败，测试了2023.3.28最新代码 (Issue #654)
前置确认
网络能够访问openai接口，
python 已安装：版本在 3.7 ~ 3.10 之间
git pull 拉取最新代码
执行pip3 install -r requirements.txt，检查依赖是否满足
在已有 issue 中未搜索到类似问题
FAQS 中无类似问题
问题描述
文字回复一直没问题，就是语音一直无法使用。
已经安装了：pysilk
终端日志 (报错信息)
[ERROR][2023-03-29 09:22:23][wechat_channel.py:31] - Worker return exception: There is no current event loop in thread 'ThreadPoolExecutor-0_1'.
Traceback (most recent call last):
File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/2023/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 274, in handle
# mp3转wav
File "/2023/chatgpt-on-wechat/voice/audio_convert.py", line 2, in 
import pysilk
File "/usr/local/lib/python3.9/dist-packages/pysilk/init.py", line 1, in 
from .pysilk import encode, encode_file, decode, decode_file
File "/usr/local/lib/python3.9/dist-packages/pysilk/pysilk.py", line 12, in 
_LOOP = asyncio.get_event_loop()
File "/usr/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_1'.

**Comment by gwailee** [comment]
我在config.json里面这样设置
"single_chat_reply_prefix": "",
  "group_chat_prefix": ***@***.***","bot","ai"],
看了一下代码，貌似判断有问题，判断不到合成的语音输出：

if context["isgroup"]: # 群聊
                        # 校验关键字
                        match_prefix = check_prefix(content, conf().get('group_chat_prefix'))
                        match_contain = check_contain(content, conf().get('group_chat_keyword'))
                        if match_prefix is not None or match_contain is not None:
                            # 判断如果匹配到自定义前缀，则返回过滤掉前缀+空格后的内容，用于实现类似自定义+前缀触发生成AI图片的功能
                            if match_prefix:
                                content = content.replace(match_prefix, '', 1).strip()
                        else:
                            logger.info("[WX]receive voice, checkprefix didn't match")
                            return
                    else: # 单聊
                        match_prefix = check_prefix(content, conf().get('single_chat_prefix'))  
                        if match_prefix: # 判断如果匹配到自定义前缀，则返回过滤掉前缀+空格后的内容
                            content = content.replace(match_prefix, '', 1).strip()
                        else:
                            logger.info("[WX]receive voice, checkprefix didn't match")
                            return



***@***.***
 
发件人： gittuib
发送时间： 2023-03-29 09:24
收件人： zhayujie/chatgpt-on-wechat
抄送： gwailee; Author
主题： Re: [zhayujie/chatgpt-on-wechat] 新版本语音失败失败，测试了2023.3.28最新代码 (Issue #654)
前置确认
网络能够访问openai接口，
python 已安装：版本在 3.7 ~ 3.10 之间
git pull 拉取最新代码
执行pip3 install -r requirements.txt，检查依赖是否满足
在已有 issue 中未搜索到类似问题
FAQS 中无类似问题
问题描述
文字回复一直没问题，就是语音一直无法使用。
已经安装了：pysilk
终端日志 (报错信息)
[ERROR][2023-03-29 09:22:23][wechat_channel.py:31] - Worker return exception: There is no current event loop in thread 'ThreadPoolExecutor-0_1'.
Traceback (most recent call last):
File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/2023/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 274, in handle
# mp3转wav
File "/2023/chatgpt-on-wechat/voice/audio_convert.py", line 2, in 
import pysilk
File "/usr/local/lib/python3.9/dist-packages/pysilk/init.py", line 1, in 
from .pysilk import encode, encode_file, decode, decode_file
File "/usr/local/lib/python3.9/dist-packages/pysilk/pysilk.py", line 12, in 
_LOOP = asyncio.get_event_loop()
File "/usr/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_1'.

**Comment by gittuib** [comment]
已经调试好了，默认google语音，原因是我没有重新app.py程序，重启一下就好了
