### ISSUE TITLE
@完机器收到消息后请求openAI 报错“error”

### ISSUE THREAD

**Issue by qq765490023** [zhayujie/chatgpt-on-wechat#659]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
此为登陆成功后出现的错误，可以肯定电脑已经收到了微信的消息，在请求openAI的过程中出错。不存在墙的问题。

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/hongzhouyang/Documents/Zhouyang/projects/test_codes/wechat/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 269, in handle
    reply = super().build_reply_content(context.content, context)
  File "/Users/hongzhouyang/Documents/Zhouyang/projects/test_codes/wechat/chatgpt-on-wechat/channel/channel.py", line 33, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/Users/hongzhouyang/Documents/Zhouyang/projects/test_codes/wechat/chatgpt-on-wechat/bridge/bridge.py", line 42, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "/Users/hongzhouyang/Documents/Zhouyang/projects/test_codes/wechat/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 57, in reply
    reply_content = self.reply_text(session, session_id, 0)
  File "/Users/hongzhouyang/Documents/Zhouyang/projects/test_codes/wechat/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 109, in reply_text
    except openai.error.RateLimitError as e:
AttributeError: module 'openai' has no attribute 'error'

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by qq765490023** [comment]
[INFO][2023-03-28 16:02:43][chat_gpt_bot.py:34] - [OPEN_AI] query=你好呀
[ERROR][2023-03-28 16:02:43][wechat_channel.py:33] - Worker return exception: module 'openai' has no attribute 'error'
Traceback (most recent call last):
  File "/Users/hongzhouyang/Documents/Zhouyang/projects/test_codes/wechat/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 102, in reply_text
    response = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'

已解决.
requirements.txt
openai>=0.27.2
改为
openai==0.27.0

然后
pip3 uninstall openai
pip3 install -r requirements.txt
完美解决
