### ISSUE TITLE
在railway部署时扫码登录后错误

### ISSUE THREAD

**Issue by lajixuebiancheng** [zhayujie/chatgpt-on-wechat#664]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[ERROR][2023-03-28 17:18:30][app.py:23] - App startup failed!
[ERROR][2023-03-28 17:18:30][app.py:24] - list index out of range
Traceback (most recent call last):
File "/app/./app.py", line 21, in run
channel.startup()
File "/app/channel/wechat/wechat_channel.py", line 77, in startup
raise e
File "/app/channel/wechat/wechat_channel.py", line 69, in startup
itchat.auto_login(enableCmdQR=2, hotReload=hotReload)
File "/app/lib/itchat/components/register.py", line 35, in auto_login
self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
File "/app/lib/itchat/components/login.py", line 60, in login
status = self.check_login()
File "/app/lib/itchat/components/login.py", line 153, in check_login
if process_login_info(self, r.text):
File "/app/lib/itchat/components/login.py", line 198, in process_login_info
skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by dwyo** [comment]
在railway.app 上部署同样遇到此问题

**Comment by lanvent** [comment]
see [FAQs](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)

**Comment by dwyo** [comment]
> see [FAQs](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)

实名认证后已正常使用
