### ISSUE TITLE
多次尝试，wechaty无法从chatie服务器获取端点，token昨天刚申请的，还有效。

### ISSUE THREAD

**Issue by zxr11241** [zhayujie/chatgpt-on-wechat#674]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

root@iZj6c3fgsqad71ql49tnflZ:~/chatgpt-on-wechat# touch nohup.out                                   # 首次运行需要新建日志文件                     
root@iZj6c3fgsqad71ql49tnflZ:~/chatgpt-on-wechat# nohup python3 app.py & tail -f nohup.out          # 在后台运行程序并通过日志输出二维码
[1] 19984
2023-03-29 14:45:23,767 - PuppetService - INFO - init puppet ...
2023-03-29 14:45:23,767 - PuppetService - INFO - fetching endpoint from chatie-server: https://api.chatie.io/v0/hosties/Zxr229802264
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wechaty/wechaty.py", line 445, in start
    await self.puppet.start()
  File "/usr/local/lib/python3.9/dist-packages/wechaty_puppet_service/puppet.py", line 911, in start
    self._init_puppet()
  File "/usr/local/lib/python3.9/dist-packages/wechaty_puppet_service/puppet.py", line 876, in _init_puppet
    raise WechatyPuppetGrpcError(
wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)
nohup: ignoring input and appending output to 'nohup.out'
[INFO][2023-03-29 14:46:45][config.py:127] - [INIT] load config: {'open_ai_api_key': 'sk-
[INFO][2023-03-29 14:46:46][plugin_manager.py:39] - Loading plugins config...
[INFO][2023-03-29 14:46:46][plugin_manager.py:55] - Scaning plugins ...
[INFO][2023-03-29 14:46:46][plugin_manager.py:30] - Plugin Banwords_v1.0 registered
[INFO][2023-03-29 14:46:46][plugin_manager.py:30] - Plugin Hello_v0.1 registered
[INFO][2023-03-29 14:46:46][plugin_manager.py:30] - Plugin Role_v1.0 registered
[INFO][2023-03-29 14:46:46][plugin_manager.py:30] - Plugin Dungeon_v1.0 registered
[INFO][2023-03-29 14:46:46][plugin_manager.py:30] - Plugin BDunit_v0.1 registered
[INFO][2023-03-29 14:46:46][plugin_manager.py:30] - Plugin sdwebui_v2.0 registered
[INFO][2023-03-29 14:46:46][plugin_manager.py:30] - Plugin Godcmd_v1.0 registered
[INFO][2023-03-29 14:46:46][godcmd.py:135] - [Godcmd] inited
[WARNING][2023-03-29 14:46:46][banwords.py:41] - Banwords init failed: [Errno 2] No such file or directory: '/root/chatgpt-on-wechat/plugins/banwords/banwords.txt', ignore or see https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/banwords .
[WARNING][2023-03-29 14:46:46][sdwebui.py:33] - [SD] init failed, /root/chatgpt-on-wechat/plugins/sdwebui/config.json not found, ignore or see https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/sdwebui .
[INFO][2023-03-29 14:46:46][role.py:46] - [Role] inited
[INFO][2023-03-29 14:46:46][dungeon.py:43] - [Dungeon] inited
[WARNING][2023-03-29 14:46:46][bdunit.py:39] - BDunit init failed: config.json not found, ignore 
[INFO][2023-03-29 14:46:46][hello.py:15] - [Hello] inited
2023-03-29 14:46:46,433 - Wechaty - INFO - on() listen event <scan> with <<bound method WechatyChannel.on_scan of <channel.wechat.wechaty_channel.WechatyChannel object at 0x7fbc6d4de9d0>>>
2023-03-29 14:46:46,433 - Wechaty - INFO - on() listen event <login> with <<bound method WechatyChannel.on_login of <channel.wechat.wechaty_channel.WechatyChannel object at 0x7fbc6d4de9d0>>>
2023-03-29 14:46:46,433 - Wechaty - INFO - on() listen event <message> with <<bound method WechatyChannel.on_message of <channel.wechat.wechaty_channel.WechatyChannel object at 0x7fbc6d4de9d0>>>
2023-03-29 14:46:46,433 - Wechaty - INFO - init_puppet_event_bridge() <<wechaty_puppet_service.puppet.PuppetService object at 0x7fbc69184190>>
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(dong) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(error) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(heart-beat) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(ready) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - receive <reset> event <%s>
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(reset) (listenerCount:0) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(friendship) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(login) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(logout) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(message) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-invite) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-join) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-leave) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-topic) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - initPuppetEventBridge() puppet.on(scan) (listenerCount:1) registering...
2023-03-29 14:46:46,434 - Wechaty - INFO - starting puppet ...
2023-03-29 14:46:46,434 - PuppetService - INFO - init puppet ...
2023-03-29 14:46:46,434 - PuppetService - INFO - fetching endpoint from chatie-server: https://api.chatie.io/v0/hosties/Z。r229802264
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wechaty/wechaty.py", line 445, in start
    await self.puppet.start()
  File "/usr/local/lib/python3.9/dist-packages/wechaty_puppet_service/puppet.py", line 911, in start
    self._init_puppet()
  File "/usr/local/lib/python3.9/dist-packages/wechaty_puppet_service/puppet.py", line 876, in _init_puppet
    raise WechatyPuppetGrpcError(
wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)
ping api.chatie.io能通。
https://api.chatie.io/v0/hosties/token。显示下文。
{"host":"192.81.130.192","ip":"192.81.130.192","port":8080}
我真找不到问题在哪，我试了好多天，希望有懂的能感受我一下，谢谢

### 环境

 - 操作系统类型  (Linux)：阿里云香港
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( ，执行 `pip3 -V`)：

**Comment by Cliffe97** [comment]
请问你的https://api.chatie.io/v0/hosties/token是怎么显示出来的？为什么我的都是{"host":"0.0.0.0","ip":"0.0.0.0","port":0}

**Comment by lanvent** [comment]
我的启动方式：
```bash
docker pull wechaty/wechaty:0.65
docker run -ti --name wechaty_puppet_service_token_gateway_padlocal --rm -e WECHATY_LOG="verbose" -e WECHATY_PUPPET="wechaty-puppet-padlocal" -e WECHATY_PUPPET_PADLOCAL_TOKEN="puppet_padlocal_XXX" -e WECHATY_PUPPET_SERVER_PORT="9001" -e WECHATY_TOKEN="YOUR TOKEN" -p "9001:9001" wechaty/wechaty:0.65
```

并注释掉这行:
```bash
https://github.com/zhayujie/chatgpt-on-wechat/blob/388058467cc6592bde8bbab5de82307cc865138a/app.py#L19
```

注意不要设置全局代理。

**Comment by huangzhitian** [comment]
> ```shell
> puppet_padlocal_XXX
> ```

大佬请问一下puppet_padlocal_XXX这里填什么

**Comment by ZeWu-Tao** [comment]
> > ```shell
> > puppet_padlocal_XXX
> > ```
> 
> 大佬请问一下puppet_padlocal_XXX这里填什么

这个是wechaty的token，去这个地方获取http://pad-local.com
