### ISSUE TITLE
新版本语音提问失效，已经重新git pull过

### ISSUE THREAD

**Issue by cntink** [zhayujie/chatgpt-on-wechat#678]
所有依赖已安装，前两天用着还好好的，从昨天起就不行了，之前不用ffmpeg也可以接收语音，然后文字回复，现在是必须要ffmpeg了，但是把ffmpeg放到同目录后，又报“文件正在使用”的错误，windows 2012，python 3.8.10

Start auto replying.
[INFO][2023-03-29 16:38:22][bridge.py:28] - create bot openai for voice_to_text
[ERROR][2023-03-29 16:39:26][wechat_channel.py:33] - Worker return exception: [WinError 32] 另一个程序正在使用此文件，进
程无法访问。: 'tmp/230329-163822.wav'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrator\Desktop\ChatGPT_WX\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 280, in hand
le
    os.remove(wav_path)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'tmp/230329-163822.wav'

**Comment by lanvent** [comment]
感谢issue，已修复。
现在如果ffmpeg未安装，虽然mp3转wav失败，但仍然会继续传递mp3文件。openai的whisper接口可处理mp3音频文件。
