### ISSUE TITLE
启动成功后，不回复

### ISSUE THREAD

**Issue by a937282042** [zhayujie/chatgpt-on-wechat#69]
提示Start auto replying.在配置文件只是修改了apikey，群聊中使用 bot 今天天气怎么样 无法触发

**Comment by a937282042** [comment]
win环境 需要全局翻墙么

**Comment by zhayujie** [comment]
> win环境 需要全局翻墙么

翻墙会有问题，正常国内网络就好

**Comment by zhayujie** [comment]
群聊是被好友艾特触发， 或者用 group_chat_prefix 配置中的关键字触发

**Comment by a937282042** [comment]
"single_chat_prefix": ["bot", "@bot"],
  "single_chat_reply_prefix": "[bot] ",
  "group_chat_prefix": ["@bot"],
  "group_name_white_list": ["ChatGPT测试群", "ChatGPT测试群2"],
  "image_create_prefix": ["画", "看", "找"],
  "conversation_max_tokens": 1000,
  "character_desc": "你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你乐于回答人们的任何问题"
  
  群聊中使用  @bot 今天天气怎么样  没有回复

**Comment by a937282042** [comment]
触发后提示  You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.

**Comment by a937282042** [comment]
@zhayujie

**Comment by a937282042** [comment]
You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.
Traceback (most recent call last):
  File "D:\chatgpt-on-wechat-master\bot\openai\open_ai_bot.py", line 40, in reply_text
    response = openai.Completion.create(
  File "C:\Users\thpower\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\thpower\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\thpower\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\thpower\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\thpower\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.

**Comment by a937282042** [comment]
You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.
Traceback (most recent call last):
  File "D:\chatgpt-on-wechat-master\bot\openai\open_ai_bot.py", line 40, in reply_text
    response = openai.Completion.create(
  File "C:\Users\thpower\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\thpower\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\thpower\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\thpower\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\thpower\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.

**Comment by a937282042** [comment]
微信中触发了回复 提示错误如上 @zhayujie

**Comment by WeiZhang-bigdata** [comment]
你的错 和我的错一样 。我也卡在这里了

**Comment by WeiZhang-bigdata** [comment]
我这个openai的账号 租的淘宝的  ，能在网页和机器人正常chat

**Comment by WeiZhang-bigdata** [comment]
![image](https://user-images.githubusercontent.com/67574798/217218686-9880bcb6-8637-467c-ba63-b4901ba27ea0.png)

**Comment by WeiZhang-bigdata** [comment]
其他转发微信的程序 也是这个错

**Comment by zhayujie** [comment]
看来是账号的问题， 账号不是独享的吧？

**Comment by zhayujie** [comment]
see #75
