### ISSUE TITLE
自己单人聊天触发bot回复报错 openai无效链接

### ISSUE THREAD

**Issue by 1797072990** [zhayujie/chatgpt-on-wechat#692]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
![屏幕截图 2023-03-30 113734](https://user-images.githubusercontent.com/73577309/228745863-05222145-25dc-4f71-8489-cb7327cdca02.jpg)




### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by 1797072990** [comment]
Start auto replying.
[INFO][2023-03-30 03:35:40][bridge.py:28] - create bot chatGPTOnAzure for chat
[INFO][2023-03-30 03:35:42][chat_gpt_bot.py:34] - [OPEN_AI] query=你是谁
[ERROR][2023-03-30 03:35:42][chat_gpt_bot.py:129] - Invalid URL (POST /v1/openai/deployments/gpt-3.5-turbo/chat/completions)
Traceback (most recent call last):
File "/app/bot/chatgpt/chat_gpt_bot.py", line 102, in reply_text
response = openai.ChatCompletion.create(
File "/opt/venv/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
return super().create(*args, **kwargs)
File "/opt/venv/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
response, _, api_key = requestor.request(
File "/opt/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 226, in request
resp, got_stream = self._interpret_response(result, stream)
File "/opt/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 619, in _interpret_response
self._interpret_response_line(
File "/opt/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /v1/openai/deployments/gpt-3.5-turbo/chat/completions)
[INFO][2023-03-30 03:35:42][wechat_channel.py:198] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
请再问我一次吧), receiver=@8fe80cfccdf6a4e788944486d9520f38839d13f4667103096920e1418f67ec17
LOG OUT!


Showing 568 logs

**Comment by lanvent** [comment]
请查看主页跟`azure`相关的配置项，它需要设置`open_ai_api_base`和`model`。
