### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by Rickyyyliu** [zhayujie/chatgpt-on-wechat#70]
Please the contact, this may take a little while.目前在这里卡住了，请问如何解决？

**Comment by zhayujie** [comment]
> Please the contact, this may take a little while.目前在这里卡住了，请问如何解决？

这样就是成功了，回车一下看看

然后手机发消息触发回复

**Comment by Rickyyyliu** [comment]
> > Please the contact, this may take a little while.目前在这里卡住了，请问如何解决？
> 
> 这样就是成功了，回车一下看看
> 
> 然后手机发消息触发回复

虽然手机显示了桌面微信登陆，但好像还是不行唉，发了消息没反应~

**Comment by zhayujie** [comment]
有发消息触发吗？

**Comment by Rickyyyliu** [comment]
> 

用了@bot

**Comment by Rickyyyliu** [comment]
> 消息中有关键字触发吗？

用了@bot

**Comment by Rickyyyliu** [comment]
> > 消息中有关键字触发吗？
> 
> 用了@bot

程序一直没看到输出"Start auto replying"

**Comment by zhayujie** [comment]
国内网络吗，没开代理吧？

**Comment by Rickyyyliu** [comment]
> 

嗯嗯，没开

**Comment by zhayujie** [comment]
加下我帮你看看吧

**Comment by Rickyyyliu** [comment]
> 加下我帮你看看吧

okok

**Comment by Rickyyyliu** [comment]
Please scan the QR code to log in.
Please press confirm on your phone.
[ERROR][2023-02-07 21:44:22][app.py:19] - App startup failed!
[ERROR][2023-02-07 21:44:22][app.py:20] - ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "C:\ProgramData\Python3.9.0\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\Python3.9.0\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\ProgramData\Python3.9.0\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\ProgramData\Python3.9.0\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\ProgramData\Python3.9.0\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\Python3.9.0\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
目前遇到了这个问题，是怎么回事？

**Comment by Rickyyyliu** [comment]
> 加下我帮你看看吧

现在扫码后程序能够显示Start auto replying，但在消息中使用关键字触发后报了下面的错误，请问是什么原因？

[ERROR][2023-02-07 21:56:27][app.py:19] - App startup failed!
[ERROR][2023-02-07 21:56:27][app.py:20] - ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "C:\ProgramData\Python3.9.0\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\Python3.9.0\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\ProgramData\Python3.9.0\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\ProgramData\Python3.9.0\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\ProgramData\Python3.9.0\lib\http\client.py", line 307, in begin
  File "C:\ProgramData\Python3.9.0\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by Rickyyyliu** [comment]
> 

没开啊

**Comment by Rickyyyliu** [comment]
> 

没开啊
