### ISSUE TITLE
Railway一键部署扫描登录后发送消息回复报错如下

### ISSUE THREAD

**Issue by hy546880109** [zhayujie/chatgpt-on-wechat#713]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as Harry
[INFO][2023-03-31 03:27:19][wechat_channel.py:95] - Wechat login success, username: @00fca2bbc745ad177a6628ea658eb624f760e35221136727fc0a8c9b3f317250, nickname: Harry
Start auto replying.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
response.begin()
File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
response.begin()
File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/lib/itchat/components/login.py", line 296, in maintain_loop
msgList, contactList = self.get_msg()
File "/app/lib/itchat/components/login.py", line 383, in get_msg
r = self.s.post(url, data=json.dumps(data),
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
return self.request("POST", url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[INFO][2023-03-31 03:27:34][bridge.py:28] - create bot chatGPTOnAzure for chat
[INFO][2023-03-31 03:27:35][chat_gpt_bot.py:34] - [CHATGPT] query=你是
[WARNING][2023-03-31 03:27:37][chat_gpt_bot.py:127] - [CHATGPT] Exception: Invalid URL (POST /v1/openai/deployments/gpt-3.5-turbo/chat/completions)
[INFO][2023-03-31 03:27:38][wechat_channel.py:263] - [WX] sendMsg=Reply(type=ERROR, content=ERROR:
我现在有点累了，等会再来吧), receiver=@2ea66d44b56a4499b0d8b8b849da0eba6c1f6ac94fb27f22b50e10e26c797957
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
```
[INFO][2023-03-31 03:27:34][bridge.py:28] - create bot chatGPTOnAzure for chat
```
检查配置项use_azure_chatgpt是否没关

**Comment by hy546880109** [comment]
![image](https://user-images.githubusercontent.com/44777854/229036212-cfb99ef7-9fc0-463f-b45c-3e8c5b7f351c.png)
已经配置了

**Comment by lanvent** [comment]
布尔变量首字母要大写

**Comment by hy546880109** [comment]
感谢，已经成功了

**Comment by hy546880109** [comment]
改成大小解决了我的问题
