### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lonny1987** [zhayujie/chatgpt-on-wechat#714]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

### 终端日志 (如有报错)

^[Traceback (most recent call last):
  File "/home/ubuntu/chatgpt-on-wechat/lib/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 41, in handler_single_msg
    WechatChannel().handle_text(msg)
  File "/home/ubuntu/chatgpt-on-wechat/common/time_check.py", line 36, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 70, in wrapper
    return func(self, msg)
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 153, in handle_text
    context = self._compose_context(ContextType.TEXT, content, isgroup=False, msg=msg, receiver=other_user_id, session_id=other_user_id)
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 240, in _compose_context
    img_match_prefix = check_prefix(content, conf().get('image_create_prefix'))
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 379, in check_prefix
    for prefix in prefix_list:
TypeError: 'NoneType' object is not iterable

[在此处粘贴终端日志]
```



### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
配置文件中有`img_match_prefix `吗，不能直接删除，把数组改成空就可以。
```json
"img_match_prefix" : []
```

**Comment by lonny1987** [comment]
你好啊，感谢，问题解决，不过现在有新的问题，我用的是AWS服务器，登录后，终端显示无法连网。
ERROR:
我连接不到你的网络。
<img width="881" alt="image" src="https://user-images.githubusercontent.com/129271373/229094675-3567242a-fbcd-468a-b892-daab4041f710.png">

**Comment by lanvent** [comment]
这跟云服务器和`openai`的连接有关
