### ISSUE TITLE
railway一键安装后,修改仓库里的godcmd的密码没有用

### ISSUE THREAD

**Issue by KumaBoom** [zhayujie/chatgpt-on-wechat#723]
返回
ERROR:
未设置口令，无法认证

**Comment by lanvent** [comment]
可以把自己仓库的DockerFile删掉，但部署时间会长一些。

**Comment by KumaBoom** [comment]
> 可以删除fork库里主目录下的DockerFile，这样每次都会从你的库重新构建，但部分时间会长。

删了之后再重新构建  就会
[INFO][2023-04-01 07:14:57][config.py:108] - 配置文件不存在，将使用config-template.json模板
[ERROR][2023-04-01 07:14:57][app.py:23] - App startup failed!
[ERROR][2023-04-01 07:14:57][app.py:24] - Expecting value: line 12 column 25 (char 461)
Traceback (most recent call last):
File "/app/./app.py", line 12, in run
load_config()
File "/app/config.py", line 115, in load_config
config = Config(json.loads(config_str))
File "/nix/store/al6g1zbk8li6p8mcyp0h60d08jaahf8c-python3-3.10.9/lib/python3.10/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/nix/store/al6g1zbk8li6p8mcyp0h60d08jaahf8c-python3-3.10.9/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/nix/store/al6g1zbk8li6p8mcyp0h60d08jaahf8c-python3-3.10.9/lib/python3.10/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 12 column 25 (char 461)

恢复DockerFile文件即恢复正常

**Comment by lanvent** [comment]
我刚测试了下，删除仓库主目录下DockerFile是可用的
