### ISSUE TITLE
扫码登录后报错  list index out of range

### ISSUE THREAD

**Issue by xyouAI** [zhayujie/chatgpt-on-wechat#728]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

服务器运行启动后，出现了二维码，扫码后点击确认登录报错了。

### 终端日志 (如有报错)

```
[ERROR][2023-04-02 11:21:33][app.py:28] - App startup failed!
[ERROR][2023-04-02 11:21:33][app.py:29] - list index out of range
Traceback (most recent call last):
  File "/home/wwwroot/chatgpt-on-wechat/app.py", line 26, in run
    channel.startup()
  File "/home/wwwroot/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 104, in startup
    raise e
  File "/home/wwwroot/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 96, in startup
    itchat.auto_login(enableCmdQR=2, hotReload=hotReload, qrCallback=qrCallback)
  File "/home/wwwroot/chatgpt-on-wechat/lib/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/home/wwwroot/chatgpt-on-wechat/lib/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/home/wwwroot/chatgpt-on-wechat/lib/itchat/components/login.py", line 153, in check_login
    if process_login_info(self, r.text):
  File "/home/wwwroot/chatgpt-on-wechat/lib/itchat/components/login.py", line 198, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range
```

### 环境

 - 操作系统类型  Linux：
 - Python版本  ( 执行 `python3 -V` )：3.9                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：21.3.1

**Comment by zouyourou** [comment]
我也碰到了相同的问题

**Comment by Monkiesh** [comment]
我也遇到了同样的问题

**Comment by lanvent** [comment]
see [FAQ](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)

**Comment by Monkiesh** [comment]
实名认证后可解决问题
