### ISSUE TITLE
Hello 插件的问题

### ISSUE THREAD

**Issue by Li-Eternally** [zhayujie/chatgpt-on-wechat#734]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 在已有 issue 中未搜索到类似问题
6. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

>向bot发送 Hello 会报出以下错误，发送 End 则正常回复图片

### 终端日志 (如有报错)

```
[ERROR][2023-04-02 17:37:33][wechat_channel.py:30] - Worker return exception: 'WeChatMessage' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 115, in _handle
    reply = self._generate_reply(context)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 125, in _generate_reply
    e_context = PluginManager().emit_event(EventContext(Event.ON_HANDLE_CONTEXT, {
  File "/root/chatgpt-on-wechat/plugins/plugin_manager.py", line 131, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/root/chatgpt-on-wechat/plugins/hello/hello.py", line 31, in on_handle_context
    reply.content = "Hello, " + msg['User'].get('NickName', "My friend")
TypeError: 'WeChatMessage' object is not subscriptable
```

### 环境

 - 操作系统类型  ：Ubuntu Server 20.04 LTS 64位
 - Python版本  ：3.8.10                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
感谢issue! 之前重写了部分逻辑，忘掉改`Hello`里的代码了 😂

**Comment by Li-Eternally** [comment]
> 感谢issue! 之前重写了部分逻辑，忘掉改`Hello`里的代码了 😂

哈哈，我以为是我本地的问题
