### ISSUE TITLE
运行时出现KeyError: 'debug' 这个错误怎么办?

### ISSUE THREAD

**Issue by kz1802** [zhayujie/chatgpt-on-wechat#744]
~/chatgpt-on-wechat$ nohup python3 app.py & tail -f nohup.out
[1] 24994
nohup: ignoring input and appending output to 'nohup.out'
[ERROR][2023-04-04 07:50:05][app.py:28] - App startup failed!
[ERROR][2023-04-04 07:50:05][app.py:29] - 'debug'
Traceback (most recent call last):
  File "app.py", line 13, in run
    load_config()
  File "/home/A907227911/chatgpt-on-wechat/config.py", line 143, in load_config
    if config["debug"]:
  File "/home/A907227911/chatgpt-on-wechat/config.py", line 94, in __getitem__
    return super().__getitem__(key)
KeyError: 'debug'

**Comment by raydoomed** [comment]
一样[ERROR][2023-04-04 15:55:43][app.py:28] - App startup failed!
[ERROR][2023-04-04 15:55:43][app.py:29] - 'debug'
Traceback (most recent call last):
  File "C:\Users\xRay\chatgpt-on-wechat\app.py", line 13, in run
    load_config()
  File "C:\Users\xRay\chatgpt-on-wechat\config.py", line 143, in load_config
    if config["debug"]:
       ~~~~~~^^^^^^^^^
  File "C:\Users\xRay\chatgpt-on-wechat\config.py", line 94, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'debug'
PS C:\Users\xRay\chatgpt-on-wechat> python app.py
[ERROR][2023-04-04 15:55:49][app.py:28] - App startup failed!
[ERROR][2023-04-04 15:55:49][app.py:29] - 'debug'
Traceback (most recent call last):
  File "C:\Users\xRay\chatgpt-on-wechat\app.py", line 13, in run
    load_config()
  File "C:\Users\xRay\chatgpt-on-wechat\config.py", line 143, in load_config
    if config["debug"]:
       ~~~~~~^^^^^^^^^
  File "C:\Users\xRay\chatgpt-on-wechat\config.py", line 94, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'debug'
PS C:\Users\xRay\chatgpt-on-wechat>

**Comment by raydoomed** [comment]
> 更新下代码试试， 默认不开启debug模型。
> 
> 在config.json 中增加 "debug": true， 可以输出debug日志。

增加后可以用了，但是一直在输出日志，能不能不输出日志解决吗？

**Comment by lanvent** [comment]
改成false或者删去这一行。
```json
"debug": false
```

**Comment by lanvent** [comment]
没有拉最新代码吧
