### ISSUE TITLE
argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by wenchico** [zhayujie/chatgpt-on-wechat#773]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述
[ERROR][2023-04-07 17:56:12][log.py:50] - argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/lyw/Documents/chatbot/bot-on-anything/model/openai/chatgpt_model.py", line 50, in reply_text
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.8/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py", line 670, in _interpret_response_line
    if 'text/plain' in rheaders.get('Content-Type'):
TypeError: argument of type 'NoneType' is not iterable

### 环境
 - 操作系统类型  (Linux)：
 - Python版本  (3.8)：

**Comment by zhayujie** [comment]
这个是偶发问题还是每次出现的？ 看下你的 openai 版本是什么,   pip3 show openai

**Comment by alon-qianyue** [comment]
> 
我也出现了，第一次发消息成功回复，后面都不行
Name: openai
Version: 0.27.2
Summary: Python client library for the OpenAI API
Home-page: https://github.com/openai/openai-python
Author: OpenAI

**Comment by alon-qianyue** [comment]
> > 
> 
> 我也出现了，第一次发消息成功回复，后面都不行 Name: openai Version: 0.27.2 Summary: Python client library for the OpenAI API Home-page: https://github.com/openai/openai-python Author: OpenAI


打印了原始返回值，{'Content-Length': '0', 'Connection': 'keep-alive',  'Vary': 'Accept-Encoding', 'X-Scf-Message': 'TimeLimitReached'} 433，触发限制了
