### ISSUE TITLE
收到信息后报错

### ISSUE THREAD

**Issue by qq78446504** [zhayujie/chatgpt-on-wechat#79]
Start auto replying.
[ERROR][2023-02-07 19:43:03][wechat_channel.py:116] - No module named 'openai'
Traceback (most recent call last):
  File "/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 112, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "/chatgpt-on-wechat/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/chatgpt-on-wechat/bridge/bridge.py", line 9, in fetch_reply_content
    return bot_factory.create_bot("openAI").reply(query, context)
  File "/chatgpt-on-wechat/bot/bot_factory.py", line 24, in create_bot
    from bot.openai.open_ai_bot import OpenAIBot
  File "/chatgpt-on-wechat/bot/openai/open_ai_bot.py", line 6, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

登录成功后 接到消息就提示这个 是什么问题

**Comment by zhayujie** [comment]
see #47
