### ISSUE TITLE
news工具的api输入无误，但显示api密钥无效

### ISSUE THREAD

**Issue by Xuj69** [zhayujie/chatgpt-on-wechat#792]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法
其余工具都可以正常使用，在使用news一直显示sendMsg=Reply(type=TEXT, content=[0] 由于API密钥无效，我无法获取今天的英国新闻。请检查API密钥是否正确或前往https://newsapi.org创建免费API密钥。)

但是本人已经再三确认api输入无误，且找旁人复查无误

### 环境

 -windows
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by Xuj69** [comment]
![8989fba6ae1592413baebbb523a31aa](https://user-images.githubusercontent.com/98643830/230933064-641fc728-c3f5-479f-b549-c91149c0dfd2.png)
![111967589fa5c26bcc2c48e6bdf1977](https://user-images.githubusercontent.com/98643830/230933085-97a7fe6a-da38-48c0-b6ab-81dc90e38781.png)
是这样的问题就一直显示要我用api key但是我的api key都是确认无误的

**Comment by DayDreammy** [comment]
```
self.process = subprocess.Popen(
File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/local/lib/python3.10/subprocess.py", line 1863, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/noroot/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/apps/victorinox.py", line 86, in ask
return self.bot.run(query)
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/chains/base.py", line 212, in run
return self(args[0])[self.output_keys[0]]
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/chains/base.py", line 115, in __call__
raise e
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/chains/base.py", line 112, in __call__
outputs = self._call(inputs)
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/engine/tool_engine.py", line 158, in _call
next_step_output = self._take_next_step(
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/engine/tool_engine.py", line 123, in _take_next_step
observation = tool.run(
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/base_tool.py", line 72, in run
raise e
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/base_tool.py", line 69, in run
observation = self._run(tool_input)
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/news/tool.py", line 45, in _run
return parent_bot_prefix + self.bot.run(query)
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/chains/base.py", line 212, in run
return self(args[0])[self.output_keys[0]]
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/chains/base.py", line 115, in __call__
raise e
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/chains/base.py", line 112, in __call__
outputs = self._call(inputs)
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/engine/tool_engine.py", line 158, in _call
next_step_output = self._take_next_step(
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/engine/tool_engine.py", line 123, in _take_next_step
observation = tool.run(
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/base_tool.py", line 72, in run
raise e
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/base_tool.py", line 69, in run
observation = self._run(tool_input)
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/news/finance_news/tool.py", line 28, in _run
_response = BrowserTool().run(self.jin10_url)
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/web_requests/browser.py", line 127, in __init__
self.browser = ChromeBrowser()
File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
File "pydantic/main.py", line 1102, in pydantic.main.validate_model
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/web_requests/browser.py", line 50, in validate_environment
browser = cls._build_browser_option(proxy)
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/web_requests/browser.py", line 77, in _build_browser_option
browser = webdriver.Chrome(
File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
super().__init__(
File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
self.service.start()
File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 96, in start
self._start_process(self._path)
File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 212, in _start_process
raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/plugins/tool/tool.py", line 99, in on_handle_context
_reply = self.app.ask(query, user_session)
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/apps/victorinox.py", line 90, in ask
return self.ask(query, chat_history, retry_num + 1)
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/apps/victorinox.py", line 93, in ask
raise TimeoutError("超过重试次数")
TimeoutError: 超过重试次数
[ERROR][2023-04-22 14:00:31][tool.py:104] - 超过重试次数
[INFO][2023-04-22 14:00:31][chat_gpt_bot.py:48] - [CHATGPT] query=请你随机用一种聊天风格，提醒用户：这个问题tool插件暂时无法处理
[INFO][2023-04-22 14:00:40][wechat_channel.py:193] - [WX] sendMsg=Reply(type=TEXT, content=嘿，小家伙，听说你有一个问题要问我？很不幸的是，我现在无法回答你的问题。我的工具插件正在进行维护，我还需要一些时间来使其恢复正常工作。不过，别担心，我将尽快找到解决方案，以确保未来有更好的服务，让我们一起期待它早日恢复正常吧！), 
```

**Comment by goldfishh** [comment]
收到了，news工具应该返回空所以chatgpt再一次调tool去尝试，重试现在chatgpt有一个会自己构造url不按prompt提示的问题
这涉及到tool对用户侧解释的问题，所以现在不能处理那么快，建议设置debug参数反馈给你更多信息

简而言之：问题原因是news-api返回空重试捏造api 非news-api的url导致反馈给你的`API key used is invalid or incorrect`
后期我会挑，但你这个问题问browser可能会得到更有用的答复

**Comment by goldfishh** [comment]
> 出现了同样的结果，news-api 输出 `API key used is invalid or incorrect` ，但是key是直接复制过来的，再三确认无误。 以下是原始输入和输出
> 
> ```
> [INFO][2023-04-22 14:03:33][victorinox.py:85] - 提问: 使用news，查看上个月特斯拉的新闻
> [INFO][2023-04-22 14:03:37][base.py:107] - 执行Tool: news中...
> [INFO][2023-04-22 14:03:37][bot.py:91] - 输入: 请问上个月有关特斯拉的新闻有哪些？
> [INFO][2023-04-22 14:03:39][base.py:132] - 执行Tool: news-api中...
> [INFO][2023-04-22 14:03:39][bot.py:91] - 输入: What were the top news stories about Tesla last month?
> [INFO][2023-04-22 14:03:48][tool_engine.py:169] - [news-api]输出: I'm sorry, but I was unable to generate the full API url to answer your question about the top news stories about Tesla last month. The API response indicates that the API key used is invalid or incorrect. In order to generate a valid API url, a valid API key is required. Please check the API key or obtain a new one from https://newsapi.org/.
> [INFO][2023-04-22 14:03:53][base.py:132] - 执行Tool: Obtain a valid API key for news-api from https://newsapi.org/
> Thought: Now that I have a valid API key, I can try to answer the question again.
> Action: news-api中...
> [INFO][2023-04-22 14:03:53][bot.py:91] - 输入: What were the top news stories about Tesla last month?
> [INFO][2023-04-22 14:03:53][tool_engine.py:169] - [Obtain a valid API key for news-api from https://newsapi.org/
> Thought: Now that I have a valid API key, I can try to answer the question again.
> Action: news-api]输出: `Obtain a valid API key for news-api from https://newsapi.org/
> Thought: Now that I have a valid API key, I can try to answer the question again.
> Action: news-api` is not a valid tool, try another one.
> [INFO][2023-04-22 14:03:53][tool_engine.py:169] - [news]输出: <property object at 0x7fc28d9d2700>: Bot stopped due to max iterations.
> [INFO][2023-04-22 14:03:54][wechat_channel.py:193] - [WX] sendMsg=Reply(type=TEXT, content=<property object at 0x7fc28d9d2700>: Bot stopped due to max iterations.), 
> ```

收到了，news工具应该返回空所以chatgpt再一次调tool去尝试，重试现在chatgpt有一个会自己构造url不按prompt提示的问题
这涉及到tool对用户侧解释的问题，所以现在不能处理那么快，建议设置debug参数反馈给你更多信息

简而言之：问题原因是news-api返回空重试捏造api 非news-api的url导致反馈给你的API key used is invalid or incorrect
后期我会挑，但你这个问题问browser可能会得到更有用的答复
