### ISSUE TITLE
4.6日后按配置流程配置无法启动

### ISSUE THREAD

**Issue by zkaiera** [zhayujie/chatgpt-on-wechat#820]
### 前置确认

1. 网络能够访问openai接口
2. python 3.8.10
3. 最新代码
4. 依赖满足
5. 拓展功能依赖满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS]中无类似问题

### 问题描述

> 在德国服务器配置，4.6日前使用均无问题，4.6日后发送消息回应为：
ERROR:
我没有收到你的消息
检查未发现问题，重新运行app.py时报错无法运行，之后尝试重新安装、重装python等、最后更换服务器按https://github.com/zhayujie/chatgpt-on-wechat首页配置流程重新配置依然出现此问题。

### 终端日志 (如有报错)

```
[INFO][2023-04-13 00:11:16][config.py:157] - 配置文件不存在，将使用config-template.json模板
[ERROR][2023-04-13 00:11:16][app.py:47] - App startup failed!
[ERROR][2023-04-13 00:11:16][app.py:48] - [Errno 2] No such file or directory: './config-template.json'
Traceback (most recent call last):
  File "c:/Users/Administrator/Desktop/Code/chatgpt-on-wechat/app.py", line 24, in run
    load_config()
  File "c:\Users\Administrator\Desktop\Code\chatgpt-on-wechat\config.py", line 160, in load_config
    config_str = read_file(config_path)
  File "c:\Users\Administrator\Desktop\Code\chatgpt-on-wechat\config.py", line 196, in read_file
    with open(path, mode='r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './config-template.json'

```

### 环境

 - 操作系统类型  (Windows10)：
 - Python版本  ( 3.8.10 )：                      
 - pip版本  ( 23.0.1)：

**Comment by Maddaxman** [comment]
config-template.json 改成config.json
