### ISSUE TITLE
你好，微信扫码后报错 list index out of range并进程自动退出

### ISSUE THREAD

**Issue by Changego** [zhayujie/chatgpt-on-wechat#824]
### 问题描述
启动后，微信扫码后报错 list index out of range并进程自动退出

### 终端日志 (如有报错)

```
[ERROR][2023-04-13 11:36:23][app.py:47] - App startup failed!
[ERROR][2023-04-13 11:36:23][app.py:48] - list index out of range
Traceback (most recent call last):
  File "app.py", line 45, in run
    channel.startup()
  File "/opt/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 109, in startup
    raise e
  File "/opt/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 101, in startup
    itchat.auto_login(enableCmdQR=2, hotReload=hotReload, qrCallback=qrCallback)
  File "/opt/chatgpt-on-wechat/lib/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/opt/chatgpt-on-wechat/lib/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/opt/chatgpt-on-wechat/lib/itchat/components/login.py", line 153, in check_login
    if process_login_info(self, r.text):
  File "/opt/chatgpt-on-wechat/lib/itchat/components/login.py", line 198, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Anolis OS release 8.6
 - Python版本  ( 执行 `python3 -V` )：Python 3.8.12                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 19.3.1

**Comment by dqzboy** [comment]
我也是同样的问题，进程结束之后，重新运行扫码登入 就报上面的错误

**Comment by ShooflyL** [comment]
我也遇到了这个问题，我用小号扫码时就有这个问题，而大号没有。看代码应该是skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0] 时没有查找到<skey>。问了一下ChatGPT，根据它的回答：”<skey> 是微信登录凭证，每个微信号都有一个独立的<skey>，用于标识微信用户的身份。“，应该是需要完成微信号的实名认证才能获取到<skey>，所以试了一下，只要到微信钱包里绑定个银行卡实名认证一下，就可以成功了。

**Comment by le0zh0u** [comment]
需要实名认证一下的。

**Comment by fanheshe** [comment]
同问

**Comment by dqzboy** [comment]
我知道问题了，需要微信号可以正常登入 网页端的问题才行，如果网页端微信登入不了那这里也无法使用

**Comment by Changego** [comment]
多谢，已解决。
