### ISSUE TITLE
has no attribute 'Timeout'

### ISSUE THREAD

**Issue by LemonMemory** [zhayujie/chatgpt-on-wechat#835]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

Login successfully as 时光🤪
[INFO][2023-04-13 16:13:15][wechat_channel.py:112] - Wechat login success, user_id: @6c876b08fb8da51393ccedd8862329bdfd4f5e586a47c65bfb571dcaa4efb910, nickname: 时光🤪
Start auto replying.
[INFO][2023-04-13 16:13:26][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-04-13 16:13:26][chat_gpt_bot.py:45] - [CHATGPT] query=你是谁
[ERROR][2023-04-13 16:13:26][chat_channel.py:244] - Worker return exception: module 'openai.error' has no attribute 'Timeout'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/chatgpt-on-wechat/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 107, in reply_text
    response = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/chatgpt-on-wechat/chatgpt-on-wechat/chatgpt-on-wechat/channel/chat_channel.py", line 132, in _handle
    reply = self._generate_reply(context)
  File "/root/chatgpt-on-wechat/chatgpt-on-wechat/chatgpt-on-wechat/channel/chat_channel.py", line 148, in _generate_reply
    reply = super().build_reply_content(context.content, context)
  File "/root/chatgpt-on-wechat/chatgpt-on-wechat/chatgpt-on-wechat/channel/channel.py", line 35, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/root/chatgpt-on-wechat/chatgpt-on-wechat/chatgpt-on-wechat/bridge/bridge.py", line 42, in fetch_reply_content
    return self.get_bot("chat").reply(query, context)
  File "/root/chatgpt-on-wechat/chatgpt-on-wechat/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 71, in reply
    reply_content = self.reply_text(session, api_key)
  File "/root/chatgpt-on-wechat/chatgpt-on-wechat/chatgpt-on-wechat/bot/chatgpt/chat_gpt_bot.py", line 122, in reply_text
    elif isinstance(e, openai.error.Timeout):
AttributeError: module 'openai.error' has no attribute 'Timeout'

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：                      
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
`openai`版本过低了，`pip3 show openai`可以查看版本是否是0.27.2
