### ISSUE TITLE
Ubuntu服务器上，运行nohup python3 app.py & tail -f nohup.out后报错

### ISSUE THREAD

**Issue by michael7908** [zhayujie/chatgpt-on-wechat#84]
报错讯息为：Please scan the QR code to log in.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/itchat/components/login.py", line 255, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "/usr/local/lib/python3.10/dist-packages/itchat/components/messages.py", line 62, in produce_msg
    produce_group_chat(core, m)
  File "/usr/local/lib/python3.10/dist-packages/itchat/components/messages.py", line 257, in produce_group_chat
    utils.msg_formatter(msg, 'Content')
  File "/usr/local/lib/python3.10/dist-packages/itchat/utils.py", line 69, in msg_formatter
    d[k]  = htmlParser.unescape(d[k])
AttributeError: 'HTMLParser' object has no attribute 'unescape'

咨询chatgpt后，更新itchat；但没用；而且运行上述命令后生成的QRcode 微信无法扫描。

**Comment by zhayujie** [comment]
执行 python3.10 -m pip show itchat-uos  看看
