### ISSUE TITLE
看起来是官方修改模型了

### ISSUE THREAD

**Issue by yzq497259225** [zhayujie/chatgpt-on-wechat#88]
Login successfully as ccc
Start auto replying.
[ERROR][2023-02-07 19:34:09][wechat_channel.py:116] - No module named 'openai'
Traceback (most recent call last):
  File "/opt/chatGpt/chatgpt-on-wechat-master/channel/wechat/wechat_channel.py",                                                    line 112, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "/opt/chatGpt/chatgpt-on-wechat-master/channel/channel.py", line 31, in b                                                   uild_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/opt/chatGpt/chatgpt-on-wechat-master/bridge/bridge.py", line 9, in fetc                                                   h_reply_content
    return bot_factory.create_bot("openAI").reply(query, context)
  File "/opt/chatGpt/chatgpt-on-wechat-master/bot/bot_factory.py", line 24, in c                                                   reate_bot
    from bot.openai.open_ai_bot import OpenAIBot
  File "/opt/chatGpt/chatgpt-on-wechat-master/bot/openai/open_ai_bot.py", line 6                                                   , in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Comment by lifeofbow** [comment]
是的我也发现 2022那个模型用不了了，而且切换回原来的达芬奇3后，回答文不对题

**Comment by zhayujie** [comment]
see #47
