### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by notwin** [zhayujie/chatgpt-on-wechat#9]
[ERROR][2022-12-20 18:39:33][app.py:19] - App startup failed!
[ERROR][2022-12-20 18:39:33][app.py:20] - list index out of range

Traceback (most recent call last):
  File "/Users/notwin/Code/chatgpt-on-wechat/app.py", line 17, in <module>
    channel.startup()
  File "/Users/notwin/Code/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/Users/notwin/Library/Python/3.9/lib/python/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/notwin/Library/Python/3.9/lib/python/site-packages/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/Users/notwin/Library/Python/3.9/lib/python/site-packages/itchat/components/login.py", line 152, in check_login
    if process_login_info(self, r.text):
  File "/Users/notwin/Library/Python/3.9/lib/python/site-packages/itchat/components/login.py", line 197, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

**Comment by notwin** [comment]
登陆不上，itchat的源码sleep我也改了

**Comment by zhayujie** [comment]
> 登陆不上，itchat的源码sleep我也改了

你的微信是不是没有实名认证，需要在支付那里认证下

**Comment by notwin** [comment]
哦哦，谢谢

**Comment by ailanmty** [comment]
已经实名认证过的账号还是出现这个问题是什么原因

**Comment by zhayujie** [comment]
@ailanmty  账号状态正常吗，有没有被冻结或者限制

**Comment by yh200212121212** [comment]
> 已经实名认证过的账号还是出现这个问题是什么原因

退出重新登陆一下试试看

**Comment by ailanmty** [comment]
是账号被限制了，电脑端等不了了
