### ISSUE TITLE
扫码登陆后出错

### ISSUE THREAD

**Issue by cadben** [zhayujie/chatgpt-on-wechat#90]
手机扫码登录后，显示以下错误：

Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

**Comment by nullcanon** [comment]
一样的问题 怎么解决的
