### ISSUE TITLE
 Failed to import plugin tool: No module named 'webdriver_manager'

### ISSUE THREAD

**Issue by hy546880109** [zhayujie/chatgpt-on-wechat#914]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

railway启动报错如下

### 终端日志 (如有报错)

```

[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
```
chatgpt-tool-hub 0.3.8后，部分工具名将变更：requests -> url-get
[ERROR][2023-04-21 02:45:35][plugin_manager.py:110] - Failed to import plugin tool: No module named 'webdriver_manager'
Traceback (most recent call last):
File "/app/plugins/plugin_manager.py", line 105, in scan_plugins
self.loaded[plugin_path] = importlib.import_module(
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/app/plugins/tool/__init__.py", line 1, in <module>
from .tool import *
File "/app/plugins/tool/tool.py", line 4, in <module>
from chatgpt_tool_hub.apps import load_app
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/apps/__init__.py", line 1, in <module>
from chatgpt_tool_hub.apps.load_app import load_app
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/apps/load_app.py", line 7, in <module>
from chatgpt_tool_hub.tools import dynamic_tool_loader
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/__init__.py", line 5, in <module>
from chatgpt_tool_hub.tools.web_requests.browser import BrowserTool
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/web_requests/__init__.py", line 42, in <module>
from chatgpt_tool_hub.tools.web_requests.wrapper import RequestsWrapper
File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/web_requests/wrapper.py", line 11, in <module>
from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：  
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by LuoChengzhi** [comment]
试一下
pip install webdriver_manager
我手动装了这个包之后就不报这个错了，但是我有其他问题还没解决

**Comment by goldfishh** [comment]
请pull wechat on chatgpt 最新代码
并把tool hub 更新至0.4.1
如有问题，请同步给我

**Comment by lanvent** [comment]
fixed
