### ISSUE TITLE
（问题）私聊可以，群聊无效，报错

### ISSUE THREAD

**Issue by apple157** [zhayujie/chatgpt-on-wechat#919]
### 前置确认

腾讯云，有代理，可以私聊，没问题
### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

私聊可以，群聊无效，报错

### 终端日志 (如有报错)

```
[INFO][2023-04-21 17:13:51][chat_channel.py:114] - [WX]receive group at
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 47, in handler_group_msg
    WechatChannel().handle_group(cmsg)
  File "/root/chatgpt-on-wechat/common/time_check.py", line 48, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 65, in wrapper
    return func(self, cmsg)
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 205, in handle_group
    context = self._compose_context(
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 118, in _compose_context
    content = re.sub(pattern, r"", content)
  File "/usr/local/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/local/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.8/sre_parse.py", line 962, in parse
    raise source.error("unbalanced parenthesis")
re.error: unbalanced parenthesis at position 4
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Linux
 - Python版本  ( 执行 `python3 -V` )：  python3
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：pip 23.1

**Comment by lanvent** [comment]
你的bot是什么名字

**Comment by apple157** [comment]
微信名字

> 你的bot是什么名字

微信名字是中文的：小丑:)咸鱼币
是因为带了个括号吗？

**Comment by lanvent** [comment]
是bug，这个问题会在近期修复

**Comment by lanvent** [comment]
fixed
