### ISSUE TITLE
公众号语音问题

### ISSUE THREAD

**Issue by zhang19523zhao** [zhayujie/chatgpt-on-wechat#928]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间
3. `git pull` 拉取最新代码
4. 执行`pip3 install -r requirements.txt`，检查依赖是否满足
5. 拓展功能请执行`pip3 install -r requirements-optional.txt`，检查依赖是否满足
6. 在已有 issue 中未搜索到类似问题
7. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

>    简要说明、截图、复现步骤等，也可以是需求或想法

发送语音就显示该公众号提供的服务出现故障

### 终端日志 (如有报错)

```
[在此处粘贴终端日志, 可在主目录下`run.log`文件中找到]
[ERROR][2023-04-22 21:32:27][SubscribeAccount.py:171] - 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/channel/wechatmp/SubscribeAccount.py", line 24, in POST
    wechatmp_msg = receive.parse_xml(webData)
  File "/root/chatgpt-on-wechat/channel/wechatmp/receive.py", line 13, in parse_xml
    return WeChatMPMessage(xmlData)
  File "/root/chatgpt-on-wechat/channel/wechatmp/receive.py", line 36, in __init__
    self.content = xmlData.find('Recognition').text.encode("utf-8")  # 接收语音识别结果
AttributeError: 'NoneType' object has no attribute 'encode'
162.62.81.123:62822 - - [22/Apr/2023 21:32:27] "HTTP/1.1 POST /wx" - 200 OK
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python3 -V` )：  
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
查看部署文档，需要开启语音识别
