### ISSUE TITLE
配置修改  "channel_type": "wxy"后，终端错误：TypeError: str expected, not NoneType

### ISSUE THREAD

**Issue by 10822123** [zhayujie/chatgpt-on-wechat#945]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 问题描述 😯

你好，很感谢你的分享。但我在执行的过程遇到了问题，需要你的帮助。

配置了配置  "channel_type": "wxy"。
终端跑起来遇到下面错误。

Traceback (most recent call last):
  File "E:\chatgpt\chatgpt-on-wechat\app.py", line 49, in run
    channel.startup()
  File "E:\chatgpt\chatgpt-on-wechat\channel\wechat\wechaty_channel.py", line 41, in startup
    os.environ["WECHATY_PUPPET_SERVICE_TOKEN"] = token
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\os.py", line 742, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType

### 终端日志 📒

```log
Traceback (most recent call last):
  File "E:\chatgpt\chatgpt-on-wechat\app.py", line 49, in run
    channel.startup()
  File "E:\chatgpt\chatgpt-on-wechat\channel\wechat\wechaty_channel.py", line 41, in startup
    os.environ["WECHATY_PUPPET_SERVICE_TOKEN"] = token
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\os.py", line 742, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
```

**Comment by lanvent** [comment]
wechaty部署比较麻烦，建议看#244 #923

**Comment by lsCoding666** [comment]
需要修改一个文件 可能是没改。
channel/wechat/wechaty_channel 
要在
```
os.environ["WECHATY_PUPPET_SERVICE_TOKEN"] = token
```
下面加一行
```
os.environ['WECHATY_PUPPET_SERVICE_ENDPOINT'] = "localhost:9999"
```
9999是docker启动时配置的端口号

另外其实chatgpt-on-wechat 这个项目完全可以不需要服务器本地部署。我拿家里的笔记本挂着，很不错。windows跑就行

**Comment by lsCoding666** [comment]
家里电脑部署的好处就是归属地在本地
