### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ktluv** [zhayujie/chatgpt-on-wechat#954]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

[ERROR][2023-04-25 17:42:22][app.py:52] - App startup failed!
[ERROR][2023-04-25 17:42:22][app.py:53] - Expecting ',' delimiter: line 19 column 5 (char 362)
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat-1.2.5/app.py", line 29, in run
    load_config()
  File "/root/chatgpt-on-wechat-1.2.5/config.py", line 154, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 19 column 5 (char 362)

### 问题描述 😯

[ERROR][2023-04-25 17:42:22][app.py:52] - App startup failed!
[ERROR][2023-04-25 17:42:22][app.py:53] - Expecting ',' delimiter: line 19 column 5 (char 362)
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat-1.2.5/app.py", line 29, in run
    load_config()
  File "/root/chatgpt-on-wechat-1.2.5/config.py", line 154, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 19 column 5 (char 362)

### 终端日志 📒

[ERROR][2023-04-25 17:42:22][app.py:52] - App startup failed!
[ERROR][2023-04-25 17:42:22][app.py:53] - Expecting ',' delimiter: line 19 column 5 (char 362)
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat-1.2.5/app.py", line 29, in run
    load_config()
  File "/root/chatgpt-on-wechat-1.2.5/config.py", line 154, in load_config
    config = Config(json.loads(config_str))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 19 column 5 (char 362)

**Comment by lanvent** [comment]
json格式不对，建议对着模版慢慢调

**Comment by ktluv** [comment]
好
