### ISSUE TITLE
文字回复正常，调用画图接口会报错， SSL ERROR

### ISSUE THREAD

**Issue by Kiteflyingee** [zhayujie/chatgpt-on-wechat#959]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Master (branch)

### 运行的`channel`类型是?

wechatmp(公众号, 订阅号)

### 复现步骤 🕹

输入画一个苹果，报错。

### 问题描述 😯

文字回复正常，调用画图接口会报错，线上api.weixin.qq.com SSLError，在issue中找到相关sslerror，但是没有遇到过api的ssl error，这个是我翻墙软件的问题吗？
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))

### 终端日志 📒

```log
04/26 10:08:43
wechatmp5-008
画一张苹果
[INFO][2023-04-26 02:08:42][passive_reply.py:100] - [wechatmp] Request 3 from oMfj25kormNgHw-5Mn33ZfSN91qI 24087246215802372 10.14.254.241:23524
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/api/material.py", line 53, in add
response = self.client.material.add("image", (filename, image_storage, content_type))
File "/app/channel/wechatmp/wechatmp_channel.py", line 114, in send
self.send(reply, context)
File "/app/channel/chat_channel.py", line 251, in _send
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
raise MaxRetryError(_pool, url, error or ResponseError(cause))
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)
self._sslobj.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
self.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
return self.sslsocket_class._create(
File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
conn.connect()
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
self._validate_conn(conn)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
Traceback (most recent call last):
[ERROR][2023-04-26 02:08:43][chat_channel.py:256] - HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
[ERROR][2023-04-26 02:08:43][chat_channel.py:253] - [WX] sendMsg error: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
raise MaxRetryError(_pool, url, error or ResponseError(cause))
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)
self._sslobj.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
self.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
return self.sslsocket_class._create(
File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
conn.connect()
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
self._validate_conn(conn)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
raise SSLError(e, request=request)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
return self.request("GET", url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
res = self._http.get(
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/base.py", line 197, in _fetch_access_token
return self._fetch_access_token(
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/__init__.py", line 60, in fetch_access_token
return super().fetch_access_token()
File "/app/channel/wechatmp/wechatmp_client.py", line 33, in fetch_access_token
self.fetch_access_token()
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/base.py", line 248, in access_token
return self._client.access_token
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/api/base.py", line 23, in access_token
'access_token': self.access_token,
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
raise SSLError(e, request=request)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
return self.request("GET", url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
res = self._http.get(
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/base.py", line 197, in _fetch_access_token
return self._fetch_access_token(
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/__init__.py", line 60, in fetch_access_token
return super().fetch_access_token()
File "/app/channel/wechatmp/wechatmp_client.py", line 33, in fetch_access_token
self.fetch_access_token()
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/base.py", line 248, in access_token
return self._client.access_token
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/api/base.py", line 23, in access_token
'access_token': self.access_token,
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/api/material.py", line 53, in add
response = self.client.material.add("image", (filename, image_storage, content_type))
File "/app/channel/wechatmp/wechatmp_channel.py", line 114, in send
self.send(reply, context)
File "/app/channel/chat_channel.py", line 251, in _send
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
10.14.254.241:23524 - - [26/Apr/2023 02:08:46] "HTTP/1.1 POST /wx" - 200 OK
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)
self._sslobj.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
self.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
return self.sslsocket_class._create(
File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
conn.connect()
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
self._validate_conn(conn)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
Traceback (most recent call last):
[ERROR][2023-04-26 02:08:51][chat_channel.py:256] - HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
[ERROR][2023-04-26 02:08:51][chat_channel.py:253] - [WX] sendMsg error: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
conn.connect()
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
self._validate_conn(conn)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
raise SSLError(e, request=request)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
return self.request("GET", url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
res = self._http.get(
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/base.py", line 197, in _fetch_access_token
return self._fetch_access_token(
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/__init__.py", line 60, in fetch_access_token
return super().fetch_access_token()
File "/app/channel/wechatmp/wechatmp_client.py", line 33, in fetch_access_token
self.fetch_access_token()
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/base.py", line 248, in access_token
return self._client.access_token
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/api/base.py", line 23, in access_token
'access_token': self.access_token,
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/api/material.py", line 53, in add
response = self.client.material.add("image", (filename, image_storage, content_type))
File "/app/channel/wechatmp/wechatmp_channel.py", line 114, in send
self.send(reply, context)
File "/app/channel/chat_channel.py", line 251, in _send
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
raise MaxRetryError(_pool, url, error or ResponseError(cause))
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
self._validate_conn(conn)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
raise SSLError(e, request=request)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
return self.request("GET", url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
res = self._http.get(
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/base.py", line 197, in _fetch_access_token
return self._fetch_access_token(
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/__init__.py", line 60, in fetch_access_token
return super().fetch_access_token()
File "/app/channel/wechatmp/wechatmp_client.py", line 33, in fetch_access_token
self.fetch_access_token()
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/base.py", line 248, in access_token
return self._client.access_token
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/api/base.py", line 23, in access_token
'access_token': self.access_token,
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/api/material.py", line 53, in add
response = self.client.material.add("image", (filename, image_storage, content_type))
File "/app/channel/wechatmp/wechatmp_channel.py", line 114, in send
self.send(reply, context)
File "/app/channel/chat_channel.py", line 251, in _send
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
raise MaxRetryError(_pool, url, error or ResponseError(cause))
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)
self._sslobj.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
self.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
return self.sslsocket_class._create(
File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
raise SSLError(e, request=request)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
return self.request("GET", url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
res = self._http.get(
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/base.py", line 197, in _fetch_access_token
return self._fetch_access_token(
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/__init__.py", line 60, in fetch_access_token
return super().fetch_access_token()
File "/app/channel/wechatmp/wechatmp_client.py", line 33, in fetch_access_token
self.fetch_access_token()
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/base.py", line 248, in access_token
return self._client.access_token
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/api/base.py", line 23, in access_token
'access_token': self.access_token,
File "/usr/local/lib/python3.10/site-packages/wechatpy/client/api/material.py", line 53, in add
response = self.client.material.add("image", (filename, image_storage, content_type))
File "/app/channel/wechatmp/wechatmp_channel.py", line 114, in send
self.send(reply, context)
File "/app/channel/chat_channel.py", line 251, in _send
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/token?grant_type=client_credential (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
raise MaxRetryError(_pool, url, error or ResponseError(cause))
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)
self._sslobj.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
self.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
return self.sslsocket_class._create(
File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
conn.connect()
```

**Comment by Kiteflyingee** [comment]
具体报错如下：
![image](https://user-images.githubusercontent.com/12490322/234451133-12805341-7de6-4bc2-8b6b-2b95f59f1b50.png)
服务部署在微信云托管上的

**Comment by lanvent** [comment]
似乎是证书问题，搜索引擎找一下解决方案 ```SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)```
