### ISSUE TITLE
企业微信中语音转换输出结果会报错

### ISSUE THREAD

**Issue by kalong0126** [zhayujie/chatgpt-on-wechat#974]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

other

### 复现步骤 🕹

拉取最新版本，配置企业微信接入，采用语音输入，就会出现问题

### 问题描述 😯

文本转语音无法转成功，看日志提示貌似是没有默认编码器

### 终端日志 📒

```log
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/wechat/channel/chat_channel.py", line 251, in _send
    self.send(reply, context)
  File "/root/wechat/channel/wechatcom/wechatcomapp_channel.py", line 68, in send
    any_to_amr(file_path, amr_file)
  File "/root/wechat/voice/audio_convert.py", line 94, in any_to_amr
    audio.export(amr_path, format="amr")
  File "/usr/local/lib/python3.9/dist-packages/pydub/audio_segment.py", line 970, in export
    raise CouldntEncodeError(
pydub.exceptions.CouldntEncodeError: Encoding failed. ffmpeg/avlib returned error code: 1

Command:['ffmpeg', '-y', '-f', 'wav', '-i', '/tmp/tmp8m1cx9b1', '-f', 'amr', '/tmp/tmpj7g91s7v']

Output from ffmpeg/avlib:

ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from '/tmp/tmp8m1cx9b1':
  Duration: 00:00:03.94, bitrate: 128 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 8000 Hz, mono, s16, 128 kb/s
Automatic encoder selection failed for output stream #0:0. Default encoder for format amr (codec amr_nb) is probably disabled. Please choose an encoder manually.
Error selecting an encoder for stream 0:0

```

**Comment by lanvent** [comment]
debian/ubuntu 系统上刚才找到了解决方案：
```
apt install libavcodec-extra
```

**Comment by kalong0126** [comment]
谢谢解答，不过我是参照了[这篇文章](https://mark1998.com/raspi-ffmpeg-self-compile/)重新自编译安装了一个ffmpeg的版本，也把问题解决了，就是麻烦了很多，幸好还算顺利。

**Comment by bentennysonyoung** [comment]
我遇到的ffmpeg安装问题也很奇葩
pip安装无效，其他各种源都无效。
```
[root@mydomain chatgpt-on-wechat]# yum install ffmpeg
Last metadata expiration check: 2:49:30 ago on Mon 22 May 2023 09:28:18 AM CST.
Error: 
 Problem: package ffmpeg-2.8.15-2.el7.nux.x86_64 requires ffmpeg-libs(x86-64) = 2.8.15-2.el7.nux, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides libgnutls.so.28()(64bit) needed by ffmpeg-libs-2.8.15-2.el7.nux.x86_64
  - nothing provides libgnutls.so.28(GNUTLS_1_4)(64bit) needed by ffmpeg-libs-2.8.15-2.el7.nux.x86_64
  - nothing provides libgnutls.so.28(GNUTLS_3_0_0)(64bit) needed by ffmpeg-libs-2.8.15-2.el7.nux.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
参考下面链接，更新了源，注意rpmfind.net中的rpm地址更新，直接搜 SDL2 获取链接
[在CentOS 8上安装FFmpeg](https://blog.csdn.net/mdykj33/article/details/104020068)
这才安装成功。

**Comment by AlberHu** [comment]
> debian/ubuntu 系统上刚才找到了解决方案：
> 
> ```
> apt install libavcodec-extra
> ```
这个方法解决了，感谢！
