### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by HQwizardK** [zhayujie/chatgpt-on-wechat#981]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

Traceback (most recent call last):
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1682609276409&skey=%40crypt_68781b03_7dd56710cea24a301711e7a88bda3a25&sid=hRcaVMvMnfR%2BLz40&uin=3455207045&deviceid=e695069500210759&synckey=1_789142408%7C2_789142537%7C3_789142430%7C11_789142371%7C19_33041%7C23_1682608182%7C24_1682608620%7C27_247473%7C201_1682608620%7C206_103%7C1000_1682600461%7C1001_1682600523&_=1682608185513 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86185\chatgpt-on-wechat\lib\itchat\components\login.py", line 356, in sync_check
    r = self.s.get(url, params=params, headers=headers,
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 518, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1682609276409&skey=%40crypt_68781b03_7dd56710cea24a301711e7a88bda3a25&sid=hRcaVMvMnfR%2BLz40&uin=3455207045&deviceid=e695069500210759&synckey=1_789142408%7C2_789142537%7C3_789142430%7C11_789142371%7C19_33041%7C23_1682608182%7C24_1682608620%7C27_247473%7C201_1682608620%7C206_103%7C1000_1682600461%7C1001_1682600523&_=1682608185513 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86185\chatgpt-on-wechat\lib\itchat\components\login.py", line 295, in maintain_loop
    i = sync_check(self)
  File "C:\Users\86185\chatgpt-on-wechat\lib\itchat\components\login.py", line 360, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range

### 问题描述 😯

[ERROR][2023-04-27 22:59:19][app.py:53] - HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxstatusnotify?lang=zh_CN&pass_ticket=Oi7IntDRxG6iS%2B%2BmMVYeyNMmzPoqs9YLRpRRFkXVbVl%2BJ8KDdvSZtswFOGVJFqyj (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
Traceback (most recent call last):
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxstatusnotify?lang=zh_CN&pass_ticket=Oi7IntDRxG6iS%2B%2BmMVYeyNMmzPoqs9YLRpRRFkXVbVl%2BJ8KDdvSZtswFOGVJFqyj (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 50, in run
    channel.startup()
  File "C:\Users\86185\chatgpt-on-wechat\channel\wechat\wechat_channel.py", line 116, in startup
    itchat.auto_login(
  File "C:\Users\86185\chatgpt-on-wechat\lib\itchat\components\register.py", line 37, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "C:\Users\86185\chatgpt-on-wechat\lib\itchat\components\login.py", line 83, in login
    self.show_mobile_login()
  File "C:\Users\86185\chatgpt-on-wechat\lib\itchat\components\login.py", line 284, in show_mobile_login
    r = self.s.post(url, data=json.dumps(data), headers=headers)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\86185\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 518, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxstatusnotify?

**Comment by lanvent** [comment]
https://github.com/zhayujie/chatgpt-on-wechat/issues/952#issuecomment-1521706915 看看这个有没有用

**Comment by HQwizardK** [comment]
好的，谢谢
